### ISSUE TITLE
[NPC] Private Thorsen gives nothing, despite the "!" mark.

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1137]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I've just came to STV Rebel Camp as alliance and grabbed the quests here, except one. Private Thorsen has an "!", but gives no quest.
**Current behaviour**:
![wowscrnshot_100318_120803](https://user-images.githubusercontent.com/43505031/46404283-06581580-c705-11e8-86b6-de9bf52209d0.jpg)

He started to walk away for a patrol and lost his "!" mark.
![wowscrnshot_100318_120928](https://user-images.githubusercontent.com/43505031/46404358-369fb400-c705-11e8-9044-d3116d8beec7.jpg)

**Expected behaviour**: 
He shouldn't indicate a "!" mark when he doesn't give any quest. (Or he should give it?)
**Server Revision**: 
2108

**Comment by Shanghi** [comment]
@Evolvee I think he needs to stop offering his quest (he only has [Jungle Secrets](https://www.wowhead.com/quest=215/jungle-secrets) (215)) once he says "I've been gone a long time...I better get back." and starts walking back to camp. The messed up exclamation mark is just from a condition that doesn't let you take the quest while he's in the camp, but the server doesn't force the client to update that when changing areas so it keeps showing it. That can be removed later since it will be useless if you make him stop offering it.

**Comment by Evolvee** [comment]
check condition 19 and 20 in DB for this NPC ^^ it will tell you how I made it :D

**Comment by Evolvee** [comment]
The problem was that the "jungle secret" quest is supposed to be given only after the event. but he also has some other quest where he is the NPC quest rewarded so disabling NPC flag fully for the entire duration is not an option

so i conditioned the area he is in for the other quest

so rn, he should be able to reward the other quest and jungle secret quest only after the event ^^ if the shows the "!" its probably a core bug or a condition is messed up

**Comment by Evolvee** [comment]
or maybe I added only 19 and forgot 20, everything is possible :D

**Comment by Evolvee** [comment]
after certain waypoint, he loses his NPC flag fully... and regains it after someone saves him

**Comment by Evolvee** [comment]
@Shanghi I mean I could theoretically do it as you said, but then when he walks back to his camp, it would be like this again until he goes to his jorney again... the NPC flag cannot be fully disabled since the camp is his only place where he can reward the other quest.

**Comment by Shanghi** [comment]
@Evolvee I forgot about having to turn in another quest while he's at the camp! The conditions are set right, but it doesn't update 20 when he switches areas so the exclamation mark stays. Could you disable quests just while he's walking back to the camp, then enable them again once he's back in camp and the event is over? That should hopefully fix it all and still allow turning in quests without needing a core change!

**Comment by Evolvee** [comment]
i will see

**Comment by Kidtoucher** [comment]
this is still bugged, we are awaiting a fix please :)

**Comment by Selektiv** [comment]
@Evolvee Have you had time to take a look at this?

**Comment by Selektiv** [comment]
"I found that it works, you just have to follow him on his patrol and save him"

**Comment by Evolvee** [comment]
No time until my exams are over :(

**Comment by turkhero** [comment]
Still bugged :(

**Comment by Evolvee** [comment]
my exams werent over 🤣

**Comment by deathkneel** [comment]
I just followed him on patrol. He walked to around (40,8), sat there for ~10 minuted and then flew back to the camp ignoring all terrain. No mobs spawned to ambush him during all of this. It's pretty annoying because we can't do an entire quest chain.
