### ISSUE TITLE
[NPC][Quest][Arathi Highlands] Professor Phizzlethorpe Sunken Treasure

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1145]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The quest [Sunken Treasure](http://db.hellfire-tbc.com/?quest=665) has a different name on [retail](https://www.wowhead.com/quest=26050/goggle-boggle). The [questgiver](https://www.wowhead.com/npc=2768/professor-phizzlethorpe) is stuck in the cave and doesn't give a quest.

**Current behaviour**:
Professor Phizzlethorpe is inside of the cave. This is where he goes for the escort quest. He doesn't have a quest to accept.
![prof](https://imgur.com/E1kvXBa.jpg)

**Expected behaviour**:
He should stand next to Doctor Draxlegauge at the fire and have a quest for you.
![doc](https://imgur.com/wASSfow.jpg)

**Server Revision**: 2108

**Comment by Shanghi** [comment]
The event gets messed up if the water elementals kill you because then they'll go back to the cave entrance and stand there until despawning. After that, the professor will just stand there forever.

![image](https://user-images.githubusercontent.com/2672633/46411782-a6547580-c6ea-11e8-8d04-fee61792d025.png)

The water elementals currently always attack the player, even if they're a much higher level and farther away. They should always attack the professor when spawning instead.

**Comment by Evolvee** [comment]
reworked

try again in rev 439kcolb
