### ISSUE TITLE
[Quest] Gammerita, Mon!

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#1174]
**Description**: Quest given by a troll in Revantusk Village.

**Current behaviour**: Is acceptable right away with no prerequisite.

**Expected behaviour**: Requires "Snapjaws, Mon!" to be completed first.
https://classicdb.ch/?quest=7816

**Server Revision**: 2124

**Comment by Shanghi** [comment]
classicdb.ch is just a stock database so can't really be trusted. It was changed because:
* The Master Guide shows it having no requirements
* An old Allakhazam comment: "Snapjaws, Mon! is not a pre-requisite for this quest. Had both listed for when I talked to him."
* An old Thottbot comment: "I was doing the other turtle quest too..."
* https://www.youtube.com/watch?v=UbpA7mGsIq8 - from a newer expansion so normally wouldn't be proof alone, but still adds more evidence on to the other things
