### ISSUE TITLE
[Felwood][Object] Cleansed Songflower

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1185]
[Object] [Cleansed Songflower](https://www.wowhead.com/object=164882/cleansed-songflower)
[Spell] [Songflower Serenade](https://www.wowhead.com/spell=15366/songflower-serenade)

**Current behaviour**:
One shown on the screen is cleansed already, and doesn't require player to cleanse it.
![screenshot_4](https://user-images.githubusercontent.com/43505196/46461859-0a953900-c7c0-11e8-9608-26a74c65aa21.png)

**Expected behaviour**: 
It shouldn't be "cleansed", it should be like the rest in Felwood, you need to cleanse it first to get it's respective buff / consumable.

On side note: since we have lvl cap 60, you can also check if it will give buff after lvl 65, cause it shouldn't on in and higher. So it's worth checking for you.

![screenshot_1](https://user-images.githubusercontent.com/43505196/46462180-07e71380-c7c1-11e8-994f-87021209560f.png)

**Server Revision**: 
2124

**Comment by Shanghi** [comment]
The already spawned one should be fixed after revision 2539.

I tested the level and it stopped working on 64. I'm not sure if that's right since that one guy said 65, but there's 3 others that say 64 (but 2 are during WotLK)! I guess they'll be trusted for now unless someone has better information somehow.
![image](https://user-images.githubusercontent.com/2672633/50550787-672fb500-0c44-11e9-8619-024fa445b1fb.png)
![image](https://user-images.githubusercontent.com/2672633/50550788-70208680-0c44-11e9-8663-c7d1586f6250.png)
![image](https://user-images.githubusercontent.com/2672633/50550789-77e02b00-0c44-11e9-9a69-81d5261cb148.png)
