### ISSUE TITLE
[Spell][Paladin] Exorcism (and holy resistance in general)

### ISSUE THREAD

**Issue by BeyondNoMore** [Atlantiss/NetherwingBugtracker#1190]
**Description**: 
Exorcism being consistently resisted by mobs that are on-par with my level or lower level. 
The idea: holy resistance doesn't exist. Most of the private servers don't get this and treat holy spells as any other ordinary spell. 
I get the idea that I could *miss* my spell, due to the lack of spell hit and such, but fully resisted?
Holy-based spells get the advantage of not having to go through a spell-resistance check, but they still need to go through hit-check. 

**Current behaviour**:
![wowscrnshot_100418_125308](https://user-images.githubusercontent.com/43840468/46467668-00326980-c7d7-11e8-851c-2ebc5a8b960a.jpg)
![wowscrnshot_100418_130059](https://user-images.githubusercontent.com/43840468/46467682-09bbd180-c7d7-11e8-9537-f437b837291f.jpg)
As you can see, the log says that my spells have been fully resisted. 
**Expected behaviour**: 
I would expect it tell me that I missed my spell rather than resisted, if it's the case. If it's not, than it shouldn't have been resisted, I should've hit the mob with my Exorcism.
**Server Revision**:

**Comment by Lephidiles** [comment]
AFAIK and with as much source as you gave:

Holy resistance exist in the game but you can not stack this from other sources than spell or items that adds "All resistance" meaning you probably want get enough resistance to actually resist a holy spell.

Also Exorcism is considered a spell and is on the spell hit table. Mages and other caster don't get "Miss" on spell in TBC but rather "resisted" meaning it missed or the 1% miss that can not be mitigated in TBC.

This probably works even though i have not tested this.

Anyway add sources for this claim other than old wowhead chats or other post since people mistake this when you don't have a Holy in char tab. pref a blue post from a developer saying this has been added as a exception to the resistance table (binary or partial)

**Comment by Wolffenstein** [comment]
It can still be resisted fully even if holy resistance is not counted into it (e.g. 1% resist chance for all spells). I believe this is working correctly.
