### ISSUE TITLE
[Warrior] Hamstring rank 2 (7372) applies hamstring slow on block.

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#1270]
**Description**: 

Hamstring currently applies hamstring on a full block if hamstring is already applied - Aka duration is refreshed on a full block - unlike initial application which is not applied on block currently.

Should not refresh duration if blocked/dodged/parried or missed.

**Server Revision**: 2130

**Comment by knasen88** [comment]
why wouldn't hamstring be applied upon a block?

**Comment by Easyfraggy** [comment]
hamstring doesnt apply when attack is fully blocked. That's just how it is in TBC.

**Comment by ahlens** [comment]
Not sure about that. As I know it should block only dmg but not the effect as the attack was done. 

The other problem is that many mobs like demons or beast with no shields have the ability to parry or block. Hamstring and rend are blocked all the time.

**Comment by Easyfraggy** [comment]
@ahlens that is just blizzard for you - every mob in the game can block dodge and parry. 

I'm 100% sure you are wrong that hamstring should be applied on a full block. So as with everything you have to provide proof that current behavior is wrong - But I'm telling you already now that you won't find any because it never worked like that.

**Comment by ahlens** [comment]
It's a little bit more complicated to find any proofs regarding 2.4.3 patch, compared to 8 years ago. I haven't found any info yet but I will try to dig deeper. 

I must admit I've never seen this mechanic working that way on other private servers but I assume you might be right. In the past, many things were simply skipped from fixing due to low priority level.
