### ISSUE TITLE
Specific [Object]Power Core Fragment#186441 isn't working [Quest]Corrosion Prevention#11174

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1285]
**Description**: 
The [[Object]Power Core Fragment#186441](https://db.excalibur.ws/?object=186441) isn't working properly, video [here](https://www.youtube.com/watch?v=eZ13Axfs-5E&feature=youtu.be) it is spamming casting [[Spell]Energized!#42490](https://db.excalibur.ws/?spell=42490) as can be seen in the combat log. But I never receive the aura and thus can't use [[Item]Ooze Buster#33108](https://db.excalibur.ws/?item=33108) on [[NPC]Bubbling Swamp Ooze#4394](https://db.excalibur.ws/?npc=4394) or [[NPC]Acidic Swamp Ooze#4393](https://db.excalibur.ws/?npc=4393).

.gps here, but should also be in the video:
![99983d52a2323cf2c56dd1ae54728438](https://user-images.githubusercontent.com/34839199/46569169-59260d00-c951-11e8-9864-89abe00e7914.png)

**Expected behaviour**: 
Expected to apply aura to player.

**Server Revision**: 
2130

**Comment by Tenoutoften** [comment]
Editing title to make it easier to search up for others

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTbcBTOLD/issues/1367

**Comment by craigsurbrook** [comment]
Update to previous post. I was able to find one power core that was working. So it may be that the only problem is the power core next to the ship, where that one is always supposed to be working. Perhaps the active power core (or cores) aren't active like they should be, as well, because it is very hard to find an active power core.

**Comment by Tereneckla** [comment]
fixed
