### ISSUE TITLE
[Spell][Paladin] Seal of the Crusader makes you uselessly weak

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1315]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Applying Seal of the Crusader makes me weak as hell.
**Current behaviour**:
Before seal:
![wowscrnshot_100718_112216](https://user-images.githubusercontent.com/43505031/46580373-de79f200-ca23-11e8-9f19-eeb4c9539d78.jpg)
After applying seal (rank4):
![wowscrnshot_100718_112220](https://user-images.githubusercontent.com/43505031/46580376-e2a60f80-ca23-11e8-828f-72ef051cb361.jpg)
And it is even worse on lower ranks, because the less AP.
Maybe you tried to implement the "deals less dmg / every hit" mechanic, but it made it to deal the minimum dmg after applying the seal?
**Expected behaviour**: 
I should not deal this low dmg before hiting anything.
**Server Revision**: 
2137

**Comment by Wolffenstein** [comment]
I never found any information regarding the damage being lowered with each consecutive hit. The general consensus was that it just reduces the damage you do with melee swings, but there was nothing about a damage reduction with each hit (just general flat reduction).

**Comment by Wolffenstein** [comment]
I reduced the penalty in rev 2138, but for now I'm closing the issue since all the information I have is indicating that current behaviour is the proper one.

**Comment by Mikik3jr** [comment]
I mean look at my dps. As soon as I use the seal it reduces my dps from 59.7-->34.1 . In this state you literally pay mana to be weaker.

**Comment by Easyfraggy** [comment]
"Seal of the Crusader is NOT a good seal for DPS or tanking paladins. Although it increases your attack speed, it makes each hit deals less damage. So its real benefit in damage output is the additional attack power it provided. Obviously, this means this seal don't scale with your gear, unlike Seal of Command, Seal of Blood or Seal of Righteousness. Seal of the Crusader is only good if you have extremely low attack power. This is the reason why no experienced paladins with reasonable gear use Seal of the Crusader.
http://wowwiki.wikia.com/wiki/Seal_of_the_Crusader?oldid=1631794

**Comment by Mikik3jr** [comment]
I am a level 43 prot paladin at the moment and I removed ALL my gear. I grabbed a lv5 uncommon 2h slow sword and I checked again the seal. Even in this bad "gear" (when I am naked) I lose dps using this seal.
![wowscrnshot_101018_120409](https://user-images.githubusercontent.com/43505031/46729105-b1784a00-cc84-11e8-99f4-d7061f06f3d7.jpg)
![wowscrnshot_101018_120413](https://user-images.githubusercontent.com/43505031/46729109-b3420d80-cc84-11e8-913a-94d134a7fe4c.jpg)
![wowscrnshot_101018_120418](https://user-images.githubusercontent.com/43505031/46729111-b4733a80-cc84-11e8-884c-2b8ab43e6e91.jpg)

**Comment by Easyfraggy** [comment]
It might be applying the haste or damage reduction wrong, how much should the seal reduce damage by? My math tells me this is how it should be - reduce damage by 40% increase attack speed by 40%.  0.6*1.4 = 0.84 and then from applying the AP you should see something between .9 and 1. It does seem to lower your dps by more than 10% though.

**Comment by Mikik3jr** [comment]
But it increases my AP by 258. Even if I calculate the 14 AP = +1 dps formula, it still should give me like 18dps from ap. I still doubt that +18dps AND +40% attack speed gets that high penalty to lower my dps.

And on the wowwiki that you sent you can read "This is the reason why no experienced paladins with reasonable gear use Seal of the Crusader."and I was really not in reasonable gear at all. On Ares I experienced that on lv70 the seal increased my dps, but later when I had better gear I saw that it lowered my damage. I know that is another private server.

**Comment by Mikik3jr** [comment]
http://et.worldofwarcraft.wikia.com/wiki/Attack_power

**Comment by Mikik3jr** [comment]
Or maybe this:
https://www.wowhead.com/forums&topic=28735

**Comment by Easyfraggy** [comment]
With my calc the ap (258) you should land on 37,7 dps when using your seal with that setup you showed above currently you get to 26, which means something seems to be off here. Your video is too early, it is from vanilla.

**Comment by Mikik3jr** [comment]
I am a lv45 naked prot paladin with a lv5 green sword.
My weapon:
![wowscrnshot_101218_230413](https://user-images.githubusercontent.com/43505031/46894125-a59eaa80-ce73-11e8-982a-da282ce5b5a3.jpg)
Seal rank1 (+40 AP):
![wowscrnshot_101218_230302](https://user-images.githubusercontent.com/43505031/46894169-d848a300-ce73-11e8-8743-ecdc634f0c1f.jpg)
Seal rank2 (+67 AP):
![wowscrnshot_101218_230305](https://user-images.githubusercontent.com/43505031/46894170-d8e13980-ce73-11e8-8d7b-af6d8027edc8.jpg)
Seal rank3(+121 AP):
![wowscrnshot_101218_230309](https://user-images.githubusercontent.com/43505031/46894171-d8e13980-ce73-11e8-8a7c-ae4021c09513.jpg)
Seal rank4(+183 AP):
![wowscrnshot_101218_230312](https://user-images.githubusercontent.com/43505031/46894172-d8e13980-ce73-11e8-9331-2ad1b209ef09.jpg)
Seal rank5(+260 AP):
![wowscrnshot_101218_230315](https://user-images.githubusercontent.com/43505031/46894173-d8e13980-ce73-11e8-953d-afc6aaa04962.jpg)

Without seal:
![wowscrnshot_101218_230226](https://user-images.githubusercontent.com/43505031/46894205-ff9f7000-ce73-11e8-9f5a-3d2b0cf11240.jpg)

**Comment by Eidous** [comment]
so, to compile some research I did.

http://www.clanyawa.com/viewtopic.php?t=3363

states the following: _Crusader Strike - This is the final and best Retribution DPS ability. Deals 110% of weapon damage as Physical damage with a 6 second cooldown and refreshes all Judgements on the target. Just like Seal of Command, it scales with the base damage of your weapon. It's also treated as a melee ability, not a spell, so it can be used when silenced. This talent has been hugely buffed in 2.3 and 2.3.2, first with a reduced cooldown, and second that it no longer relies on spell damage. In 2.4.2, Seal of the Crusader no longer reduces Crusader Strike's damage._

Patch 2.4.2 patch notes states that Seal of the Crusader increases the damage done by Crusader strike by 40%.

https://forums.penny-arcade.com/discussion/comment/9486657#Comment_9486657

The above gives a formula for how SotC's damage was calculated in vanilla.

https://www.mmo-champion.com/threads/699880-Blizzard-removed-the-wrong-Seal

post #11 states: _'deals less damage with each attack' should be rewritten as 'but your melee attacks deal less damage'.

Or even more specific, 'your auto-attacks deal less damage'.

It doesn't degrade your damage as you attack, it simply lowers the weapon damage of auto-attacks due to normalization with the haste portion._

From all of the above I am led to believe that the damage decrease should serve to normalize the damage increase from the attack speed increase. Hence the damage decrease should be 1/1.4 = 0.71. This means that the dps increase from this seal comes fully from the AP that it provides.

This seems to be supported by the fact that seal of the crusader was buffed to give a 40% damage increase to Crusader strike so that seal of the crusader doesn't decrease the damage that Crusader strike does.

**Comment by Wolffenstein** [comment]
Reduced the damage penalty even more in rev 2192.

**Comment by Holdfast12** [comment]
The damage that should be given at the beginning of the seal action is intended for the paladin not to lose much damage during two strokes, switching seals between judgements. too bad!
