### ISSUE TITLE
[Quest][Hinterlands] Recover the Key! The Ancient Egg

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1320]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:
https://www.wowhead.com/quest=4787/the-ancient-egg
https://www.wowhead.com/quest=7846/recover-the-key

both quest lead to the very back of the cave in Jin'talor. This area is non-elite since 2.3 and players should be able to do this solo. Which won't be the case for many clases because the two [guards](https://www.wowhead.com/npc=2648/vilebranch-amanzasi-guard) at the end  nearly stunlock you.

**Current behaviour**:
https://thumbs.gfycat.com/GlumFirmGroundhog-size_restricted.gif
The guards stun for 2sec every 8sec. With two guards that leaves you a 4sec window to do something.

**Expected behaviour**:
I couldn't find any wowheadcomments about the stun. Most comments after 2.3 say that it's easy soloable. There are many classes that can deal with this easily but for some it's such a big punishment.

**Server Revision**: 2137

**Comment by Firroth** [comment]
I think it's because of DR timer of those abilities, normally when they stun you for 2s, next should be 1s, and next one immune to next stun for 8-10s. Right now be it stun/roots/net etc. you non-stop get full duration of them, which is insane as meele especially against mobs which use those skills and you can't even get even few hits on them.

I didn't look into it, if it's supposed to be like that on 2.0 patch where there is no DR timer for those mobs against player. But if there wasn't anything like that, then that's the issue :P

**Comment by Evolvee** [comment]
increased the cooldown in rev `hehexd`
