### ISSUE TITLE
[Quest][Object] Stones in The Stones that Bind Us become unable to interact with after one use.

### ISSUE THREAD

**Issue by FrozenBread** [Atlantiss/NetherwingBugtracker#1389]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Tried completing the quest The Stones that Bind Us http://db.excalibur.ws/?quest=2681
In the quest, you have to weaken the servants, which patrol around a Stone of Binding object (several DB entrances for the object). After weakened, they become banished so you can use the objects, which provide them of immortality. When interacted with, the object breaks and you can finish off the servant

**Current behaviour**: After using several stones once, when I came back to kill the respawn, I wasn't able to interact with the object, I also found objects which were already not able to interact with, presumably someone had already tried the quest and encountered the same problem?

**Expected behaviour**:  Objects should be able to interact with after they respawn in the world

**Server Revision**:  2137

**Comment by Firroth** [comment]
Since this wasn't wrote, but it's a rather huge issue in this quest, I will write it here. 

**Current behaviour:**

**Issue 1.** [Servant of Razelikh](https://www.wowhead.com/npc=7668/servant-of-razelikh) part works mostly fine, since they get banish/immune and you can't kill them - after using a stone you can kill them and get credit. Only issue in this part is they should "unbanish" which they don't after their "nearby" stone is destroyed.

**Issue 2.** [Servant of Grol](https://www.wowhead.com/npc=7669/servant-of-grol) - this part doesn't work at all, he gets banish/immune, but when you destroy their stone, they don't remove their banish/immune and they still can't be killed to get credit for the quest. Simply impossible to kill them, and complete the quest.

**Issue 3.** [Servant of Allistarj](https://www.wowhead.com/npc=7670/servant-of-allistarj) - same as above (look Issue 2).

**Issue 4.** [Servant of Sevine](https://www.wowhead.com/npc=7671/servant-of-sevine) - same as Issue 2 and 3 + their objects (stones) can't be interacted with.

**Expected behaviour:**

**Issue 1.** [Servant of Razelikh](https://www.wowhead.com/npc=7668/servant-of-razelikh) should "unbanish" himself and restart attacking the player after their "nearby" stone is destroyed.

**Issue 2.** [Servant of Grol](https://www.wowhead.com/npc=7669/servant-of-grol) - when their stone gets destroyed their banish should end, they should restart attacking the player and be possible to kill to get credit.

**Issue 3.** [Servant of Allistarj](https://www.wowhead.com/npc=7670/servant-of-allistarj) - same as above (look Issue 2).

**Issue 4.** [Servant of Sevine](https://www.wowhead.com/npc=7671/servant-of-sevine) - same as Issue 2 and 3 + their objects (stones) should be possible to interact with.

**Server Revision:** 
2137

**Comment by mbzz88** [comment]
This quest is now bugged in a different way, the servant mobs get the buff www.wowhead.com/spell=10794/spirit-shock, which should make them immune.
However, it does not make them immune, and they are able to be killed like a normal mob, you do not have to interact with the stone at all.

Server Revision:
2169

**Comment by Evolvee** [comment]
i specifically remember this 100% working when i scripted it :D 
this core will make me kms someday 🤕

**Comment by Evolvee** [comment]
The issue you are reporting in initial report comment is wrong, stones will only be activatable after the NPC nearby(currently 12 yards max) uses the invulnerability buff on yourself. So working as intended.

**Comment by Evolvee** [comment]
slightly reworked in rev "ff15"
