### ISSUE TITLE
[Durid][Spell] Force of Nature - Ignores target and attacks other pack

### ISSUE THREAD

**Issue by wowthings** [Atlantiss/NetherwingBugtracker#1410]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Once the treants are summoned they should be attacking instantly the ones they have near them
**Current behaviour**:
But they ignore the current target and runs for another pack, this may cause wipes.

Video:
https://streamable.com/ge2mh
**Expected behaviour**: 
Since you can't control them, once summoned they should be attacking the nearest enemy.
**Server Revision**: 
2137

**Comment by wtRCH** [comment]
@Evolvee Comment on the target please. Is it random or currently targeted target by the player.

**Comment by Evolvee** [comment]
dunno

**Comment by devo6969** [comment]
I think the Expected behavior is happening on the PTR, seems to prioritize attacking the player's target if close enough on the spawn point otherwise it goes to nearest enemy.
PTR - https://www.youtube.com/watch?v=_Oy_NR7WrwM


https://wow.gamepedia.com/Force_of_Nature
 Patch 2.1.2 (2007-06-19): This spell will no longer causes players it is cast on to enter combat with nearby creatures. All of the treants summoned will now attack a neutral creature they are summoned on.
