### ISSUE TITLE
[NPC][The Barrens] Lost Barrens Kodo

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#1449]
**Description**: 
https://www.wowhead.com/npc=3234
https://classicdb.ch/?npc=3234

**Current behaviour**:
I killed kodo's and after respawn  kodo was standing in one place

**Expected behaviour**: 
After respawn kodos should still patrolling

**Server Revision**: 
2151

**Comment by The14me** [comment]
Possible Kodo 3234: ID 7

**Comment by duzyizly** [comment]
killed few of them around stagnant oasis, after respawn they are patroling, rev 3390 ptr.
Probably fixed with leader formation month+ ago.


![WoWScrnShot_061920_204353](https://user-images.githubusercontent.com/43931626/85170754-1fed1800-b26e-11ea-9f6a-e60cb3dcb407.jpg)
![WoWScrnShot_061920_204705](https://user-images.githubusercontent.com/43931626/85170760-211e4500-b26e-11ea-9563-e6dacc94ddef.jpg)
![WoWScrnShot_061920_204713](https://user-images.githubusercontent.com/43931626/85170761-21b6db80-b26e-11ea-8e69-36a1cee06efb.jpg)
