### ISSUE TITLE
[Object][Blackrock Depths] Plans: Dark Iron Shoulders - missing plans

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1475]
[Object] [Blacksmithing Plans](https://www.wowhead.com/object=173232/blacksmithing-plans)
I guess that's the correct one, though for this one you will need to set 100% drop for Dark Iron shoulders plans, for one specific location only, rest with the same id should be 100% for dark iron mail (other locations which are already in-game)

**Current behaviour**:
Such plans do not currently exist in BRD.

**Expected behaviour**: 
They should be in this location (ONLY IN THIS ONE LOCATION) for players with Blacksmithing profession to loot.

![darkironshouldersspawn](https://user-images.githubusercontent.com/43505196/46767812-76a6fe00-cce6-11e8-9158-d79ec151c52d.jpg)

If you don't know from the screen where it still is then look on the video 0:36.
https://www.youtube.com/watch?v=WHdsVujJ2KY

Rest of the plans (4 other spawns) is for Dark Iron Mail, which currently exist and can be aquired.

![screenshot_1](https://user-images.githubusercontent.com/43505196/46768138-722f1500-cce7-11e8-863e-840e502c7ab0.png)

**Server Revision**: 
2152

**Comment by Shanghi** [comment]
## Drop chance
They were all set to 100% before, but you need blacksmithing or else it rudely disappears. It seems in some later expansion they made it so you can't interact at all if you weren't able to take it. Right now it requires 300 blacksmithing, but I think based on the comments below it should probably be 280. I can't remember why they were set to 300 before!

> "items can be looted by anyone in the group, but if you're not on the quest, all that happens is that you despawn the item, preventing anyone actually a blacksmith or on the quest from completing it until the instance is reset. So if you're not a blacksmith and/or don't have the quest, DON'T TOUCH."
>
> "Be warned if you're the only person in the group and you don't have 270 blacksmithing the object will despawn and not show anything to loot."
>
> "Make sure you have 280+ Blacksmithing before attempting to get this pattern.  I looted the plans twice at 275 and they just disappeared with no pattern.  Came back at 280 and I got them fine."

[Wowwiki](http://wowwiki.wikia.com/wiki/Dark_Iron_Shoulders): "To pick up the plans, you must have a Blacksmithing level of 285. If anyone else tries to pick up the plans, they will get nothing and the plans will be destroyed."

***
## Locations

I'm not so sure about that being the only spawn location for shoulders, especially since he says "this plan will possibly take you a long time to get to spawn" which could mean he keeps missing the other place!

> From 3.0.3:
> "The other I found in one of the rooms behind the High Interrogator Gerstahn during the same sweep."
>
> The rest from 4.0+:
> "I'd like to say that there's a spawn point not mentioned in this post behind Gerstan over in the Detention Block.  There are 4 rooms behind Gert's room, the northeasterly room has a table that can have a blacksmithing plans scroll on it.  I got my Dark Iron Shoulders plans on this table."
>
> "Found one on a bench in the Detention Block."
>
> "Found another location not mentioned above for these plans tonight on a table in the Detention Block..."
>
> "Thank you, I was checking all the spawns listed above with no luck. This was the one"
>
> "Best bet for these plans. Got them first go!"
>
> "Awesome advice - ty so much - tried the others with no luck. Still works post 5.3"
>
> "Perfect, I found them exactly there on the first attempt, after trying a few times on the other location"

**Comment by Firroth** [comment]
I think they are saying it about other location of another spawn for Dark Iron Mail plans (since it got 4+), not shoulders. Shoulders only had one. Too many comments about getting them only from this one spawn, after a lot of "farming other" plans (dark iron mail, thinking it would also give shoulders).

![screenshot_1](https://user-images.githubusercontent.com/43505196/46787086-10969700-cd37-11e8-9522-5f94a182ae90.png)
![screenshot_2](https://user-images.githubusercontent.com/43505196/46787087-10969700-cd37-11e8-88ea-c4a5ba3d2633.png)
![screenshot_3](https://user-images.githubusercontent.com/43505196/46787089-112f2d80-cd37-11e8-9f7a-427d432083ff.png)

In one post you can see comment "After AGES of farming, I can confirm this. The four other Plan locations always dropped Dark Iron Mail for me, while the first and only time they spawned in this location I got the Dark Iron Shoulders. Just keep trying until it shows up in this spot."

Meaning he must have tried a lot to loot from the other locations and always got chest not shoulders.
Either way I can just say I personally experienced it the same way, though I guess it's no much proof.

**Comment by Shanghi** [comment]
Some of them are surely confused and didn't know that 4 places will only have the mail, but some of them specifically mention the Detention Block area while talking about getting the shoulders there and none of the 4 mail spawn points are in that area. I thought it may have been a new one for Cataclysm too, but that 3.0.3 guy mentions it and he's specific about getting both in the same instance run so it couldn't have been mail.
![image](https://user-images.githubusercontent.com/2672633/46797807-2ea3cd80-cd1e-11e8-9c8d-8251b3bece0d.png)

**Comment by Firroth** [comment]
Maybe your view is the correct one. Anyway since it's vanilla related, as long as it does it's intended work - object with plans available and can aquire those plans no matter from which spawn, it should be enough in my opinion. It's simply not worth wasting time, just to look for info that it should indeed spawn in 1 or other locations too :d 

So all what needs to be fixed is too add object in the place where it's missing, and as long as it will provide plans (preferably 100% on dark iron shoulders, as comments state) should be good enough. You can also add it to other spawns too I think.

**Comment by Shanghi** [comment]
The shoulders already have a spawn point set at the bed place too so it's just random between there and the detention block room each instance (and the mail plans already have their 4 separate places too where 1 of those are picked for it).

They all have a 100% drop rate too, but only drops for blacksmiths. In revision 2175 it was changed to require 280 blacksmithing instead of 300 based on a comment where someone tried 275 twice and it didn't work, but did work at 280. Other comments said 290 and something else I forgot now, but I just trusted the lowest that seemed reasonable so hopefully it's all fixed now!
