### ISSUE TITLE
[Core] Crit Calculation v2

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1560]
**Description**: 
Missed weapon skill in the first report (Thanks Evolve for clarification) but there are still some things related to weapon skill that are wonky (at best).

Level 50 Warrior, specced 31/10/0 with Sword Spec and 5% crit in Fury tree.

**Current behaviour**:
Before equipping any weapon: 
![wowscrnshot_101318_122422](https://user-images.githubusercontent.com/20336567/46904349-f6012100-cee2-11e8-8f1c-543df6a67326.jpg)

You can notice that I have 6.63% crit even though the Agility Calculation shows I should have at least 7.79%. 

Fyi, you can probably only recreate this if you have different weapon skill for unarmed, sword and axe because after Evolve set all my weapon skills to 250 I was not able to reproduce this anymore. Then try to change between axe and sword (that have different weapon skill) and try to unequip the weapons and/or replace the weapons.

For reference issue #1559 which is partly flawed because I forgot that weapon skill results in different crit ratings.

**Server Revision**: 
[2169]

**Comment by Azalen** [comment]
On a sidenote - should weapon skill really change the tooltip crit rating? The way I understood it it comes down to the enemies defense rating as well so the tooltip will never be accurate.

**Comment by Peglaa** [comment]
There is something definitely wonky here, I just never figured out what. I noticed these char sheet issues with crit rating way back in alpha, but I never figured out what caused them and reproducing them was troublesome.
If I had to make a guess, I would say it could be some auras not updating or refreshing when a change occurs like switching weapons or similar. 
As for the char sheet, It should definitely update itself based on weapon skill because it automatically takes into consideration the defense rating of a target that is your level. If you level up you will notice your crit go slightly down because you gained no crit rating on lvl up but defense rating is higher at that level. If you raise the weapon skill to max range for that lvl it should go back up slightly.(I think this is how it works with updating but not 100% sure).

**Comment by Easyfraggy** [comment]
Further playing around, this might just be an update thing?'

With 5/5 crit this adds up perfectly.
![image](https://user-images.githubusercontent.com/36134067/46910138-a3098700-cf3f-11e8-853b-a43c4404e4d0.png)

![image](https://user-images.githubusercontent.com/36134067/46910119-5cb42800-cf3f-11e8-9452-f28d04564f41.png)

**Comment by Easyfraggy** [comment]
Seems to just be unarmed not getting benefit from agility.

**Comment by Easyfraggy** [comment]
Might just be an update issue.

Fresh char - level to 70 and do .maxskill
![image](https://user-images.githubusercontent.com/36134067/46910194-8ae63780-cf40-11e8-8bd3-eb7b110386ba.png)

Relog same character:
![image](https://user-images.githubusercontent.com/36134067/46910201-a5b8ac00-cf40-11e8-958e-579384c08133.png)
