### ISSUE TITLE
[misplaced NPC]Reginald Windsor riding around in Stormwind City.

### ISSUE THREAD

**Issue by Dosdaltherir** [Atlantiss/NetherwingBugtracker#1564]
**Description**: 
Reginald Windsor - the NPC who unmasks Onyxia, and is a part of the Onyxia Attunement questline, is riding around in Stormwind City. 
**Current behaviour**:
Reginald Windsor is riding around in Stormwind City without anyone having begun the quest "The Great Masquerade". 
**Expected behaviour**: 
Reginald Windsor should not be present in Stormwind City, unless some one has accepted the quest "The Great Masquerade"
**Server Revision**: 
rev: 2169.

**Comment by Firroth** [comment]
It doesn't mean he should only be during quest in Stormwind. Before Onyxia and BWL were released (attu for onyxia) he was patrolling Stormwind like he is doing now. When attunement was added, he was removed, for it's sake. So yeah, he shouldn't be there, since we're already "after onyxia" not before and he shouldn't be patroling in SW. 

https://github.com/TrinityCore/TrinityCore/issues/20743

So there are 2 options: either remove him from SW since we're already past this point OR just leave him be for visuals sake (more moving npc's = world more alive = better experience).

**Comment by aresbrutus** [comment]
He will be riding through Stormwind until we fix vanilla raids and accompanied quests.

**Comment by Evolvee** [comment]
fixed
