### ISSUE TITLE
[Spell][Rogue] Ruthlessness talent proc

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1645]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
It's seems that the spell procced out of itself. I used Slice and Dice. By that, there's a 60% chance of getting one combo point, and one combo point only. But, for some reason, I got 2 combo points. I had the feeling that it had happened multiple times already, but this time I was paying attention and saw it with my own eyes (I was unarmed, so there's no chance of using sinister strike or whatever accidentally).
**Current behaviour**:
Ruthlessness is "Proccing out of a proc"
**Expected behaviour**: 
You should only get 1 combo point in a proc, never 2.
**Server Revision**: 2179

**Comment by Dusky1** [comment]
Can confirm that. Ruthlessness sometimes adds two combo points. Also, proc chance seems to be VERY big. Its like 90%. Its hard not to get combo point

**Comment by NikiProToss** [comment]
I'd like to add that "initiative" talent (tier 3 subtlety tree) also works 100% of the times based on my sestings in Durotar.

**Comment by ahlens** [comment]
"Initiative" has 75% which is high enough to proc almost all the time. I think it works correct.

When it comes to Ruthlessness I confirm that it can add one more cp. It seems like it proc from itself but I haven't noticed more cp being added. So it can add 1 or 2 cp.

**Comment by Phibs77** [comment]
I've tested it a bit:

Out of 288 Slice and Dice i got:
36x    12,5%  0 ComboPoint
150x  52,1%  1 ComboPoint
102x  35,4%  2 ComboPoint

When calculating 2 independant and consecutive rolls with 60% chance for a +1 ComboPoint and 40% chance for a +0 ComboPoint you would get with enough samples:
16% 0 ComboPoint (+0 and +0) (0,4*0,4=0,16)
48% 1 ComboPoint (+1 and +0; +0 and +1) (0,6*0,4+0,4+0,6=0,48)
36% 2 ComboPoint (+1 and +1) (0,6*0,6=0,36)

Comparing the numbers we can conclude that Ruthlessness gets calculated twice instead of once.
(Numbers are slightly off, probably because my assumption is either wrong or i got a bit unlucky with the low amount of samples i did. :))

**Comment by Wolffenstein** [comment]
Fixed in rev 2380.
