### ISSUE TITLE
[Quest] Set them Ablaze - The Torch of Retribution

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#1700]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The tower doesn't go on fire after using the torch of retribution
**Current behaviour**:
The tower doesn't go on fire after using the torch of retribution
**Expected behaviour**: 
The tower should go on fire after using it.
**Server Revision**: 
2186

**Comment by Tenoutoften** [comment]
Figured I'd post some evidence since zero was provided, here is a picture on [wowhead](https://www.wowhead.com/quest=3463/set-them-ablaze#screenshots)
https://wow.zamimg.com/uploads/screenshots/normal/11156-set-them-ablaze-the-flaming-sentry-tower-after-being-set-ablaze.jpg

posted 23rd of december, 2006.

**Comment by Mewmewww** [comment]
I need to check that window and see if it actually burns there. I assumed it would be on the platform you were standing on. 2 seconds.

**Comment by Evolvee** [comment]
rev Block
