### ISSUE TITLE
[Quest][Dustwallow Marsh] Marg speaks

### ISSUE THREAD

**Issue by natoxz** [Atlantiss/NetherwingBugtracker#1792]
**Current behaviour**:
Questitem Jeweled Pendant doesn't drop

**Expected behaviour**: 
Questitem should drop

**Server Revision**: 
before todays server update

**Comment by Tenoutoften** [comment]
It dropped for me when I leveled(Twice, because I had one early so I deleted it to verify that it had a low drop chance)
![1a0d89648b7f0ab93bb610c011bcf43c](https://user-images.githubusercontent.com/34839199/47280174-6855bd80-d5d5-11e8-9928-c8a3715cedfb.png)
![55a3286fb69430fa027dfab27b0199cf 1](https://user-images.githubusercontent.com/34839199/47280175-68ee5400-d5d5-11e8-9dd6-4ec5b1148f5e.png)
![55a3286fb69430fa027dfab27b0199cf](https://user-images.githubusercontent.com/34839199/47280176-6986ea80-d5d5-11e8-92dc-226bb0319262.png)
![b5132afcf78e23bfa72bc18a3102e27b](https://user-images.githubusercontent.com/34839199/47280177-6986ea80-d5d5-11e8-939c-028195e89cc0.png)
![cc7b05dbe068c08a3975f6e5efa22bfb](https://user-images.githubusercontent.com/34839199/47280178-6a1f8100-d5d5-11e8-8ed7-5636e76bcf84.png)

Please tell us how many you killed

**Comment by Tenoutoften** [comment]
It's a low drop chance item:
![1a0d89648b7f0ab93bb610c011bcf43c](https://user-images.githubusercontent.com/34839199/47280221-87544f80-d5d5-11e8-9eaf-f6ea734e4dd9.png)
![55a3286fb69430fa027dfab27b0199cf 1](https://user-images.githubusercontent.com/34839199/47280222-87ece600-d5d5-11e8-9776-935997368f68.png)
![55a3286fb69430fa027dfab27b0199cf](https://user-images.githubusercontent.com/34839199/47280223-88857c80-d5d5-11e8-80c0-5ea1c52c6f4d.png)
![b5132afcf78e23bfa72bc18a3102e27b](https://user-images.githubusercontent.com/34839199/47280224-88857c80-d5d5-11e8-8912-5d5ab4d03df1.png)
![cc7b05dbe068c08a3975f6e5efa22bfb](https://user-images.githubusercontent.com/34839199/47280225-891e1300-d5d5-11e8-93a4-c8c1c103c6d4.png)

I've grinded two of them on this server... how many did you kill?

**Comment by aresbrutus** [comment]
Nothing is wrong with this item. It drops but has a low drop chance so it might give you the illusion that it is not ever going to drop.
