### ISSUE TITLE
Gray level enemies give experience

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1883]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
On the picture I am level 51 and I killed a lv42 wolf. Lv43 enemies were green to me and it switched gray after lv42.
**Current behaviour**:
![wowscrnshot_102518_165241](https://user-images.githubusercontent.com/43505031/47515945-6d8c6400-d884-11e8-9106-56775f9677d0.jpg)
(I killed another lv42 non rare enemy just in case and it still gave me exp)
**Expected behaviour**: 
I don't think I should get exp from gray enemies.
**Server Revision**: 
2214

**Comment by ScottieDOESknow** [comment]
At that level (51) 
level ≤ 40 should be gray and 41+ should be green

https://gyazo.com/1363003b7af2cb9330ae54250d1df15a

**Comment by Easyfraggy** [comment]
Actually Scottie has a point, how come lvl 42 mob is grey to you at 51 🤔

**Comment by Mikik3jr** [comment]
Is that a client issue?

**Comment by Peglaa** [comment]
The formula for con level is probably busted. Those grey NPCs should give XP because they aren't really grey but are visually shown as grey. The formula for showing con difficulty colors is prolly off. 
This is the correct one for certain levels:
![2018-10-27_22h36_20](https://user-images.githubusercontent.com/15163719/47609117-e92f1200-da38-11e8-80ea-1499e35fab1f.png)

by this formula only lvls 40 and down are supposed to be shown as grey and if you go and kill a lvl 40 mob at lvl 51 you will see that you get no XP(if that part is working correctly which I think it is). So it's mainly a visual issue and using that formula in the picture should fix it. I'm guessing this is something that can be fixed, dunno.

**Comment by xmesaj2** [comment]
fixed in rev 2330, client will show them as grey but lvl<=40 won't give exp anymore, 41 will still give it despite being gray
