### ISSUE TITLE
[Quest] Blessing of the Ancients

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2084]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/quest=9785/blessings-of-the-ancients
Getting the buffs from the ancients does not count towards progress of the quest.
**Current behaviour**:
![wow 2018-11-01 18-39-30-18](https://user-images.githubusercontent.com/43872263/47868960-eb60ea00-de05-11e8-8a01-028b834600e4.jpg)

**Expected behaviour**: 
Should get credit for getting the buffs. 
**Server Revision**: 
2244

**Comment by zauru7** [comment]
can also confirm, no progress when getting buff

**Comment by mhdemn** [comment]
still bugged, server revision 2253

**Comment by Defgha** [comment]
still bugged

**Comment by oootmoo** [comment]
still bugged

**Comment by mhdemn** [comment]
I did something close to this, so I'm guilty too. Point is you don't need to comment every few days that it is still bugged, it is in the to-do list, issue isn't closed, saying it's still bugged doesn't serve any purpose. Devs know already.

Adding footage for clarification is ok, suggesting solutions/possible causes is ok, giving more detailed info or adding related malfunctions is also ok. But just saying it's still bugged is unnecessary and annoying since every participant gets an email everytime somebody comments. Thanks for reading and not commenting yet again that it's still bugged.

**Comment by miviv1268** [comment]
still bugged for me too

**Comment by aresbrutus** [comment]
Fixed by Pelekon in rev `2320`
