### ISSUE TITLE
[Talent/Mechanic] Improved Shadowbolt talent

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#2174]
Improved Shadowbolt talent: Your Shadow Bolt critical strikes increase Shadow damage dealt to the target by 20% until 4 non-periodic damage sources are applied. Effect lasts a maximum of 12 seconds.

Currently when you get a crit with Shadow Bolt, only 3 charges of Improved Shadow Bolt debuff appear on the target and the first crit (which applied ISB debuff) does not gain the 20% bonus. This is resulting in the Warlock losing out on one charge of 20% stronger shadow damage on the target.

I believe that the initial crit of Shadow Bolt should receive no bonus damage AND THEN have 4 charges of Improved Shadow Bolt be applied to the target.

**Comment by BezawitNW** [comment]
I just received a crit and had 4 charges appear so I'm not sure what is sometimes causing the 3 charge issue.

**Comment by BezawitNW** [comment]
Here is a clip from stream: https://clips.twitch.tv/HeartlessObedientTildeFloof

**Comment by Balanarr** [comment]
This still occurs

**Comment by LostInLyrics** [comment]
Could you give an update on this issue? 

I know you have a lot of other stuff to work on, but this is an important class bug which makes locks lose a substantial amount of dmg.

**Just to repeat:** If a Shadow Bolt crits, it should apply 4 stacks of the Improved Shadow Bolt debuff to the target. Currently only 3 get applied because the crit Shadow Bolt that applied the debuff already used the 4th one (but without getting the +20% bonus dmg). The obvious cause for this would be spell delay being strange, but I'm sure you will find the reason either way.

(Proof from today: https://gyazo.com/4fd0de00451385b7de90cbf7aae262e7)

**Comment by LostInLyrics** [comment]
@Wolffenstein Can we get any update on this?

**Comment by gemt** [comment]
I have yet to see 4 stacks of ISB a single time.

**Comment by Wolffenstein** [comment]
Fixed in rev 2862.
