### ISSUE TITLE
[Dungeon][The Underbog] Underbog bugs.

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#2216]
Chests and Sanguine Hibiscus respawning on cleared dungeon after some time, making it abuseable to farm.
[Lost in Action] Windcaller Claw discovery didnt counted for me because I was dead and didnt count for me when I came back to talk to him.
![wowscrnshot_110318_204932](https://user-images.githubusercontent.com/41975070/47955531-4e878380-dfa2-11e8-923b-df4d9de892fa.jpg)
Swamplord Muse'lek aimed shot hitted me (66 lvl druid 9-11k armor, 8k hp) for 11.5k first time and 10.2k second time. Not sure if its bug or inproper tactic for boss, but Im pretty sure tanks not supposed to get oneshotted.
![wowscrnshot_110318_195358](https://user-images.githubusercontent.com/41975070/47955529-43ccee80-dfa2-11e8-8c4d-6da107ea03a3.jpg)

**Comment by mhdemn** [comment]
2304 update
**Heroic** Underbog
The [Underbats](https://db.excalibur.ws/?npc=20185) seem to trigger the extra damage in their [Tentacle Lash](https://db.excalibur.ws/?spell=37956) every time, regardless of their position around their target, resulting in way too much damage taken by the tank. There's groups of these mobs with up to 4 of them, one is barely tankable if you don't get lucky.

**Comment by Ceago** [comment]
Not sure about the rev but as of 11/20 the Underbats still do Tentacle Lash almost as soon as they pull and without 2 CC will instant kill tanks on the pulls that have 4 of them.

**Comment by DragunovUA** [comment]
fix when guys? not fixed since November, for real? u joking right?

**Comment by DragunovUA** [comment]
#4925 4925

**Comment by someaddons** [comment]
still getting oneshots from 11k aimeds

**Comment by devo6969** [comment]
seems fixed, hit for 4.8-6k on a plate wearer (52.94%) 11879 armor reduction and 11-13k on my naked mage. in regards to Claw not completing, if you released, and they killed him you obviously wouldn't get credit cause you "weren't there".

**Comment by devo6969** [comment]
- Waited 1 hour 15 mins, none of the Hibiscus spawned on a cleared Heroic UB that i picked. 
- You didn't get credit because you released, "you weren't there", they probably talked to him before you came back, triggering it.
- Multiple comment stating how much aim shot hits for from 3.1 and was nerfed in 3.2 (hotfix)

https://www.wowhead.com/npc=17826/swamplord-muselek#comments
"Then Swamplord aimed shot hit (not crit) me for 10,000."

https://wow.gamepedia.com/Swamplord_Musel%27ek
WOTLK "Hotfix (2009-05-07): "The damage done by Swamplord Musel'ek's Aimed Shot ability has been reduced and be more in line for players at the appropriate level to face him."

**Comment by Wolffenstein** [comment]
Credit will be given to dead players in rev 3495.
