### ISSUE TITLE
Trinkets don't share cooldown

### ISSUE THREAD

**Issue by Shiek94** [Atlantiss/NetherwingBugtracker#2290]
**Description**: 
Trinket's with the same effect do not share coodown (possibly also trinkets with different effects)

**Current behaviour**:
For example 2 trinkets that both grant AP on use don't share a cooldown, so you can use both of them at once, while the 2nd used trinket overwrites the AP buff from the first, both go on CD.

**Expected behaviour**: 
There should be a cooldown of 30 seconds for the second trinket after the first one got used.

**Server Revision**: 
2253

**Comment by HopelessRomant1c** [comment]
It seems like like CD right now is 1m30s instead of 30 seconds.

**Comment by Colovion** [comment]
Just had this similar bug happen:

When I use Trinket A, Trinket B cannot be used until the first one comes off cooldown. You can click it and it looks like it's not on cooldown, the hands glow, but it will say it's not ready yet. It basically makes one trinket dead and unable to be used, it seems to be "locked" until the 90 seconds elapses for the first trinket, rather than the 15~second standard.

I tried logging in and out and switching trinkets into different slots, to no avail.

**Comment by Colovion** [comment]
Also just replicated this bug:

https://github.com/cmangos/issues/issues/1807

**Comment by maidros** [comment]
I typed up a new ticket but saw that this one was already active, so here is another occurrence of this bug on spell damage trinkets: 

**Description**: 
I have two trinkets, Scryer's Bloodgem (item 29132) and Xi'ri's Gift (item 29179), both have an on-use effect that is literally the same effect, Spell Power (spell 35337). They appear to put each other on cooldown for 15 seconds, but using one makes the second unusable for 1.5 minutes.

**Current behaviour**:
Using one puts it visibly on cooldown for 1.5min and the other on visibly cooldown for 15 seconds, however attempting to use the second one after 15 seconds does not work.

**Expected behaviour**: 
Either both trinkets should clearly display a 1.5min cooldown to the player when either is used, or alternatively, you should be able to use one and then the next after 15 seconds, since that's what the UI tells the player.

**Server Revision**: 
AtlantissCoreTBC - Server Revision: 2928 [Branch: master, Hash: b6fca9f53a31]

**Comment by KevinTyrrell** [comment]
I also am having the same issue with Bladefist's Breadth and Ancient Draenei War Talisman. Seeing the users above, it's clear that when two trinkets with the exact same effect are triggered, it puts the entire cooldown for both. Effectively only allowing one cooldown for both. This severely affects the viability of many trinkets.

Please implement a system where individual trinkets have their own cooldowns, not the spell itself going on cooldown.

Server Revision 2950

**Comment by devo6969** [comment]
On the PTR:
Bladefist's Breadth + Ancient Draenei War Talisman = fixed
Scryer's Bloodgem + Xi'ris Gift = fixed
All of these are usage 15 seconds after which ever one is poped.
