### ISSUE TITLE
[Loot] Venomtail Poinson Sac stop dropping after finishing non-repeatable quest

### ISSUE THREAD

**Issue by Jezofine** [Atlantiss/NetherwingBugtracker#231]
**Current behaviour**:
If you finish quest [Finding the antidote](http://db.hellfire-tbc.com/?quest=813) but lose antidote for some reason, [Venomtail Poison Sac](http://db.hellfire-tbc.com/?item=4886) never drops again and it's impossible to finish [Need for a Cure](http://db.hellfire-tbc.com/?quest=812).

**Expected behaviour**: 
I don't know how it was on retail but they should drop for repeatable quest Finding the antidote.

**Server Revision**: 2028

**Comment by aresbrutus** [comment]
This is probably the same bug with the timed/failed quests disappearing for some reason.

**Comment by Shanghi** [comment]
After losing the antidote, did you go back and retake the Finding the Antidote quest before trying to get the items again? I just tried it and could take it over and over (while on the Need for a Cure quest), and each time the poison sacs still dropped.

**Comment by Jezofine** [comment]
I finished Finding the Antidote, and it became repeatable blue. After that I abandoned quest Need for a Cure, cause i was failed. It also destroyed my antidote. After retaking Need for a Cure poison sacs never dropped again.

**Comment by Shanghi** [comment]
You still need to go back and accept Finding the Antidote again. It's one of those quests where you need it in the quest log instead of just taking items to him and completing it instantly there. I just tried it a few ways, like:
1. take Need for a Cure -> take Finding the Antidote -> wait until failed then abandon Need for a Cure -> take Need for a Cure -> poison sacs still drop because Finding the Antidote was still in the quest log
2. take Need for a Cure -> take and complete Finding the Antidote -> abandon/retake Need for a Cure -> take Finding the Antidote again -> poison sacs drop again
3. take Need for a Cure -> take and complete Finding the Antidote -> destroy antidote in front of quest person maliciously -> retake Finding the Antidote -> poison sacs drop again

**Comment by Jezofine** [comment]
I finished Finding the Antidote, and it became repeatable blue. After that I abandoned quest Need for a Cure, cause i was failed. It also destroyed my antidote. After retaking Need for a Cure poison sacs never dropped again.

**Comment by Jezofine** [comment]
I'm sorry, maybe I was wrong or maybe some glitch did let me accept Finding the Antidote after completing it that time.
I've checked again, and it works as you described, everything's good.

**Comment by aresbrutus** [comment]
Closing it then, thanks for rechecking Jezofine.
