### ISSUE TITLE
All-Follower Entities Stand On Same Spot

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2331]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Twitch Clip](https://clips.twitch.tv/HonorableGiantCarrotRuleFive)

**Current behaviour**:
All followers, whether they are pets, non-combat pets, follow-escorts, or temporary summons (barov peasant collar) will follow you directly on the left on the same x,y coordinate.

**Expected behaviour**: 
Mobs should spread naturally around you. The exact implementation of this should be researched.

**Server Revision**: 
2255

**Comment by KevinTyrrell** [comment]
[Twitch Clip](https://clips.twitch.tv/TemperedKindCrowTebowing)

Followup: In one quest I had in Felwood I was given a pet cat as a guardian pet to follow me. When given to me, the pet actually was displaced to the side of my regular pet, allowing both to be visible. I'm not sure if this is correct or not but it does look better than both pets stacked on the same x,y coordinate.

However, the moment the guardian pet got in combat, his new place besides the master was on the same x,y coordinate as my pet. Would like to hear your guys opinions.

**Comment by devo6969** [comment]
This is still happening but I looked at as much videos as i could and I'm pretty sure this is as intended, wasn't well thought of back in the day having 3 pets stack upon eachother. I know Retail they naturally surround you. I been looking at old videos/patch notes and the only thing i can find that comes close to this issue is:
(2019 video)https://youtu.be/-bXLefUL8rc?t=244
The turtle even bugs out for reasons I don't know. The turtle still is on the left side on the hunter though. For Companion pets I don't know when they changed the movement of the pet but when i logged on Retail BFA it would patrol behind me. If anyone can find the patch note date if there is even one would be great help.

PTR - https://www.youtube.com/watch?v=2GAi4GczeMM

**Comment by Tereneckla** [comment]
https://www.youtube.com/watch?v=SJyZQ0fpsg4
Barov Servants spread around each of the shamans at the end.


![image](https://user-images.githubusercontent.com/50233983/86574609-5fa64600-bf76-11ea-9fd2-a3acb31fe169.png)
Current behaviour.

**Comment by Zarant** [comment]
If you use the classic client as reference you will see that non combat pets will always stay behind the player, and the same thing happens for quest npcs however, the distances where they are positioned are different.

https://youtu.be/1cfc3KLPKj0?t=314

![image](https://user-images.githubusercontent.com/26726709/86617466-a18eb680-bf8d-11ea-9fe9-5f6d66505f9f.png)

**Comment by Godmatik** [comment]
Wolf already fixed this in previous revision (mobs not spreading), can be closed
