### ISSUE TITLE
[NPC] Raven's Wood Ent

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2436]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Summoned NPC from Raven's Wood Leafbeards.
**Current behaviour**:
Currently they aren't despawned and they are only lvl 53. (21583, 1) and (21583, 2)
**Expected behaviour**: 
Should despawn and not be lvl 53.
**Server Revision**: 
2256

**Comment by Easyfraggy** [comment]
I have not yet been through this area for corrections - we had some problem with sniffs this week when I had time. I hope to fix this area in the coming week.

**Comment by mhdemn** [comment]
Forgot to add that after server went down to apply 2273 (Although now it's 2279, not sure if it was on actual 2273 or it went straight to 2279) all the Leafbeards and Stonebarks in the area were neutral. I think it's an unintended change since databases have these guys as hostile towards both horde and alliance.
I didn't do more research regarding the Exorcism Feather after this change.

**Comment by Evolvee** [comment]
rev qwe
