### ISSUE TITLE
Berserking does not reduce cast speed by 10-30%

### ISSUE THREAD

**Issue by mantusks** [Atlantiss/NetherwingBugtracker#2442]
At 95% health, a 2.5 second cast time was reduced to 2.38 seconds. This is not 10% or 11% for that matter.

**Comment by Easyfraggy** [comment]
Read my reply to your previous haste post. PLEASE research things before reporting you are 4/4 invalid so far.

**Comment by Easyfraggy** [comment]
This is what a valid report of this issue would have looked like: https://github.com/Atlantiss/NetherwingBugtracker/issues/2450

**Comment by AndrewNB41191** [comment]
https://www.youtube.com/watch?v=pQ-q-s4tDqA here is footage that i found that actually proves that you are right! sorry for wasting your time regarding the mater. That being said, there still might be something coded wrong on the beta. upon further testing after creating a mage myself i think its the troll racial berserking that is behaving incorrectly. im happy to make a new github report on that if needed but just gonna post it here to add to the discussion. according to your formula cast time with a 10% haste (full health) from berserking should be 2.5/1.1=2.27. coupled with icy veins should be 2.5/1.3=1.92. however on the beta server a 10% berserking yields a value of 2.38 (5% actual value observed) and coupled again with icy veins is 1.98 (6% value observed? (after solving for the value berserking is providing)) 

copy pasted this from my icy veins post since this is probably where it should belong?
