### ISSUE TITLE
Hunter's pets bug compilation [Hunter] [Pets]

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#2452]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Hunter's pets doing to much damage. I diged some info about pets scaling, formulas, etc. That what I found. Mostly I used this site do dig info: http://web.archive.org/web/20080512055026/http://petopia.brashendeavors.net:80/index.php. This is a wayback machine of petopia (some kind of pet's wowhead). All tests made without any talents and with "Content" Happynes (100% of normal pet damage), so pets stats are in basic state.

**Current behaviour**:

1)
 First of all "All pets now have a base attack speed of 2.0."  Patch 2.0.8. 
http://web.archive.org/web/20070302082031/http://petopia.brashendeavors.net:80/index.shtml
On Netherwing:
![wowscrnshot_110718_164713](https://user-images.githubusercontent.com/43533040/48159840-f375c980-e2de-11e8-8f0f-76662b947fbb.jpg)
![wowscrnshot_110718_211605](https://user-images.githubusercontent.com/43533040/48159845-f5d82380-e2de-11e8-92e6-e0fae52538be.jpg)
This is important, becouse with BM talents + Lightning Reflexes Cats will have 0.6-0.7 attack speed, which is real pain for casters on Arena.

2)
 Pets stats. Starting with Patch 2.0, hunter pets now benefit from "pet scaling". Pet scaling just means that your pet gets to add some of your stats to his own stats, so that his power scales with your power. The basics are very simple:
Pets get about 30% of the hunter's stamina added to their stamina.
Pets get about 35% of the hunter's armor added to their armor.
Pets get about 22% of the hunter's ranged attack power added to their melee attack power.
Pets get about 12.5% of the hunter's ranged attack power added to their spell damage.
Pets get about 40% of the hunter's resistances added to their own resistances.
http://web.archive.org/web/20080512054116/http://petopia.brashendeavors.net:80/html/articles/stats_scaling.php
Stats above scale correct on Netherwing. But Pets Strength, Agility, Intellect, Spirit - is static for every lvl and for every pet tipe.
http://web.archive.org/web/20080512054051/http://petopia.brashendeavors.net:80/html/articles/stats_attributes.php
Example(this is from wowwikia):
![char_pet_tab](https://user-images.githubusercontent.com/43533040/48160452-911dc880-e2e0-11e8-9a75-75f5dec4a324.png)
Stats like shown in table.
On Netherwing:
![wowscrnshot_110718_211605](https://user-images.githubusercontent.com/43533040/48160611-fa9dd700-e2e0-11e8-8458-af4d934b3c56.jpg)
![wowscrnshot_110718_164713](https://user-images.githubusercontent.com/43533040/48160616-fd003100-e2e0-11e8-9d37-c3152c2d11c5.jpg)
Ammount of Agility, Intellect, Spirit is wrong. Int and Spirit not so important, but agility increase pets crit rate.

3)
 Attack power scales wrong. Every 14 AP should increase DPS by 1. Tooltip of pet attack power prove it:
![wowscrnshot_110718_230707](https://user-images.githubusercontent.com/43533040/48160945-f4f4c100-e2e1-11e8-8b35-62f28e37d82e.jpg)
153AP/10.9DPS = 14
On Netherwing pets got double DPS increase from AP.
Proves:
This is normal state pet with 181 AP(it's wolf, wolf family haven't any damage multipliers):
![wowscrnshot_110718_174854](https://user-images.githubusercontent.com/43533040/48161977-8b29e680-e2e4-11e8-812a-0ebf67dd285a.jpg)
This is the same pet, but with warriors Demo Shout(AP decreased):
![wowscrnshot_110718_174948](https://user-images.githubusercontent.com/43533040/48162259-45215280-e2e5-11e8-94a7-f9ffa652ec12.jpg)
Same pet, same warrior, but warrior with 4/5 Improved Demo Shout talent:
![wowscrnshot_110718_233532](https://user-images.githubusercontent.com/43533040/48162514-fd4efb00-e2e5-11e8-9581-9f657f7780ba.jpg)
Last screen shows base pet damage (18-28) without AP, this damage depends on pet lvl.
Second screen shows us pet attack speed - 2.0.
So base pet DPS is: (18+28)/2= 23(average damage); 23/2= 11.5(base DPS).
With 36AP(second screen) pet damage should be:
(11.5 + 36/14)*2=28.2(average damage) 23-33(damage with 36 AP).
But as we can see on screen it's 28-39. 33.5(average damage) 33.5/2=16.8 DPS
And now lets count DPS gain from AP:
16.8(36AP DPS) - 11.5(base DPS)= 5.3 DPS gained from 36AP. 36/5.3= 6.8AP need for 1 DPS, but should be 14.
Same calculations for 181AP.
181AP damage 69-80. 74.5 average damage. 37.3 DPS.
37.3 - 11.5(base DPS)= 25.8DPS gained from 181AP.
181/25.8= 7AP need for 1 DPS, but should be 14.
Damage should be:
(11.5 + 181/14)*2=48.8(average) 44-54.
44-54 vs 69-80. As much attck power pet will gain, more difference will be, and this is without any multipliers.

4)
This is Lupos(rare wolf from Duskwood):
![wowscrnshot_110718_161205](https://user-images.githubusercontent.com/43533040/48164046-12c62400-e2ea-11e8-91be-19facb3f8af9.jpg)
And he's doing Shadow damage. =)
![wowscrnshot_110718_162949](https://user-images.githubusercontent.com/43533040/48164125-4a34d080-e2ea-11e8-8bd9-036bdd77e9e7.jpg)
Which means he ignoring target armor.
http://web.archive.org/web/20080512054523/http://petopia.brashendeavors.net:80/html/mobs/mob_lupos.php
"Lupos was once everyone's favorite wolf because he inflicted shadow damage instead of physical damage with his attacks. Alas, this is no longer the case." He was nerfed in patch 1.7. All TBC pets doing physical damage with melee swings, some abilities (like Lightning Breath) doing spell damage.

Now imagine all this bugs (double DPS gain from AP, Lupos Shadow damage) with all multipliers of BM talents, Happines(another +25% of damage), Orc racial (5% pet damage), Bestial Wrath(50% damage increase) and u'll receive hunter's pet dealing the same damage as lvl 70 pet in raid.

5)
 Dismiss Pet should decrease happiness by 50.
![wowscrnshot_110718_163641](https://user-images.githubusercontent.com/43533040/48166344-f4175b80-e2f0-11e8-9277-678d0b56f8da.jpg)

**Expected behaviour**: 
1) All pets base attack speed should be 2.0.
2) Strangth, Agility, Intellect, Spirit - are static stats for each pet lvl. Should be like in this table:
http://web.archive.org/web/20080512054051/http://petopia.brashendeavors.net:80/html/articles/stats_attributes.php
3) Attack power scaling 14AP = 1 DPS increase.
4) Lupos should deal physical damage.
5) Dismiss Pet should decrease pet happiness for 50.
**Server Revision**: 2259.

**Comment by Wolffenstein** [comment]
Base attack speed and physical damage fixed in rev 2262.

**Comment by aresbrutus** [comment]
Great report!

**Comment by KevinTyrrell** [comment]
Something seems wrong with pet exp too. If you tame Lupos for example at 23, you're 58, it will take eons to get that pet to your level. At least a few days. Something with the exp scaling seems not right but I can't tell how/why.

**Comment by KevinTyrrell** [comment]
> > Something seems wrong with pet exp too. If you tame Lupos for example at 23, you're 58, it will take eons to get that pet to your level. At least a few days. Something with the exp scaling seems not right but I can't tell how/why.
> 
> Didn't uderstand what u mean. I didn't level him at all. I've made this character, tamed Lupos and did some researches/tests. It took few hours, but I didn't lvl with this pet.

I'm bringing up another pet issue that I've noticed. Was wondering if you or any other Hunter players also noticed that pets exp seems off.

**Comment by mhdemn** [comment]
Brilliant and meticulous post, tyvm
Wanted to add some other relevant/critical pet issues to this thread:

- #2291 - Pet's abilites can't crit, neither KC.
- Pet pathing issues, there's a bunch of issues open about this. Happens often with "flying" mobs, but not only.
- There's some more smaller issues that I don't consider critical / I don't remember right now. Please add these to the thread, give it a good read first to make sure it's not repeated and devs have a decent compendium of pet bugs in one place.

Sidenote - Worth mentioning hunter bugs while I'm at it:
#1674 - Rapid Killing
#2339 - Bunch of issues with various Shots, macros, etc

**Comment by Wolffenstein** [comment]
Pathing, crits, attack power fixed in rev 2273.

**Comment by mhdemn** [comment]
I'm unsure about this, since I can't find much info to back me up, but here it goes since this is faster than asking and then elaborating if I get a positive answer:

Afaik and as this guy says

![image](https://user-images.githubusercontent.com/25901582/48306980-962e8200-e543-11e8-99cd-9ed6bbba2e55.png)

pet's crit chance looks like this, in my case:

![image](https://user-images.githubusercontent.com/25901582/48306994-cf66f200-e543-11e8-918c-9d30cf404380.png)
+
![image](https://user-images.githubusercontent.com/25901582/48306998-d55cd300-e543-11e8-8b47-3a6a12590009.png)

15.15% crit chance.

Now, looking at the info I've been gathering since Wolf fixed pet's capacity to crit in 2279 (iirc), and including unsuccessful attacks in the total (since I suck at math and I don't wanna mess up later):
.....................................................................................................................................................................................................................
**Melee**

![image](https://user-images.githubusercontent.com/25901582/48307013-089f6200-e544-11e8-8866-6cbd582ed3a0.png)

453 crits in 2981 melee hits equals to **15.19% crit chance for melee**
.....................................................................................................................................................................................................................
**Gore**

![image](https://user-images.githubusercontent.com/25901582/48307033-967b4d00-e544-11e8-90bd-05af4962f5eb.png)

207 crits in 1999 gore hits equals to **10.35% crit chance for Gore**.
.....................................................................................................................................................................................................................
**Kill Command**

![image](https://user-images.githubusercontent.com/25901582/48307050-0558a600-e545-11e8-80dc-c688037865b3.png)

41 crits in 236 Kill Command hits equals to **17.37% crit chance for Kill Command**.
.....................................................................................................................................................................................................................

Data exposing over, this is what I'm unsure about and where speculation starts - assuming 15.15% is the right number:

- **Gore**'s crit chance is lower than it should. However, I don't know if hunter pets are supposed to have lower crit chance in their abilities, never played much hunter, but I haven't ever heard about that.

- **Kill Command**'s crit chance bothers me the most, 17.37% is higher than expected, yeah, but we have to take into account the talent [Focused Fire](https://db.excalibur.ws/?spell=35030). This brings me to the following:

![image](https://user-images.githubusercontent.com/25901582/48307225-8feed480-e548-11e8-9b30-de01b29e7270.png)

Can't find sources where it's specifically said that it either increases the number in KC's crit chance by 20, or rather it augments this number by an amount equal to a 20% of it. I'm strongly inclined towards thinking the former case is blizzlike, so are the two hunters I talked with; and in the latter case it seems like such a small thing for a spell you end up using with such low frequency; but let's revise both:

  - **If Focused Fire summed 20% to our 15.15% crit chance as a regular sum** we would be sitting at 35.15% crit chance.

  - **If Focused Fire summed 20% of 15.15 to our 15.15% crit chance** we would be looking at 18.18% crit chance.

Looking at current NW (2282), the latter case seems to be the one working, since the deviation between 17.37 and 18.18 is expectable in such a small data input like 236 casts.

Therefore I'd like to ask, since I'm pretty sure the former is the blizzlike case but I don't have proof to back me up, that this is looked at / proof is thrown in to prove me right or wrong if necessary. Changing it to flat 20% as I think it should be without further research also works for me tho :)

Sorry if the math is complete shit and I should have taken misses/dodges/parries into my calculations, never been good at this.

**Comment by Easyfraggy** [comment]
You'd need to do something like 10000 hits with those abilities to even get close to a 5% error rate.

**Comment by mhdemn** [comment]
> You'd need to do something like 10000 hits with those abilities to even get close to a 5% error rate.

You're right, but anyhow the difference between 35.15% and 18.18% crit chance is too big. I could have skipped the math to be honest, just tried to back myself up with something since I can't find proof to prove my opinion lol

**Comment by Neophrone** [comment]
Btw, I forgot about another bug I found. Position of pet in combat. If pet fighting the mob/boss/player he always should stand behind the target (except situations when this target fighting pet ofc). Realy important especialy for boss fights, since boss can't parry from behind and chance to die in front of boss (cleave abilities, cone abilities of boss etc.) higher than from behind.

**Comment by mhdemn** [comment]
Will update the crit post with more data soon.

I wanna add to the thread that several bosses in different places that have AoE spells seem to ignore hunter pet's Avoidance (the taught passive that reduces 50% of the AoE they receive). Will update soon with recorded footage. I noticed this so far in:

- Thorngrin the Tender's with Hellfire.
- Dalliah the Doomsayer, with Whirlwind.
- Captain Skarloc does too, not sure about the ability.

**Comment by mhdemn** [comment]
AxeCell noted another bug in #2711 
I added video clarification to it as a response in that thread

**Comment by Easyfraggy** [comment]
This post is very old - I believe it was mostly fixed long time ago.

Please open 1 issue per bug if anything from here isn't fixed yet - bug compilations something always gets left out and forgotten. Better to have 1 issue per bug.
