### ISSUE TITLE
[Zone][Mobs AI][Shadowmoon Valley] Deathforge Tinkerer bugged.

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#2476]
Deathforge Tinkerer, Entry 19754, GUID 69853 which patroling area outside of entrance into Deathforge chainpulling some mobs inside and making you stuck into combat.
Info on mob and where combat stuck happened for me
![report1](https://user-images.githubusercontent.com/41975070/48217648-9df9f500-e390-11e8-9527-2b56815a6875.jpeg)
Combat bugged.
![wowscrnshot_110818_204248](https://user-images.githubusercontent.com/41975070/48217749-e31e2700-e390-11e8-9892-d05479b42ebf.jpg)
Tonn of mobs coming for my life.
![wowscrnshot_110818_204724](https://user-images.githubusercontent.com/41975070/48217801-09dc5d80-e391-11e8-9a3a-410e62cc6d34.jpg)
Also.
Deathforge Tinkerer's ability: [Shrapnel Bomb is too overtuned].
http://db.hellfire-tbc.com/?spell=38753
+150 Physical damage - supposed to be.
What we have.
Damage without Shrapnel Bomb.
![report3](https://user-images.githubusercontent.com/41975070/48218385-7015b000-e392-11e8-9739-50754250d27c.jpeg)
Damage with Shrapnel Bomb.
![report2](https://user-images.githubusercontent.com/41975070/48218409-80c62600-e392-11e8-81ee-7917611f1f0c.jpeg)

**Comment by Tereneckla** [comment]
Shrapnel is fixed.
Chainpull happened because their movement/spawn de-synced I guess.
The patrol is 2 Tinkerers and 1 Infernal Soul. They patrol from the lava chamber outside into the other entrance, over the bridge and then despawn altogether, then they respawn in the lava chamber again.

Trying to desync their movement did not work for me.
