### ISSUE TITLE
[Quest][Hellfire Penisula]Spinebreaker Post

### ISSUE THREAD

**Issue by Tankitall** [Atlantiss/NetherwingBugtracker#2485]
![wowscrnshot_110818_233604](https://user-images.githubusercontent.com/44883325/48233932-31422300-e3af-11e8-8e61-718df9a15f92.jpg)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Hellfire Penisula] Spinkebreaker Post)
[//]: # ([NPC] Apothecary Zelena and Wing Commander Brack)

**Description**:  Not allowing player to take taxi path from Wing Commander Brock, if accepting the quest while mounted. Also refuses to logout or Exit game for client!

**Current behaviour**: "You are busy and can't use the taxi service now!" Is the text that you get at the top of the screen even after you have dismounted and retry taking the taxi service.

**Expected behaviour**: Dismount player automatically and auto fly using Armored Wyvern Destroyer to Spinebreaker Post (map coords 61.1 81.8)

**Server Revision**: Beta latest version

**Comment by Easyfraggy** [comment]
For sure auto-flying - the thing I objected to was the auto-dismount I remember having to forcefully dismount on tons of quests like this - and even to be able to start flightpaths on retail - not sure when they changed it - that's why I ask for proof.

**Comment by Tenoutoften** [comment]
* This is the only option the regular interface will give you regarding dismounting. And it's about dismounting you while you are on a flying if you are starting a cast / mining / herbing
![](https://i.gyazo.com/beb9e397396e278180e08f4899f19b28.png) 

* An [addon](https://www.wowinterface.com/downloads/info4713-EzDismount.html) to auto dismount in order to get on your flight path from early 2007.

* A [comment](https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/51921707) from a player in Wrath saying he has an addon to auto dismount him for flight paths, weird if it was built in:
![](https://i.gyazo.com/4709d429c7767c97a91baa5051d106f3.png)
