### ISSUE TITLE
[NPC] Bonechewer Evoker not moving when interrupted

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#2501]
I am using counterspell on Bonechewer Evoker's Fireball and they are not moving after being interrupted- they are just standing still, allowing me to freely damage them. This only seems to be happening to the Bonechewer Evoker's that are next to the ravine/fence. I used counterspell on one of the Evoker's standing out in the open and it began moving toward me correctly.

**Comment by ScottieDOESknow** [comment]
Since leveling up a mage I'm starting to notice this more, mainly with NPC's that cast spells. It doesn't seem to be related to any particular zone either. As far as I can tell, it only happens when at max range for abilities and then use counterspell (improved or untalented) on NPC cast. Just as OP said, the NPC will just stand there allowing you to damage them freely if you remain stationary. Though, as soon as you move any direction, they aggro as usual.

**Comment by The14me** [comment]
Fixed in last rev.
