### ISSUE TITLE
[Quest] Teron Gorefiend, I am...

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2544]
**Description**: 
The Ancient Shadowmoon Spirit has used you as a pawn! Now that you have collected the items he required, he has revealed himself to be Teron Gorefiend. To break free of his possession, you must do his bidding and slay Karsius the Ancient Watcher.

If you succeed, return to Zorus the Judicator at Wildhammer Stronghold.

**Current behaviour**:
Once Teron Gorefiend "Mind-controls" you the RP wont play alongside none of the adds spawning. The adds will however spawn once you release the mind-control, but at that point you can't use Teron Gorefiend to defeat Karsius the Ancient Watcher anymore.

**Expected behaviour**: 
Once mind-controlled, you should be able to control Teron Gorefiend to defeat Karsius the Ancient Watcher, who should've spawned.

**Server Revision**:

**Comment by Kuska101** [comment]
This quest is still completely broken and you cannot finish in any way. Which is a shame because rewards from this quest are very good, pre-raid bis in some cases.

Can simply confirm the issue and add some footage of what is going on atm with this q:
1. Pick up the quest, you gain control over Teron Gorefiend (well, by lore its other way around but w/e)
And nothing happens, event trigger is not triggering.  
https://clips.twitch.tv/AdventurousMiniatureGnatTinyFace

2. You have debuff which allow you to control Teron, for 5 min, you cannot remove it yourself in any way so you have to wait, when it fades off, you lose control over Teron and the event begins, but now you cannot control Teron to kill Krasius and Karsius is friendly to you, so you cannot attack him with your own abilities either.
https://clips.twitch.tv/ShortAbstemiousTubersDoubleRainbow

What should happen here:
Well, you should take control over Teron and fight Krasius 1v1 as Teron, after his death there should be some RP talking and Teron should run away on a horse.
https://www.youtube.com/watch?v=BXvHoA2Ypww

**Comment by Tenoutoften** [comment]
Also mistakes in text...
![](https://images-ext-1.discordapp.net/external/31enN28vDX6q2ppw--H_Szd1RlUN1W920G_SSupNkeg/https/cdn.discordapp.com/attachments/405238694337970177/534204412084879371/unknown.png?width=160&height=13)

**Comment by Evolvee** [comment]
rev 2684
