### ISSUE TITLE
[Core Mechanic]Leashing a linked group and moving closer with one of the members of the specific linked group will re-aggro the linked group from ~40yards

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2566]
**Description**: 
When you pull a group that is linked, continuously hitting one of them to prevent that specific to leash, the other members of the group will correctly leash and return to their spot.

However, if you bring the mob you are still in combat with closer towards the remaining members  of the group that just leashed they will reaggro from very far away, 30-40 yards.

I uploaded an example [here](https://youtu.be/jyVQ4cDngu4), this is not unique to this place, it's happening in general with these circumstances.

**Expected behaviour**: 
Expected to have normal aggro range rather than a extended aggro range when you return closer towards the group

**Server Revision**: 
2282

**Comment by Easyfraggy** [comment]
These mobs are in a formation and as such should never leash as long as one of them is still being attacked - attacking 1 mob in a formation should reset flagpole for all members. 

They shouldn't leash like you said if they are in formation.

**Comment by Tenoutoften** [comment]
Well this is how it currently works, at least we discovered an error:]

**Comment by Tenoutoften** [comment]
This is still happening despite the fix in Karazhan. Reproduced this at the same place in Nagrand

**Comment by fantom8** [comment]
Why would single pull mobs in the overworld join into a "formation"? Because this behavior is happening no matter where the mobs were standing before they aggroed.

I'm also very skeptical about the current behavior of your flagpoles. At the moment it's impossible to reset any mob unless you do literally nothing to it or mobs around it for 60+ yards from the moment you last touched it, no matter how far it's gone. Maybe that's how it was in vanilla, but not TBC.

Sometimes it's even more than 60, I've gone a good 100+ without using a spell without a pet and had mobs not reset, and that's while already 50-100 yards from their initial pull location.

**Comment by Drayo** [comment]
@fantom8 

The initial position of the mob has no influence on it's leash range once you hit it, the area is updated to its current position whenever it takes damage.
The actual leash range is a combination of a fixed value (around 35y or something) plus the aggro range of the mob itself.

I don't know about other mobs extending each others leash range while NOT in formation, this would be a new bug and might warrant a new separate issue.

**Comment by Godmatik** [comment]
Closing this one out - more complete details are here:
https://github.com/Atlantiss/NetherwingBugtracker/issues/2260
