### ISSUE TITLE
Bloodmaul Brute health bug

### ISSUE THREAD

**Issue by craigsurbrook** [Atlantiss/NetherwingBugtracker#2653]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Bloodmaul brutes are supposed to have an ability (bloodmaul buzz) which gives them 20% health and higher attack speed. Instead it "heals" them a huge amount, and when it does enrage, it gives them another heal, so they essentially have two stacks of bloodmaul buzz, and they get healed 100%.

**Current behaviour**:
Bloodmaul Buzz and enrage both get used as a double-stack, heals mob 100%.

**Expected behaviour**: 
Bloodmaul buzz happens (just one stack), and it gives +20% max health, not a huge heal.

**Server Revision**: 
2304

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2333

**Comment by mfaulkie** [comment]
Description:
Bloodmaul brutes are supposed to have an ability (bloodmaul buzz) which gives them 20% health and higher attack speed. Instead it "heals" them a huge amount, and when it does enrage, it gives them another heal, so they essentially have two stacks of bloodmaul buzz, and they get healed 100%.

Current behaviour:
Bloodmaul Brute heals to full upon death.

Expected behaviour:
Bloodmaul buzz happens (just one stack), and it gives +20% max health, not a huge heal.

Server Revision:
2749
