### ISSUE TITLE
[NPC] Bonechewer Ripper (Heroic)

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2678]
**Description**: 
Bonechewer Ripper in heroic Ramparts has an enrage ability alongside a possible grow ability.

**Current behaviour**:
Becomes enraged, and loses the effect after 3 seconds. Doesn't get anything beyond the initial enrage and he wont grow as the fight goes along.

**Expected behaviour**: 
The enrage should last longer, and he should potentially grow throughout the fight to make him a higher priority target.

**Server Revision**: 
2304

**Comment by Easyfraggy** [comment]
He should gain one stack per add you kill - permanently.

**Comment by Evolvee** [comment]
the enrage has 5 seconds duration i need evidence from retail for this npc

**Comment by AxeCell** [comment]
I've not managed to find any proof that they're supposed to enrage for more than 5 seconds after the initial pull, or if they can grow outside of being fel infused by the Scryers.

https://www.wowhead.com/npc=17281/bonechewer-ripper#comments
http://wowwiki.wikia.com/wiki/Bonechewer_Ripper

They are mentioned to be immune against all forms of CC, but this remains untested from myself.

**Comment by Fenvarien1** [comment]
from: 23.12.2006
https://youtu.be/MJ-1H6nz8Oc?t=250 here you see the pull on a pack with a bonechewer ripper and he enrages for 5sec ( from pull 4:10-4:16)

from: 23.06.2008 
https://youtu.be/hVsGMFCNAIk?t=90 better view. on pull he enrages for 5sec.
https://youtu.be/hVsGMFCNAIk?t=318 again. on pull 5sec enrage.

but i couldn't fine one with infusion.
here are some more details:
https://www.wowdb.com/npcs/17478-bleeding-hollow-scryer#related:casts
https://www.wowdb.com/spells/30659-fel-infusion
spell ID: 30659
http://db.hellfire-tbc.com/?spell=30659


https://www.wowhead.com/spell=30659/fel-infusion#comments

By AoBman05 (9,532 –  2·23·68)  on 2008/06/09 (Patch 2.4.2) |   |  
"It's the buff they cast on the lone **Bonechewer Ripper** when they die. It makes the ripper bigger, prevents him from fleeing when near death, and makes him hit alot harder. And it stacks, so groups usually drop it first so that they don't get gibbed by an oversized fel orc."


he made that comment a few days before the 2nd video. if you kill the casters they buff the Bonechewer Ripper.

**Comment by Fenvarien1** [comment]
https://imgur.com/a/HV75gXu i am in ramparts right now. the mob get fel infused and got the 5sec enrage on pull.
its working
