### ISSUE TITLE
double campfire zangarmarsh

### ISSUE THREAD

**Issue by femtaur** [Atlantiss/NetherwingBugtracker#2698]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

![world of warcraft screenshot 2018 11 15 - 19 24 16 04](https://user-images.githubusercontent.com/45077394/48573326-2a199880-e90c-11e8-89ae-813fce69b13e.png)

**Description**: 
2 campfires right next each other(75.1, 78.1). What is this madness? 
**Current behaviour**:
One has "Campfire" mouseover tooltip, other does not.
**Expected behaviour**: 
Should only be 1 camp fire, i thnk xD
**Server Revision**: 
2304

**Comment by Shanghi** [comment]
Unfortunately this is how it's supposed to be! That annoyed me when I was fixing Outland objects.
https://www.youtube.com/watch?v=0PyG6e9w_RM#t=1m4s

The one without a tooltip is just a decoration in the world that the server can't change and it won't burn you like the real campfire object that they put much too close to the pillar so that it looks terrible.
