### ISSUE TITLE
[Spell][Hunter] Serpent Sting, Steady Shot, Arcane Shot, Concussive Shot, Scorpid Sting, Volley and Viper Sting

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2708]
**Description**: 
Topic is related to the behaviour of these spells.

**Current behaviour**:
None of the above listed spells consume ammunition when shot.
Moving and casting a good amount of these spells will queue you into firing the ability without it ever releasing, leaving you unable to attack. To continue attacking you will need to stand still and click the spell again.

**Expected behaviour**: 
Most of the shots should consume ammunition just like Multi-Shot and Aimed Shot does.
Abilities should not prevent you from attacking further when casting while moving.

**Server Revision**: 
2321

**Comment by mhdemn** [comment]
I'm pretty sure no shot besides Auto Shot consumes ammo, both from memory and from basic reasoning. Find proof that what you say is blizzlike though, I surely can't find any.

The rest you're saying has been posted for days here #2339 
There's a search bar up there not to repeat posts.

**Comment by AxeCell** [comment]
As stated in my post, both Multi-Shot and Aimed Shot consume ammunition. If no other shot other than Auto Shot should consume ammo, then why would the aforementioned shots consume it?

**Comment by mhdemn** [comment]
Mhm, seems you're right. Found it easier to see it in this [video](https://youtu.be/feMfZRijNK4?t=693) rather than the one you linked.

I'd be happy to keep it as is for moneysaving's sake though, wouldn't be the first server to do it, but yea it seems blizzlike is to consume ammo with everything.

About the shots getting locked now and then that it's explained already in #2339, you can work around the issue until devs fix whatever's causing it by adding a bunch of /stopcasting lines to your macros, I added it to my arc and multi shots and serpent stings, aswell on a couple start/stop attack buttons I frequently use, pretty decent bandaid.

**Comment by Easyfraggy** [comment]
I'm unsure if arcane shot should consume ammo - but the others should for sure.

About the ability getting stuck thing thats a completely different issue like mhdemn linked.

**Comment by raethkcj** [comment]
This is likely related to whether the shots use ammunition dps in their damage calculations. 

Aimed Shot and Multi-Shot are the only ones that scale with ammunition, therefore it makes sense that they would be the only ones that consume it.
