### ISSUE TITLE
[Spell][Hunter] Kill Command

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2709]
**Description**: 
Topic is related to Kill Commands general behaviour.

**Current behaviour**:
Kill Command can be used regardless of in which state the pet finds itself in. The spell will always be consumed when triggered even if the pet is **out of range** or **dead**, although it wont deal damage unless the pet is alive in melee range.

**Expected behaviour**: 
Should only be useable when the pet is within range of its target.

**Server Revision**: 
2321

**Comment by mhdemn** [comment]
Didn't ever happen to me.

**Comment by AxeCell** [comment]
You need to specify more of what didn't happen. Can you not activate Kill Command while your pet is dead or LoS, or was this always the fact in TBC? I can repeat this with a 100% consistency on a Wind Serpent pet.

**Comment by mhdemn** [comment]
Jeez. 
I've never experienced any bug whatsoever related to Kill Command, works just fine ever since I first tried it, works just fine in 2321. I'm using a Ravager pet I tamed in Hellfire Peninsula, and when the pet is dead, stunned, out of range or whatever it won't let me use Kill Command even though it's highlighted due to a recent crit. Tried this same thing with another Ravager which another Ravager that I tamed in Blade Edge's Mountains and with a Wind Serpent I tamed nearby. No bug of those you describe ever happened.

**Comment by Tenoutoften** [comment]
Retail Video: Pet dies [here](https://youtu.be/Izv9vZr-wF0?t=279) but you can see KC still lights up even if pet is dead.

I am rather convinced that the spell will light up regardless of what state the pet in based on this. And when it is out of range  it will be spent without damage unless the pet will get in range very shortly afterwards

**Comment by Wolffenstein** [comment]
Fixed in rev 2435.

**Comment by Zarant** [comment]
I just tested it in revision 2451 and it's not working properly, there is no error message, the spell simply goes off but no damage is dealt.
