### ISSUE TITLE
[Rogue] Stealth Detection probably too high? 

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2791]
**Description**: I could detect a rogue stealthed on the top of the bridge on blade's edge arena while being in the bottom

**Current behaviour**:I could detect a rogue stealthed on the top of the bridge on blade's edge arena while being in the bottom
https://gfycat.com/BountifulRemoteCygnet

**Expected behaviour**: Probably shouldn't be the case

**Server Revision**:  2336

**Comment by ScottieDOESknow** [comment]
You had paranoia buff from felhunter which adds +30 stealth detect...

**Comment by killablink** [comment]
True I didn't notice that but I'm more talking about being able to detect a rogue from under the bridge. I feel that normally your detection should be in the same plane as you and not above. Could be wrong but yeah

**Comment by ScottieDOESknow** [comment]
If you can see a non-stealth player on top the bridge, having +30 stealth detect will allow you to see a stealth player on top of the bridge. Pretty straightforward. 

> I feel

Any retail TBC video showing detection should be in the same plane?

**Comment by killablink** [comment]
Sorry but that is the most stupid argument I've ever heard. It's about how stealth detection works, not because you see a non-stealth player on top that you should be able to see a stealthed character wth lol.

http://et.worldofwarcraft.wikia.com/wiki/Stealth_(mechanic)

Only mentions about a 180 degree arc in front of you. Stealth detection works, afaik, to detect people in front of you in that arc, and doesn't expand. Please look at it again and see how I'm also able to detect that rogue while not even facing him the second time before I start heading up the upper level. Pretty sure that isn't blizzlike lmao

**Comment by ScottieDOESknow** [comment]
No need to be sorry OR passive aggressive and throw insults, this is simply a discussion.

>It's about how stealth detection works

Stealth detection = **stealth level** vs **detection level** vs **distance**. (360 degrees horizontal and vertical)

>Only mentions about a 180 degree arc in front of you. Stealth detection works, afaik, to detect people in front of you in that arc, and doesn't expand.

I think you misread the wiki. The link you provided says otherwise AND mentions much more. 

http://et.worldofwarcraft.wikia.com/wiki/Stealth_(mechanic)

_**The difference** between **subtlety** and **detection** will determine **the distance** that a player will be seen at. **The closer you are** to your target, **the higher the probability** that you will be detected. **The chance of detection is also increased if you anywhere in a 180° arc in front of the target**_

>I'm also able to detect that rogue while not even facing him the second time 

The 180 degree frontal arc applies to increased probability, nothing more.

The enemy rogue was close enough and you had the paranoia buff, it's that simple.
Look when you first detected rogue, right before they get bubble from priest @ 3.99s in your video

https://gyazo.com/224cff3870fcb5b0127206dbfc1c7afa

...the enemy rogue stays visible until you get near the ramp and lose paranoia buff due to range.

Pretty sure that **IS** blizzlike.

Countless times I've detected a rogue that was behind me, or flanking my side because their stealth level was too low compared to my detection level. Happens **a lot** using perception or really any + stealth detection.

 I can even prove this to you in game, quick and easy.
DM me on discord @ ScottieDOESknow

**Comment by ScottieDOESknow** [comment]
1. drop down
2. enters stealth
3. use perception
4. detect druid in stealth on right flank

https://www.youtube.com/watch?v=0qqs7BUGOsM&feature=youtu.be&t=545

screencap right when he uses perception
https://i.gyazo.com/6f78dfe39afaf560cc75a7f266ea8c98.jpg

**Comment by Easyfraggy** [comment]
Doesn't matter what Z something/someone is - it's only based on distance and being in front.
