### ISSUE TITLE
Several hunter bugs

### ISSUE THREAD

**Issue by arckoss** [Atlantiss/NetherwingBugtracker#2793]
-freezing trap sometimes randomly disappears from the target even though no dots are applied on it (essentially rendering the spell useless)

-(tested in passive stance): pets sometimes come back to me while engaged in combat, although I didn’t manually made them do that

-pet disappears while in combat, and “abandons me” even while at 100-125% happiness.

Also, the view distance seems to be causing a lot of combat problems (mobs are only seeable when you’re very close to them, which might be something you guys implemented temporarily)

**Comment by Easyfraggy** [comment]
Report 1 issue at a time.

Freezing trap has heartbeat resist like any other CC - this makes hunter trap more unreliable than sheep and fear/banish because hunters have no spell hit.

Pet issue with passive stance is already reported - please use search function.

Pets disappearing midfight is new - haven't heard before - you should report that on its own - but you need to give more information - we can't recreate it from that tiny information. Are you checking pet happiness in the pet panel? The pet panel icon is always green just FYI - it just shows what kind of food it eats, not its happiness level.

View distance is temporary fix to client crashes while we fix the packet compression.
