### ISSUE TITLE
[Spell][Priest] Unable to cancel Mind Vision

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#2884]
**Description**: 
After casting Mind Vision on a friendly target I am unable to cancel the debuff.

**Current behaviour**:
I am unable to stop myself from being in Mind Vision, I have to let this run off the full duration.

**Expected behaviour**: 
I should be able to right-click mind vision from my debuff list.

**Server Revision**: 
2339

**Comment by towneh** [comment]
Mind Vision is being treated as a debuff on my player when casting it on another target, so I cannot right click this off.

**Comment by Wolffenstein** [comment]
I don't think it's a bug - see https://www.youtube.com/watch?v=hW46h_q68lE.

Wowpedia also says: "Casting any spell will cancel Mind Vision. Taking actions or using items will also cancel the channel. Cancelling buffs by right-clicking on them will not break the channel. ". I'm closing for now since the spell attributes force it to be a debuff regardless of what I do server-side.

**Comment by Nicemann1089** [comment]
just jump ;)
