### ISSUE TITLE
[stealth] [delay]

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#295]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
pressing stealth, walking into aggro range then stealth applies aggros + resets mob
**Current behaviour**:
https://streamable.com/427m4
**Expected behaviour**: 
faster stealth + if detected shouldn't reset mob? definetely wasn't a thing in retail atleast.
I understand its cos of the spellbatch system, i approve of it but i believe it's a bit overtuned. Especially on self cast stuff.

**Server Revision**:

**Comment by totaemoeggerli** [comment]
same thing can happen with druid prowl https://gfycat.com/GrimyInsidiousAmethystsunbird

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/867 gif showing it.

**Comment by totaemoeggerli** [comment]
https://gfycat.com/ArcticEssentialHapuku
bump

**Comment by wowthings** [comment]
And this can be abused, a bit tricky to perform but yeah... 
https://streamable.com/ozlg3
No, obviously this doesn't work on world bosses, once they see you they smack you.
@Evolvee 
@wtRCH

**Comment by Evolvee** [comment]
this is most likely issue with spell delay which needs a full rework

most likely the issue lies between switching bar stances

**Comment by JamesIsAwkward** [comment]
Also if you stealth as soon as you aggro you can sometimes drop aggro and the mob will either do one of two things, pause for a moment and then fight you, or return to its position without aggro.

Gaining aggro should lock your stealth ability due to combat.

**Comment by mistermeta** [comment]
Bump - as of lv40 boost this issue still exists. Massive annoyance for any stealth class. This batching has to be selectively removed from certain abilities like Stealth/Prowl to better the gameplay experience.

**Comment by KevinTyrrell** [comment]
#2230

**Comment by ScottieDOESknow** [comment]
current stealth / combat delay @ 120ms - November 12th

clip1
https://gyazo.com/dc51f6b941ad5b9e1022940c192b51a2

clip2
https://gyazo.com/5131e8f8186815f2602e19dd7e1ab7e0

NOTE: lvl 70 player vs lvl 63 NPC

**Comment by Easyfraggy** [comment]
Do you have some sort of proof that this didn't happen on retail when doing exactly what you are showing?

**Comment by ScottieDOESknow** [comment]
Likewise, evidence of absence is nonexistent considering there is no burden of proof that this is blizzlike. 
Lets say for example, there is a video showing this behavior... well what patch was it on? Was it before one of the many stealth hotfixes or patch updates? There were many over the years, from early to late game.

Stealth has had bugs since WoW's inception and those issues were always game breaking. That's why having alt was nice. If they broke your class for few days, weeks, or months, you could play something else. Losing the ability to play your class as intended for extended periods, is memorable. If someone played another class, they may have zero knowledge on these past problems with stealth. That's completely understandable.

What I have no recollection of is this: 

Going into stealth stance (aura visible) being in stealth for nearly 1 second THEN entering combat (in stealth) with NPC visibly running to attack me, then dropping combat split second later and running back to reset.
https://gyazo.com/dc51f6b941ad5b9e1022940c192b51a2

Multiple times I have done what you see in the ^ above clip ^ except I also sap the enemy, and I am STUCK IN COMBAT with a sapped enemy, while still being in stealth... or I sap when the combat state is transitioning and my sap doesn't land, etc. If it's a higher level enemy and they reset facing towards me, guess what? 9/10 times they aggro and pop me from stealth. Now even though these latter instances do occur, I will say, it's much harder to reproduce than the above instance shown in above video vs low level NPC.

Don't get me wrong, this issue has been much improved since launch regardless if anything was changed, and I should have mentioned that in my last post: **it's much better**. Still, I don't believe this this is strictly a stealth problem but combination of aggro mechanics / stealth combined... or maybe just aggro. I really don't know. That's why I am providing more information for devs / testers at in hopes that the problem can be discovered and adjusted as needed. 

I think we can all agree, a ticket being open since Sept 23rd indicates that it's not working as intended.

**Comment by Easyfraggy** [comment]
Well one of the problems is that there isn't a single post here showing how it should work - just saying something is wrong doesn't help fix it much quicker - you could have linked atleast some videos of people entering stealth after pressing their stealth button - that would be a start. 

Stealth was never instant and you enter stealth very late imo.

The real problem might be that the mob doesnt just straight up run to you and attack you in stealth because you entered stealth too late - or it might be that stealth is activated too slowly after being pressed. 

There are multiple options and that is why there is no fix to this issue yet.

Or it might even be a combination of the two.

You provide no info on how it should be and as long as that is the case you are unlikely to see a fix anytime soon.

**Comment by Easyfraggy** [comment]
You can see on this video fx: https://youtu.be/14sFYHIKpX0?t=141 that he gains the stealth buff almost instantly (same batch as pressing stealth) just like on your video above - same thing - so then the issue is either:

A) Stealth level is updated on the player too slowly after entering stealth. Hard to prove - but wolf can check for it. You can check from a 3rd person view if this is the case. (recording someone else entering stealth)

B) Mob agro is decided before the mob starts moving - and incorrectly resets after entering into combat with the player. To prove B you'd need a video of someone entering stealth and then being attacked by a mob shortly after.

**Comment by Easyfraggy** [comment]
It is more likely that it is problem A - simply record someone else entering stealth that should clarify the issue.

**Comment by ScottieDOESknow** [comment]
Never opened a separate ticket because I figured it would just be a duplicate but the title for this ticket could possibly need changed to reflect the problem, which is IMO not a delay to the steath spell, but as you mentioned: player stealth level updating slower than it should, or even some type of combat / aggro delay,

>To prove B you'd need a video of someone entering stealth and then being attacked by a mob shortly after

Happened to me a handful of times esp when level ranges are closer. Example: as you see in my above video except combat will loop (entering & leaving) until the mob finally hits player, and occasionally I will get a sap off between those looping combat states.

I've even had instances where a mob hit me out of stealth in this manner, sap connects for a split second, then the mob evades from combat loop and the sap is removed, meanwhile I am out of stealth and in combat, which causes the mob to immediately attack me after completely resetting.

Like I said it's harder to reproduce, but it's happened, and not just once. I just don't know anyone who would willingly follow me around, recording the entire time, for who knows how long, until this happens.. If anyone watching this thread is willing to do that, then I am willing to try and reproduce these instances. @ScottieDOESknow on NW Discord

**Comment by Easyfraggy** [comment]
I was referring to a video from retail in B)

**Comment by ScottieDOESknow** [comment]
aggro in stealth 3rd person

https://clips.twitch.tv/SpeedySoftKoupreyCmonBruh

**Comment by Dollywog** [comment]
Came on to report this today, still an issue as 58 druid Prowl prior to engaging mobs ; mobs already aggro.  Never encountered this on any other TBC server or re-call this from Retail.

**Comment by femtaur** [comment]
https://gfycat.com/PowerfulWetAsianpiedstarling still happening, probably in 1/10 saps

**Comment by The14me** [comment]
Rev 3441.Still happen.
