### ISSUE TITLE
[Spell][Warrior] Intervene 

### ISSUE THREAD

**Issue by shockave** [Atlantiss/NetherwingBugtracker#2969]
**Description**: 
Intervene doesnt "charge" on ally
**Current behaviour**:
when i use intervene on my party member she gain's a buff but i dont move at all.
**Expected behaviour**: 
I should "run at high speed towards a party member" i.e. charge them.
**Server Revision**:

**Comment by shockave** [comment]
update: it happens at random, sometimes i charge sometimes i dont hard to re-create

**Comment by tcberk12** [comment]
if you could somehow capture a clip of the issue, that would help alot in terms of resolving it.

https://getsharex.com/ This is the NW recommended video capture tool

**Comment by Easyfraggy** [comment]
It never bugs for me. Very strange.

**Comment by Nixazzar** [comment]
One thing also about intervene, im not sure it is suposed to work like this. U can intervene by targeting enemy target, lets say BOSS, and by doing that you would actually intervene Bosses target if you party aggored. 

So EG. Im a tank usually, i tank boss that runs from target to target, 2nd boss in Mecha. Once i lose aggro to it, and it switches to next one the aggro table i can intervene still targeting boss, save my party member from dying and taunting while im charging there.

I dont mind it working like this i like it actually, but i think its not supossed to work like this, because i remember on retail i was making target of targets macros to be able to do that.

**Comment by Easyfraggy** [comment]
It should definitely work like that Nixazzar.

**Comment by Easyfraggy** [comment]
No - it should work exactly like you describe.

**Comment by Easyfraggy** [comment]
This issue seems invalid - can anyone confirm/deny?
