### ISSUE TITLE
[Quest] [Blackrock Depths] Jail Break! - Windsor no weapons / movement

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#2971]
**Description**: 

Help Marshal Windsor get his gear back and free his friends. Return to Marshal Maxwell if you succeed.

**Current behaviour**:

Marshal Windsor RP walks to the storage room, picks up his armor (but not his weapons) speedwalks to North cell block and requests (group) to free Tobias, then proceeds towards exit where quest is completed.

speedwalk (accelerated animation?)
https://gyazo.com/5505631947ccba31e0209f9a2baff4b0

**Expected behaviour**: 

1. Windsor should pick up weapons along with his armor
2. Windsor should buff group with Devotion Aura once his armor on.
3. Windsor should continue to RP walk (no speedwalk) to the 4 cells that need opened on the other side.
4. After Tobias is free, Windsor should emote and then 'jog' to the entrance (no speedwalk)

**Server Revision**:  2349

**Comment by SchwarzCodes** [comment]
Additionally:
He doesn't attack any enemies, he just runs through them pulling everything.
There are also three cells that contain named NPC who should turn hostile after you open the cell: These don't turn hostile, remaining green. Windsor then talks as if they had been killed and continues.

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/58573248-9f601180-823d-11e9-884b-ae2144dc63e7.png)

**Comment by Tereneckla** [comment]
1. He should not pick up a weapon.
2. He should not buff anything.
[ ] 3. Yes, he should RP walk.
[ ] 4. Still should RP walk.
[ ] He should attack enemies instead of just walking through.
[ ] The 4 prisoners should become hostile once you open their respective door with the Marshal.
![WoWScrnShot_010820_202851](https://user-images.githubusercontent.com/50233983/72011604-82bb9b80-325a-11ea-9fcb-62aa412990bb.jpg)
Jaz and the missing [Ograbisi](https://wowwiki.fandom.com/wiki/Ograbisi)
https://youtu.be/XJoAC-CSiR4?t=72
![WoWScrnShot_010820_204856](https://user-images.githubusercontent.com/50233983/72011658-99fa8900-325a-11ea-9ae3-17b68a6856fb.jpg)
Shill Dinger
https://youtu.be/GTaC5v53d8M?t=203
![WoWScrnShot_010820_204959](https://user-images.githubusercontent.com/50233983/72011684-a5e64b00-325a-11ea-9a1e-804c28cc5526.jpg)
Crest Killer
https://youtu.be/z5yD3tRvQu4?t=294

[ ] He should /yell emote that stuff before jogging off.
https://youtu.be/z5yD3tRvQu4?t=390

**Comment by Godmatik** [comment]
Closing - all BRD information will be consolidated into one thread
