### ISSUE TITLE
White hits through walls

### ISSUE THREAD

**Issue by Shiek94** [Atlantiss/NetherwingBugtracker#2986]
**Description**: 
Players can white hit through walls that should line of sight, meaning that rogues/druids can barely restealth in pvp, it also works in pve. Yellow attack do not work through walls though.

**Current behaviour**:
Its possible for players to white hit through walls that should line of sight.

**Expected behaviour**: 
Walls that line of sight (they do with spells) should also not be possible to hit through with white hits.

**Server Revision**: 
2349
**Proof**
https://www.youtube.com/watch?v=P5ccYVW_azQ&feature=youtu.be

**Comment by zauru7** [comment]
white hits aren't affected by LoS #1982

**Comment by Evolvee** [comment]
works as intended

**Comment by slicplaya** [comment]
This is NOT working as intended at all.

**Comment by Evolvee** [comment]
are you willing to bet money on it?

**Comment by slicplaya** [comment]
It's based on the hit box of the character, and hilariously, if you're moving forward it increases your hit box for melee. It's even higher for Tauren classes specifically. Blizzard didn't intend for people to be hit through the walls, but their shit hit boxes back in the day allowed it to do so. I forgot they didn't fix a lot of shit til wotlk. And no, I will not bet money on it. Because I follow rules: "Attempting to persuade a member of the Staff by offering money, goods or other services either in-game or outside of it." You seem to be a master of baiting.
