### ISSUE TITLE
[NPC][Spell]Prince Malchezaar - Cleave

### ISSUE THREAD

**Issue by Haipethdev** [Atlantiss/NetherwingBugtracker#3000]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Cleave AoE

**Current behaviour**:

Cone vertex is too far back or its 360 AoE

**Expected behaviour**: 

Should only hit in front of boss

**Server Revision**:

**Comment by Haipethdev** [comment]
Either the cone vertex is starting too far behind the boss or the aoe itself is 360.  Happened 4-5 times now and it is definitely not poor positioning.,

**Comment by Tenoutoften** [comment]
Easy explained this on the Discord with these comments,
![1717](https://user-images.githubusercontent.com/34839199/48973337-86339980-f03d-11e8-8fa3-5036610352d0.png)
![1718](https://user-images.githubusercontent.com/34839199/48973338-86339980-f03d-11e8-8345-1837a0bb9a01.png)
![1719](https://user-images.githubusercontent.com/34839199/48973339-86339980-f03d-11e8-905e-8f75904d4198.png)
![1720](https://user-images.githubusercontent.com/34839199/48973340-86339980-f03d-11e8-8edd-dd15da8728c2.png)
![1721](https://user-images.githubusercontent.com/34839199/48973341-86339980-f03d-11e8-9f27-8e44c7c6779f.png)
![1723](https://user-images.githubusercontent.com/34839199/48973342-86339980-f03d-11e8-8baf-ca8cbb108ad8.png)

**Comment by Easyfraggy** [comment]
What could be wrong is that the chain range is too far - altho to clarfiy on the picture at the bottom of Tentoutens post the tank is too close to the boss causing cleaves on the pet/melee.

On the gif the chain range for that mob type is clearly wrong - could be wrong spell or simply wrong chain range on that particular cleave ability.

Not saying theres no bug here - just saying if it is bugged its most likely because chain range is too big on that cleave ability - altho I have myself played this fight as melee and the only time I got cleave was when tank suddenly moved him towards the melee safe spot.

**Comment by Easyfraggy** [comment]
Who said it should be 5 yards?

You are clearly standing too close to the tank on the google drive video. Theres 4 yards more melee range behind you you could have used.

**Comment by Anonyxx** [comment]
Have proof this is broken:

https://www.twitch.tv/plasquar/clip/CooperativeBlitheGarageBrokeBack

**Comment by Manaci** [comment]
Fixed
