### ISSUE TITLE
Devotion aura wiping out scroll of protection if the scroll is already active.

### ISSUE THREAD

**Issue by Anselm123** [Atlantiss/NetherwingBugtracker#3095]
https://www.wowhead.com/item=27500/scroll-of-protection-v#comments

**Description**:  Devotion aura is meant to stack with scroll and does if the scroll is cast second however if you need to recast devotion aura for some reason then it wipes out your scroll.

**Current behaviour**: New cast of devotion aura will wipe the scroll but can be stacked as is meant to be before casting devotion aura

**Expected behaviour**:  Just meant to stack and shouldn't be wiping each other out.

**Server Revision**:

**Comment by Easyfraggy** [comment]
Not a single comment in there proves your claim - likely invalid report.

**Comment by Easyfraggy** [comment]
I don't think I'm reading the same things as you are - What im reading is that in 3.0 they made buffs raid wide - this means every tank now got devo aura - in tbc it's a lot less common to use a devo aura on the tank.

I still don't see sufficient proof of this. Afaik if you have scroll on and gain aura both get applied but only strongest buff has effect - this is due to devo aura being a temporary aura that has no duration and scroll of protection is a timed buff. 

Even EJ thread gives no conclusive answer as to how it should work in 2.4.3:

![image](https://user-images.githubusercontent.com/36134067/49211204-51b63980-f3bf-11e8-9838-042ddc7956db.png)

**Comment by Anselm123** [comment]
http://web.archive.org/web/20080113213515/http://elitistjerks.com:80/368534-post17.html

This post is for patch 2.3 and is for survival hunters but shows that they were using scrolls alongside agility totems from shamans for their calculations. Since totems work the same as auras in terms of being a static buff and not a limited time effect, they should work the same as totems and stack with limited time effects right?

**Comment by Anselm123** [comment]
https://www.wowhead.com/item=27498/scroll-of-agility-v#comments:id=156055


By Vacc (5,960 – 2·17·47) on 2007/09/21 (Patch 2.1.3) |   |  
-- | -- | --


They stack with any and all buffs EXCEPT player given buffs that buff a single stat.

So the intellect, spirit and stamina scrolls cannot stack with Arcane Intellect, Divine Spirit or Fortitude respectively.

But you can have a Str, Agi and Armour scroll equipped without any regard to normal raid buffs, elixirs and flasks.

**Comment by Easyfraggy** [comment]
Totems don't work the same as paladin auras btw - str and agi scroll stacks with totem - that is common knowledge. Only armor scroll is up for question.

The last comment: 
![image](https://user-images.githubusercontent.com/36134067/49238444-b776e580-f400-11e8-969a-6663ef38274c.png)

Is the very first comment from all the info linked above that armor scroll should stack with all buffs.

So right now we have 1 comment and a bunch of contradictory statements about this issue.

Unless we can find something more conclusive we might have to go with armor scroll stacking since it's the only actual datapoint we have although I have to say the evidence is EXTREMELY weak for this.

**Comment by Anselm123** [comment]
Can you explain why totems and auras don't work the same? They don't stack with each other in terms of resistances and effectively work the same way, it's not far fetched to consider them working in the same way?

**Comment by Easyfraggy** [comment]
I already explained one difference above - shadow prot and pala shadow res vs agi totem+scroll of agi.

**Comment by Anselm123** [comment]
But they are both applied because one is times and one is an aura effect. Surely this is the same as the totem and the scroll and they shouldn't stack since they provide the same buff type but one is an aura and the other is a timed buff and should both be on by only the most powerful active?

 And that doesn't work when it comes to this since it's not applying both but it will wipe the scroll when you reapply the devo aura.

**Comment by devo6969** [comment]
Devo aura doesn't remove the scroll buff after reapplying it, currently on the PTR it does.
Classic- https://www.youtube.com/watch?v=VmdVE37QP0U&feature=youtu.be

**Comment by Godmatik** [comment]
Fixed in new aura branch update.
