### ISSUE TITLE
[Core][Pets] Threat dropping abilities should not put you out of combat if your pet is in combat

### ISSUE THREAD

**Issue by Zarant** [Atlantiss/NetherwingBugtracker#3134]
Whenever you successfully cast feign death or any other similar spell you are supposed to clear threat from all mobs and you should only drop out of combat if your pet is not attacking anything (either on Follow or Stay).
Currently, only the very first hit will put you in combat, whenever you use feign death, you drop out of combat regardless if your pet is chasing after an enemy or not.

Sources: 

In the clip below you can see the hunter losing aggro and not dropping combat when his pet is on defensive, fighting another mob:
https://youtu.be/6DTmw7FvKCk?t=1256

In this other clip, the hunter feigns, his pet gets hit by the enemy pet (Corean hits Angelo for 59.) and then the hunter is put back in combat once he casts scatter shot. 
https://youtu.be/h0eVrsYItpI?t=368

EDIT: See the research below, pets don't always put their masters in combat, this is most likely an issue with Feign Death and other similar spells.

Server Revision: 2370

**Comment by Evolvee** [comment]
Pets never triggered combat on their own. They just refreshed it.

**Comment by Zarant** [comment]
Look at this other video:
https://youtu.be/2jOKVdoPp7w?t=451

Hunter uses FD with his pet chasing after a mage, he doesn't drop out of combat not even for a split second.

**Comment by Zarant** [comment]
Found more footage: 
https://youtu.be/m8nOaNMHZIQ?t=735
Hunter recalls his pet, start drinking and then sends his pet after someone. You can see his pet spending focus, meaning that the pet is actively attacking someone and shortly after you can notice a health regen tick and then he is put back in combat after hitting an enemy.

So, to sum up, spells that drop combat Feign Death and possibly Invisibility, should only do that if the pet is not attacking anyone.

**Comment by Easyfraggy** [comment]
https://youtu.be/HYhAj9Q42LM?list=UUelCZCnwyGOJhPxjecUExng&t=164

Pet puts him in combat as soon as it hits the mob.

**Comment by killablink** [comment]
https://gfycat.com/UnrealisticChillyFlea

Make sure to not bug this, water elemental pet freeze doesn't put you in combat (old video from tbc)

**Comment by Evolvee** [comment]
Ok I didnt think I would have to state it specifically for you @Easyfraggy but I guess ppl will never learn so:

**THERE IS A DIFFERENCE BETWEEN PVE AND PVP**

Dont argue with me by posting PVE videos trying to explain PVP mechanics.

Why?

Because PVP and PVE behavior on how combat is triggered is EXTREMELY different.

---------

PVE: Pet triggers combat to owner despite owner not attacking.
PVP: Pet doesnt trigger shit, only extends the combat if owner got into combat himself.

proof:
https://www.youtube.com/watch?v=7l53X2H8Hz8&feature=youtu.be&t=678
https://www.youtube.com/watch?v=czV-xTY6NV0&feature=youtu.be&t=4m28s
https://www.youtube.com/watch?v=kiKmBnVZIjg&t=9m30s
https://www.youtube.com/watch?v=D16d5kzadYQ&feature=youtu.be&t=65
https://www.youtube.com/watch?v=szKGijo3kWY&feature=youtu.be&t=17m58s

I hope this is enough for you to just believe me when I say something in the future.

--------

What does that mean? 

This means that Feign Death should probably not cause combat drop in PVP(maybe even PVE?)(probably influenced by the pet somehow) which needs to be researched/eventually fixed.


-----

Now to add something to the actual bugreport, this video shows the combat drops when the pet didnt attack right after FD was used:

https://www.youtube.com/watch?v=kiKmBnVZIjg&t=9m30s

**Comment by Easyfraggy** [comment]
Noone stated that this issue was specificly about PvP.... The OP even has a PvE vid linked you dingus. Finally something useful from you atleast.

**Comment by Evolvee** [comment]
This issue is about feign death - pet/combat interaction, not about pets triggering combat in PVE.

it doesnt matter what OP has linked, "you dingus", what matters is the issue which has nothing to do with what you provided

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/49258200-e444f000-f434-11e8-93ec-642d3b9d3257.png)

**Comment by Evolvee** [comment]
Which is not true, as I already explained.

Now focus on the real issue...

**Comment by Zarant** [comment]
I just changed the title to better reflect the actual issue to avoid any potential confusion.

**Comment by Zarant** [comment]
One more clip: Hunter feigns, start drinking and mobs start chasing his pet.
https://youtu.be/b1ZZdKla5kc?t=194

**Comment by The14me** [comment]
Rev.3478 not an issue anymore.
Can be closed.
