### ISSUE TITLE
[Spell][Mage] Ritual of Refreshment

### ISSUE THREAD

**Issue by itsjojotbh** [Atlantiss/NetherwingBugtracker#3143]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
This spell is not supposed to be in the game in 2.0
**Current behaviour**:
It exists.
**Expected behaviour**: 
It should not exist.
Evidence: [http://wowwiki.wikia.com/wiki/Ritual_of_Refreshment#Notes](url)
It wasn't introduced until 2.3 and we are currently in patch 2.0 so it should not be available for use.
**Server Revision**: 
2370

**Comment by Evolvee** [comment]
We will go with 2.4.3 player mechanics.
Im afraid it would be another "pain in the ass" for ppl to deal with on top of already tons of annoying 2.0 things.

You can try to talk to @aresbrutus on discord and with the rest of the community about it. Who knows, maybe it turns out ppl like it more without the spell...
Note that the spell will still require both tomes to be learned first before being able to get the ritual spell.
