### ISSUE TITLE
[Dungeon]specific [NPC]Tidal/Steam Surger#21695/21696 has an enormous aggro range

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3171]
**Description/current behavior**: 
This is done in the HC version. It might be a [[NPC]Steam Surger#21695](https://www.wowhead.com/npc=21696/steam-surger#comments) that pulled. Regardless it is very far away and it looks to pull through the pillar.
https://youtu.be/Guhocz_9SC0

Didn't do .npc for this.

[[NPC]Tidal Surger#21695](https://www.wowhead.com/npc=21695/tidal-surger#comments)
[[NPC]Steam Surger#21696](https://www.wowhead.com/npc=21696/steam-surger#comments)

**Expected behaviour**:
I'd expect this to not pull through a pillar ~40 yards away

**Server Revision**: 
2370

**Comment by Easyfraggy** [comment]
Are you sure the engineer wasn't stuck on the other side of the pillar causing them to assist agro on him like in https://github.com/Atlantiss/NetherwingBugtracker/issues/3165?

**Comment by Tenoutoften** [comment]
I don't, I guess that's why I commented
>possibly related to what I just posted
#3171

3 day ago... is a mob stuck behind there?

**Comment by Kidcudi123** [comment]
What do you think about this clip
https://clips.twitch.tv/BelovedVainSquidBudBlast

**Comment by devo6969** [comment]
The mob in question is Entry: 17721, Id: 7. (Coilfang Engineer) It appears when pulled from the right side the engineer will be stuck in combat with you come in LoS of the mob. Otherwise it will stand still and chain the elemental patrol. If pulled from the left side this issue doesn't happen. Perhaps a pathing issue because its in water? 🤔 

PTR - https://www.youtube.com/watch?v=cklDxzjWjqQ

(Screenshot of mob) -  https://i.imgur.com/JIkrRq0.jpg
