### ISSUE TITLE
[Spell]Melee Attack

### ISSUE THREAD

**Issue by Many12997** [Atlantiss/NetherwingBugtracker#3176]
https://www.wowhead.com/spell=150039/melee-attack
https://youtu.be/eQ0yTKRgLaI
**Description**: 
Melee Attack should be the same range for both players and mobs,still I was able to ourtange mobs and kill them without taking any damage just with white hits
**Current behaviour**:
Player have higher range thank mobs,(more than 5 yards)not sure about mobs melle range tho
**Expected behaviour**: 
Both mobs and player should have 5 yards range on Melee Attacks

**Server Revision**:

**Comment by Many12997** [comment]
Sorry for laggy video,but it serves its purpose,you can clearly see that i havent taken a single point of damage while killing this mob

**Comment by towneh** [comment]
Further testing on the dummies in Shattrath, I'm not convinced there is any leeway mechanic, at least I wasn't able to hit them whilst strafing just outside of the normal melee range when standing still.

Following is copied from another bug tracker:
"How it's suppose to work:

If you and your target is running, the game client will give you a +2.5 yard leeway range, same goes for your target, basically the range indicator for your melee abilities will be white when you're within 7.5 yards of the target(point to point). The server should allow you to cast your melee abilties as well as auto-attack during this mechanic.

There are some conditions to the mechanic though:
*Both you and the target has to be running/moving

*Leeway mechanic will immediately stop if you or your target becomes slowed to more than -29% of normal run speed(-30% is when your character will switch animation to walking instead of running). Note that it has to be more than -29% of normal running speed, meaning if you or your enemy is on a 100% and become slowed, but the slow doesn't slow down enough to go below -29% normal run speed, then mechanic will still work.
Example: Warlock with Curse of Exhaustion talented to grant 30% slow, you cast it on a rogue that has 8% run speed boots enchant. Then leeway mechanic will still work."

https://www.youtube.com/watch?v=_DgUcqXwtwk&feature=youtu.be&t=2m
^ This is an example of the retail leeway mechanic initiated by strafing.

https://youtu.be/SwSR1SHYZRI?t=190
^ Maydie strafes left and is able to attack the rogue to finish him off.

https://youtu.be/6oiIy5j5oUA?t=371
^ Chasing the rogue the melee attacks are visibly further than 5 yards,

**Comment by towneh** [comment]
Confirmed melee leeway mechanic is in place on Netherwing. The only thing that remains now is if this is being inherited by the NPC in the original post.

**Comment by Many12997** [comment]
I think I might've found where the problem is.I've noticed,that mobs sometimes stop for like half of a second when attempting to melee you.If they lose  Leeway bonus in moment,when one of us stop moving,that could explain why mob haven't touched me even once.

**Comment by Wolffenstein** [comment]
Fixed in rev 2421.
