### ISSUE TITLE
[Hunter] Feign Death - Pet Threat

### ISSUE THREAD

**Issue by Tim130** [Atlantiss/NetherwingBugtracker#3182]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
NPCs attacking pet after using Feign Death, even if the pet didn´t attacked / used abilties (short fights, few seconds).  

**Current behaviour**:
If my pet stayed in ~15 yd range and i use my Feign Death after pulling, the NPC will attack my pet.

**Expected behaviour**: 
The NPC should be reseted.

**Server Revision**: 
2377

**Comment by Tim130** [comment]
Thank you for your response. 
Like u shared, it would happen in a dungeon, but in my case it happens in the open world with a single pull. I can´t remember well and i still try to find a decent source.

**Comment by Zarant** [comment]
Hostile mobs should actively put players/pets on their threat list if they are within the npc aggro radius. I'm pretty sure that mechanic only works inside instances, it doesn't work outside as it can be used for griefing purposes, like aggroing a shit ton of mobs and then feigning in order to kill people from your own faction.

That explains the behavior towneh just described and this following clip:
https://youtu.be/FmT3oyRUB_o?t=226
The video above says that the pet has a "weird aggro range" but I honestly think that this particular mechanic I just described ticks every few seconds, adding a random element here, it's probably related to how long the pet is within the npc aggro radius.

**Comment by Zarant** [comment]
More sources of this particular mechanic: https://youtu.be/ZfTV61jJyQY?t=297
Shaman gets in combat by proximity, slightly before dropping a water totem. Notice that he got in combat ~5 seconds into the fight because someone else pulled.

**Comment by Zarant** [comment]
I did some testing and found the culprit:

- Whenever you feign, mobs do not properly reset and will attack your pet if your pet is nearby.
- If your pet is out of combat and get hit, you will get put back into combat, regardless if you are feigning or not.
- If the npcs pass through your pet, or even cast abilities aoe abilities (chilling howl, a npc version of demo shout) on your pet and you feign far away from your pet, mobs will reset properly and not attack your pet

As seen on the following clip: https://youtu.be/7FaV4as5rS0

**Comment by Tereneckla** [comment]
fixed rev 3052
