### ISSUE TITLE
[Boss][Karazhan] Curator Astral Sparks has too much hp.

### ISSUE THREAD

**Issue by Cptnlobbe** [Atlantiss/NetherwingBugtracker#3183]
**Description**: 
The adds spawned during the encounter has a very high HP pool.
**Current behaviour**:
Astral Spark is around 23k hp.
**Expected behaviour**: 
Should be around 13-14k hp.
Proof: https://www.youtube.com/watch?v=OqofXJ3uTw8    (best I could find, but you can figure out that its 13-14k.)
Uploaded before the 2.1 patch: https://www.youtube.com/watch?v=zXXRwYkEySg  
**Server Revision**: 
2377

**Comment by Drayo** [comment]
This Server is using pre-nerf values researched by the alpha and beta testers, they are also based on CC research that sadly cannot be found online anymore because many of those super old sites got taken offline and any videos of super early raid content no longer exist. (Might be able to find some on warcaftmovies, but even their hosts are often down)

That said though, I did Curator today and we killed him in pretty much only blue gear (some players unequipped weapons and trinkets + no elixiers), it was very challenging but doable.

**Comment by towneh** [comment]
![image](https://user-images.githubusercontent.com/25694892/49367403-e5e80f80-f6e3-11e8-8550-6ee139826082.png)

**Comment by Easyfraggy** [comment]
Not a bug - by march 22 karazhan was already nerfed significantly.
