### ISSUE TITLE
[Rogue][Talent]Sword Specialization

### ISSUE THREAD

**Issue by bloodwindz** [Atlantiss/NetherwingBugtracker#3212]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
sword spec procs
**Current behaviour**:sword spec procs (x2 swords)  when triggered by offhand they peformed by offhand (incorrect)

**Expected behaviour**: 
https://www.wowhead.com/forums&topic=28135
i was hardcore pve rogue in tbc  i remember it well   when offhand sword trigger sword spec its delivered by the mainhand instead 

**Server Revision**: 2386

**Comment by nullfoxh** [comment]
Additional proofs off-hand procs should indeed be performed by the main hand:

https://web.archive.org/web/20080529002950/http://elitistjerks.com:80/705985-post1.html#Weapon_Specialization_and_Dual_Wield

http://roguecrap.blogspot.com/2006/05/more-on-sword-spec-modeling.html

**Comment by Neophrone** [comment]
Idk did dews already fixed it or not (probably they even didn't try to fix it since this issue is still open becouse they were busy with fixing another high-prio issues) but everything works fine. Bloodwind told me about this bug yesterday. I loged on to my rogue, tested it on Dummy in Shatr, and saw in recount that some of Sword spec damage equivalent to my off-hand damage. I thought that this is a bug, since all extra attacks should be with Main hand damage. Pretty sure that Bloodwind and other testers were using recount to track sword spec damage as I was.
And we all fucked up.
Problem is that recount using combat log to track all this damage, procs and etc.
And when extra attack happens that is how it shows in combat log:
![1](https://user-images.githubusercontent.com/43533040/49960632-444d9300-ff19-11e8-9bad-7b8f87c424ca.jpg)
This is the end of combat log, message about 1 Extra attack is a last massage in it. But extra attack happened (I saw it in my combat text). Extra melee swing in combat log showed right after melee swing that triggered this extra attack ( on screenshot: 376 damage - melee swing that triggered extra attack, 195 damage - extra attack) and after that combat log wrote that last swing was an extra attack.
But recount count next swing after "Neophrone's gain 1 Extra attack through Sword Specializtion" as an extra attack.
![2](https://user-images.githubusercontent.com/43533040/49961550-9db6c180-ff1b-11e8-90ec-fc29c2df68f8.jpg)
Look at the screenshot. Extra attack happened, but recount doesn't show any Sword Spec damage.
![3](https://user-images.githubusercontent.com/43533040/49962058-e58a1880-ff1c-11e8-8544-6f41b2e338bd.jpg)
He even can count Sinister Strike as an extra attack.
Everything works as it should:
![4](https://user-images.githubusercontent.com/43533040/49963013-84b00f80-ff1f-11e8-8eb7-839225bfb801.jpg)
