### ISSUE TITLE
Tiger´s fury Feral druid

### ISSUE THREAD

**Issue by Evgenyx123** [Atlantiss/NetherwingBugtracker#3242]
![wowscrnshot_120518_000638](https://user-images.githubusercontent.com/44301820/49479177-601eae00-f822-11e8-90c6-07d96fd03389.jpg)
![wowscrnshot_120518_000641](https://user-images.githubusercontent.com/44301820/49479181-63b23500-f822-11e8-8b7a-3adf381247ec.jpg)

Feral druid ability Tiger´s fury

Tiger´s fury is not increasing damage to Ferocious bite and Rip

Tiger´s fury should increase damage done by Ferocious bite and Rip.

(see screenshots)

**Comment by rjorgensen** [comment]
This is not a bug.
I did some testing on my own druid and tiger's fury applied to ferocious bite.
![ferocious bite](https://user-images.githubusercontent.com/45169919/49481966-944b9c00-f82d-11e8-8156-60b425bd0a9d.png)
_Top: With Tigers Fury active. Bottom: Without Tigers Fury active_
Each was done with max energy, although the one low number for each is likely due to not full energy (the 903 hit without definitely was).
The numbers i saw will testing where very consistent with very little variance +-5.
