### ISSUE TITLE
[NPC] The Curator

### ISSUE THREAD

**Issue by nycheia** [Atlantiss/NetherwingBugtracker#3284]
Currently drops aggro and goes for a healer at a random point in the fight, and one shots them, despite the healers not being 2nd or 3rd on threat (according to omen, which is probably not the most reliable source). 

https://www.youtube.com/watch?v=3iUY4ijcH94&feature=youtu.be

Another issue, the hateful bolts were pretty much exclusively targetting healers through 3 attempts, despite them not being 2nd or 3rd on threat either. 

**Server Revision**: 
2401

**Comment by Drayo** [comment]
Looks like it happened very early into the fight, Curator takes 90% reduced damage when he is not evocating, that means tank threat is very low early on.
He aggroed right after a heal went through so it very much looks like healing aggro. You can also see the priest being over the tank @0.05s in the video, after that the Paladin tops two players off.

How can healers not be 2nd or 3rd on threat this early into the fight? Who else is supposed to do enough damage to take their place?
Also, remeber, Curator won't cast his Bolt on players that would not survive it before he enrages, so that means he could also target the 5th player on threat.

**Comment by nycheia** [comment]
Its not that early into the fight if its over half way to first evo, and it happened 3 times to both healers. It happened after the first evo once, and it happened once half way to evo and one time right before the first evo. 
I have a hard time believing that its blizzlike to out-aggro the tanks and dps consistently, even after evo.

**Comment by Drayo** [comment]
You killed 5 flares, it's an ~ 8-10 Minute fight, of course 1 minute into it is early. And like I said, when you target the Boss at 0.05s you can even see the priest having dangerously high threat.

His buff called "Astral Armor" is part of his pre-nerf state, it was not present for most Raids clearing Kara back in TBC because it was removed very early on.

If I'm seeing this correctly you are also trying to heal this fight with 2 healers, I doubt that is even possible, at least in blue HC-Gear but aside from that it also increases the threat on the healers even more.
We did not have any issues when we did it last week, so there is a possibility that recent changes introduced a bug, but it really does not look like it.

**Comment by nycheia** [comment]
Its not an 8-10 minute fight with this gear and setup. We did it in two evos last two times with this setup. This is the first time there has been any issue regarding healers directly over aggroing the boss, and it happened consistently. Both before the first evo, and after the first evo. There's no way im supposed to get aggro, especially after the first evo.

**Comment by Drayo** [comment]
In that case it would most likely good if a GM can test it when they have time to spare, it should be easy to see if anything is off by using .damage and extremely strong heals. They also have access to the debug threat command and don't need to rely on omen.

@Easyfraggy

**Comment by Easyfraggy** [comment]
I have yet to see any proof of this happening with anything other than paladin tanks that have a problem doing threat during Astral Armor.
