### ISSUE TITLE
Unstuck Abuse

### ISSUE THREAD

**Issue by JamesCutter** [Atlantiss/NetherwingBugtracker#3431]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: On certain servers the unstuck feature can be used to speed up the leveling process (like a free Hearthstone). I think if you have your HS up and you use unstuck it should put your HS on CD and send u to your HS's location. In case your HS is on CD, unstuck should bring u to your race starting location and most important Refresh your HS's remaining CD back to full. This way ppl cannot abuse the feature like they can on other servers.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by hunterclassy** [comment]
can be exploited to change continents, if you are for example in kalimdor and your race is human, it sends you to northshire Eastern Kingdoms. So the slightly up teleport spell "stuck" would be the fix to go.

Patch 2.4.3

    If you have a hearthstone it will use that to get you out of a tough spot, if not it will attempt to manually teleport your character slightly.

**Comment by Shanghi** [comment]
This can negatively affect the launch letting people abuse it to get a lead over people that slowly walk back each quest instead of teleporting back, so if the nudging mechanic can't be safely added before then (I expect lots of possible abuse with it too!), then maybe a temporary cooldown change can be until it's properly fixed. Something like:
* increase the unstuck cooldown to 30 minutes instead of 5 which is still abusable but not as badly
* or don't allow unstuck to be used if their hearthstone is on cooldown if they're below level 10, which is a bit dangerous for anyone unlucky enough to actually get stuck before level 10 somehow, but they could make a ticket!

**Comment by Wolffenstein** [comment]
Fixed in rev 2577 (it will kill instead of nudging).

**Comment by cah4ec182** [comment]
Unstuck kill the character, please, fix.

**Comment by Shanghi** [comment]
That's intended to stop people from abusing it. In the very rare case of actually getting stuck while your hearthstone is on cooldown you can still free yourself.
