### ISSUE TITLE
([Talent][Mage] Master of Elements)

### ISSUE THREAD

**Issue by Kantrul** [Atlantiss/NetherwingBugtracker#3477]
****Description**:** 

The talent Master of Elements from the mage fire tree is inconsistent and doesn't give mana back when you land a spell critical hit.

****Current behaviour**:**

The talent Master of Elements is inconsistent and sometimes it doesn't give mana back on spell crit.

proof: https://streamable.com/qpq7p

****Expected behaviour**:** 

Master of Elements should always give mana back on spell crit.

****Server Revision**:** 

2451

**Comment by Saben65** [comment]
The issue seems to be that it only checks for a crit on the first damage portion. The same thing is happening with [The Lightning Capacitor](https://www.wowhead.com/item=28785/the-lightning-capacitor) where you will not get a charge if the 2nd target gets crit and the first target (from the combat log's point of view) does not get hit.

This also prevents you from getting ignites on any secondary targets.

Crit lands on second target, no ignite, no electrical charge from lightning capacitor.
> Frigid's Flamestrike hits Test Dummy for 1108 Fire. 
**Frigid's Flamestrike hits Test Dummy for 1671 Fire. (Critical)** 
Test Dummy suffers 171 Fire damage from Frigid's Flamestrike. 
Test Dummy suffers 171 Fire damage from Frigid's Flamestrike. 
Test Dummy suffers 171 Fire damage from Frigid's Flamestrike. 
Test Dummy suffers 171 Fire damage from Frigid's Flamestrike. 
Test Dummy suffers 171 Fire damage from Frigid's Flamestrike. 
Test Dummy suffers 171 Fire damage from Frigid's Flamestrike. 
Test Dummy suffers 171 Fire damage from Frigid's Flamestrike. 
Test Dummy suffers 171 Fire damage from Frigid's Flamestrike. 

Crit lands on first target, procs ignite and a lightning capacitor charge.
> **Frigid's Flamestrike hits Test Dummy for 1573 Fire. (Critical)** 
Frigid's Flamestrike hits Test Dummy for 1048 Fire. 
Frigid gains 352 Mana from Frigid's Master of Elements. 
Frigid's Electrical Charge is refreshed. 
**Frigid gains Electrical Charge.** 
Test Dummy suffers 171 Fire damage from Frigid's Flamestrike. 
Test Dummy suffers 171 Fire damage from Frigid's Flamestrike. 
**Test Dummy suffers 314 Fire damage from Frigid's Ignite.** 
Test Dummy suffers 171 Fire damage from Frigid's Flamestrike. 
Test Dummy suffers 171 Fire damage from Frigid's Flamestrike. 
Test Dummy suffers 314 Fire damage from Frigid's Ignite. 
Test Dummy suffers 171 Fire damage from Frigid's Flamestrike. 
Test Dummy suffers 171 Fire damage from Frigid's Flamestrike. 
Test Dummy suffers 171 Fire damage from Frigid's Flamestrike. 
Test Dummy suffers 171 Fire damage from Frigid's Flamestrike.

**Comment by killablink** [comment]
Still not fixed, it's very important for fire mage's aoe dps and mana management

**Comment by knasen88** [comment]
it's related to AoE only, for the talent to work every single hit of flamestrike must crit. Same with the crit talent usable, it won't lose a charge if not the entirety of flamestrike crits. if they ALL crit, you should be getting mana back. Easily testable with the 31 point talent

**Comment by Saben65** [comment]
If even just one crits, you should get mana back.

> Master of Elements is a popular PvE talent for any talent build with more than 15 points in the Fire tree. **It restores up to 10/20/30% of the mana cost of a Fire or Frost spell that critically hits one or more targets** (so AoE spells such as Flamestrike, Cone of Cold and Blast Wave are affected by this talent). Since most mages critically hit between 20 and 40% of the time this talent is equivalent to an effective mana cost reduction to Fire and Frost spells.
> 
> Other talents that reduce mana cost include Elemental Precision, which reduces mana cost of Fire and Frost spells up to 3% directly, and Frost Channeling which reduces the mana cost of Frost spells only by up to 15% directly.
 
https://wowwiki.fandom.com/wiki/Master_of_Elements?oldid=859822

**Comment by killablink** [comment]
Yeah not sure was knasen88 means, but you should get mana back if at least 1 target gets critically hit from your aoe spells

**Comment by killablink** [comment]
It gives mana back even if you crit 5 out of 10 for example because right now it's somehow checking if the "main target" ( I don't know how that target is decided ) gets crit or not and then you get your mana back accordingly. Combustion is also bugged where it doesn't give +5 charges if you aoe 5 mobs and get no crits.

**Comment by Tereneckla** [comment]
Fixed
