### ISSUE TITLE
Darkshore-Azuremyst Isle boat

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#352]
The boat between Darkshore and Azuremyst does not show the full length of travel.
When you are leaving the zone (in either direction) the boat freezes for about 30 seconds, then the loading screen appears, then the boat reappears already at the dock.
https://youtu.be/AZuyRqBDIfI

**Comment by ttghnw** [comment]
I confirme I witnessed this too.

**Comment by Firroth** [comment]
I will add one more thing to this issue. While waiting for the boat on Azuremyst to Darkshore you can't even get on the ship since you don't see the boat, you only see it when it starts leaving the port where you waited for the boat - so you have like 1 second to react and jump onto it or else you need to again wait for next opportunity. I failed getting onto the boat 3 times, till I got what's happening and that boat is here but I just can't see it. Same went for another player who was near me waiting for it.

**Comment by Sothanwow** [comment]
I am going to add some more ontop of what was said earlier as I think it is related to this issued  I had a issue where  the boat didn't load for me at all until it started the moving animation. Before then it was invisible. As noted in this video [here](https://streamable.com/0x2ts) I tried a few other test list jumping onto the boat while I couldn't see it but fell through.  It stayed completly glitched for about a hour before going back to the boat freezing and teleporting.

**Comment by Sinyr** [comment]
In rev 2050, seems this bug got even worse. When traveling from Azuremyst to Auberdine, you do get the load screen when you should (the boat doesn't stay in place) but it teleports you to this weird spot:

![screenshot_4](https://user-images.githubusercontent.com/9539181/46046589-e97a7b80-c121-11e8-9f32-7689e8a9f193.png)

After half a minute or so it teleports you to the destination with no loading screen.

Similar thing now also happens when traveling from Auberdine to Wetlands, which was working properly  earlier today.

**Comment by narayagh** [comment]
1. For me, the boat just pops in when it's docking - see this video: https://streamable.com/xdxih

2. Also there is no ding-ding sound when the boat docks - I assume this sound should be a standard on docks.

3. After departure from Azuremyst, the boat stops moving when the loading screen should appear (I think), and after ~30 seconds there is a short loading screen with taurens in it and the player shows up on a boat **already docked** at the Auberdine dock.

**Comment by Sinyr** [comment]
Going from Auberdine to Azuremyst Isle now ports you to Hellfire Peninsula first for a couple of seconds.
![screenshot_14](https://user-images.githubusercontent.com/9539181/46257174-bb948e80-c4b5-11e8-929b-fa3c1b56ab27.png)

**Comment by Easyfraggy** [comment]
Retest in 2131 should be fixed.
