### ISSUE TITLE
Quest "The Perfect Stout"

### ISSUE THREAD

**Issue by craigsurbrook** [Atlantiss/NetherwingBugtracker#3597]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Testing from a lvl 1 that I kept in reserver, now that we are two weeks away from release, the shimmerweed baskets aren't even at any of the camps. At each troll camp there are only two trolls, and they do, after awhile respawn. But so far, I haven't been able to even get a single shimmerweed off of them.

**Current behaviour**:
Two trolls only per camp, long respawn time. No shimmerweed baskets. No shimmerweed.

**Expected behaviour**: 
Lot's of trolls at each camp. Shimmerweed baskets are available. You can actually get shimmerweed drops off of killing trolls as well as from the baskets.

**Server Revision**: 
2485
2018-12-23

**Comment by Shanghi** [comment]
The low or no spawning is caused by a problem in the big update last night affecting every mob/object that has dynamic respawning enabled. All the trolls and baskets will be there once it's fixed. Until it is, quest testing is going to be terrible because almost everything involved with them will have dynamic spawning, so unless you're the first to visit a place it's going to look bad!

I think you just got unlucky with the shimmerweed drop. They already have them set as loot and I just got 4 out of 10 kills when testing.

Related: https://github.com/Atlantiss/NetherwingBugtracker/issues/3591

**Comment by Tereneckla** [comment]
Many trolls there, but no drops of shimmerweed.
http://web.archive.org/web/20081022093149/http://thottbot.com/c1397

The basket gameobject 276 Shimmerweed Basket exist, but they are not interactable with.
Testing in GM mode also showed them having no Shimmerweed inside.

**Comment by Tereneckla** [comment]
Actually fully working as of 3418
