### ISSUE TITLE
[Spell][Shaman] Fire totems agro

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3599]
**Description**: 
Fire totems generate low or no threat.

**Current behaviour**: 
1. Fire nova totem: Generates 0 threat when you drop the totem
2. Searing totem: Doesnt seem to generate any threat aswell. When you facepull mob searing totem can kill it alone without overagro.
3. Magma totem: Generates very low threat

**Expected behaviour**: 
1. Fire nova totem is supposed to generate moderate threat when you drop the totem on ground
2. Searing totem is supposed to cause some threat aswell.
3. Magma totem should generate high threat (hence there is talent "Improved fire Totems")

**Server Revision**: 2485

**Comment by syphex97** [comment]
This shit is still bugged, and is randomly engaging invisible enemies or neutrals as well that can be attacked.

**Comment by devo6969** [comment]
Suppose to attack random nearby targets.

https://classic.wowhead.com/npc=7402/searing-totem-vi#comments

"Good mana efficient damage. To make the best use of this totem cast it at the beginning of a fight so you get the full duration and use out of the mana spent. Can be dangerous to use in certain areas since it will automatically attack another target once the current target is dead."

https://classic.wowhead.com/spell=3599/searing-totem#comments
"The totem automatically attacks any enemies in range, regardless if you're in combat with them or not."

**Comment by Tereneckla** [comment]
Fire Nova Totem generates a bit of threat
Searing Totem is a seperate issue
Magma Totem threat is fine
