### ISSUE TITLE
[Spell][Shaman] Stoneclaw Totem

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3600]
**Description**: 
Stoneclaw totem doesnt stun attackers
https://github.com/Atlantiss/NetherwingBugtracker/issues/237

Stoneclaw agro is very low

**Current behaviour**:
Stoneclaw doesnt stun attackers
Stoneclaw agro is very low

**Expected behaviour**: 
Should have 50% chance to stun attackers for 3s
Stoneclaw agro should be higher

**Server Revision**: 2485

**Comment by Epsynus** [comment]
**Server Revision**: 2566

The issue is still present.
In the following video: https://www.youtube.com/watch?v=ybal9h5epJc&feature=youtu.be

I put down the Stoneclaw totem and do an Earth Shock on a Teromoth and then position myself close to the totem. With just me doing that one attack, the Stoneclaw totem doesn't manage to aggro the mob from me until the very last second it is active.

This makes the totem completely useless!

**Comment by Wolffenstein** [comment]
Fixed
