### ISSUE TITLE
[Spell][Mage] Spellsteal forberance buffs

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3616]
**Description**: 
Spellstealing forberance buffs while having already forberance, refreshes the duration of forberance.
**Current behaviour**:
Spellstealing forberance buffs while having already forberance, does not aplly the buff (correct)  but also refreshes the duration of forberance (not correct)

**Expected behaviour**: 
Should only dispell the buff (works), but not refresh the duration of forberance, because no new buff that causes forberance was gained in first place.
**Server Revision**: 2485

**Comment by torrenzGH** [comment]
http://wowwiki.wikia.com/wiki/Patch_2.3.0
Spellsteal: It is no longer possible via this spell to get two Forbearance debuffs at the same time. 

in practice, current behavior is the same as before this patch
so unless they only patched this for aesthetics it should probably not refresh duration

**Comment by killablink** [comment]
I'm pretty sure you can still spellsteal the BoP and have the buff correctly apply. You will receive forbearance if you first didn't have it to make it so that you can't receive a BoP from another paladin. It has always been like that.

The fact that you could have 2 forbearance debuffs at the same time was because you indeed had the buff transferred to you in the first place, otherwise receive a second forbearance debuff without the buff makes no sense.

https://us.battle.net/forums/en/wow/topic/20753886492

**Comment by Aeded** [comment]
why are you linking topics from legion? 🤔

**Comment by killablink** [comment]
Because it hasn't changed since

**Comment by Wolffenstein** [comment]
Fixed in rev 2491.
