### ISSUE TITLE
[NPC] Troll Roof Stalkers detected from ground floor of buildings

### ISSUE THREAD

**Issue by Hidole555** [Atlantiss/NetherwingBugtracker#3692]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Level 70 players going about their business in Orgrimmar will hear unstealthing sounds over and over again as the stealthed Troll Roof Stalkers can be easily detected through the roofs from the ground floor of multiple buildings.
There are several buildings that can be used to recreate this. Inside the Auction House was where I first noticed it. Going up the tower to the Orgrimmar Flight Master will result in you hearing the Stalker on a nearby roof unstealth multiple times as your character's direction faces them and turns away repeatedly due to the spiral ramp. I find Kaja's Boomstick Imports next to the Auction House to the most severe as both the second floor ramp and the roof are obstructing your vision of the above Troll Roof Stalker yet he still becomes unstealthed.
**Current behaviour**:
Troll Roof Stalkers can be detected by level 70 players from inside many buildings.
**Expected behaviour**: 
I feel that a Stalker on the roof wouldn't be easily detected by people on the ground floor.
**Server Revision**: 
2515

**Comment by Evolvee** [comment]
I reported the same few years ago. http://tbc.internal.atlantiss.eu/showthread.php?tid=1353&highlight=sound

https://www.youtube.com/watch?v=SZYCX7uq50Y
its pretty annoying

**Comment by killablink** [comment]
Are their stealth "level" just really low? You can see them from really far away, compared to for example finding a stealthed rogue even same faction.

Because not only I feel you really shouldn't be able to find a stealthed person so far above you, there is also implications in pvp on this report that was "closed". I still believe you shouldn't be able to see a stealthed person above you.
https://gfycat.com/BountifulRemoteCygnet
#2791

**Comment by killablink** [comment]
What I'm saying is that is the stealth of the troll really shit and are you able to generally NPC stealthed mobs more easily than players? Because this is where you can detect a same faction 70 rogue without MOD
![wowscrnshot_122818_133429](https://user-images.githubusercontent.com/43510874/50524792-c0adad80-0aa5-11e9-90e8-f2b50de1b4ed.jpg)

With MOD
![wowscrnshot_122818_133408](https://user-images.githubusercontent.com/43510874/50524796-c60af800-0aa5-11e9-9458-45e6ffb26b0f.jpg)

And about how far you can detect the trolls
![wowscrnshot_122818_133616](https://user-images.githubusercontent.com/43510874/50524805-cf946000-0aa5-11e9-8e9f-0bb532395353.jpg)

Either way, I think there is definitely something going on how you can detect stealthed people from way above you, but I think the problem is that their stealth level is too low

**Comment by The14me** [comment]
rev.3472 not an issue anymore.
Can be closed.
