### ISSUE TITLE
Murlocs dropping cloth in general

### ISSUE THREAD

**Issue by Thorgrimme** [Atlantiss/NetherwingBugtracker#372]
[//]: # https://web.archive.org/web/20080210005545/http://thottbot.com:80/c1024
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC]Murlocs in general
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Linen cloth, Wool cloth etc
[//]: # ([Web] Armory doesnt work)

**Murlocs in general dropping cloth, which they shouldnt**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by tiSchnarr** [comment]
Same issue with Naga.

**Comment by scarabadookie** [comment]
Worgen are also affected

**Comment by Tenoutoften** [comment]
**Description**: 
These NPCs are dropping [[Item]Linen Cloth#2589](https://www.wowhead.com/item=2589/linen-cloth) but shouldn't.
* [[NPC]Murloc#285](https://www.wowhead.com/npc=285/murloc)
* [[NPC]Murloc Streamrunner#735](https://www.wowhead.com/npc=735/murloc-streamrunner#drops) 

Generally sea creatures don't drop cloth.
http://web.archive.org/web/20071122034028/http://thottbot.com:80/c285
![0bc0d0cd136dd2b6d050144629a74b93](https://user-images.githubusercontent.com/34839199/49640595-48a41880-fa0e-11e8-8302-9671ceabfa64.png)
http://web.archive.org/web/20071109131317/http://thottbot.com:80/c735#A::A
![c6599094b160984eea935ec5fd2c4058](https://user-images.githubusercontent.com/34839199/49640460-ee0abc80-fa0d-11e8-92ae-9afdfc78a28a.png)

**Expected behaviour**: 
Shouldn't drop [[Item]Linen Cloth#2589](https://www.wowhead.com/item=2589/linen-cloth)
* [[NPC]Murloc Streamrunner#735](https://www.wowhead.com/npc=735/murloc-streamrunner#drops) 
* [[NPC]Murloc#285](https://www.wowhead.com/npc=285/murloc)

**Server Revision**: 
2402

**Comment by Shanghi** [comment]
This should be fixed (for them and similar cases like nagas and yetis and the rest) after revision 2525.
