### ISSUE TITLE
[Spell][Hunter] Tame Beast

### ISSUE THREAD

**Issue by fazhenghan** [Atlantiss/NetherwingBugtracker#3723]
**Description**: 
Hunter seems can tame another beast by just dismiss current pet. Which I don't think is right.
**Current behaviour**:
Hunter seems can tame another beast by just dismiss current pet. Sorry, I don't know how to record but a GM (Smaily) witnessed what I did.
**Expected behaviour**: 
You need to save your pet in stable/abandon the current pet, to tame another beast.
**Server Revision**: 
2546

**Comment by The14me** [comment]
Need Hunter Experts.

**Comment by fazhenghan** [comment]
http://us.battle.net/wow/en/game/patch-notes/4-0-1
"Five pets can now be stored with the hunter at all times. Any one of these five pets can be summoned via the Call Pet ability."

I think start from 4.0.1 hunter no need to saving their pet in Stable to tame another beast. Now in test server hunter can tame another beast by dismiss current one and it seems just overlap your last pet.

**Comment by fazhenghan** [comment]
Wingsam find this first, thanks to him we have the chance to solve this now.

**Comment by Zarant** [comment]
https://youtu.be/wcA8O_dRLy0?t=361

You should be able to tame another pet by abandoning the first one.

**Comment by Argonn** [comment]
Hunter here, in TBC you should not be able to tame an other beast by simply dismissing (not disbanding) your current pet.
In retail they changed it around, so you can tame another beast and send your current to the stable. But in pre cata versions, you should always visit a stable master in order to store your current pet, or disband it from anywhere, in order to tame a new beast.

**Comment by Manaci** [comment]
Fixed
