### ISSUE TITLE
[Gameobject][Loot] The Den Issues

### ISSUE THREAD

**Issue by Shrizz** [Atlantiss/NetherwingBugtracker#3829]
**Description**: 

Couple of bugs I noticed while testing out The Den quests on Horde (the quests themselves worked fine, so that's good, although I noticed that you don't have to plant a flag for credit on Horde Presence. Even though the quest tells you to, there doesn't seem to be any effect to doing so, as far as I could tell).

**Current behaviour**:

1) Tattered Chests in The Den were empty :(
2) The rare mob, Nal'tazsar, casts a Chain Lightning spell that hits for a massive ~400 damage. This seems excessive for a lv30ish mob. It's not impossible to kill but it seems overtuned nonetheless.

**Expected behaviour**: 

1) Tattered Chests should contain appropriate chest loot.
2) Not sure if Nal'tazsar's Chain Lightning is tuned; not game-breaking either way. At the very least it makes for a nasty surprise to anyone trying to kill it at that level ;)

**Server Revision**: 

2590

**Comment by Shanghi** [comment]
1. Chest loot should be fixed with the release
2. That damage seems to be normal based on some comments! Hopefully it kills a lot of people who think it looks weak!
![image](https://user-images.githubusercontent.com/2672633/50700196-e8f25a80-1017-11e9-83cc-484235cf370d.png)
![image](https://user-images.githubusercontent.com/2672633/50700206-f60f4980-1017-11e9-9442-1ba0f8f2b12a.png)

Not having to plant the flag thing is strange but that's how it was on retail too. I can't remember the item to look it up again now, but I had a report ready to post about it before because it tricked me too when I tested that quest.
