### ISSUE TITLE
Warlock Pet questionable behavior?

### ISSUE THREAD

**Issue by pmachielsen** [Atlantiss/NetherwingBugtracker#384]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
 # [Warlock] [Pet Behavior]
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Warlock pet in defense mode starts attacking when i toggle melee atack on a target from  #range.
**Current behaviour**:
When i target a mob from range and toggle melee attack my Warlock Pet (Imp at the moment) in Defensive and Aggresive stance starts casting Firebolt.
**Expected behaviour**: 
Don't know what the proper behavior is on this one so i leave it here to be reviewed. 
**Server Revision**:

**Comment by wtRCH** [comment]
Refered to https://github.com/Atlantiss/NetherwingBugtracker/issues/321

**Comment by BlessedByTheSin** [comment]
"Theres somethin rly weird  goin on whenever you switch your pet from being passive to defensive. Sometimes pet doesnt want to attack even tho im in combat (gettin melee'd) or whenever pet opens the fight and I retake an aggro and start kiting mob, forcing my pet to follow (not attacking). Once I  start attacking again (not moving) pet stands still. Also sometimes giving pet command to "Stay" and pressing again "Follow" , it forces pet to attack again. "

**Comment by The14me** [comment]
There is related bug with stance too.If u kill Npc and dont move after that,the pet wont follow any commands.

**Comment by Tereneckla** [comment]
Only warlock pets go to attack on right click when set on defensive.

**Comment by devo6969** [comment]
https://wowwiki.fandom.com/wiki/Defensive
A defensive pet will attack any mob that attacks it or attacks its master. This can be helpful for a hunter or a warlock character who is working solo, as the pet will immediately respond to any threat. It can be particularly useful if the opening attack from the mob stuns or otherwise incapacitates the character. 

Will say that when you toggle passive while kiting and when you switch back to defensive stance, the pet does not attack and just follows you. 
https://www.youtube.com/watch?v=8jby9D3dEZI

**Comment by Wolffenstein** [comment]
Fixed in rev 3520.
