### ISSUE TITLE
Enemy dodges/parries not giving rage 

### ISSUE THREAD

**Issue by femdead** [Atlantiss/NetherwingBugtracker#3846]
Enemy dodges/parries not giving rage on your white swings, they should give rage equal to an average white swing's damage (misses ofc should not give rage)

source would be https://youtu.be/ILH-CdfvVfI?t=42, from vanilla yes but you can see a parried white swing generates rage

**Comment by femdead** [comment]
Well he is hitting the whelps in this section of the video for ~420-450 damage with his other white swings, which translates to 14-15 rage at level 60. It's hard to tell the exact number on the ui in this video but seems believable that it's either this number or some high coefficient of it

**Comment by Crusaderz** [comment]
@Easyfraggy since you closed #3947 with "high-prio-issues", "Core Mechanic" and "Class: Warrior" tags then you need assign those tags to this one. This bug is **CRITICAL**.

From patch notes:
Patch 1.3.0 (2005-03-07): Fixed a bug where rage was not being generated when normal melee attacks were parried, dodged, and blocked.

Warriors should gain same amount of rage as successful hit.
Vanilla video:
https://www.warcraftmovies.com/movieview.php?id=29219
YT reupload: https://youtu.be/FkTaOBJplK8
19:27 - from 49 rage to 63 normal hit, 421 damage, 14 rage gained.
19:31 - from 53 rage to 67 normal hit dodged, 14 rage gained.

**Comment by Easyfraggy** [comment]
Well ofc I closed it - it was a duplicate - use the search function before reporting next time.

**Comment by Crusaderz** [comment]
@Easyfraggy my bad. Can you add proper tags to this bug report?

**Comment by Easyfraggy** [comment]
These priority lists mean a lot less than you think. I'm a warrior myself and I don't think this is a high-priority issue. It's not as big as a lot of other issues that are around atm - user: Wtrch is a bit trigger happy with the high-prio tag in general - I've complained about it several times. 

In any case wether it's high or medium priority has no impact on how fast it will be fixed atm. Sorry if the tags are confusing to people who don't know how development is being done.

**Comment by Wolffenstein** [comment]
Fixed in rev 2804.

**Comment by Crusaderz** [comment]
@Wolffenstein thanks! Does this fix also affects blocked attacks? Only dodge and parry mentioned in changelog.

>Patch 1.3.0 (2005-03-07): Fixed a bug where rage was not being generated when normal melee attacks >were parried, dodged, and blocked.
