### ISSUE TITLE
Bloodscalp Witch Doctor Earthgrab Totem deals damage

### ISSUE THREAD

**Issue by Jseay1313** [Atlantiss/NetherwingBugtracker#3931]
deals 110 damage a pulse, should not deal damage

**Description**: 

**Current behaviour**: deals damage

**Expected behaviour**:  no damage on earthgrab

**Server Revision**: 2606

**Comment by Drayo** [comment]
This issue is still present.

- Every time the mob puts down the totem, it roots you once and quickly ticks 4 times for about 140-150 damage. 

Meaning you take up to 600 damage with no way out. At level 35 that's at least 30-40% of your entire HP pool.

- Also, the Totem only roots you once, it should cast the root again after about 10 seconds, giving you only a few seconds to move and kill it.

**Comment by Wolffenstein** [comment]
Fixed in rev 3475.
