### ISSUE TITLE
Druid talent Primal Fury with bear form swipe

### ISSUE THREAD

**Issue by aresbrutus** [Atlantiss/NetherwingBugtracker#3938]
Druid talent Primal Fury does not give the 5 rage on crit when swiping in bear form. Requesting more info on if this is correct or if it should give you 5 rage on this abilities crit. Also, if druids get this rage with swipe crit, should it only give once or on every crit for that 1 swipe?

**Comment by Zadiel** [comment]
I'm reasonably certain Swipe is supposed to give you 5 rage every time you crit, and that includes multiple hits of a swipe critting on a single use of it.

**Comment by wtRCH** [comment]
Confirmed because of comments.

**Comment by Hatson22** [comment]
This issue isn't only for Bear Swipe. It's for everything in Bear Form.  What's strange is that it seems to be random? Sometimes I get 5 rage for crit, sometimes I don't. Sometime I get 2x5 rage for double crit, sometimes I get nothing for double crit. Very confusing.
Here's example of triple crits and I get absolutely no range, not for the melee swing or the swipe (which hit 2 units): https://puu.sh/Cx5SF/fc5c043975.jpg

Pretty huge detriment for Druid tanking!

**Comment by Hatson22** [comment]
This is still broken. It feels like the Bear Form Primal Fury is stuck at Rank 1/2 (50% chance), like how the Cat form version was broken before. 
But the Cat Form version is also still broken. If you're not in melee range after you crit with an ability in Cat Form, you do not get an extra combo point. This often happens when doing things like jumping around in PvP or away from something as you're attacking with an ability. 
The crit will happen, the first combo point is applied, and then, as usual, there's a short delay before the 2nd combo point is applied (I assume this delay is because of spell batching or something? Whatever it is, it's pretty stupid for combo points being delayed) - But the 2nd point is never applied if you're out of range of the opponent you just crit.

**Comment by Luminnar** [comment]
yes. can confirm. wanted to make my own bug report too. you should also add that MAUL should also grant 5 rage on a critical hit, despite being an ability that uses rage on the next attack. it's super easy to test that one as well (get into bear form with natural shapeshifter talent so you have 10 rage, buffer maul on a critter and observe results). this talent is a HUGE buff for druids and it's gamebreaking as it is. i also think that primal fury might be stuck being at rank 1, despite having it 2/2 (or 100% chance to proc it in bear form)

**Comment by Wolffenstein** [comment]
This issue has been resolved.
