### ISSUE TITLE
[spell][mage] blink to ground (from air)

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#395]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
should be able to avoid fall dmg, sometimes does nothing, sometimes port you to ground but still take damage
**Current behaviour**:
https://streamable.com/xtlvs
**Expected behaviour**: 
https://www.youtube.com/watch?v=nlrEsEKCU3s
**Server Revision**:

**Comment by killablink** [comment]
Here's another behavior that blink is supposed to have. I clip I had recorded from retail :
https://youtu.be/0Tr4vjhawQc?t=429

The way blink in the air works is I believe if you blink in the air and the distance between you and the ground is 20 yards, you blink to the ground. I believe there's a bit more leeway in the air because I remember blinking pretty far up in the air and still blink down to the ground, kind of how it works on retail right now (I can record a clip if needed). But generally, if you are really high up in the air then of course you blink but don't move at all. 20-30yards~ from the ground and you blink to the bottom

**Comment by knasen88** [comment]
Did several jumps from og tower after to try but couldn't get it to work without fall damage, I think if it slopes downwards it's impossible here, had limited success when meeting a ramp surface on other places but mainly the window of blink seems really small

**Comment by Tenoutoften** [comment]
https://www.youtube.com/watch?v=eiC7fX07cGE&feature=youtu.be&t=499
https://github.com/Atlantiss/NetherwingBugtracker/issues/2626
