### ISSUE TITLE
[Warrior] 100% of rage lost when ability miss instead of 20%

### ISSUE THREAD

**Issue by Crusaderz** [Atlantiss/NetherwingBugtracker#3957]
Only 20% of rage should be spend when ability miss. It worked this way since vanilla.

TBC:
https://www.youtube.com/watch?v=9Dj2KCL6tSc @ 1:54 he went from 29 rage to 27 when his heroic strike missed warlock.
Heroic strike cost 15 rage * 0.2 = 3. He either had imp. heroic strike (12 rage = 2.4) or gained 1 rage from anger management talent (he does have it).

Two videos from vanilla era:
https://youtu.be/FkTaOBJplK8?t=976
16.16: 29 rage
16.17: hamstring miss (10 rage) -> 27 rage -> 2 rage lost, 20%

https://youtu.be/LSLZJQFoTKs?t=428
7.07: 42 rage
7.09: overpower miss (5 rage) -> 41 rage -> 1 rage lost, 20%

**Comment by Zarant** [comment]
Warriors and Druids are refunded 80% of the rage cost on dodge/parry:

> [...] Obviously, this needs to be rectified asap, since it directly impacts the warriors DPS and rage use (since missing wastes 20% of the rage cost of the ability).

Source: http://blue.mmo-champion.com/topic/69365-18-02-05-kalgans-response-to-warriors/


https://youtu.be/YzPlictRoK8?t=1m45s (Dodged mortal strike cost only 6 rage)

That also applies to energy, not just rage: 
http://roguecrap.blogspot.co.uk/2006/03/energy-regeneration-oddities.html
https://youtu.be/aDXXr3ad3is?t=3m07s (parried hemo only cost 6 energy, instead of 30)

**Comment by Wolffenstein** [comment]
Fixed in rev 2804.
