### ISSUE TITLE
[EN][Spell][Shaman] Flametongue Weapon

### ISSUE THREAD

**Issue by Kvel2D** [Atlantiss/NetherwingBugtracker#403]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:
Flametongue Weapon spell fails to apply.

**Current behaviour**:
When trying to apply Flametongue Weapon to item "Primitive Club", it fails and a message "Target is too low level" comes up.
![2018-09-24 10_26_40-wowscrnshot_092418_102346 - windows photo viewer](https://user-images.githubusercontent.com/13269470/45970310-06606300-bfeb-11e8-8cfe-a5b438ed51e4.png)

**Expected behaviour**:
Flametongue should apply to the weapon.

**Steps to reproduce the problem**:
1. Equip "Primitive Club"
2. Cast Flametongue Weapon

Revision: 2040

**Comment by Peglaa** [comment]
Flametongue worked fine for me so far. This is weird. Did you try any other weapons?

**Comment by Kvel2D** [comment]
Tried with Cudgel as well. Also tried disabling all addons and applying to weapon with/without Rockbiter on already.

**Comment by Easyfraggy** [comment]
Did you try to clear cache? Just to be sure.

**Comment by Kvel2D** [comment]
Yes, tried that too.

**Comment by Kvel2D** [comment]
Ok, the spell worked on "Stinging Mace". Stinging's ilvl is 11, the other two I've tried is 5 and 7, so might be something about items being lower than ilvl 10 and Flametongue being a lvl 10 spell.

**Comment by Easyfraggy** [comment]
It should have a level requirement indeed but it might be using wrong intervals. Will need someone else to look into this! Thanks for the report!

**Comment by Galawer** [comment]
It's because it follows the same rule as other buff spells, like Fortitude or Mark of the Wild etc. where you can't buff targets lower than the spell level, in this case the target being the weapon. Rank 1 Flametongue is a lvl 10 spell, Primitive Club is a lvl 5 item, hence the level error.

I couldn't find any confirmation if this is how it's supposed to work, but common sense suggests that it's a  bug, since when you learn new weapon imbues your weapon will almost always be lower level than you, meaning you wouldn't be able to use the highest rank imbue until levels later, when you get a new, higher ilvl item.

**Comment by Easyfraggy** [comment]
Same problem as Windfury: https://github.com/Atlantiss/NetherwingBugtracker/issues/586

**Comment by Easyfraggy** [comment]
Same problem: https://github.com/Atlantiss/NetherwingBugtracker/issues/403

**Comment by Wolffenstein** [comment]
Fixed in rev 2078.
