### ISSUE TITLE
[Desolace] [Quest] Gizelton Caravan. 

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#4030]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I was standing near quest giver, when he yells, but I can't start the quest. Probably this is becouse I'm alliance. [Bodyguard for Hire] worked fine for me, but wowhead say that both quests should be available for both factions: 
https://www.wowhead.com/quest=5943/gizelton-caravan
![wowscrnshot_011119_030100](https://user-images.githubusercontent.com/43533040/51007135-0b700080-154f-11e9-85ff-58ba6eeb65a4.jpg)

**Current behaviour**:
Quest doesn't available for Alliance players.
**Expected behaviour**: 
Both quests [Gizelton Caravan] and [Bodyguard for Hire] should be available for both factions.
**Server Revision**: 2604.

**Comment by Lipmode** [comment]
Not to create a duplicate, because it's the same quest (but from Horde perspective)
Quest cannot be completed on Horde.
It can be started, although there's no "!" when hovering over the quest giver;
Event mobs spawn and despawn correctly (three different demons 3 times over the route) and the caravan fights as intended;
The quest giver puts out the dialogue (on screenshot) signaling that the quest is completed;
(Bug) After the dialogue, quest isn't flagged as "completed" and can't be turned in.
Done 2 different times, same result
[Bodyguard for Hire], as of today, February 21st, still works fine 
**Rev:** 2825
![wowscrnshot_022119_211933](https://user-images.githubusercontent.com/47869178/53200874-f644c200-3622-11e9-8fcf-2e7687bde83d.jpg)

**Comment by Manaci** [comment]
Fixed
