### ISSUE TITLE
[Loot][NPC]Voidspawn#17981 has significantly too low mote drop rate(10%, should be 25%)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#4075]
**Description**: 
[[NPC]Voidspawn#17981](https://www.wowhead.com/npc=17981/voidspawn#comments)
Evidence from [Thottbot Archive](http://web.archive.org/web/20070514081526/http://www.thottbot.com:80/c17981)
![](https://i.gyazo.com/291a8e164f7348edaa9ecd12db16f414.png)

---
![](https://i.gyazo.com/2e123b1b47ee83e502acd117b47530fb.png)

I am aware of other elementals with wrong drops too, I just haven't gotten to it yet... 

**Current behaviour**:
~10%

**Expected behaviour**: 
~24-27%

**Server Revision**: 
2604

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by Shanghi** [comment]
It's already set to about 18% which is what both old Wowhead and Allakhazam show. Thottbot usually calculates the chance a different way when you can get more than 1 each drop. If you got 2 after 1 try, that would be a 200% chance instead of 100%, so it will usually be higher than it should. The 18% is probably too high too because the other databases have a problem where if the creature drops nothing at all then it doesn't count as a loot attempt, so things without guaranteed loot will have the no loot attempts ignored making the chances higher! 15% * 1.5 = 22.5 or 16% * 1.5 = 24 is probably what it really should be, but all the elementals need to be looked at to see if there's a noticeable pattern that makes is easier to decide.
