### ISSUE TITLE
[NPC]Apothecary Lydon (2216)

### ISSUE THREAD

**Issue by Kentamentiu** [Atlantiss/NetherwingBugtracker#408]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Quest giver has all quests available

**Current behaviour**:
Elixir of Suffering, Elixir of Pain and Elixir of Agony are all available at the same time.

**Expected behaviour**: 
After completing Elixir of Suffering (part 2), Elixir of Pain becomes available.
After completing Elixir of Pain (part 2), Elixir of Agony becomes available.

**Server Revision**: 
2040

**Comment by totaemoeggerli** [comment]
You can still accept Elixir of Pain without doing Elixir of Suffering first.
Elixir of agony isn't available which is correct.
![laydon](https://imgur.com/Va1gP3g.jpg)

**Comment by Shanghi** [comment]
Proof would be needed for this. It was changed because:

* The Master Guide shows no prerequisites for these 3 quests.
* Wowwiki [\[1\]](http://wowwiki.wikia.com/wiki/Quest:Elixir_of_Pain) / [\[2\]](http://wowwiki.wikia.com/wiki/Quest:Elixir_of_Agony) says "Elixir of Pain is the first quest in a very short Horde quest chain..." and "Elixir of Agony is the first quest in a Horde quest chain..."
* Each requires a different minimum level and that's very rare for chains besides on starting area quests. It does happen sometimes though, but it's just something else making it less likely.
* The quest stories are self-contained and don't mention the others.

**Comment by totaemoeggerli** [comment]
The quests have a totally clear connection and most of all escalate towards the end:

- the first quests is called **suffering** and ends with a **frog**
- the second quest is called **pain** and ends with the **dog**
- the last quest is called **agony** and ends with **humans**

The whole quest chain is weird because each part has a different name and they don't end at apothecary laydon. They build ontop of each other thematicly. I don't think wowwiki is a good source for this btw, I don't see how this information has any credibility. Here is a comment with equally little credibility about first quest of Elixir of Pain:
By DarkNeo (184 – 3·3) on 2007/09/20 (Patch 2.1.3)
> For some reason this quest isn't available to me, why?

**Comment by Shanghi** [comment]
Wowwiki is only to add evidence and certainly isn't used for 100% proof of anything! We know it's wrong a lot and just edited by anyone so it's just treated like comments. The Master Guide is a much better source though (but can still have errors of course)!

Poor DarkNeo probably wasn't a high enough level.

Here's 2 more comments on [Allakhazam](https://web.archive.org/web/20080420102439/http://wow.allakhazam.com:80/db/quest.html?wquest=509) about Elixir of Agony:
> "Elixir of pain is not a prereq."
>
> "Elixir of Pain is not a Prereq for this. I had this done before I did Elixir of Pain."
