### ISSUE TITLE
[Maraudon] Scepter of Celebras quest, NPC getting stucked.

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#4138]
If you will start the quest and your group members will accept your quest, NPC will bug out on channeling making you not being able to proceed with the quest. 

Not happening when 1 person doing the quest.

Probably related to 1 person taking quest and OTHER person trying to read the book. 
Cant confirm that.

**Comment by wtRCH** [comment]
This was reported earlier during Open Beta. It's duplicate but refreshes thread.

**Comment by Evolvee** [comment]
need steps how to reproduce this.

npc id/quest id etc.

**Comment by DragunovUA** [comment]
when u turn in Legends of Maraudon (http://db.excalibur.ws/?quest=7044) on Celebras the Redeemed (http://db.excalibur.ws/?npc=13716), and 1 member in your party starts The Scepter of Celebras (http://db.excalibur.ws/?quest=7046), npc stucked on stone when creating staff and noone can do anything after. pls fix

**Comment by MAY-THE-ETERNAL-SUN-SHINE-UPON-YOU** [comment]
I can confirm this is still an issue in revision 2825. The exact step where the NPC gets bugged is after he tells the person that started the quest "read the words aloud" etc. and the book that you're supposed to use disappears (maybe the softlock happens if someone other than the person that started the quest uses it?)

**Comment by Evolvee** [comment]
fixed in next rev
