### ISSUE TITLE
[Quest] The Essence of Aku'mai doesn't have prerequisite.

### ISSUE THREAD

**Issue by Jezofine** [Atlantiss/NetherwingBugtracker#419]
**Current behaviour**:
Quest [The Essence of Aku'mai](http://web.archive.org/web/20070825122907/http://www.thottbot.com:80/q6563) has no prerequisite.

**Expected behaviour**: 
Should only be available after [Trouble in the Deeps](http://web.archive.org/web/20070830125452/http://www.thottbot.com:80/q6562).

**Server Revision**: 2040

**Comment by Shanghi** [comment]
Trouble in the Deeps is an optional breadcrumb quest only meant to lead you to the real one. You can do The Essence of Aku'mai without it, but then you won't be able to do Trouble in the Deeps anymore. There will be a lot of similar ones that were fixed.

From the comments on [Trouble in the Deeps](http://web.archive.org/web/20070830125452/http://www.thottbot.com:80/q6562):
"This quest has been removed, you can now start the second part of the chain without talking to **tunaman**."

and then the reply explaining what really happened:
"the quest still exists, and if u can not obtain it it is simply because you have already done the following BFD quest.  if u have not gone into ashenvale and gotten the quest for BFD, u can obtain this one and it will lead u there, but you do not HAVE to have it"
