### ISSUE TITLE
Mage portal to Shattrath does not work for low level players; sends them to their hearthstone locations.

### ISSUE THREAD

**Issue by lolazaurus** [Atlantiss/NetherwingBugtracker#4200]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by lolazaurus** [comment]
My guild just paid for this level 70 mage to port us to shattrath only for us all to get sent to our hearth locations. The mage didn't refund us BTW, We should be able to have anyone be able to take a shattrath portal at any level.

**Comment by Wolffenstein** [comment]
Outland has a level 55 requirement.

**Comment by Brasso** [comment]
Is there a reason for this? Because I don't think that is blizzlike.

> 
POSTED BY A BLIZZARD REP ON THE LINKED FORUM:
"Which is perfectly acceptable and well appreciated.  



I come bearing an update in relation to the original concern brought to light in this topic. As I mentioned previously, the matter of players below level 58 being able to access Outlands by means of summons was being actively looked into by our staff. Through luck or coincidence, or perhaps a bit of both, a conclusion was recently reached by such staff members. 

For clarification and for future reference: as it currently stands, players level 57 or below can be legitimately summoned beyond Azeroth's borders; if their presence in Outlands was accomplished by means of a warlock summoning spell, this is considered to be working appropriately. The level restriction, however, still applies for the Dark Portal."
> 
[https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-exploits/10339-get-outlands-before-lvl-58-a.html](url)

**Comment by killablink** [comment]
Yeah to be blizzlike there is no requirement to take a mage portal

**Comment by towneh** [comment]
https://web.archive.org/web/20090125195143/http://forums.worldofwarcraft.com/thread.html?topicId=81953839&pageNo=1&sid=1

"Although the Dark Portal has a level restriction we don't have any policy or problem with players under level 58 being summoned to Outland. The level restriction on the portal was mainly to prevent a launch day rush where a bunch of lower level players may just want to look around."

**Comment by The14me** [comment]
Rev.3482 not an issue anymore.

**Comment by Tereneckla** [comment]
Current level requirement set is lvl 50
It should be able to summon and portal characters of any level to outlands.
http://web.archive.org/web/20080916235327/http://forums.worldofwarcraft.com/thread.html?topicId=69812755&sid=1&pageNo=1

> For clarification and for future reference: as it currently stands, players level 57 or below can be legitimately summoned beyond Azeroth's borders; if their presence in Outlands was accomplished by means of a warlock summoning spell, this is considered to be working appropriately. The level restriction, however, still applies for the Dark Portal.

**Comment by Godmatik** [comment]
It's set at level 50 for exploit reasons - closing
