### ISSUE TITLE
wand targeting issue

### ISSUE THREAD

**Issue by quacked123** [Atlantiss/NetherwingBugtracker#4211]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
wand attacks are targeting a non-targeted target.
**Current behaviour**:
wand attacks are targeting a non-targeted target.
**Expected behaviour**: 
wand attacks should attack targeted target
**Server Revision**:

**Comment by Desst** [comment]
Also when you're attacking with wand and switch targets with tab it could act strangely.

can add this:
**Current behaviour:**
Killing a target with last hit from wand and switching target while the projectile is flying stops autoattack
**Expected behaviour:**
When your wand projectile is about to kill your target and you chose another target, Autoattack should not stop and you should continue firing wand at another target after killing the first

**Comment by Mikik3jr** [comment]
I gave a wand to my alt character and as you can see I gained like 10 skill under really short time. I shot with my wand EXACTLY 5 times but I gained more skill in shorter time. Maybe this helps in finding the issue:
![image](https://user-images.githubusercontent.com/43505031/52109650-854f5300-25fe-11e9-8089-6933e55e2895.png)

**Comment by The14me** [comment]
Rev .3460 it work just fine with switch/tab targets .
Can be closed.
