### ISSUE TITLE
severe lack of herbalism nodes

### ISSUE THREAD

**Issue by staplerx300** [Atlantiss/NetherwingBugtracker#4261]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
no herb nodes in sight anywhere

**Current behaviour**:
^
**Expected behaviour**: 
more herbalism nodes

**Server Revision**:

**Comment by Jalapan** [comment]
Same with mining, its broken

**Comment by wtRCH** [comment]
@Shanghi

**Comment by Brasso** [comment]
Zones are extremely node depleted at the moment. Terrokar forest seems to be the only zone in Outland with enough herb spawns, and only a fraction are in Outland.

**Comment by Shanghi** [comment]
After launch there was a bug causing herbs/veins to not be limited in each area so you would be covered in them every few steps if the server stayed up long enough. They were quickly changed to use a different, temporary method of respawning that unfortunately has much less spawning at once or else some areas would be very exploitable. For now everyone has to suffer with low rates because that's better than extremely high rates making the herbs/ores worthless. Now that the crash crisis is finally over I'm hoping the first respawn method can be fixed soon and then they can be set back to using it!

**Comment by antikiller69** [comment]
extremely high rates is better than low rates, just need that lvl so u can start lvling at outland

**Comment by Searcher314** [comment]
Herbalism does indeed feel pretty terrible atm. I agree that spawning too quickly would also be an issue but we need to find a middle ground quickly.

**Comment by toucem** [comment]
I am struggling with this issue too. Tried to get 100 herbalism for like 2-3 hours last night in stonetalon, ashenvale, hillsbard and ghostlands zone and respawns are not enough. It shall fixed asap

**Comment by Ashfall7x** [comment]
There are a lot of ores around but no herbs, especially in the low level zones.

**Comment by ircfelix** [comment]
I got to 375 herbalism without ans problems

**Comment by fruvel** [comment]
confirmed no herbs in hinterlands 0 nods 23.4.19 20;00 eu time

**Comment by fruvel** [comment]
swamp of sorrows 3 blindweed nods at 40 minutes of farming, i was alone there

**Comment by DDL-Blue** [comment]
I have the same problem. And it is really annoying. I went through several zones. Some seemed completely OK, some were literally empty. Even though I've made a circle around the whole zone.
So... I've got a suggestion.

------
For each herb type individually:
- For each zone there is a minimum number of this type of herb for this zone. It might be some fraction of total number of nodes present in this zone.

- Each herb node can be in one of 3 states:
  - **Grown** - Grown herb waiting for player to be gathered. When gathered, random node in this zone that is in "Waiting" state will be changed to "Growing" state.
  - **Growing** - Hidden for players. After some given period of time it changes the state into the "Grown" state.
  - **Waiting** - Hidden for players. Waiting to be changed to "Growing" state.

The duration of "Growing" state should be something reasonable. Probably not 2 mins, but also not hours. You do not want to have zone empty hours after a player went through. Might be individual for each zone.

This will result in:
- There is constant number of non-waining herb nodes in each zone, so there will no more be "empty and and full worlds". The number of "gatherable" herbs will drop temporarily, but will be recovered really fast.
- It will be quite hard to abuse, because of the "Growing" duration and the randomness of spawns.
- Server will not be full of herbs when online for a long time.

Possible tweaks might be something like "when picking a random herb, prioritize those that are waiting for more than 3 hours" or something. But that is optional. The rules above are enough I would say. Also there might be a second, hard limit set to much lower number that would change a herb's state to "grown" right away.

---

Btw if the lack of dev power is the problem, I might actually help you. I have never been doing anything with WoW servers, but I do know C++ and I do have some experience with working on big projects with huge codebase. I do not have much time, but I might be able to spent some time when exams of this semester are over.

**Comment by Tereneckla** [comment]
rev 3205

**Comment by raethkcj** [comment]
Is it possible that the fix in 3205 somehow got reverted on Karazhan launch? All nodes on Azeroth are again following weird patterns where the first 3-4 zones you check will have ZERO nodes, and then suddenly you stumble across a zone where 100% of the possible spawns are up at the same time.
