### ISSUE TITLE
[Druid] Cat Form auto-attack not working

### ISSUE THREAD

**Issue by Kromials** [Atlantiss/NetherwingBugtracker#4323]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: From time to time when engaging a mob in cat form form there is no auto-attacking. Skills such as Claw or Mangle work and hit the target correctly, however right clicking or using a /startattack macro do not start "white swinging". Shifting out of Cat Form and back into seems to almost always solve this issue.

**Current behaviour**: Inability to auto-attack enemies

**Expected behaviour**: Ability to auto-attack enemies

**Server Revision**:

**Comment by SlapZech** [comment]
Can confirm.

The bug not only affects mobs, but pvp flagged players as well.
Sometime swings do not occur, as if the target was not in range. 
This happens even when the player is position on top of the enemy to the point models clip through each other. Melee range skills work, autoswing does not.

Important to note is that the bug happens not only to moving targets, but to those immobile as well.

There is no consistency as to the areas in which the bug occurs, nor in enemy models, so it's doubtful the problem lies in specific movemaps or hitboxes.

**Comment by agraff16** [comment]
Here is a video of it. 
[intro4.zip](https://github.com/Atlantiss/NetherwingBugtracker/files/2780203/intro4.zip)

I can send a better quality video if needed. pm me on the netherwing discord "outee"
