### ISSUE TITLE
[PETs][HUNTER]  - Ravager disappear after death.

### ISSUE THREAD

**Issue by albinatorek** [Atlantiss/NetherwingBugtracker#4326]
**Description**: 
Ravager from Azuremyst Isle. Player is a horde hunter. 
Pet dies, Player dies. Both are dead. Player is ressing up, trying to summon pet's body to ressurrect it and there is not pet. Like I would never have it before.

**Current behaviour**:
Pet disappears.

**Expected behaviour**: 
Pet is summoned.

**Server Revision**: 
2647

**Comment by albinatorek** [comment]
Assign it to someone and take care of this, can't play being worried if my pet dissappear again or not.

**Comment by DarthNekr0s** [comment]
i just had this happen to me too. during a fight my ravager disappeared and i assumed he died because it was in 0.2 seconds, then i tried to revive and it did nothing, tried to call pet and it did nothing. but i know he didnt run away because i have been feeding him reguarly.
just to say though, me and my pet have died multiple times before and its been fine.

**Comment by Tereneckla** [comment]
Fixed
