### ISSUE TITLE
[Dungeon][Ragefire Chasm] Could not self-resurrect; ghosts' inside dungeon

### ISSUE THREAD

**Issue by sbeckerman** [Atlantiss/NetherwingBugtracker#4328]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Party could not resurrect from their corpses after wiping in Ragefire Chasm. We were all in ghost form inside the dungeon and the resurrect dialogue was not functional what-so-ever. Relogging did not work, only graveyard.

**Current behaviour**: Self Resurrect not working inside dungeon; stuck in ghost form.

**Expected behaviour**: Resurrect upon re-entry into Ragefire Chasm.
![mpv-shot0001](https://user-images.githubusercontent.com/19241251/51404214-b73bd080-1b8d-11e9-99c0-81afc1553472.jpg)

**Server Revision**: 2647

**Comment by Aquaorangez** [comment]
this happened to me in Maraudon as well. It was because there was specific spot in the instance that was considered "Desolace" as opposed to "Maraudon". You could see your chat channel leave maraudon general chat and join desolace general chat even though you were in the instance. if you died in this spot, this bug occurs. might be same thing happening in RFC

**Comment by The14me** [comment]
Rev.3483 can ress other ppl without a problem in RFC at the same spot.
