### ISSUE TITLE
[Quest][Dun Morogh] Frostmane Hold

### ISSUE THREAD

**Issue by Zirda** [Atlantiss/NetherwingBugtracker#44]
**Current behaviour**:
After turning in [Senir's Obeservations](https://classicdb.ch/?quest=420) to [Senir Whitebeard](https://classicdb.ch/?npc=1252) The npc shows the quest [Frostmane Hold](https://classicdb.ch/?quest=287) as an available quest. When accepted the quest is declined for not being meeting the requirements. 

Character is level 6 and the required level is 7 for Frostmane Hold

**Expected behaviour**: 
Quest givers should not offer quests that the player do not meet the requirements for.

**Comment by Shanghi** [comment]
I think that's how it should be, but if you have any proof then it would be changed. I wanted to change it long ago because it's stupid to offer the next quest then not let you accept, but I could only find evidence for it really being like that.

There's Wowhead/Thottbot/Allakhazam comments on other quests about other types of requirements (like not being the right race or with quest chains like 1->2->3 where 1 and 2 are optional and you do 3 first, then 1, then try to accept 2 but can't because you already did 3):
> However when i tired to accept it, all i got was "You don't meet the requirements for that quest".
>
> i clicked accept, but after it said "you don't meet the requirements for that quest"
>
> When I clicked to accept the quest, I got a message, "You don't meet the requirements for this quest."
>
> when I went to hit accept, it said you do not meet the requirements for this quest

(and many more)

I think I've seen the same kind of comment specifically about level requirements too, but can't remember the quest now to check again.

**Comment by The14me** [comment]
@Shanghi  is right about that.It suppose to work that way when its chain quest line.
