### ISSUE TITLE
Shaman's Windfury only procs 1 additional attack(not the totem)

### ISSUE THREAD

**Issue by Mizers** [Atlantiss/NetherwingBugtracker#4407]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Windfury bugged

**Current behaviour**: When it procs the shaman only gets 1 extra attack instead of the two. Here's screenshots of combat log and recount. https://imgur.com/a/kvwMJbf I think I've might've seen it do two hits once, but I'm not sure.

**Expected behaviour**: When it procs the shaman gets 2 extra attacks.

**Server Revision**:

**Comment by Wolffenstein** [comment]
It procs one attack that has damage equal to two extra attacks.

**Comment by Mizers** [comment]
The damage of the one attack isn't remotely close to being two attacks. If
you look at the screenshots I've provided at https://imgur.com/a/kvwMJbf you
can see in the second screenshot that I auto attack for 88 damage and then
WF procs for 90. None of the procs in the 3 screenshots do enough damage to
be two attacks in one considering the WF attacks also get an attack power
boost.

**Comment by hitbutton** [comment]
@Wolffenstein This issue needs to be reopened.

Windfury Weapon was working correctly before the last update. When the weapon with the imbue procced, you would immediately hit with two extra attacks.

After the update you are only hitting with one attack, for the same damage as a normal single Windfury hit (e.g. half as much damage as before as there is only a single hit).

Additionally it appears to be proccing on next hit after the proccing hit, rather than immediately. Here's an example of my combat log when dual wielding with Windfury and Flametongue:
![image](https://user-images.githubusercontent.com/16194079/51448785-cb640700-1d20-11e9-8ce4-7558930fadfa.png)
You can see that the Windfury proc appears after the smaller OH hit, along with the Flametongue proc which the OH is imbued with.

These changes are absolutely gamebreaking to enhancement shaman, as windfury is one of our main sources of damage. Enhance is also the usual levelling spec for shaman, so this will be impacting a lot of players right now.

**Comment by Wolffenstein** [comment]
Reverted in rev 2668.

**Comment by HuskyHuskyz** [comment]
Providing extra proof that Windfury Weapon should in fact prove two additional instances of damage:

http://web.archive.org/web/20080912045533/http://elitistjerks.com:80/f47/t15809-shaman_windfury/

On this link from Elitist Jerks you can see that while Windfury Totem gives one extra attack, Weapon gives 2 additional ones.

If you need more, check this wowwiki link from TBC era:

http://wowwiki.wikia.com/wiki/Windfury_Weapon?oldid=1225154

"Windfury procs CAN trigger weapon based procs and enchants -- meaning you could potentially have a Crusader proc 3 times (your normal swing and the 2 Windfury occurrences" As you can see, one Windfury proc can trigger Crusader 3 times, because it has the normal hit + 2 additional hit instances.

 @HuskyHuskyz
