### ISSUE TITLE
[Shaman] [Windfury Weapon] Only one attack

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#4425]
**Current behaviour**: Then it proc it do only one extra attack.
https://cdn.discordapp.com/attachments/514045629027057686/536868520039022602/Skrmbillede_2019-01-21_kl._12.21.52.png

**Expected behaviour**:  Suppose to be two extra attacks
https://cdn.discordapp.com/attachments/514045629027057686/536868719104753664/Skrmbillede_2019-01-21_kl._12.24.29.png

**Server Revision**:

**Comment by hitbutton** [comment]
duplicate #4407

**Comment by MrOrgmo** [comment]
This is not a bug. It does one additional instance of damage with damage equal to two extra attacks with additional attack power, as it says in the tooltip.

**Comment by HuskyHuskyz** [comment]
Providing extra proof that Windfury Weapon should in fact prove two additional instances of damage:

http://web.archive.org/web/20080912045533/http://elitistjerks.com:80/f47/t15809-shaman_windfury/

On this link from Elitist Jerks you can see that while Windfury Totem gives one extra attack, Weapon gives 2 additional ones.

If you need more, check this wowwiki link from TBC era:

http://wowwiki.wikia.com/wiki/Windfury_Weapon?oldid=1225154

"Windfury procs CAN trigger weapon based procs and enchants -- meaning you could potentially have a Crusader proc 3 times (your normal swing and the 2 Windfury occurrences" As you can see, one Windfury proc can trigger Crusader 3 times, because it has the normal hit + 2 additional hit instances.

**Comment by hitbutton** [comment]
Additional Evidence that Windfury should be two separate attacks here in this potato quality video from March 2008:
https://youtu.be/QDO8vCL7-Qs?t=71
At the timestamp shown you can see Stormstrike hitting for 2413, then Windfury hitting for 3707 and 2132

**Comment by The14me** [comment]
Fixed in rev 2668.
