### ISSUE TITLE
[Talent][Hunter] Rapid Killing 

### ISSUE THREAD

**Issue by yeti1991** [Atlantiss/NetherwingBugtracker#4459]
**Description**:Rapid Killing Reduces the cooldown of your Rapid Fire ability by 2 min. In addition after killingan opponent that yieldexperience or honor you next Aimed shot,Arcane Shot or Auto Shot  causes 20%additional damage lasts20 sec.

**Current behaviour**:Rapid Killing does not work properly, turns on and immediately turns off without using skills

**Expected behaviour**: Buff 20% damage should work for 20 sec and for the first time you use Aimed shot arcane shot or auto shot

**Server Revision**: 2676
https://www.youtube.com/watch?v=aD4T2YMckQE&feature=youtu.be
PS, Sorry for my eng

**Comment by zonk2** [comment]
Can confirm. Sometimes it is just gone without doing one single shot

**Comment by yeti1991** [comment]
https://www.youtube.com/watch?v=aD4T2YMckQE&feature=youtu.be

**Comment by fishworld** [comment]
Still bugged as of 02/09

**Comment by fishworld** [comment]
When you kill an opponent (i.e. a mob) that yields xp you don't get the buff. However if the pet gets the last hit, you do get the buff.

**Comment by BidingMyTime** [comment]
This is still an issue. The problem is that The buff is instantly consumed (by the kill shot, without improving it) if you kill it with one of the shots it should be buffing.

This renders one of the best leveling talents in MM tree nearly useless, simply because as MM hunters your only other tools for killing the target are Serpent Sting and Multishot (melee, traps and pet damage just aren't MM's strong points) - both are so mana infficient you hardly ever use them while leveling.

**Comment by Manaci** [comment]
Fixed
