### ISSUE TITLE
[Hunter] [Freezing Trap] Does not activate immediately when set out of combat

### ISSUE THREAD

**Issue by fishworld** [Atlantiss/NetherwingBugtracker#4537]
**Current behaviour**:

When you place freezing trap out of combat, the trap still takes 2 seconds to activate just as if you would put it in combat. 

**Expected behaviour**: 

When you place freezing trap out of combat (I.e. if you feign death + trap), the trap should activate right away if someone steps on it. 

Patch 2.0.1 (05-Dec-2006): Freezing Traps will now cancel combat when cast. **Traps can be set while in combat, but require a 2 second arming time.**

https://wowwiki.fandom.com/wiki/Freezing_Trap

**Comment by Zarant** [comment]
The wording there is not very clear, you should provide some other source just in case. I played a hunter during S3/S4 and from memory I don't ever recall hunters dropping traps without an arming time, I might be wrong though.

**Comment by killablink** [comment]
I'm pretty sure traps in general now always take 2 seconds before activating. It has nothing to do with being in combat or not.

**Comment by fishworld** [comment]
In vanilla traps always activated right away. I played hunter too in BC, and I recall it worked the same way with the exception of 2 sec timer if they are set in combat.

I'll see if I can find any other sources.

**Comment by Kristoferhh** [comment]
in the 2.0.1 patch notes: " Traps can be set while in combat, but require a 2 second arming time."
I think this implies that while traps can be now set while in combat, they now _always_ require a 2 second arming time, even out of combat.

**Comment by balo-git** [comment]
Reading the same note I think it implies that the 2 second arming time is only incurred when used in combat.

**Comment by blackersun** [comment]
"Traps can be set while in combat, but require a 2 second arming time."

When interpreting this sentence, the second part is describing the first part due to the comma break. To me it reads that setting a trap while in combat will give a 2 second arming time, but only while cast in combat. If the changes to traps were to be universal then there would have been a period at the end instead of a comma: "Traps can be set while in combat. They now require a 2 second arming time." Something like that.

The proof is not so much in the writing, but in what was not written. Specifically, the patch note does not refer to any changes made to traps while set out of combat, but only while set in combat. When out of combat, the trap effect should behave as it was in vanilla (immediate).

**Comment by Kristoferhh** [comment]
Yea ok I can actually read it both ways now haha. Would have to ask someone who was a tbc dev at blizzard for the truth I guess

**Comment by Manaci** [comment]
Not any decisive proof of this interaction
