### ISSUE TITLE
[Quest][Blade's Edge Moutains] Showdown

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#4550]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In this quest we use a ring to summon Goc and kill him.

**Current behaviour**:
The quest item at the altar doesn't do anything

**Expected behaviour**: 
The quest item at the altar should summon the boss and a helper NPC to kill the boss.

**Server Revision**: 
2691

**Comment by Evolvee** [comment]
works fine for me

**Comment by Evolvee** [comment]
i just tried on live server and it works as well

...

**Comment by Mikik3jr** [comment]
5 of us tried it and after half an hour nothing happened when I reported this.

**Comment by Evolvee** [comment]
well, did u try it again?

**Comment by Mikik3jr** [comment]
Yeah I tried again, and now it worked.

**Comment by Falathrin** [comment]
The NPC is supposed to transform into a dragon btw, he's not supposed to stay in human form.

**Comment by Evolvee** [comment]
where
https://youtu.be/_e2Z-gQmz_o?t=76
https://youtu.be/_KYohBcTPLg?t=81

**Comment by Falathrin** [comment]
I think he's dying too fast in those videos.
I looked it up because I read the dialogue when you hand in the quest after slaying Goc.
Baron Sablemane says:

"You fought surprisingly well for a <race>, and it was an honor to have you at my side.  My transformation must have been quite a surprise for you.  I trust it was not too startling?

Let us keep my true identity between the two of us for now, shall we?  In return, and for your adept service, I grant you your choice of any of these baubles."

Then I searched the quest on Wowhead and saw there's a screenshot of him in dragon form fighting Goc:
https://www.wowhead.com/quest=10806/showdown
https://www.wowhead.com/quest=10806/showdown#screenshots:id=266682

**Comment by Evolvee** [comment]
he is on the last video i posted but its after u kill goc... there are other videos i posted that had a long fight and he never turned into dragon at all

**Comment by Falathrin** [comment]
Well he did transform before he got killed, saying this dialogue:
"Your father destroyed my children and left their bodies impaled upon the rocky blades at Dragons' End. For this, you will die! Enough of this farce. Prepare to face my full wrath"
I am not sure if he disappears or flies off after Goc dies though.

Here's 2 screenshots of when I killed him on NW:
https://imgur.com/a/Pu1mCv1

**Comment by Evolvee** [comment]
can someone tell me name/entry of this dragon? i just need his skin so any npc with the same visual skin will do it ^^

**Comment by Evolvee** [comment]
rev 2830
