### ISSUE TITLE
[Mega Thread] Warlock bugs

### ISSUE THREAD

**Issue by Jalapan** [Atlantiss/NetherwingBugtracker#4566]
I wanted to make a megathread to collect all warlock bugs so we can get the class fixed, ATM i feel warlocks needs som love.. below are the related bugs.

- [x] Curse of Elements not working properly
https://github.com/Atlantiss/NetherwingBugtracker/issues/2799

- [x] Fear is undertuned and breaks extremly fast
https://github.com/Atlantiss/NetherwingBugtracker/issues/4534

- [x] [Talent] [Warlock] Improved Drain Soul doesnt return mana or reduce threat
https://github.com/Atlantiss/NetherwingBugtracker/issues/4808
https://github.com/Atlantiss/NetherwingBugtracker/issues/4822

- [x] Curse of Recklessness
https://github.com/Atlantiss/NetherwingBugtracker/issues/4562

- [x] Succubus seduction dosent work on all humanoids
https://github.com/Atlantiss/NetherwingBugtracker/issues/4552

- [x] Felhunter devour magic  dosent work
https://github.com/Atlantiss/NetherwingBugtracker/issues/4392

- [x] Soul shard not awarded for soulburn and drain soul
https://github.com/Atlantiss/NetherwingBugtracker/issues/4494

- [x] Pyroclasm not working
https://github.com/Atlantiss/NetherwingBugtracker/issues/4477

- [x] Eye of killrogg cast problems with pet
https://github.com/Atlantiss/NetherwingBugtracker/issues/4263

- [ ] Warlock pet tanking threath undertuned and imp tanking talents not working
https://github.com/Atlantiss/NetherwingBugtracker/issues/3884
Same issue with felguard, they cant hold aggro even when a warlock is only wanding and a few dots.

- [ ] Succubus charm not working with invis
https://github.com/Atlantiss/NetherwingBugtracker/issues/3580

- [x] Imps can be attacked in phase shift
https://github.com/Atlantiss/NetherwingBugtracker/issues/3140

- [ ] Soul Link and enslaved demons/Soul Link does not work on enslaved demons.
https://github.com/Atlantiss/NetherwingBugtracker/issues/2689

- [ ] Dismiss/Recall behaviors
https://github.com/Atlantiss/NetherwingBugtracker/issues/2688

- [ ] Demonic Knowledge
https://github.com/Atlantiss/NetherwingBugtracker/issues/2687

- [ ] [Spell][Warlock] Enslave Demon not updating pet tab
https://github.com/Atlantiss/NetherwingBugtracker/issues/4693

- [ ] [Spell][Warlock][Pet] Seduction not casting
https://github.com/Atlantiss/NetherwingBugtracker/issues/4552

- [x] Warlock Summon Inferno not working properly.
https://github.com/Atlantiss/NetherwingBugtracker/issues/4679
https://github.com/Atlantiss/NetherwingBugtracker/issues/4798

- [ ] [Spell][Warlock][Pet] Felhunter Tainted Blood not stacking
https://github.com/Atlantiss/NetherwingBugtracker/issues/4778

- [ ] warlock pet disappears if unmount in combat
https://github.com/Atlantiss/NetherwingBugtracker/issues/4775

**Comment by Jalapan** [comment]
@Wolffenstein maybe when things calm down you can check this out? some of these are really game breaking for this class.

**Comment by wtRCH** [comment]
Edited: Added checkboxes.

**Comment by Brasso** [comment]
Add these three to the list. 

[ ][Soul Link and enslaved demons](https://github.com/Atlantiss/NetherwingBugtracker/issues/2689)

[ ][Dismiss/Recall behaviors](https://github.com/Atlantiss/NetherwingBugtracker/issues/2688)

[ ][Demonic Knowledge](https://github.com/Atlantiss/NetherwingBugtracker/issues/2687)

**Comment by Jalapan** [comment]
> Add these three to the list.
> 
> * [Soul Link and enslaved demons](https://github.com/Atlantiss/NetherwingBugtracker/issues/2689)
> * [Dismiss/Recall behaviors](https://github.com/Atlantiss/NetherwingBugtracker/issues/2688)
> * [Demonic Knowledge](https://github.com/Atlantiss/NetherwingBugtracker/issues/2687)

fixed.

**Comment by Jalapan** [comment]
I suspect several demonolgy talents are not working and aswell that something is wrong with threat and pets, if anyone have time to help me test, please do :)

**Comment by Mou-nw** [comment]
Also Felhunter's Tainted Blood does not stack on the target (it should get to 5 stacks)

**Comment by glubglub1337** [comment]
As of today Improved Drain Soul isn't restoring any mana whatsoever, not even when soloing.

**Comment by Jalapan** [comment]
Imp drain soul fixed in rev 2762

**Comment by Ravyd** [comment]
Please add the continuation thread #4678  to this list. I believe we are starting to make insights as to the fundamental issues involved with Fear atm

https://github.com/Atlantiss/NetherwingBugtracker/issues/4678

**Comment by thebluefish** [comment]
Improved Drain Soul appears to not be working in some cases, where it does not give back any mana while a target dies. I experience this only in group play. The first time I noticed it was in Wailing Caverns, with the druids. 

I recently experienced this with the raptors for Raptor Mastery (part 1) in Stranglethorn Veil. When killing raptors while in a party, Drain Soul did not give me any mana when they died. I killed a raptor after leaving the party, and it properly gave me my mana.

**Comment by Adunai** [comment]
2019-07-18 rev [3078] (Wolfenstein)
[Core/Warlock]:
- Fixed "Inferno" spell 
- Soul Link and Demonic Knowledge will now work with enslaved demons
- Imps in Phase Shift will now be properly immune to all spells and attacks
#4679 #4798 #2689 #2687 #3140

**Comment by Randelung** [comment]
Hey guys, one or possibly two more for the list.

I've been trying to enslave elites in Netherwing and Nagrand to complete quests. One was [Silroth](https://www.wowhead.com/npc=20801/silroth) to kill the Farahlon Giants for [In Search of Farahlite](https://www.wowhead.com/quest=10290/in-search-of-farahlite) next door, the others are [Felguard Legionnaires](https://www.wowhead.com/npc=17152/felguard-legionnaire) for [Buying Time](https://www.wowhead.com/quest=9999/buying-time).
For one thing they seem to always break enslavement really soon. Not once did I get a full duration enslavement done, but then I can't confirm if this is normal behavior or not. It seems that it's not normal since the comment page for Silroth is full of warlocks telling how awesome it is to enslave and flatten the giants.
But more importantly, using them as pets to complete Buying Time will not yield quest progress, no matter how much or little I help the demon. I think this is probably connected to the whole "pet can't have last hit" thing that also exists elsewhere, e. g. #2107.

In general, it's clear from the comments on the quest pages that they should be a breeze for warlocks. As of right now I either can't enslave the demons for more than a few seconds (Silroth is hardly out of the camp) or the kills don't count. Needless to say I was not able to complete either quest the 'warlock way'.

Revision 3185.

Thanks!

**Comment by rjeahub** [comment]
Improved Drain Soul seems to only reward mana if the warlock lands the killing blow (or at least it frequently fails to return mana when playing in a group)
