### ISSUE TITLE
[NPC][Gann Stonespire] Not pathing

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#460]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Gann Stonespire, a quest giver in southern barrens is standing still in one place.

**Current behaviour**:
![untitled](https://user-images.githubusercontent.com/37326256/45987720-1440d300-c041-11e8-97f7-595635aeb20d.png)

**Expected behaviour**: 
I beleive Gann should be pathing up and down the main road in southern barrens, between thousand needles and camp taurajo.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Someone must have talked to him recently which made him pause for a moment. He's moving fine now.

**Comment by maxturtlesc2** [comment]
Update: it is not exactly a pathing problem, but when someone talk to the NPC, he stops way longer than he should. I talked to him to complete part 2 of the quest, then went to do the last part (destroying the flying machine) which took me at least 5min from going there to coming back. He was still not patrolling and standing still at the same place I talked to him 5min earlier. The possibility of someone talking to him is also unvalid since I was the only one in The Barrens at that time (I checked on the /who list).
