### ISSUE TITLE
VanCleef's Body disappeared before i could loot his Head

### ISSUE THREAD

**Issue by Fisted** [Atlantiss/NetherwingBugtracker#4623]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
![img_2907](https://user-images.githubusercontent.com/47068936/51793933-7ac43200-2196-11e9-997b-2febdddda70d.jpg)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Somebody in my party looted the boss' body before combat was over, and his body disappeared after we rolled for the drop. I never got a chance to loot his head when we got out of combat, because his body was gone. Same problem happened for the other person in my party as well. I have embedded a screenshot showing the combat text that we killed vancleef, as well as the picture of my quest showing the incomplete objective.
**Current behaviour**:
Body despawns before quest items are completely looted
**Expected behaviour**: 
Boss body should remain available for looting until everyone has looted.
**Server Revision**:

**Comment by danbopes** [comment]
@Wolffenstein I believe this issue is caused when the party leader (Or possibly the person who won the items on the body) leaves the group. Any quest items that are still currently on that mob despawn with the body, and are unable to be looted. This is not specific to VanCleef.

Because this leaves players having to do the entire instance again in order to retrieve the quest item (Or as a result abandoning the quest), I believe this is a rather high priority bug.

**Comment by Manaci** [comment]
Fixed with loot rework
