### ISSUE TITLE
 [Spell][Shaman] Windfury Totem

### ISSUE THREAD

**Issue by quapuzi** [Atlantiss/NetherwingBugtracker#4628]
**Description**: 
Windfury Totem is not working properly at all; the benefit is the wrong

**Current behaviour**:
Basically it mirrors an attack, spell or dot with an extremly low cooldown and low proccchance. it can mirror even thorns or retribution aura.
- totem pulsing every 10seconds
- buff does not get consumed on a procc
- proccchance very low
- can procc on anything but does the same as the source of procc. even its its a shout like demo shout
Proof: https://i.imgur.com/JuCMe8l.png

**Expected behaviour**: 
- Totem pulsing every 5seconds
- buff consumed on a procc
- 20% procc chance on melee white hits to procc an extra autohit with bonus ap. also able to procc on cleave, heroic strike and raptor strike
- generating recources like rage for warrior

**Server Revision**: 
2712

**Comment by itsonlysmellz** [comment]
Windfury Totem should not have an 8 sec cooldown should only proc on white hits (basic attacks)

http://web.archive.org/web/20080811084026/http://elitistjerks.com/f47/t15809-shaman_windfury/

**Comment by itsonlysmellz** [comment]
Windfury Totem should not have an 8 sec cooldown and should only proc on white hits (basic attacks) 

http://web.archive.org/web/20080811084026/http://elitistjerks.com/f47/t15809-shaman_windfury/

**Comment by quapuzi** [comment]
- Actually the totem should tick every 5seconds (wich is basically some sort of cd), right now you get the buff instandly after a procc
- proccrate wrong, its way too low
- should procc on whitehits only, yes, but also on swing abilities like heroic strike, cleave and raptor strike
source: https://blue.mmo-champion.com/topic/18088-10-08-windfury-totem-hotfix/

**Comment by rychersky** [comment]
![unknown](https://user-images.githubusercontent.com/45608488/53187182-cf08d900-35bf-11e9-9e8c-47985261e524.png)

This is still not working and is proccing on things like Demoralizing Shout.

**Comment by hitbutton** [comment]
Just want to clarify a couple of things:

The Windfury Totem buff application is currently working correctly on Netherwing (Revision 2856). Pulses every 5 seconds, applying a 10 second buff.

The buff should *not* be consumed by a Windfury proc. There should also be no internal cooldown for Windfury Totem procs.
Source: https://www.youtube.com/watch?v=Hn8eMD8zdOo
At 1:48-1:50 in this video you can see the warrior get back to back Windfury procs.

**Comment by hitbutton** [comment]
So after some testing, it appears that Windfury Totem seems to be working as intended on Netherwing currently

*HOWEVER* the combat log events appear in the wrong order which makes it very difficult to intepret/collect data with existing tools.

With a melee swing proccing a windfury attack, the combat log should show:
`<playername>'s melee swing hits <targetname> for <swing damage>`
`<playername> gains 1 extra attack through Windfury Attack`
`<playername>'s melee swing hits <targetname> for <windfury attack damage>`

but currently on Netherwing it shows:
`<playername>'s melee swing hits <targetname> for <swing damage>`
`<playername>'s melee swing hits <targetname> for <windfury attack damage>`
`<playername> gains 1 extra attack through Windfury Attack`

This change in the order of events can cause damage parsing addons to report extremely strange results for windfury totem (since it may try to interpret the next log event as the Windfury Attack damage).
Amongst other things this makes it difficult for players to determine if Windfury Totem is indeed working like it should.

**Comment by rychersky** [comment]
Not sure how Recount parses data but I thought I'd point this out if it's any help. My combat log is showing the correct line for a Windfury totem proc causing a melee attack; however, Recount is still showing that my special attacks are being mirrored. I do not know if the combat log was showing this prior to whatever revision hitbutton posted.

Terrez's melee swing hits Maiden of Virtue for 949 Physical. 
Terrez gains 1 Rage from Terrez's Unbridled Wrath. 
Terrez's gains 1 extra attacks through Windfury Attack.

![image](https://user-images.githubusercontent.com/45608488/53852005-ab5d6f80-3f7d-11e9-9c98-2235f4988280.png)

![image](https://user-images.githubusercontent.com/45608488/53852024-badcb880-3f7d-11e9-81bd-6733e5f3e7c5.png)

![image](https://user-images.githubusercontent.com/45608488/53852036-c6c87a80-3f7d-11e9-9588-fe6575376acd.png)

**Comment by hitbutton** [comment]
The issue there is that Recount is parsing a Slam that occurs after a Windfury Proc as being the Windfury proc damage.

**Comment by quapuzi** [comment]
issue is actually recount, it just throws events randomly together, resulting in those weird appearances. either that, or as hitbutton pointed out, the lines in the combat log are in the wrong order. i guess thats the issue, since recount works correctly on other servers.
switch to dps mate and it shows the correct values. its possible that it used to not procc on heroic strike but even if it did, its fixed now.

**Comment by Easyfraggy** [comment]
Purely visual bug on recount.
