### ISSUE TITLE
[Spell][Fear] Undertuned

### ISSUE THREAD

**Issue by L33tspeek** [Atlantiss/NetherwingBugtracker#4678]
As quoted in #4534 I believe this is a very good start but I still believe we're still a little undertuned. As @Jalapan said:

> thx @Wolffenstein it's much better, but it still feels undertuned, the dmg threshold should be at least 25% higher

I would second this observation, as we're still seeing instabreaks and fear does not seem "strong" as it should.

I will try to get more footage. And I encourage keeping this issue open until it is actually resolved so I don't need to make new posts.

Server Revision: 2718

**Comment by Ravyd** [comment]
I would also like to see high level warlocks give some input, as I am only level 38 at the moment on this server

**Comment by Balanarr** [comment]
Another thing with Fear is that when used in PVP it seems to show different movement of the enemy as in showing the enemy fleeing in front of me while they actually run behind (with "Target must be in front of you" while trying to cast facing it) and at the end of Fear they just "teleport" to their actual location

**Comment by Crusaderz** [comment]
I've been feared for full duration with dots + DL while lock pet did **direct** damage and you guys want more damage threshold?

https://www.youtube.com/watch?v=aDGtKZ-xRuo
Most of the time fear breaks within seconds if there damage done during it.

**Comment by Wolffenstein** [comment]
So what's the consensus? I'm getting a lot of conflicting information...

**Comment by Jalapan** [comment]
@Wolffenstein either leave it like this or give it "slightly" less chance of breaking, because in the most cases i still feel it breaks to early even when no damage is applied. 

However there are some other warlock bugs that are more important now.

**Comment by Ravyd** [comment]
In all honesty I've been playing on a different server so I haven't been testing it. I will try to return and resume my tests

**Comment by killablink** [comment]
Fear doesn't break at all, you can take way too much dmg without it ever breaking. Specially warrior fear, that one is completed bugged.

**Comment by Ravyd** [comment]
> Fear doesn't break at all, you can take way too much dmg without it ever breaking. Specially warrior fear, that one is completed bugged. The threshold has to be reduced it's actually ridiculous. Many dots + direct dmg and feared to death

Please provide proof, I don't see anything like this in gameplay.

While the change was a good start fear still seems very undertuned. I still don't see fear ever lasting a full duration with a dot rotation up which is improper. Unless burst damage is being used, fear should last a full duration 9/10 times

**Comment by Ravyd** [comment]
To be honest, I'm not seeing any difference in behavior from before. After about 50 fears, not one of them reached full duration under a normal damage load.

https://clips.twitch.tv/FamousResourcefulOctopusLitFam
https://clips.twitch.tv/KnottyProductiveCardFutureMan

**Comment by Ravyd** [comment]
Here's a perfect example of how I don't see any differences between my original clips and current live behavior https://clips.twitch.tv/ColorfulCourageousTruffleDatSheffy

**Comment by Ravyd** [comment]
Another great example of fear instabreaking and not exhibiting proper behavior.

Also for the record killablink is a mage and a troll and so his words have no bearing on this serious discussion https://clips.twitch.tv/DarlingFitSandstormYouDontSay

**Comment by killablink** [comment]
Ah yes, apparently I'm a troll when I've reported more gameplay issues than almost anyone on this server. I'm sorry fear isn't as strong as you think it is because no, a fear should break eventually even with a full set of dots. You're crazy to think that it doesn't break unless there is direct damage.

If you didn't realize, there was an update to make fear break more easily with dots just today ( or yesterday) so maybe you can argue that right now it breaks too easily, but it's still something to see and test. Don't bring your personal vendetta when I did more for the server than you.

https://youtu.be/M92OueS3xfM?t=103  fear breaking on mage early with barely any dots.
https://youtu.be/7k30ZBJ23MQ?t=38 Fear breaking almost instantly from melee dmg.
https://youtu.be/7k30ZBJ23MQ?t=64 Fear breaking quickly right when he applies drain life

The change that I called for was that before the change, you could have full fear with dots+ppl hitting you and it wouldn't break. But right now if it's breaking early everytime with a few dots then yes it's probably something to look into

**Comment by Ravyd** [comment]
> Ah yes, apparently I'm a troll when I've reported more gameplay issues than almost anyone on this server. I'm sorry fear isn't as strong as you think it is because no, a fear should break eventually even with a full set of dots. You're crazy to think that it doesn't break unless there is direct damage.
> 
> If you didn't realize, there was an update to make fear break more easily with dots just today ( or yesterday) so maybe you can argue that right now it breaks too easily, but it's still something to see and test. Don't bring your personal vendetta when I did more for the server than you.
> 
> https://youtu.be/M92OueS3xfM?t=103 fear breaking on mage early with barely any dots.
> https://youtu.be/7k30ZBJ23MQ?t=38 Fear breaking almost instantly from melee dmg.
> https://youtu.be/7k30ZBJ23MQ?t=64 Fear breaking quickly right when he applies drain life
> 
> The change that I called for was that before the change, you could have full fear with dots+ppl hitting you and it wouldn't break. But right now if it's breaking early everytime with a few dots then yes it's probably something to look into

Whoa buddy no need to have some personal argument that nobody, including me, cares about. Take it to PMs (which I won't answer anyways). Making a blanket claim without any evidence is a troll argument in my mind.

I'm not really sure what you're claiming, the post you made before this was saying fear is completely overpowered, now you're saying it's broken. I would say that without a doubt fear is ridiculously undertuned again, to the point where I see now difference between live and issue #4534

**Comment by killablink** [comment]
You're the one calling me a troll but ok. Also, maybe you didn't understand but I was saying how before fear was bugged because you could have dots and people melee'ing you, casting spells and not breaking. That was the main problem. And intimidating shout was even more broken because you could literally spam dmg on a target and it rarely ever broke.

**Comment by Ravyd** [comment]
> You're the one calling me a troll but ok. Also, maybe you didn't understand but I was saying how before fear was bugged because you could have dots and people melee'ing you, casting spells and not breaking. That was the main problem. And intimidating shout was even more broken because you could literally spam dmg on a target and it rarely ever broke.

Yes, in your last reply you provided proof which is what we need, not someone saying "fear is so OP it never breaks" without anything verifiable to look at.

At this point I think we've come full circle, and fear is just as undertuned as it was back in the original issue. In my personal opinion, fear should be pretty darn close to unbreakable, from the reports we have from TBC fear was extremely strong. Only nuke type spells (immolate occasionally, shadowbolt, frostbolt, etc.) should break it. Any reasonable amount of dots (a full warlock dot rotation) should almost never break a fear. 

Just looking at the clips I just linked though, none of those videos show even a single full-length fear and fear feels extremely weak and unreliable yet again.

**Comment by Ravyd** [comment]
I am unsure of the mechanics the devs are tweaking when they adjust fear so I can't give any personal input into the break equation, but my general advice would be something like "make it unbreakable, and then dial it back about 15%"

**Comment by killablink** [comment]
https://youtu.be/1OaMCfCDMt4?t=552 5 seconds in broke from 2 dots
https://youtu.be/LmcKVRSzYMs?t=93 Fear broke early again
https://youtu.be/LmcKVRSzYMs?t=242 Early break again
https://youtu.be/LmcKVRSzYMs?t=406 Broke really early again
https://youtu.be/LmcKVRSzYMs?t=445 Broke just a bit before the full duration

So yeah no, fear isn't supposed to last the whole duration (IN PVP Anyawys) 90% of the time (Imagine saying it should be close to unbreakable that's a yikes)

And here is what I'm talking about warrior fear being super broken:
https://gfycat.com/OptimalPastAnemone

Warrior fear is literally always like that, you just can't break it. He also said himself he 100-0 many people with his fear.

**Comment by Ravyd** [comment]
> https://youtu.be/1OaMCfCDMt4?t=552 5 seconds in broke from 2 dots
> https://youtu.be/LmcKVRSzYMs?t=93 Fear broke early again
> https://youtu.be/LmcKVRSzYMs?t=242 Early break again
> https://youtu.be/LmcKVRSzYMs?t=406 Broke really early again
> https://youtu.be/LmcKVRSzYMs?t=445 Broke just a bit before the full duration
> 
> So yeah no, fear isn't supposed to last the whole duration (IN PVP Anyawys) 90% of the time (Imagine saying it should be close to unbreakable that's a yikes)
> 
> And here is what I'm talking about warrior fear being super broken:
> https://gfycat.com/OptimalPastAnemone
> 
> Warrior fear is literally always like that, you just can't break it. He also said himself he 100-0 many people with his fear.

I do appreciate the input and footage Killa.

However, saying Fear shouldn't break with a normal dot rotation active is **definitely not a yikes** lmfao. In PVP, fear has a max duration of 8-10 seconds, and as I have stated many times, if fear lands on you, expect to stay feared, not for it to break 4 seconds in and you just continue on with your day. 

I think you're getting confused. Spells have different durations in PVP and PVE. If you think I'm saying fear should be lasting 20 seconds on a player, well that isn't even a thing in the first place. 

Keep in mind, for most of these cases, I am saying WARLOCK DAMAGE ONLY. If you you think I'm saying fear should last 10 seconds with 5 people wailing on you, then absolutely not. However, I _wouldn't consider that completely out of the question._ 
Meaning, would I expect it to break? _Absolutely._ 
Would I be surprised if it didn't? _Absolutely not._
That is proper behavior.

In PVE, fear can last as long as 20 seconds, yet I have never seen a fear last longer than 12 seconds in my life, even without any DoTs active. 

As far as intimidating shout goes, I have absolutely no experience with that. However, that is a physical spell while fear is shadow, which may have just given us great insight as to what exactly is going on here. I think there is a massive underlying problem with heartbeat resists or spell hit/shadow resistance that is making priest/warlock fears extremely weak.

**Comment by Ravyd** [comment]
In the same breath, however, would I expect a fear to last full duration (in PVE and PVP) if no nukes of any kind hit the target, and only basic DOTs were active (immolate tick, corruption, UA, CoA, SL, Deep Wounds, etc.), 9 out of 10 times?

**_Absolutely._**

**Comment by killablink** [comment]
I am not even gonna comment anymore because you just ignore all the other clips I'm showing you where it breaks early and its definitely not a thing such as "90% of the time its full duration" I know fear has different duration in PVP and PVE and that has nothing to do with anything. In PVP it lasts 10 seconds but as you can see in many clips that I linked you, it doesn't last as long as it can 90% of the time.

"Expect to stay feared and not for it to break 4 seconds in" I guess all the clips I linked are just really lucky people that keep breaking out of it quickly. 

When you hit 70, and also have hit rating ( because yes spell hit rating influences heartbeat resists, might also be going against you), try to record clips.

**Comment by killablink** [comment]
Lmao, yeah, good luck getting fear to not break with full dots full duration, actually super cringe and I'm out.

**Comment by Ravyd** [comment]
> I am not even gonna comment anymore because you just ignore all the other clips I'm showing you where it breaks early and its definitely not a thing such as "90% of the time its full duration" I know fear has different duration in PVP and PVE and that has nothing to do with anything. In PVP it lasts 10 seconds but as you can see in many clips that I linked you, it doesn't last as long as it can 90% of the time.
> 
> "Expect to stay feared and not for it to break 4 seconds in" I guess all the clips I linked are just really lucky people that keep breaking out of it quickly.
> 
> When you hit 70, and also have hit rating ( because yes spell hit rating influences heartbeat resists, might also be going against you), try to record clips.

I'm ignoring nothing, my clips showed the exact same behavior which is why I said I appreciated it.

Lmao. I said that if you fear a target you would expect it to stay feared. I'm sorry the 9 out of 10 euphemism is triggering you so badly. Would it help if I just said "most of the time" so you don't have a stroke?

Let me put it in a way you might be able to comprehend. If you sheep a target, you would expect it to stay sheeped correct? _Provided nobody damaged it._ Well, likewise, if you fear a target, you would expect that target to stay feared as long _as nobody directly damaged it (nuked it)._ Does that make sense? 

And yes, up until the damage cap you would expect fear to stay active. hit rating or not, the behavior is the exact same as you just demonstrated.

I'm not directly attacking you, I'm having a discussion. Stop acting like everything I say is directed at you; you aren't the center of the universe. If you need to have some time to yourself in your safe space, by all means bro, do you.

**Comment by Ravyd** [comment]
Also, you overlooked the breakthrough you might've made regarding intimidating shout vs fear mechanics. 

Don't let "9 out of 10" trigger you to the point where you aren't useful any longer. It's just a euphemism for "almost always"
