### ISSUE TITLE
Warlock pet while mounted

### ISSUE THREAD

**Issue by faldas** [Atlantiss/NetherwingBugtracker#4730]
Im playing on netherwing, and got my mount. 

After short time i found out when mounted, my pet does not have any regen while im mounted. 

when i dismount it has debuffs and same hp. after minutes of riding.

**Comment by Balanarr** [comment]
That is correct. It only regenerates if he's spawned. At the start of BC he would hang with you even when you were mounted (flying mounts included) and thus it was always regenerating. 

I don't remember exactly in what patch they made it so the pet "despawns" when mounted (arenas excluded, not sure about bg's) because it was a mess when using a flying mount and he was either getting unsummoned when flying too high or just pulling all the mobs. After this change he would also not get any updates to hp/mana/buffs while you were mounted.

**Comment by Balanarr** [comment]
I don't think it ever did that after the change to "despawn" him when mounting. If it did still do updates when you mounted, theoretically it could die while you don't see him if it's low hp and has debuffs.

Gonna check on BFA when I get home.

**Comment by Jalapan** [comment]
related #4566

**Comment by Godmatik** [comment]
![qweqweqwe](https://github.com/user-attachments/assets/73fafda9-03f2-42ff-b63a-b0dd76346083)

Browsing classic forums - this appears to be intended.
