### ISSUE TITLE
No one sees my whispers, /say, /pchat or any kind of chat ingame, while I can see theirs

### ISSUE THREAD

**Issue by Pan43** [Atlantiss/NetherwingBugtracker#4764]
My issue is that no one can read my whispers or any kind of chat that I do, be it /world, /guildchat /whisper /party and such. I can get chat from the players but they won't get my response, even tho my /chat words still show up on my screen.

Might I have been muted somehow ingame ? Or this is just a bug specific to me ?

**Comment by arektrix** [comment]
I have this issue - my name is Ari. I have a guild mate with another 3 character name that has this issue so that might be part of the problem.
Guild member I tested on (4 char name) claims it made his /who list open

It's very upsetting because I'm guild master and it's difficult organising raids without being able to /w

**Comment by danbopes** [comment]
Please message Daystar or create a ticket in game to get this resolved.
