### ISSUE TITLE
[NPC] Ambassador Hellmaw

### ISSUE THREAD

**Issue by rychersky** [Atlantiss/NetherwingBugtracker#4793]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: When we pulled the boss, a trash pack from the first room of the dungeon somehow pulled.

![wowscrnshot_020219_174514](https://user-images.githubusercontent.com/45608488/52171033-9ee1bf00-2712-11e9-9961-aa0d983148dc.jpg)

**Server Revision**: 2479

**Comment by Sabre142** [comment]
That's because he calls them to aid him.

**Comment by rychersky** [comment]
https://www.wowhead.com/npc=18731/ambassador-hellmaw#comments

I don't see any comments referencing him calling trash from the first room. It doesn't really make sense that you have to clear out all the trash from his room before he unbanishes himself but then he would be able to call a trash pack from the previous room. Also, having run this instance on three other servers, I have never encountered this issue.

**Comment by Drayo** [comment]
This indeed feels very odd. While my memory of TBC is hazy, I did run SL pretty often and we never cleared the right side of the first room.

While his assist yell does imply such a functionality, it is never used in any video I could find on Youtube. On NW it seems like he always does it shortly after being pulled.

I do like the idea of him calling for help, even if this is more or less beta stuff that was maybe never implemented. But I have to say that it feels clunky right now, more like a bug than a mechanic. 

The first few times it happens, or until someone specifically confirms that it is a wanted behavior, it just feels like LOS fuckery (due to fear etc.). Maybe only let any living Fel Overseers add? Most groups clear them anyway though.
