### ISSUE TITLE
Mana Tombs x2 buggs

### ISSUE THREAD

**Issue by spoton8** [Atlantiss/NetherwingBugtracker#4794]
Boss (nexus prince shaffar)  was killed then the group died to adds, apon coming back to the boss it was grey to loot  
also the escort quest does not allow multiple people to hand in the pre quest 

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by spoton8** [comment]
Hi I turned in the quest at the box and it bugged out for everyone no one else could turn it in at the box , I was free to start it though from the Npc with a ! On his head
This also happened to another group in there.
If it helps , I handed the quest in mid fighting and the npc Helped us fighting for abit.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by devo6969** [comment]
Currently on the PTR, Anyone can turn in the quest as long as one player doesn't click the cube's "Press this button" after turning in their own quest. No one can turn in the quest on the cube if this happens. Pretty sure this is how its suppose to be.

Tried to recreate the bug with the prince, when he dies the mobs despawn now so i believe its fixed.

https://www.wowhead.com/quest=10216/safety-is-job-one#comments
"This to complete this quest you must click the cube then the speak bubble. But more important to do the follow up with the engineer, everyone must finish this part otherwise the quest won't share at all with the others. My group made this mistake and only I got the escourt quest."
