### ISSUE TITLE
[Core] [NPC] Mob Position/Facing Desync

### ISSUE THREAD

**Issue by OMEGALULW** [Atlantiss/NetherwingBugtracker#4806]
Don't know if this has been reported before

**Current behaviour**: Front/strafestab (bug I know), will sometimes not work unless you move a bit because the mob seems stuck (fully reposition the mob). Mob movement isn't very fluid I guess.

**Expected behaviour**: It shouldn't happen :P 

**Server Revision**: 2749

**Comment by Evolvee** [comment]
?

**Comment by sadfx** [comment]
I know that frontstabbing isn't supposed to work BUT it DOES work on private servers. The desync issue is making frontstabbing sometimes not work unless you reposition the mob to fix the desync, but it could potentially have other implications such as mobs being closer/farther away than you think (could explain players feeling like they get hit from a mob that is out of range).

It's kinda hard to explain what the problem is exactly but I'll try to grab a screenshot when it happens.. Maybe someone else who's tried frontstabbing can better explain the issue.

**Comment by sadfx** [comment]
Possibly a side-effect of the "fix" of #351

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/52181257-47198580-27f0-11e9-8dac-77c578b0bc5e.png)
you cant be serious with this argumentation :D

**Comment by sadfx** [comment]
> you cant be serious with this argumentation :D


The issue itself has nothing to do with frontstabbing, it was simply observed when doing it. Lol.

**Comment by torrenzGH** [comment]
What is the issue then?

**Comment by The14me** [comment]
No issue
