### ISSUE TITLE
[Talent] [Warlock] Improved Drain Soul

### ISSUE THREAD

**Issue by glubglub1337** [Atlantiss/NetherwingBugtracker#4808]
**Description**: Improved Drain Soul should restore 15% of the warlock's mana if the warlock is draining a target's soul and either the warlock or their pet lands a killing blow on the mob. As of 2/2, this was working fine.

**Current behaviour**: This talent no longer restores any mana at all.

**Expected behaviour**: Should return 15% mana if I or my pet land the killing blow on a mob I'm channeling Drain Soul onto.

https://wow.gamepedia.com/Improved_Drain_Soul_(warlock_talent)

https://tbc-twinhead.twinstar.cz/?spell=18372

**Comment by glubglub1337** [comment]
Tested it further using the Omen threat monitor addon. Having this talent, which should also reduce threat by 5%/10%, does not actually reduce threat in any measurable capacity. Getting identical threat numbers both with the talent and without it.

**Comment by dogmax** [comment]
I can confirm this - The talent no longer works as of 3rd of february 2019. 


This talent has been working as described by OP up until now. 

**Current behaviour:** No mana is returned at all. Tested with pet landing killing blow and again with warlock landing killing blow. Either way, no mana is returned. 


**Expected behaviour:** 15% mana returned with 2/2 Improved Drain Soul regardless of whether the pet or the warlock is landing the killing blow. 


**Past behaviour:** Working as expected. 1/2 Improved Drain soul returned 7% and 2/2 returned 15%.

**Comment by bluntdragonn** [comment]
improved drain soul isn't returning mana

**Comment by fantom8** [comment]
Confirmed, mana return not working.

**Comment by Lockanloads** [comment]
not working

**Comment by Jalapan** [comment]
@Wolffenstein

**Comment by Wolffenstein** [comment]
Fixed in rev 2762.

**Comment by surprentis** [comment]
hey this still is broken can this please be re-opened?

**Comment by surprentis** [comment]
hey this is working but doesnt show the buff icon.
