### ISSUE TITLE
No succubus quest available (Devourer of Souls)

### ISSUE THREAD

**Issue by AKapple** [Atlantiss/NetherwingBugtracker#4818]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Cannot start quest "Devourer of Souls" for the warlock succubus. I have tried clearing cache and ive also tried both quest givers in the respective cities Org and UC. i am an orc. 

**Current behaviour**: 
no quest available. cannot interact with quest giver.

**Expected behaviour**: 
upon reaching level 20. the pet quest, Devourer of Souls will be available from Gan'rul Bloodeye (OG)

**Server Revision**: current... 2.4.3

**Comment by AKapple** [comment]
Update:  i have gone through the entire quest chain as listed from (https://wow.gamepedia.com/Warlock_quests) no NPC has a quest attributed to the chain available to me.

**Comment by AKapple** [comment]
I was able to get the quest "Hearts of the Pure" from the respective NPC in UC. there was no pre quest "Devourer of Souls" from the proper NPC's in both city, Org and UC. mind you im an orc. not undead.

I was only able to get this quest after i deleted my WTF folder and checked out UC one last time. the quest was not given as a low lvl quest but as if it was for my level range. putting a "!" mark over the quest givers head. this is very strange and was documented as well by another person. comment from (https://www.wowhead.com/quest=1476/hearts-of-the-pure) Scroll down.

this is still not the proper quest line for an orc or undead, from the last comments link to warlock quests.

**Comment by duzyizly** [comment]
Due to classic wowhead database this looks like blizzlike.

There are TWO quests called "Devourer of Souls" (and you can pick up any quest line as bloodelf, undead, orc) BUT...
Oonce you pick up once quest line you can not pick up another one.
Even if you abandon one of delivery quests you are not capable to pick up 2nd quest line.

So... 
1. if you pick up Carendin Summons https://tbcdb.com/?quest=10605 (Silverymoon delivery to UC) or Devourer of Souls (UC) https://tbcdb.com/?quest=1472 you are forced to do Undercity quest line https://tbcdb.com/?quest=1476

2. if you pickup https://tbcdb.com/?quest=1507 you are forced to do https://tbcdb.com/?quest=1508 quest line.
