### ISSUE TITLE
 # ([Warlock Quest] The Completed Orb of Dar'Orahil)

### ISSUE THREAD

**Issue by siillywizard** [Atlantiss/NetherwingBugtracker#4836]
# ([Warlock Quest] The Completed Orb of Dar'Orahil)

**Description**: 
After completing the Quest:
https://vanilla-twinhead.twinstar.cz/?quest=4976
no follow up quest opens at the acolytes so the quest chain is blocked at this point and i cant get the final quest reward

**Comment by AWIDIUS** [comment]
Still not working
![WoWScrnShot_062619_231334](https://user-images.githubusercontent.com/45521546/60242883-38269300-98b7-11e9-8894-40e6448f5272.jpg)

**Comment by danbopes** [comment]
Confirmed. Contact a GM to help continue the questline until this gets fixed.

**Comment by duzyizly** [comment]
WORKS FINE.

In order to finish whole chain you need to complete:
1. https://tbcdb.com/?quest=4962
OR
2. https://tbcdb.com/?quest=4963
(depends of item you wanna get form the last quest).

A) https://tbcdb.com/?quest=4962 + https://tbcdb.com/?quest=4976 = https://tbcdb.com/?quest=4964

B) ttps://tbcdb.com/?quest=4963 + https://tbcdb.com/?quest=4976 = https://tbcdb.com/?quest=4975

![WoWScrnShot_050720_175442](https://user-images.githubusercontent.com/43931626/81316624-19bf2580-908c-11ea-9af3-fe8d3091722c.jpg)

**Comment by Tereneckla** [comment]
What duzyizly says
