### ISSUE TITLE
[Quest] The Cipher of Damnation

### ISSUE THREAD

**Issue by kwah8787** [Atlantiss/NetherwingBugtracker#4863]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
3 npcs help you fight the firelord that guldan summons
**Current behaviour**:
Only 1 npc, Oronok Torn-heart, helps you in the fight. Also.. after this other group just did this fine, we tried to summon the firelord but he never appeared.
**Expected behaviour**: 
A total of 3 NPCs should help you in the fight. https://youtu.be/Gc8FpKDilSI?t=270 expected behavior
**Server Revision**: 
2765

**Comment by Azalen** [comment]
They all fight but viewdistance is not high enough for you to see them all.

**Comment by Easyfraggy** [comment]
Seems invalid? Reopen if its not.

**Comment by teddys** [comment]
this is not invalid and the netherwing version of this quest is a definition of clown fiesta

**Comment by Firroth** [comment]
Yeah, it is totally clown fiesta, aside from people exploiting this quest to "solo" it, cause Oronok Torn Heart is immortal. He has 1% hp and won't die no matter how long and how much fight lasts.

This screen was made today, and hunter was soloing it, when he overaggored npc he simply FD, so q mob would go back to beat the unkillable npc Oronok...

![screenshot_1](https://user-images.githubusercontent.com/43505196/52826162-09eea680-30c0-11e9-9b6f-195d2e37a6d2.png)

Other 2 npc's are flying in air, better description would be "stuck"

![screenshot_2](https://user-images.githubusercontent.com/43505196/52826280-78336900-30c0-11e9-9c4d-a790418b8d81.png)
![screenshot_3](https://user-images.githubusercontent.com/43505196/52826311-9600ce00-30c0-11e9-98cc-efe14f897115.png)

Reopen it, since it's valid report.
