### ISSUE TITLE
Switching from Gnomish engineer to Goblin engineer does not work. 

### ISSUE THREAD

**Issue by grandmarshalpro** [Atlantiss/NetherwingBugtracker#4896]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Does not work to switch from Gnomish to Goblin Engineer.

**Current behaviour**: 
When you try unlearning Gnomish Engineering, and switch to Goblin Engineer, you get charged 10g (and 5g higher each time it seems) instead of 150g. When you then unlearn Gnomish and learn Goblin, you can not talk to the Goblin engineer trainer to learn Goblin items. As you relog, you gain Gnomish Engineering again and can use your Gnomish items. You can learn Goblin engineer patterns while you "are Goblin engineer". When you then relog, you can for example make Goblin Jumper Cables XL + Gnomish Death Ray. 

**Expected behaviour**: 
You are supposed to pay 150g to the book in Tanaris to be able to switch from Gnomish Engineer to Goblin Engineer.

**Server Revision**: 
![bugtracka](https://user-images.githubusercontent.com/47423929/52420760-fad18c80-2af2-11e9-866c-46ddafba593a.jpg)

**Comment by adrenochrom** [comment]
The Switching itself works:
- Goblin Rocket Launcher -> http://db.hellfire-tbc.com/?item=23836 -> "Requires Goblin Engineer" is white now instead of red. So I am a Gobling Engineer.

But you are not able to learn stuff from Goblin Engineer trainer because you are not able to get "Goblin Engineer Membership Card".  Maybe because it requires: http://db.hellfire-tbc.com/?quest=3644 -> http://db.hellfire-tbc.com/?quest=3639

**Comment by grandmarshalpro** [comment]
I went over to the Goblin trainer in Gadgetzan, not able to pick up the Goblin Engineer membership card etc etc.

Yeah switching works till you logout.

Sendt fra E-post<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
Fra: Drgonzo <notifications@github.com>
Sendt: Sunday, February 10, 2019 2:39:56 AM
Til: Atlantiss/NetherwingBugtracker
Kopi: grandmarshalpro; Author
Emne: Re: [Atlantiss/NetherwingBugtracker] Switching from Gnomish engineer to Goblin engineer does not work. (#4896)


The Switching itself works:

  *   Goblin Rocket Launcher -> http://db.hellfire-tbc.com/?item=23836 -> "Requires Goblin Engineer" is white now instead of red. So I am a Gobling Engineer.

But you are not able to learn stuff from Goblin Engineer trainer because you are not able to get "Goblin Engineer Membership Card". Maybe because it requires: http://db.hellfire-tbc.com/?quest=3644 -> http://db.hellfire-tbc.com/?quest=3639

**Comment by adrenochrom** [comment]
I changed my specialization too:
- I had 360 Gnomish Engineering
- unlearned Engineering
- releveled it from 0 - 350
- unlearned Gnomish Engineering at the book in Tanaris
- learned Gobling Engineering at the book in Tanaris

Now I am both: gnomish and gobling Engineer at same time, but I am unable to learn Goblin Engineering recipes because of the trainer don't want to talk with me. Probably because I don't have / unable to get "Goblin Engineer Membership Card" : http://db.hellfire-tbc.com/?item=10791#reward-of

I am able to wear/use both different 45 Stamina trinkets from Goblin/Gnomish Engineering:
Goblin Rocket Launcher -> http://db.hellfire-tbc.com/?item=23836#created-by
Gnomish Poultryizer -> http://db.hellfire-tbc.com/?item=23835#created-by

**Comment by firetruck69** [comment]
Yea,  same here.  I just want the enchanted goblin helmet.  :(

**Comment by Wolffenstein** [comment]
Fixed in rev 2933.
