### ISSUE TITLE
[NPC][Spell] Prince Malchezaar - Flying Axes dealing too much damage.

### ISSUE THREAD

**Issue by ripwarlock** [Atlantiss/NetherwingBugtracker#4958]
**Description**: Prince Malchezaar's Flying Axes (Phase 3) hit for 4000+ on cloth players with crits of upwards to 8000+.  Flying Axes should start off by hitting for 400 and ramp up to 2000 on clothies. 
Resource: https://wowwiki.fandom.com/wiki/Prince_Malchezaar
[https://i.imgur.com/PjMW88M.png](url)

**Current behaviour**:
Flying Axes hit for 4000dmg (8000 Crit) on clothies.
**Expected behaviour**: 
Flying Axes hit for 400 ramping up to 2000 dmg (4000crit) on clothies.
**Server Revision**:

**Comment by Tenoutoften** [comment]
Your picture isn't working

**Comment by Easyfraggy** [comment]
Wiki's are not sufficient evidence for prenerf values. The axe damage is correct.

**Comment by Picajzla** [comment]
So can you,  for once, link us that source of prenerf values? Because I'm seriously struggling to find a video where tank gets hit for 19k with ironshield pot on as it happens on this server. https://www.youtube.com/watch?v=wHyqB2Ruqyk is this post nerf already aswell? A kill after 2 weeks of tbc where you can clearly see a 1.5k crit on cloth. Normal hits are 700. On this server clothies get hit for 9k insta. You can see the priest getting hit on 6:20
I'm not even gonna get started on the cleave in this video. None of the melees get cleaved like they get on this server. Getting cleaved on prince if you move 1 pixel from max range, meanwhile melees are casually running sideways of boss. I'm gonna shut up if you can counterproof me with some legit evidence.  A server that has bugs is a server that i can play on, but  server that refuses to admit their mistakes and/or provide

**Comment by Mewmewww** [comment]
Personally, our group didn't have any problems with flying axe phase and it was our first prince run. Cleave didn't hit anyone behind if you positioned yourself correctly behind him at max range (we had a rogue and a enhancement shaman)

**Comment by gabbat** [comment]
requesting reopen. 
Claiming that the axe dmg is correct pre nerf values without providing a source is not acceptable behaviour. Videos have been posted 2weeks after release which is the only indication we have in this discussion and thus need to be used in order to operate on a logical thinking base. If you pretend to have correct prenerf values without providing a source you basically dont have them. Use what is available, or provide a source.

**Comment by gabbat** [comment]
And in case you know of a corresponding issue that causes the Axes and/or the Prince to deal more dmg than intended then for gods sake open a bug report on that, as this is literally impossible to anyone else without server inside knowledge. This whole behavior in all of this discussion is not getting us anywhere, as it is clear that price/axe dmg is simply absolutely bugged (but not for everyone apparently) sometimes and it needs to be fixed, whatever the cause is. Thank you for understanding this.

**Comment by Easyfraggy** [comment]
The report on prince dealing increased damage under certain circumstances is open and has never been closed or hidden.

**Comment by gabbat** [comment]
please link it then. And dont link the "[NPC] Prince Malchezaar Low Dmg" as this is actually the opposite of what happens here. If the AP scaling with debuffs is wrong, a report on that needs to be opened - if that is already open, all these issues need to be redirected/linked to that one. This is a total mess tbh

**Comment by Easyfraggy** [comment]
I linked it in the other thread. https://github.com/Atlantiss/NetherwingBugtracker/issues/3004
