### ISSUE TITLE
[Core] Stuck Auto Attack

### ISSUE THREAD

**Issue by Dusky1** [Atlantiss/NetherwingBugtracker#4963]
So as you probably know, the auto attack sometimes stucks during fight. This bug is very hard to reproduce, but I've found 3 thing that are causing it:

-in PvP when u fight someone and he starts Mining/Skining/Herbalism your white hits wont land on this target until you /cleartarget and target him again.
-in PvP when druid changes his form your autoattack also stucks (not everytime but very often, must be something else ). I found that if the druid leaves his form with Barkskin or other spell it happens more often.
-in PvE when mob evades and you chase him to his OG position, after he comes back and resets it happens again - no white hits until retarget.

Also, ive tried some ways to fix it with macro but this macro doesnt work( it resets your melee swing timer everytime you press it)

/cleartarget
/targetlasttarget

Sorry for my broken english, I hope you understand. If you got any questions I can show you ingame how to reproduce the above things. (Horde - Hazard)

REV: 2776

**Comment by teddys** [comment]
Changing targets is usually a trigger for me, but yeah this is incredibly annoying and crucial because you are missing (at the very least) 1 autoattack before you notice.

**Comment by Dusky1** [comment]
Yeah changing targets is the same. But the most annoying part is that its impossible to reproduce it in duel or controlled circumstances. It happens only if you have to fight for survival :)

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2795 We need a way to reproduce this - been leveling as a warrior now and not happened a single time aswell as playing 14days+ played on beta and never having this happen. 

It has to be some specific gameplay that makes it happen - otherwise it would happen to everyone. Please only use the existing thread. Duplicates will just be closed.
