### ISSUE TITLE
[Raid][SSC] Lady Vash'j's health pool

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#4964]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Lady Vash'j on this server has an absurdly large health pool of 8,093,300, which is taken directly from CC test server, a highly disputed number that is unverifiable. There is also a verified number attached which state that the health should be 4,856,000, which feels rather low, and is most likely post-nerf.

Since many of the boss mechanics and timers are taken from [method's second world kill](https://www.youtube.com/watch?v=SYypbzs9d44), even the mind control behavior is emulated work like it does in this video, we can use this video as a basis, and estimate the health pool of Vash'j from their kill.

The warlock in the beginning of the video is using a damage meter which shows their damage done and percentage of their damage compared to the total raid damage for phase 1. The video fades to black and switches point of view at [2:02](https://youtu.be/SYypbzs9d44?t=122). Using the damage values shown at that point, and dividing it by the total raid damage percentage, we get a total raid damage estimate of 810,155, an average from 5 random players in the list. With that value and using Vash'j's current health percentage at 86%/87%, we can divide the total raid damage with the health percentage she has lost to get a range of 5,786,819 - 6,231,959. Using the same method at any point during phase 1 in the video will yield a similar range.

Since we are using many mechanics from this fight, such as 2 mind controlled instead of 3 or even 5, the same mind control behavior etc., I think we should use the same health pool as they fought against.

Unfortunately, it is impossible to estimate which exact health percentage Vash'j is at, and the damage meter is not updated in real time, however the update rate seems to be 1 second, so the error is rather small here. Also please correct me if I my math above is wrong.

**Current behaviour**:
Health pool of 8M.
**Expected behaviour**: 
Closer to 6M.
**Server Revision**: 
2776

**Comment by Brasso** [comment]
Can you at least give an explanation, or a source, or just a screenshot saying anywhere that it should be 8M instead of just closing it, please?

**Comment by Drayo** [comment]
Most Bosses in T4/5 had inflated HP pools on CC (not just vashj), it was most likely the intention to counter the skill creep as well as 2.4.3 talents and abilities. Proper blizzlike numbers simply do not challenge the modern playerbase in any way, previous Servers have shown that more than once. Fights with actual retail HP numbers are over way too fast and the actual mechanics can often be ignore due to that.

If those adjustments are done openly, people will cry due to stuff being not blizzlike, if nothing is adjusted everything will be one-shot and players will blame the Server for being undertuned, happened to every Server before NW in one way or another. Best you can do is change stuff that isn't too obvious and does not have a great impact on established tactics. 99% of the players have zero fucking clue what the numbers should be, they simply go by feeling and judge the Server accordingly, they actually don't give a fuck about authenticity.

**Comment by killablink** [comment]
On Gummy Lady Vashj still had normal values 5M~ HP yet there were no guilds except 1 or 2 that killed her. A boss can still be hard if you script her properly. You can't claim to be a blizzlike server and then change the values of bosses based on no proof from an old Corecraft core.
