### ISSUE TITLE
"On Cast" Trinket effects not including the cast immediately after the proc

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#4972]
**Description**: 
Noticed this issue for Quagmirran's Eye (https://tbc-twinhead.twinstar.cz/?item=27683) but it will most likely effect all trinkets of that type and maybe even "On Use" trinkets (needs testing).

When Quagmirran's Eye proc's my Shadowbolt casting time goes down to 2.1 seconds from 2.5 seconds. Right now on Netherwing though it works like this:

1st spell cast finishes --> start casting 2nd spell ---> gain buff ---> 3rd spell is actually benefiting from the spell haste but actually lost 2.5 seconds of the buff effectively doing nothing

This may be related to spell batching or spell queue.

**Expected behaviour**: 
1st spell cast finishes --> gains buff -> start casting 2nd spell with the spell haste buff

Proof: https://youtu.be/dCxVJM-lTvs?t=109
At exactly 1:49 you can see the 6 second proc of (most likely) Quagmirran's Eye and immediately the following Shadowbolt is benefiting from the haste buff.

In the combatlog it shows "gains Spell Haste". The same does Quagmirran's Eye.
![untitled-1](https://user-images.githubusercontent.com/20336567/52611202-9ca30180-2e84-11e9-84b0-b92b3474d6d9.jpg)

**Server Revision**: 
[2785]

**Comment by towneh** [comment]
I'm not sure that video you linked accurately describes what you're trying to achieve? You can see the warlock in the video gain the buff whilst spamming Shadowbolt, but the 1.9 cast time only appears on the next cast bar immediately following the buff aura being gained. This is how it should also work in-game on NW.

This was painfully noticeable as a shadow priest in TBC when gaining a haste proc (including blood lust) immediately after channeling mind flay, as you had to clip mind flay on purpose in order to gain the benefit of the decreased cast time.

**Comment by killablink** [comment]
The problem right now is that because of the whole batching thing, you gain the buff midway during the second cast, when you should gain the buff right after your first cast that procs the item goes off. 

This is how it goes right now:
1st spell cast finishes --> start casting 2nd spell ---> gain buff ---> 3rd spell is actually benefiting from the spell haste.

When right now from the video how it should be is
1st spell cast finishes --> gains buff -> start casting 2nd spell with the spell haste buff

**Comment by Azalen** [comment]
killablink is right. Was late when I wrote this yesterday. Edited 1st post.

**Comment by towneh** [comment]
Just be careful as the trinket wording suggests that the procs are based on dealing damage and not on successful spell cast, so you may need to account for in-flight delay from the shadow bolt projectile hitting the target.

**Comment by killablink** [comment]
It procs on literally everything, frost armor debuff, casting ice barrier, etc

**Comment by knasen88** [comment]
it's more like it procs after a projectile/effect lands on target, a slow moving proj like frostbolt/shadowbolt can almost cast 1½ additional projectile before it applies

**Comment by killablink** [comment]
https://youtu.be/xOTrN5KShgM?t=68

Here you see it proc right after he finishes casting fireball. It's supposed to be on cast, not on damage

**Comment by Azalen** [comment]
bump

**Comment by Godmatik** [comment]
Unable to reproduce - the trinket popping mid-cast properly works on the next cast as expected.
Probably fixed at some point and this was never closed out.
