### ISSUE TITLE
Halaa bugged

### ISSUE THREAD

**Issue by Lariari** [Atlantiss/NetherwingBugtracker#4994]
Halaa bomb runs dont damage guards, have tried multiple times with all wyvern points capped.

**Comment by Mango-Ray** [comment]
**Server Revision: 2825**
**Current Behavior:**
Fire Bomb (ID 24538) does zero damage. 


**Expected Behavior:**
Fire Bomb should:

- deal 900 to 1100 direct damage

- inflict a debuff that deals 1% of maximum health every second for 5 seconds

**Side Notes:**
These should only work while using the Halaa flight path, and should be capable of hitting players of the opposing faction while on that flight path. I have not tested the bombs to do either of these things so i do not know if they are working correctly or not.

**Source:**
http://web.archive.org/web/20071231180449/http://thottbot.com/i24538 comments
![image](https://user-images.githubusercontent.com/13490949/53291545-de844f80-3782-11e9-839e-c99000c8c3b2.png)

**Comment by Mango-Ray** [comment]
Currently the only way to take over Halaa is to actually kill the 1.3m guards through normal means, or dragging them to faction cities to have the guards help damage them. It's really depressing.

**Comment by Tereneckla** [comment]
fixed
