### ISSUE TITLE
[spell][Vanish] Debuffs aren't properly applied when knocking rogue out of vanish

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#4997]

**Comment by Lotsix03** [comment]
I noticed the rogue just popped sprint just a split second after your CoC.  Could possibly be running  improved sprint which would remove the debuff. http://tbc.cavernoftime.com/spell=13743  At two talent points it 100% removes any movement impairing effects.

**Comment by killablink** [comment]
nahh its not that 
https://gfycat.com/CaringDrearyGyrfalcon

**Comment by Lotsix03** [comment]
Yep that looks like a bug.

**Comment by Dollywog** [comment]
Hi, have noticed this  today also  .    I think its a bug with the improved Sprint talent, instead of removing movement impairing effects it seems to make you immune to slowing effects for its duration (which is crazy).
Have had issues with rogues running all over frost traps and not being slowed at all.  In your second clip you can see the CoC debuff only applies when the Sprint ends

**Comment by killablink** [comment]
Don't think it's that at all, my cone of cold works fine even if a rogue is sprinting. In the second clip I happened to cast cone of cold as soon as his sprint ended.

Also in the 2nd clip of the 2nd gfy, he had no sprint yet the same thing happened.
