### ISSUE TITLE
[Core][Interactions] Gouging a blink isn't working correctly.

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#5039]

**Comment by ScottieDOESknow** [comment]
This seems to be working, from a Rogue perspective at least.
Cheap Shot then Gouge and 99% of the time Mage blinks forward and is Gouged.
I have no clips, but it's happened more often than not, from Beta P2 up to live (Feb 16th)

If you Blink and don't move, it's because certain terrain can sometimes prevent forward progress.
In the video clip you can see you tried to blink up a double incline. I'm fairly certain if you try to Blink multiple times in same exact area, facing same direction, you could replicate this.

**Comment by killablink** [comment]
??? I blinked in front of me in a plane surface what do you mean?
