### ISSUE TITLE
Screen freezes after game loads new models

### ISSUE THREAD

**Issue by mgoatoce** [Atlantiss/NetherwingBugtracker#5041]
Screen will freeze for players after a model change occurs, especially when it occurs as the model enters players vision.
Caused by things like hunter/warlock pets appearing after dismount or druids changing form after dismount.

**Current behaviour**:
Freeze screen for undefined amount of time
**Expected behaviour**: 
No screen freeze
**Server Revision**: 
2799

**Comment by Xyter** [comment]
This was happening to me frequently until I followed someones advice and changed my Questhelper performance load to 10% by typing /qh perf .1 and turning off objective sharing by typing /qh solo. Haven't had a freeze since then and I had some bad ones before making these changes that lasted several seconds many times.

**Comment by mgoatoce** [comment]
can confirm that players without questhelper have experienced this problem
