### ISSUE TITLE
Auto shot fixed but only to be broken harder

### ISSUE THREAD

**Issue by Dankbusta** [Atlantiss/NetherwingBugtracker#5043]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Auto-shot and hunter casts
**Current behaviour**:
Auto-shot has no windup. Its supposed to have a half a second windup before each shot, and its supposed to still tick while casting (so after finishing a volley channel or a steady shot cast, an auto attack immediately goes through, the half a second windup happens "behind the scenes"). 

This one I'm not 100% sure of but eitherway: Aimed shot is supposed to behave like Slam, delaying your next auto-shot. Right now when the aimed shot cast finishes, an auto shot immediately goes through.

Because the auto-shot windup was removed, 3 horrible game breaking things happened: auto-shots go through while casting steady shot and while channeling volley and you can shoot while moving (technically you have to pause but as long as the game registers a pause, no matter how short, an auto-shot will go through).

Right now hunters can use the slowest ranged weapon for maximum steady shot hits with absolutely no downside or even the possibility of a gameplay mistake. This skill was designed to allow a wider range of ranged weapon speeds to be viable without being detrimental to overall dps (compared to classic).

**Expected behaviour**: 
a cooldown-ready auto-shot is postponed/delayed until steady shot finishes the cast or volley finishes the channel.

Auto-shot cooldown is reset when an aimed shot is cast.
**Server Revision**:

**Comment by Easyfraggy** [comment]
I decided to keep this bug report open instead of the original: https://github.com/Atlantiss/NetherwingBugtracker/issues/4759

It's a known issue and I've done what I can to make it top prio - It's just up to wolf now.

What might help him though is a full write up of how hunter spells should work - which should interact with autoshot and which should just be instant.

For example:
Steady, Aimed, Volley should interact with auto shot. windup should reset whenever one of these casts complete/cancel.

I'm not a hunter guy so someone else is more qualified to make a writeup.

**Comment by Zarant** [comment]
Read the comments I posted in issue #2339 
I've done what you just asked many weeks ago.  There are lots of other major issues buried on this bug tracker, should I just open duplicates to give them the proper attention they need?

**Comment by MiekZer** [comment]
I'm glad we had 5months beta + 3years development

**Comment by DragunovUA** [comment]
id say best beta with active bug reports and 300 ppl online, but on release we have this...omegalul

**Comment by gunzbngbng** [comment]
Auto Shot also will get jammed constantly when switching targets or from melee to ranged.  This causes even special attacks like multishot to not fire.

**Comment by letterix** [comment]
After the changes today, auto shot got broken as much as it was, but in a different way; one we had on the beta. Now, steady shot seem to have precedence over auto shot, thus never firing an auto shot; this completely breaks 3:2 rotations.

Please, we have been getting iffy fixes since early november in the beta, can we dig down and actually get a fix for this now? Its completely game breaking for hunters.

**Comment by beriah** [comment]
I think this needs a rollback until there's a real fix. Rev 2816 makes the class almost unplayable.

**Comment by Easyfraggy** [comment]
Auto and steady are broken and were just as broken before just in a different way - It's gonna be a few days before wolf has time to fix it properly.

**Comment by Lecia2134** [comment]
@easyfraggy as long as you guys are aware it's all good. Just know as others above have said it's really similar to how it was in beta, around 2 weeks before release, when auto would get clipped by KC. Thanks nw team.

**Comment by Wolffenstein** [comment]
Retest in rev 2845.

**Comment by IGNPoint** [comment]
3:2 still broken.

**Comment by Easyfraggy** [comment]
https://gfycat.com/singlekindheartedhippopotamus

Seems fine to me.
