### ISSUE TITLE
Writing in chat doesn't show for other players (including gm)

### ISSUE THREAD

**Issue by miyago1** [Atlantiss/NetherwingBugtracker#5088]
**Description**: 
Other players including gamemaster Olmon was unable to see what I wrote in any chat in game.

Been playing a night elf warrior 28 levels now. Created it about 1 month ago and I believe the bug has been with me all since it's creation of the character. I don't know for sure of course since I only comfirmed it today.

Gamemaster Olmon told me to deleta WTF, addon and cache folder. AFter restarting the game I could chat again normally.

Addon list before it got deleted:

Blizzard_*

Cache
Cartographer
DrDamage
Gatherer
Gatherer_HUD
GathererDB_Wowhead
Mobinfo2
OmniCC
OmniCC_config
OmniCC_Options
Postal
Prat (tried disabling this without any effect)
Quartz
QuestHelper
RatingBuster
Recount
sct
sct_options
sctd
sctd_options
SellJunk
VendorValues

**Server Revision**: 
2819 but earlier aswell

**Comment by miyago1** [comment]
To be more specific: the things I typed showed up in chat as normal for me but nobody was able to see it

**Comment by Wolffenstein** [comment]
You must have been flagged by autospam for some reason, please ask a GM to unsilence you and the issue will be solved.

**Comment by Zuldaris** [comment]
I've tried all of this and the problem was not fixed.  There are forums posts back to February about this with no answer.  So, this private server is pretty much dead if you encounter this bug.  The support team, if one actually exists, can't seem to provide anything that even slightly resembles support.  I realize this is F2P, but if they provide both forum-based, and ingame support, they should at least be able to address a post sooner than 2 months if not an ingame ticket that is 2 days old.
