### ISSUE TITLE
Battleground graveyard bug

### ISSUE THREAD

**Issue by dalabu** [Atlantiss/NetherwingBugtracker#5096]
**Description**: You cannot ress or see Spirit Healer after you die in BG's.

**Current behaviour**: https://streamable.com/z7iij

**Expected behaviour**: Right after you die, the ress countdown needs to start immediately without the player moving or jumping around to enable it.

**Server Revision**: 2819

**Comment by carolusr3x** [comment]
I've been spamming AB the last few days and I've seen this bug a lot, but not just that - I've seen players rez while I can't see the spirit healer, and sometimes players rez at different times (afaik the spirit healer should be sync'd between players).

**Comment by raethkcj** [comment]
Bump, this is still happening. 9/10 times I cannot get resurrected by battleground Spirit Healers unless I run forward after releasing, and I often miss resurrection waves because of this. It's possible it's related to releasing very quickly (I use LazyPig to autorelease spirit), but releasing quickly should not deny you your res.

**Comment by raethkcj** [comment]
Bump @Wolffenstein @Evolvee

**Comment by Wolffenstein** [comment]
Fixed in rev 3101.
