### ISSUE TITLE
[Dungeon][Pathfinding][Exploit] Mob leashing and resetting in dungeons.

### ISSUE THREAD

**Issue by Haipethdev** [Atlantiss/NetherwingBugtracker#5097]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Mobs are leashing, and resetting, in dungeons despite there being a path to the player at the top of the threat table whenever that path is too long.  There are several examples of pulls in dungeons from Vanilla and TBC on youtube of that time period in which mobs will never reset, so long as there is a path (of any length) to the target.  I suspect this is a limitation of the path finder on the server, which breaks after a certain path length.  This is currently not blizz-like and potentially exploitable to skip large portions of end game content.

**Current behaviour**:

Mob leash breaking, causing a full reset once the path to the target player at the top of the threat table is too long.

**Expected behaviour**: 

Mob should never leash and should not reset when inside a dungeon.  See: https://wowwiki.fandom.com/wiki/Leash

**Server Revision**: 
2819

**Comment by Wolffenstein** [comment]
Could you provide a video of that happening?

**Comment by Haipethdev** [comment]
https://www.youtube.com/watch?v=31d0KCXST3A&

**Comment by Wolffenstein** [comment]
I mean a video from Netherwing.

**Comment by Haipethdev** [comment]
For clarity: I got a friend to test that pull as an example since it is a 1:1 example I could find, and while it is WotLK, no leash changes were made since then according to patch notes.  I also distinctly remember other cases such as jumping down the hole in Sunken Temple and not resetting even in vanilla.

**Comment by Haipethdev** [comment]
Oh, apologies, let me get one.

**Comment by Haipethdev** [comment]
(got a friend to record in Sunken Temple now, he will post below)

**Comment by TheRealRickle** [comment]
https://www.youtube.com/watch?v=LyFbt_-R_JY&feature=youtu.be

**Comment by someotherplayer** [comment]
I saw this happening in Dire Maul North while farming leather.
I pulled the Hyenas in there and jumped up the ledge of the ramp. The mobs stopped running after me and after waiting a bit they reset and I left combat.

**Comment by Tenoutoften** [comment]
I've pulled all the mobs in the boat room in deadmines, then jump from the ramp/on top of the boat down to the ground level(of the boat) and all mobs get confused and stand still. Eventually they will reset to their normal position. If you move closer to them(reducing their path length) then some of the mobs will suddenly remember that they are suppose to chase you.

In that situation I've also had mobs reset their position, only to remember that they are suppose to chase me as I move closer. Casters/hunter mobs often have issues when you walk down / up ramps f. ex. moving down the ramp in the second goblin room in Deadmines or up the stairs in Scarley Monastery graveyard.

I've had casters mobs agroed by myself, go on another character who has caused no threat(No healing, no buffs, no mana regen) these mobs also do reset on occasion(This happens when they are confused by the stairs for a certain mount of time). I have videos of this that I could post, I just never wrote a report about it myself...

**Comment by Tenoutoften** [comment]
[Here](https://www.youtube.com/watch?v=Z9nstAmlHms&feature=youtu.be) is a video of a caster getting confused by a ramp in Scarlet Monastery Graveyard on Netherwing

**Comment by Haipethdev** [comment]
Any potential update on this?  Any idea what was breaking it?

**Comment by The14me** [comment]
Rev.3483 still an issue.
https://streamable.com/vgu4ll
Mele mobs start to move, but range one are stuck for the most of the time (check at the end)

**Comment by Godmatik** [comment]
Pathing issues in dungeons were fixed last year in the pathing core updates.
Closing
