### ISSUE TITLE
Tauren hitbox is obnoxious on this server

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#5114]
https://www.twitch.tv/videos/384533078

This is what it is like being a Tauren on Netherwing. This cannot be correct. What's more is you cannot use Noggenfogger or Deviate Delight to make your hitbox smaller- it remains the same. I understand hitbox was altered for pvp purposes but I have never seen Tauren impacted so much in retail TBC pve videos. This is an issue on any fight with ground / proximity aoe.

**Comment by Easyfraggy** [comment]
Need as much info on this as possible - Tauren hitbox is both an advantage and disadvantage depending on situation.

If you change it to be so that for aoe their increased combat reach is not counted they will sometimes be able to outrange certain aoe's while still attacking and others will not be able to. So need to have some evidence on how it should work.

**Comment by BezawitNW** [comment]
WolfensteinToday at 7:20 PM
[2838][Core] Reworked AoE spell range calculations to be less punishing against Taurens
