### ISSUE TITLE
[Core] Permanent "Dazed" without debuff

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#5115]
**Description**:  In some cases after "dazed" debuff inside of dungeons it can got stuck without any debuff shown. Basically it looks like toggled run/walk but without possibility to toggle it back to run. Happened few times to me and my friends.

**Server Revision**: 2825

**Comment by narobi123** [comment]
yeah that happened to me too after a regular slow.

**Comment by Tenoutoften** [comment]
This seems related to a lot of the other reports

**Comment by veekk** [comment]
That happens on Pally and Shammy, so that might be general one, not only shapeshifting stuff

**Comment by weedzyx** [comment]
happend lot of times to me, after feral charge or any movement reduction affect.

**Comment by Yavannie** [comment]
This happened to me on my hunter a few days ago, and I didn't have a clue what was going on! Glad to get an explanation. It happened when I was in a group to kill Mai'Zoth for The Mind's Eye in STV. The other person must have thought I was an idiot, just walking around. Can't say what it was that triggered it since a lot of stuff was going on at the time. If it happens again I'll check the combat log. A relog fixed it.
