### ISSUE TITLE
Line of sight issues

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5153]
**Description**: I don't know how to explain in technical terms but it seems the server takes time to update your actual location? making it so that you're more easily hit when you're about to run around a pillar. https://gfycat.com/AcceptableWindingBooby https://gfycat.com/PalatableDigitalAfricanclawedfrogFor example, it shouldn't ever be possible that the target gets sheeped and is actually way around the corner

**Expected behaviour**:

**Server Revision**: Latest

**Comment by Zarant** [comment]
iirc the wow client doesn't send movement packets very often, this kind of thing was very common on retail, since what your client sees is an interpolation of the discrete movement updates, so what you see is not necessarily matches what the server sees.

I tried replicating that bug but it doesn't feel like being bugged, it's just the way it is I suppose.

Here's an example of what I just described:
https://youtu.be/KoHJk_kLCFU
https://clips.twitch.tv/ViscousGoodJaguarBigBrother

**Comment by Wolffenstein** [comment]
Indeed, the server may be delayed up to 500ms (worst case scenario). Blizzlike.
