### ISSUE TITLE
[NPC] Restless Skeleton hits way too hard

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#5205]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
This NPC is summoned by Nightbane in Karazhan during the Air Phase.

**Current behaviour**:
Restless Skeleton hit me for 3954 physical dmg (It was a crit, but sadly I didn't make a screenshoot on this. You have to believe in me at this. T_T)

**Expected behaviour**: 
According to [Revision as of 21:57, 9 December 2008 on wow.gamepedia](https://wow.gamepedia.com/index.php?title=Nightbane_(boss)&diff=1699922&oldid=1699152) and 
[Revision as of 23:14, 25 January 2009 on wow.gamepedia](https://wow.gamepedia.com/index.php?title=Nightbane_(boss)&diff=1755052&oldid=1699922) they "Hits for approximately 1,300 on cloth, 450 on plate". Well I am a holy paladin in full plate gear (Had like 11300 armor with druid buff) and I don't know for how can a 450~ dmg transform to a 3.95k crit.
**Server Revision**: 
2825

**Comment by Drayo** [comment]
T4 and T5 have adjusted damage/HP numbers to offset skillcreep and 2.4.3 talents, this has been repeatedly mentioned now, see the whole Lady Vashj discussion, esp. on discord.
Nightbane has way more HP than retail, Nightbane also hits for more than retail, same goes for every other NPC in Karazhan and all other dungeons/raids in Outland.
Aside from Lady Vashj, every one of them has been killed and they are being farmed by a a lot of Guilds by now, they all started with shitty gear and progressed through it.

Are you going to create a bugreport for every affected creature or just the ones where your group gets stuck on for a while?
I know that this does not truly belong in this report, sorry for this. I'm not trying to shit on you since I know that you also report a ton of other stuff, but it just seems so petty to specifically open reports for mobs than inconvenience your group, while ignoring the 500 other ones because you managed.

**Comment by Mikik3jr** [comment]
Nah we killed Nightbane, I didn't make this report, because we stucked on it, I just found this damage thing when I wanted to make a report about the distracting ash debuff. I was like: why not report this too? If the damage stays the same I don't care, we can still do this anyway. I report everything I see, because MAYBE it is connected to a core issue.

**Comment by Tereneckla** [comment]
they have been nerfed quite a lot since this
