### ISSUE TITLE
[Dungeon] Maraudon - Zoning issue on last patrol before Princess causes permanent combat and/or party-wiping superpulls [workaround known]

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#5237]
**Description**: 
In the last bridge of Maraudon, before the Princess final boss, there is a patrol of 1 Theradrim Guardian and a few Theradrim Shardlings.

This patrol's route crosses a zoning border.

This can somehow cause some-but-not-all of the patrol's members to get stuck on an unloaded zone, and if the "loaded part" of this patrol is pulled, the party will be permanently stuck in combat with "unloaded part" of the patrol until they zone they're in gets loaded. The act of doing so is extremely problematic for the party's survivability however, as this will cause them to also pull TONS of mobs on their way there.

WORKAROUND: Do not pull this patrol until you progress enough that the next zone is loaded.

Video of this issue:
https://youtu.be/mXdWOb-luz8?t=86
Patrol is pulled at 1:30
Patrol dies at 1:57, see how the party is stuck in combat before, during, and after the next pull
At 3:05 (or a few seconds earlier), the next zone is loaded and we are immediately greeted to the one single Theradrim Shardling that became separated from the rest of the patrol, leading an army of giants towards us

**Current behaviour**:
Stuck in combat because this shardlet 300 yards away is in an unloaded zone, take a little step closer and WHOOPS HALF THE DUNGEON IS RUNNING TOWARDS ME WITH THE SHARDLET IN THE LEAD

**Expected behaviour**: 
Shardlet does not become separated from the rest of the patrol ever

**Server Revision**: 
2831

**Comment by Imperator522** [comment]
Can confirm that our group got stuck last month due to the same thing - minus the unloaded zone part. For us, the shardling was hidden in the floor and stuck.

To work around permanent combat, we committed suicide by pulling the two giants and letting them kill us. We then popped a Soul stone and resurrected the group.

**Comment by DaedalusMachina007** [comment]
I've run Maruadon at least 3 times (as of server revision 3084) and I have not ever encountered this issue.  We pull the giant stone guys and the patrols all at once and tank/kill everything fairly quickly.  This may either be already fixed or such an edge case if it does happen.

I watched the video and that hasn't happened anymore on any of my runs since then.

On a side-note, that horribly-cluttered UI is not necessary for a simple lowbie dungeon run.  Makes it difficult to see what is going on.  Use the 'UI Size' slider in your settings to reduce the size of things until you can still read the text.

**Comment by The14me** [comment]
Rev.3483 not an issue anymore.
