### ISSUE TITLE
[Raid][SSC][NPC] Leotheras the Blind Chaos Blast debuff not working

### ISSUE THREAD

**Issue by adrenochrom** [Atlantiss/NetherwingBugtracker#5316]
**Description**: 
The "Chaos Blast"debuff from Leotheras is not working correctly

**Current behaviour**:
The Chaos Blast itself does damage.
The debuff "increases fire damage taken" is applied and stacking up.
But Fire damage is NOT increased with each stack.

**Expected behaviour**: 
Chaos Blast : Leotheras' only attack in this phase, centered on his current target.
2 sec cast
150 fire damage AoE
Applies a 45 sec debuff which increases fire damage taken by 1675 and can stack up to 20 times

**Server Revision**: 
2868

**Comment by Wolffenstein** [comment]
Fixed

**Comment by Mikik3jr** [comment]
I want to reopen, because it does not work in 2893 revision. On this picture you can see a fire mage without any fire resistance gear surviving 11 shots without any trouble. It was dealing constant 150 dmg all the time.
![WoWScrnShot_031819_212850](https://user-images.githubusercontent.com/43505031/54673161-fc32a380-4af9-11e9-8e2c-d30e57ac1ce3.jpg)

**Comment by Wolffenstein** [comment]
Fixed
