### ISSUE TITLE
[Quest][Blade's Edge Mountains] Whispers of the Raven God

### ISSUE THREAD

**Issue by dmpepper** [Atlantiss/NetherwingBugtracker#5361]
**Description**: 

The quest is a part of a 2 part chain. In the first quest "Creating the Pendant" (https://wow.gamepedia.com/Creating_the_Pendant) you create a [Harbinger's Pendant] (https://wow.gamepedia.com/Harbinger%27s_Pendant) required to the follow-up quest "Whispers of the Raven God" (https://wow.gamepedia.com/Whispers_of_the_Raven_God). However, if you destroy the [Harbinger's Pendant] or abandon the quest "Whispers of the Raven God", there is no way to obtain the Pendant again, making the follow up quest impossible to complete.

**Current behaviour**:

If you drop a quest requiring a quest item or delete said item you should be able to reobtain it after picking up the quest again.

**Expected behaviour**: 

Item is not received again, making the quest impossible to complete.

**Server Revision**: 

2883

**Comment by veekk** [comment]
You can get mats from mobs again, resummon bird and get this pendant again, even if u're on the second quest of the chain

**Comment by dmpepper** [comment]
> You can get mats from mobs again, resummon bird and get this pendant again, even if u're on the second quest of the chain

I thied this, killed every eligible mob in the area for an hour - no drop.

Also partied up with other players on the same quest, they received the drops while I did not.

**Comment by devo6969** [comment]
You're not suppose to have Harbinger's Pendant for the next quest, its legit only to complete the 1st part of the quest. Think you are misunderstanding the 2nd part "Whispers of the Raven God". You have to kill the NPC's to obtain a 2 min buff and you go around the totems in the area to complete the quest.  The text "Using the Harbinger's pendant" isn't implying "you" need to have it, It's for "lore" purposes. 

On the PTR now, when you complete "Creating the Pendant", the quest item "Harbinger's pendant disappears. This is to avoid this confusion. :) Did the 2nd part just fine as well. Will note, it is an awful quest-line because the buff is hard to get and lasts for 2 minutes, so you are rushing to the totems.

Quest text:
"Using the Harbinger's pendant, we can understand it. You will be able to take the souls of the arakkoa to understand their lanuage. While you are suffused with the arakkoa's spirit, you can visit the totems and understand their message."
