### ISSUE TITLE
[Class][Ability][Priest]Priest defensive dispell is only removing 1 debuff

### ISSUE THREAD

**Issue by gabbat** [Atlantiss/NetherwingBugtracker#5372]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Priest defensive dispell (rank2) is only removing 1 debuff instead of two on a friendly target in PVE. This bug is NOT related to any pvp related dispell resistance mechaincs. It does however remove a stack of 2+ debuffs correctly, just not when you have debuffs that dont stack

**Current behaviour**: Priest defensive dispell (rank2) is only removing 1 debuff instead of two n a friendly target. 

**Expected behaviour**: Priest defensive dispell (rank2) is removing 2 debuffs on a friendly target at all times in pve.

**Server Revision**: 2883

**Comment by Wolffenstein** [comment]
Which debuffs did you try?

**Comment by Esploye** [comment]
I've seen this bug aswell for example in Mechanar the Sunseeker Astromage casts an ability called Solarburn that leaves a dot on the target and if there's 2 of that same debuff from 2 different Astromages it will only dispell one at a time. Same happens in karazhan with offensive dispell on the trash going up the stairs towards moroes that have some kind of heal over time buff that they get and if you try to dispel them instead of removing 2 by 2 you will only remove them 1 by 1. Both of these i tried it multiple times.

Seems like when a target has 2 of the same buff/debuff applied from 2 different sources if it has the same name it will only dispel it one at a time.

**Comment by gabbat** [comment]
e.g. the horror effect (pseudo fear) from the fen dudes in UB hc before the tunnel to the third boss, but this is a quite frequent bug tbh

**Comment by Kaini27** [comment]
probably all the magic debuffs in kara too, atleast most of them

**Comment by Anduyon** [comment]
This happens when there are 2 Debuffs on your target with the same spell ID.
Example of this would be the Magtheridon Trash where all 3 mobs cast a Shadow Word: Pain on everyone.
You are only able to dispell one at a time.

**Comment by gabbat** [comment]
still not fixed. please fix priest offensive dispell
