### ISSUE TITLE
Hunter's spells scale from bonus spell damage

### ISSUE THREAD

**Issue by Dusyagonemad** [Atlantiss/NetherwingBugtracker#5481]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Hunter's spells scales with bonus spell damage, but they should depends only on range attack power.

**Current behaviour**:
For example Serpent sting with +115 bonus spell damage/+200 attack power adal buff:
![WoWScrnShot_032719_150200](https://user-images.githubusercontent.com/43555289/55074954-bb5eff80-50a2-11e9-91fc-509b9e35ca01.jpg)

and without this buff:
![WoWScrnShot_032719_150204](https://user-images.githubusercontent.com/43555289/55074967-c1ed7700-50a2-11e9-8221-1d49c50d0394.jpg)

It should take only 0.02 RAP per tick (+4 damage per tick).
But it takes +20% spell damage per tick.

Explosive trap scales too.

**Expected behaviour**: 
Those abilities should not scale with spell damage.

**Server Revision**: 
2908

**Comment by Tenoutoften** [comment]
As absurd as it sounds, do you have any proof that it shouldn't scale with spell damage?

**Comment by Tenoutoften** [comment]
From https://wow.gamepedia.com/Serpent_Sting
* The Burning Crusade Patch 2.3.0 (2007-11-13): Now scales with ranged attack power instead of spell damage. It was considered to be a nature-spell-damage based attack thus was buffed by all nature and general spell-damage buffs including but not limited to:  [Wizard Oil],  [Improved Divine Spirit],  [Wrath of Air Totem]. This is no longer the case. 

Directly from https://wow.gamepedia.com/Patch_2.3.0
* [Serpent Sting]: The total damage dealt by this sting is now also increased by 10% of your ranged attack power.

Fair to say it shouldn't scale with spell damage since the server goes by 2.4.3 mechanics and this change was done prior that.

**Comment by Wolffenstein** [comment]
Fixed in rev 2933.
