### ISSUE TITLE
Fix the completely messed up arenas please

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#5504]
**Current behaviour**:
1) you tried to implement a wotlk mmr system in a tbc client
2) it was bugged and allowed people to very easily exploit the system by simply spamming games with 50-50 win ratio and gaining a fuck ton of rating
3) people complained that the system makes no sense so you claimed that you did some changes to the mmr and that it should be better now
4) as a result of this, people that were never even close to 2400 are 2900 mmr and are feeding actual teams free rating
5) people are now 2700 rated thanks to that

**Expected behaviour**: 
1) disable this absolutely retarded and failed joke of an mmr system
2) reset all teams to 1500 rating
3) Instead of +15 -15 on same team rating make it +15 -13 or something simmilar (so the system generates rating by itself, but not a lot of it)
4) profit

1+2 have to be done as soon as possible .... it's been fucked up for way too long and honestly if Evolve had time to play 1 day of arenas in this "perfectly working mmr system" he'd make sure that it's gone within hours

**Server Revision**: 2909

On behalf of everyone that enjoys healthy competition

Thanks

**Comment by Schaka** [comment]
I still stnad by everything I've previously said about MMR. It's a great tool that prevents a lot of shit. Look at the Warmane Wrath ladder. 2.5k rating cap (basically). 

People have said, you don't lose MMR if you just leave the arena. This way, you only GAIN MMR. Your teamrating will slowly adjust to it over time (at 2.8k MMR 2k teamrating, you lose -2, because teamrating is "trying" to get closer to your actual rating).

People have also reported, that when mixing players of different MMRs, it seems MMR isn't given to each player individually, rather both receive an average - this would also inflate the rating. A 1500 and a 2500 would average at 2k. They face teams at 2k. A win will reward +24 for the 1500 (cap, iirc) and like +4 for the 2500 or so. Instead, they both get the average of +10 (or so). 

I don't know how much of that is true, since a lot of it is hard to check without any tools - so I'm just going by user reports. 

For all I care, they can remove MMR in S2. But I 100% foresee that you guys will be crying like little bitches after a while. You won't get a lot of points from flushes anymore and PvE heros will outgear you heavily. Then low shitters will quit, because rating requirements for gear seem unachievable altogether. Then you won't have anyone to farm rating off anymore except each other - but everytime someone remakes a team you get -30 and within 2 months the arena scene will be more dead than on Outland.

**Comment by teddys** [comment]
I think people wouldn't mind the mmr had it been 100% bugfree, but that was never the case and look what kind of mess it caused (you can't because there's no armory xD)

**Comment by ircfelix** [comment]
It has been reported now and you can stop shitting around. Do you think it motivates devs to actually do something for free for people who show no respect for their work? Whenever there is a server restart or bug fix, negative comments are the first reaction, instead of showing gratitude for this free and high quality server.

**Comment by teddys** [comment]
I am sorry m8, I was a pre alpha tester here for 18 months, what have you done other than judge me in your comment?

**Comment by ircfelix** [comment]
It was not against you or your report but the tone in here.
