### ISSUE TITLE
All honor items have the wrong price

### ISSUE THREAD

**Issue by bajkorv** [Atlantiss/NetherwingBugtracker#5505]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in 

Description: Currently the Pendant of Triumph and Dominance cost too much honor in comparison to other items. Every item looks like honor cost has been reduced, except for necklaces which looks like theyve increased in pricing for some reason?
Please dont close this thread without doing something, third thread about same thing and its just getting closed

Current behaviour: Necklace costs 2.5x any other part atm, at 22950 honor (450 honor too much) while other items cost 5-10k honor too little

Expected behaviour: Necklace should cost 22500 honor in patch 2.1 - High Warlord weapons (70)  cost 15300 atm, very very fishy, as it should be higher than that.

Server Revision: 2909

**Comment by bajkorv** [comment]
Change title to ”All honor items have the wrong price” as pvp is too wide and they will just close the ticket without adressing it at all

**Comment by wtRCH** [comment]
> Change title to ”All honor items have the wrong price” as pvp is too broad.**
> Cant do it manually

Changed

**Comment by Zarant** [comment]
Just to give an idea of what is going on here:

2 handed/ranged weapons: http://web.archive.org/web/20070823175713/http://www.thottbot.com/i28933 
30000 honor pre 2.1, 20400 honor post 2.1.

1 handed weapons: http://web.archive.org/web/20070516045653/http://www.thottbot.com/i28937 
20400 honor pre 2.1, 15300 honor post 2.1

Belt/Boots: http://web.archive.org/web/20071016082330/http://thottbot.com/i28995
 21000 pre 2.1 14280 post 2.1

And the trend continues to pretty much all honor items. S1 items in 2.0 were approximately 1.47 times more expensive than they are right now. The main issue here is the lack of consistency, pvp necklaces and 2 handed weapons are close to their 2.0 values while everything else is post 2.1.

This also raises a question of fairness, since a lot of people are done with the honor grind, and changing the costs at this point is just adding an extra hurdle for people that are just starting their pvp grind.
