### ISSUE TITLE
[QUESTS] Trial of the Sea Lion + Aquatic Form (Horde)

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#5524]
**Description**: 
Quests to give Aquatic Form for Druids

**Current behaviour**:
Gives no experience upon turn-in for either, just 300 and 500 Cenarion rep respectively, not sure if it's the same for Alliance

**Expected behaviour**: 
Should give experience. shows 875xp in this video for first one (@ 3:52), and 1150xp for second quest (@ 4:00)
https://www.youtube.com/watch?v=VW6Rm7XVLEM

**Server Revision**: 
2915

**Comment by duzyizly** [comment]
tested on ptr rev 3404 as clvl 18:

part 1: lesson to learn https://classic.wowhead.com/quest=27/a-lesson-to-learn.
**gives 10 XP** (as x1 exp mod), due to classic DB should be 120..

part 2:  trial of the lake https://classic.wowhead.com/quest=28/trial-of-the-lake#see-also
**gives 0 XP**, due to classic DB it's 880.
also gives 300 rep with cenarion cirsle, due to DB - it's 75.

part 3: trial of the sea lion https://classic.wowhead.com/quest=30/trial-of-the-sea-lion
**gives 0 XP**, due to DB it's 880.
also gives 300 rep with cenarion cirsle, due to classic DB - it's 75.

part 4: aquatic form https://classic.wowhead.com/quest=31/aquatic-form
**gives 0 XP**, due to DB it's 1150.
also gives 500 rep with cenarion circle, due to classic DB it's 100.

**Comment by Wolffenstein** [comment]
Fixed in rev 3405. (more or less, classic DB isn't 100% accurate when it comes to XP)
