### ISSUE TITLE
herbs spots 

### ISSUE THREAD

**Issue by fruvel** [Atlantiss/NetherwingBugtracker#5562]
**Description**: 
 Herb nodes seem to have very long respawn times or are just not spawning at all. At least in the few zones I've run through. That being barrens, silverpine forest, stranglethorn vale, ashenvale, tanaris. Perhaps all nodes? When I timed it, it took me 8 minutes to find another herb in barrens after finding one. Seems a bit off.

**Current behaviour**:
ALL vanilla herbs have problem with spawn, today i went from rebel camp to booty bay i find only one kingsblood, 0 goldthorn 0 whisker's , this is not one issue with herbs, sometimes i spent 2h for farming herbs and i get only 2 stacks, please if u can do with this something it will be cool for gameplay.

what numer of herbs on map must be, but from respawn to respawn, i dont know what number of herbs must be in duskwood or stranglethorn, i quess that herbs have their optional number in specific zone.

vanilla herbs goldthorn - https://vanilla-twinhead.twinstar.cz/?object=2046
bruiseweed https://vanilla-twinhead.twinstar.cz/?object=1622 or any other herb have low respawn and i quess that on map where must be 20 herbs or 40 displayed is 10 or 5 herbs that is a very annoying me and other players- hard to skill alchemy, herbalism and for 4500 ppl on the server if in one zone will be like 300, where 100 have herbalism... so tell me what now ?
**Expected behaviour**: 
in zones must be more herbs and they must have better spawn time

**Server Revision**: 
2930

**Comment by fruvel** [comment]
some stranglekelp is too far away from land, in the sea

**Comment by ircfelix** [comment]
Leveled herbalism to 375 twice, had no problems. Maybe you are looking the wrong places/time.

**Comment by markus048** [comment]
> Leveled herbalism to 375 twice, had no problems. Maybe you are looking the wrong places/time.

This problem showed up like few weeks ago

**Comment by ircfelix** [comment]
Try blood elf or draenei Starter zones

**Comment by Godmatik** [comment]
I think it is a known issue that some vanilla zones have a very low spawn rate. Barrens in particular was bad for me, Silverpine was fine though.

**Comment by ScottieDOESknow** [comment]
Bumping this thread

23:50 Server time looted 4 Ghost Mushroom nodes @ Skulk Rock cave in Hinterlands

waited 60 minutes and no other Ghost Mushroom nodes have spawned OR re-spawned

**Comment by ScottieDOESknow** [comment]
> They respawn one random spots (your cave or elsewhere) and if in 100 min no one else will pick ghost mushrooms, none will respawn in your cave.

Do you have a source for this claim?

**Comment by ScottieDOESknow** [comment]
All the comments shown below indicate that NW has incorrect spawn times for Ghost Mushroom.

![image](https://user-images.githubusercontent.com/43949261/55816641-c6f9ef80-5ac0-11e9-992a-1d1af212297c.png)

![image](https://user-images.githubusercontent.com/43949261/55816656-d0835780-5ac0-11e9-9de0-5cc281169b0d.png)

![image](https://user-images.githubusercontent.com/43949261/55816665-d7aa6580-5ac0-11e9-8acf-3624cfde67d6.png)

![image](https://user-images.githubusercontent.com/43949261/55816677-df6a0a00-5ac0-11e9-85de-fb367a3d0ee8.png)

![image](https://user-images.githubusercontent.com/43949261/55816696-ed1f8f80-5ac0-11e9-8b5c-a070609141e2.png)

![image](https://user-images.githubusercontent.com/43949261/55816706-f27cda00-5ac0-11e9-932c-2c8ebae244bc.png)

![image](https://user-images.githubusercontent.com/43949261/55816719-fa3c7e80-5ac0-11e9-9dbb-decc1ef0dd97.png)

My personal experience (since 2005) mirrors all comments above. Spawns times are incorrect.

**Comment by niedro** [comment]
Tried to level herbalsim, did 3 full rounds of nothern barrens without seing a single herb spawn.
Something is really wrong with it and it should be fixed.

After a full round in Silverpine with 1 Silverleaf spawn, i stopped herbalism for now

**Comment by Godmatik** [comment]
Niedro what worked for me - herb a starting zone up to 75 on silverleaf, peacebloom, and earthroot. Mulgore works best.

Don't bother with Barrens, waste of time. Go to Silverpine after 75, and only look at southern half of it, tons of briarthorn and mageroyal spawning constantly. Use all of those to get up to 125. Once you are there, you can do Bruisweed, wild steelbloom, and kingsblood - after this point I have had no issues at all with later herb leveling.

**Comment by ircfelix** [comment]
> > They respawn one random spots (your cave or elsewhere) and if in 100 min no one else will pick ghost mushrooms, none will respawn in your cave.
> 
> Do you have a source for this claim?

If I understood the devs in the past correctly, herbs should have a pooling behavior, which might be the reason why sitting still and waiting doesn't work unless someone else also herbs in that zone.

**Comment by ScottieDOESknow** [comment]
> herbs should have a pooling behavior, which might be the reason why sitting still and waiting doesn't work unless someone else also herbs in that zone.

The problem with that argument, is not all herbs are behaving like this. There are very inconsistent behaviors with herbs across the board. Some have the correct spawn time while others simply do not. Some herb nodes are reduced compared to retail (Dire Maul) Some herbs aren't even available where they should be (Ghost Mushroom in Maraudon) and some herbs have incorrect spawns and even other herbs spawning on the node, such as Goldthorn instead of Fadelaf in SM.

One lap and they ALL respawn (Searing Gorge) when zone was emtpy (I was the only person there)
![image](https://user-images.githubusercontent.com/43949261/55900554-70121a00-5b95-11e9-8a2e-66b799b93ec7.png)

I really wish these issues with nodes could have been sorted out on the beta where we could have tested it BUT Pyralis apparently didn't work on nodes until the last minute before live launch. There are enough people raising concern about these problems and it should really be addressed since many of these herbs are still used for progression. Come BT the Elixir of Demonslaying is BiS buff for all physical classes, which require Ghost Mushroom to create. Currently farming them as per retail experience is not even close to how it should be.

**Comment by markus048** [comment]
> Leveled herbalism to 375 twice, had no problems. Maybe you are looking the wrong places/time.

what do you mean wrong time\place, goddamit peacebloom have 1 min respawn time, and spawning everywhere

**Comment by ircfelix** [comment]
Try blood elf starter zone

**Comment by Tereneckla** [comment]
rev 3205
