### ISSUE TITLE
[Quest][Deadwind Pass] Digging up the Past

### ISSUE THREAD

**Issue by trubz** [Atlantiss/NetherwingBugtracker#5568]
Unable to interact and loot the charred bone fragment need to progress in the Nightbane urn summon quest chain. I was unable to interact after deleting my cache and disabling add-ons in addition to restarting my client as directing from daystar from the netherwing discord!

**Comment by danbopes** [comment]
**Description**: 
Quest: [Digging up the past](https://tbc-twinhead.twinstar.cz/?quest=9680). Charred bone fragment is not intractable.

**Current behavior**:
Navigated to bone fragment (Near Karazhan), and attempted to gather. The bone fragment was not interactable. Could not complete quest.

**Expected behaviour**: 
Bone fragment should be interactable, and should loot [Charred Bone Fragment](https://tbc-twinhead.twinstar.cz/?item=24152).

**Server Revision**: 
2930

**Comment by Jalapan** [comment]
You cant loot it while in a Raid, leave your raid and its fine.

**Comment by trubz** [comment]
can confirm this was my fuck up . no issue at hand
