### ISSUE TITLE
[Item][Debuff] Annihilator

### ISSUE THREAD

**Issue by Wahrheit42** [Atlantiss/NetherwingBugtracker#5619]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![Annihilator](https://user-images.githubusercontent.com/49454234/55827698-0e0cd280-5b0b-11e9-91f7-65a99ea1b9ca.PNG)
**Current behaviour**:
Item isn´t working as intended
The debuff doesn´t work as intended.
The debuff doesnt stack with similar debuffs
**Expected behaviour**: 
Debuff should stack with other armer reducing debuffs
**Server Revision**: 
2930

**Comment by Anselm123** [comment]
they broke it to make the server "feel more blizzlike"

**Comment by Valmere** [comment]
no, blizzlike is letting the item work. they broke it to make stuff artificially harder, same reason half the raid bosses have nearly 50% more hp.

**Comment by towneh** [comment]
"50% more hp" are the original values from 2.0 (pre-March '07 hot-fix patches).

There is an existing issue thread open for this btw https://github.com/Atlantiss/NetherwingBugtracker/issues/4728

**Comment by Tenoutoften** [comment]
@towneh They are veritably not using Blizzlike health values and this is something they are well aware and proud of, nothing they keep secret.
https://github.com/Schaka/TBC-research/issues/10

**Comment by Easyfraggy** [comment]
Show ANY video of annihilator being used in a raid.

**Comment by gabbat** [comment]
> Show ANY video of annihilator being used in a raid.

are you arguing it never worked in vanilla since you cant find a video of it working? just asking to understand why this issue isnt getting fixed

**Comment by Easyfraggy** [comment]
No I'm asking you to show any raid video where it's being used in TBC. You can't.

**Comment by Anselm123** [comment]
That logic is so backwards it hurts. People can come to ideas in the future, like how people now play feral druids in vanilla now yet didn't due to a lack of ideas back in 2004. People can come up with new ideas using old mechanics or implementing new ideas into how to play an older game. Your constant moving of goalposts to justify having things the way you want them is sad.

**Comment by Anselm123** [comment]
Punishing people for that due to people in the past not doing so is dumb.

**Comment by Anselm123** [comment]
That's like telling off people for using antibiotics for an known infection of 300 years because "well they didn't back when they found it"

**Comment by Easyfraggy** [comment]
I can mention about 100 things that would be super OP that noone knew about in TBC that got bugfixed before people realized. You also want the broken LC+Meta arcane mage implemented?

**Comment by Easyfraggy** [comment]
> That's like telling off people for using antibiotics for an known infection of 300 years because "well they didn't back when they found it"

If you were trying to reenact the period of that disease then no you wouldn't use antibiotics in that case.

**Comment by Anselm123** [comment]
Your logic is so backwards mate...

**Comment by Anselm123** [comment]
Going by the same logic: Do you have any videos of anyone doing "pure" 2.0 health values you've pulled from your arse? They are super broken and no one did them in TBC. Why does this magic rule only apply to features we discover to help us and not hinder us? WHy are you so hell bent on making TBC way harder than it actually was?

**Comment by Easyfraggy** [comment]
Did you raid SSC/TK in 2.0? If no - how do you know it's harder?

**Comment by Anselm123** [comment]
I did yes. also you can go look at videos of top guilds doing bosses with near half the Hp values you've added on to here.

**Comment by Easyfraggy** [comment]
> I did yes. also you can go look at videos of top guilds doing bosses with near half the Hp values you've added on to here.

I remain skeptical.

Theres not a single boss with twice the HP. 30% more sure. Only maggy adds have almost double but thats a prenerf thing. They had even more in the very first version.

In those same videos you also have the top DPS'ers doing 800-900 dps average being somewhere around 600-700. That's not the amount done here on NW in patch 2.4.3. The highest dpsers are doing 1500+ or more.

The first vashj kill on retail had 4 seconds left on hard enrage. On NW 18 seconds - I think we hit the mark pretty well.

**Comment by Anselm123** [comment]
https://cdn.discordapp.com/attachments/353532497973346315/571240043965054976/unknown.png

**Comment by Anselm123** [comment]
Hydross has 6.3 million HP here.

**Comment by Anselm123** [comment]
By your reasoning mate: if no one did them with those "pure" hp values then they shouldn't be allowed. It's only fair right? I mean you said yourself that you want to reenact the expansion

**Comment by Anselm123** [comment]
If people are doing more because we're better at the game and learnt how to play then surely that shouldn't be allowed because we are only allowed to do that and use that which was used in 2.0?

**Comment by Anselm123** [comment]
This fallacy of making the content as hard as it was for players back in 2.0 12 years ago for today's player with 12 years more of experience and knowledge of how to play is stupid. You're literally punishing people for learning to play the game better than people did way back. If you want harder content that's fine, but be honest about it and don't cloak it with a guise of using "real 2.0 values" when you state yourself that you are buffing bosses to fit in with some idealised perception of how hard things used to be for people and translating that into balance changes for now. You can't say "this wasn't used in 2.0 so you can't have it" for a thing and then say "we buffed content to make it harder because people do this thing to make a fight harder than it was for people in 2.0", it's backwards logic.

**Comment by Easyfraggy** [comment]
You do realize that if we used blizzard values everything would die day1. You'd maybe wipe once or twice on vashj. Hydross HP is high for sure but its not double - far from it even. double would be 7.2m.

Most of the hp changes are to mimic the fight lengths of retail and we've done that surprisingly well for the most part.

Let me ask you this - why do you raid if you don't want a challenge?

**Comment by Anselm123** [comment]
There's a difference though. People have played this game for so long that ofc they can slog things over day one. You promised blizzlike values and now you use fun server scaling. Again, This is fine if you're open and honest about it which you haven't been. 

For me the challenge isn't the bosses and it never was. The challenge of older wow is always the organisation and dynamics that come with that. Over tuning a boss to satisfy some nostalgic fantasy of perception of difficulty is intellectually dishonest. Hydross had 3.6 million Hp and so on. This is blizzlike, not the feeling of how hard people felt it was when we were shitters back 12 year ago.

Inflating these doesn't make it challenging it makes it punishing, there's a difference. It's not difficult to do the DPS requirements but it does require you to basically class stack to achieve them, for which most middling guilds don't have access to 5-6 shamans and warlocks a raid to meet your inflated dps requirements or bugged mechanics. Inplying that I don't like a challenge is a strawmanning of my points. You have been dishonest in your approach to the server and have used this guise of "blizzlike 2.0" to create something that is there to satisfy your need for a harder version of something that never existed but in your brain of some vision of the past that is blurred by your anecdotal experiences.

**Comment by Easyfraggy** [comment]
Theres no "blizzlike" when doing 2.0 content on patch 2.4.3. Just like playing vanilla servers on 1.12 is really not "blizzlike" at all either. That term is so bastardized - it used to just mean 1x rates and no new bosses/instances/content. Didn't have anything to do with tuning.

Only vashj and magtheridon adds hp values weren't already shown on the beta btw. It was known to be Corecraft values long before server launched - just because it wasn't in an official post doesn't mean it wasn't known. I'm not in charge of the server - I'm not really a part of the team so to speak so I didn't have much say in what would be in such official posts. Theres not a single server using blizzards values btw - even gummy was completely custom and he handpicked so many changes from different patches.

**Comment by Anselm123** [comment]
Then how can you justify other changed based on the grounds of it being "2.0" if you yourself say that it doesn't mean anything. You can't use one argument for one thing and then turn around not apply it to another facet. 

Your constant moving of the goal posts with vague reasoning and demanding evidence for things while also not applying the same rules to yourself is exhausting. The absence of evidence is not the evidence of absence. You as a team prided yourself (and was told personally in beta) that everything was based on fact not feeling, yet it's shown that you use "feelings" as a justification for the values you use. It's just straight up lying at this point by still using the veil of "blizzlike 2.0".

**Comment by wtRCH** [comment]
It is not forum. Closing.
