### ISSUE TITLE
Perception not working as intended 

### ISSUE THREAD

**Issue by nicolaj1991** [Atlantiss/NetherwingBugtracker#5630]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Perception is not working as it should, im a warlock with the detect invisability up and the passive fel hunter buff who also provides stealth detection.
**Current behaviour**:
when using perception i dont even see stealth classes in arena atleast. they shouldnt be able to sap or open on me without being seen by me with perception up. 
**Expected behaviour**: 
the expected behaviour is that i would be able to see stealth classes way before they get close to me like if i stand in the middle of nagrand arena i should be able to see a stealth class close to one of the four pillars.
**Server Revision**:

**Comment by Drayo** [comment]
Detect Invisibility does not increase stealth detection.

**Comment by ScottieDOESknow** [comment]
If a level 70 Rogue uses max rank Vanish (+370 stealth) you wouldn't be able to see them even
if you had Perception (+50 detect) and Paranoia (+30 detect) up simultaneously. Pre-vanish is a common tactic used in PvP in order to almost guarantee an opener regardless of an opponents stealth detection.

**Comment by nicolaj1991** [comment]
It has nothing to do with vanish it is when the arena Opens and they are in “normal” stealth

**Comment by ScottieDOESknow** [comment]
If you know for a fact they aren't using pre-vanish (combat log, etc) then the reason you don't see them is likely stealth detection range and/or the rogue playing cautious because they are aware you have Paranoia + Perception. It's also rather easy to Shadowstep + Sap without being detected. You could test detection range vs rogue in normal stealth using a duel or at either arena in Nagrand & BEM.

**Comment by Wolffenstein** [comment]
Check again after rev 2939.
