### ISSUE TITLE
Arcane Torrent vs Scalewing Serpent Ligtning Strike

### ISSUE THREAD

**Issue by hxlich** [Atlantiss/NetherwingBugtracker#5669]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Bloodelf Arcane Torrent cannot silence LightningStrike from ([NPC]Scalewing Serpent), not sure it is a bug, but Arcane Torrent can silence Lightning Strike from other npc
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Tenoutoften** [comment]
As stupid as it sound, are you sure you stood close enough?

**Comment by hxlich** [comment]
I play a protein paladin, so it is auto attacking range. I test multiple
time as well.

**Comment by Easyfraggy** [comment]
Pet Lightning Strike is not the same as NPC lightning strike - are you sure that it should be silenceable? Spell data is rarely wrong.

**Comment by devo6969** [comment]
https://www.wowhead.com/npc=20749/scalewing-serpent#comments
"Technically it's not "quite" a spell.... It's an innate ability of the pet species, like claw is for cats. Even though the damage is nature rather than physical, it cannot be interrupted because it is absolutely instant"
"Silencing shot doesn't work either"
"GM said that the spell was working correctly. Seems really odd for a spell from some regular mob to be irresistable and uninterruptable (by Kick, at least)."
