### ISSUE TITLE
Quest: Tree's Company

### ISSUE THREAD

**Issue by AlteredAli** [Atlantiss/NetherwingBugtracker#567]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Even after completing the quest, you cant turn it in.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
2050

**Comment by AlteredAli** [comment]
Update: When standing a little far away from the naga flag, the quest wont complete after the dialogue

**Comment by craigsurbrook** [comment]
Reaffirmed Sep. 28th 2018

[Current Behavior]
You turn into a tree and can watch the dialogue but the quest does not complete (uncovering the traitor). Unfortunately, this truncates the quest chain.

[Expected Behavior]
You watch the speech between the Gnome and the Goblin and then get a notification that you have uncovered the traitor.

**Comment by craigsurbrook** [comment]
UPDATE on error for Tree's Company.

Even though you use the mask near the tree, and it does not say that the quest is complete, when you return to the quest giver it is marked as complete, **so the actual bug here is that you don't get the "quest completed" notification in yellow, indicating that you succeeded.**

**Comment by Gniddikon** [comment]
As of December 9th quest is still bugged and does not complete :(

**Comment by Gniddikon** [comment]
I want to add, that apparently the range for the quest to complete is quite narrow. When I used to disguise right on top of the flag, it completed.

**Comment by Tenoutoften** [comment]
I was able to turn this in just fine

**Comment by Evolvee** [comment]
rev 2538
