### ISSUE TITLE
[Zone] Hellfire PvP Objective allows capping while mounted

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#5725]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
While capping the Overlook, Stadium, or Broken Hill in Hellfire Plateau, you are able to capture the objectives while mounted. This is not correct.

This applies to all zone-based PvP objectives, such as the towers in EPL. This issue may involve those as well.

**Current behaviour**:
Mounting does not stop the capture process.

**Expected behaviour**: 
A mounted player should not participate in the capture process.

**Server Revision**: 
2950

**Comment by Tenoutoften** [comment]
Proof? I thought you should be able to cap on mount, the exception being if you are in the air on a flying mount

**Comment by Evolvee** [comment]
i think its also the case for EoS

but i didnt have time to research it so i never went ahead with it

**Comment by KevinTyrrell** [comment]
I had a friend logon retail and he informed me the bar moved while he was on a ground or flying mount. However the bar disappears if he goes airborne on the flying mount.

I'm astounded that's the case, because in any video from 2007-08 I look up, people are dismounted while waiting for the objective to cap. 99% of Netherwing players are mounted while capturing it, because that's the smart thing to do. However I don't think Blizzard ever changed that mechanic, so it must be that way.

**Comment by Tenoutoften** [comment]
my memory is truly remarkable...

**Comment by Evolvee** [comment]
this got changed with wotlk afaik thats why u cant test this on retail

**Comment by KevinTyrrell** [comment]
> this got changed with wotlk afaik thats why u cant test this on retail

Ah in that case then I guess this is still on the table. I searched through maybe two dozen videos of Eye of the Storm and Hellfire PvP videos. It's hard to find evidence though because sometimes it's unclear if the mounted player is assisting the capture, or if another player is. If the capture bar doesn't move, there may be a horde off screen which is stopping the capture. So you'd basically need to find a clip of a mounted player in a capture area standing there for a few seconds with no one else around him.

**Comment by Evolvee** [comment]
i reported this like 6 years ago on different servers, it was talked about  but i dont remember the outcome now

**Comment by jcdenton2k** [comment]
I was a retail player here on Tichondrius back in around TBC timeframe (pre-Black Temple patch) and when World PvP was still a thing.  You can 'cap the objective' while mounted on the ground.  You cannot do so while flying (for obvious reasons).

I don't believe opening an issue based on 'memory' is going to do much good.  As 'WoW Classic' feedback has shown, even the 'hardcore' Vanilla veterans don't remember certain specific things clearly enough and end up reporting it as a 'bug' when it actually worked properly like that in Classic.

For TBC, the main reason you may remember players dismounted near specific objectives is if they are interacting with specific items (or just crafting bandages while they wait, that was a popular thing to do).  Certain objectives in HellFire peninsula in particular had an 'interact' node near the flag at that time.  It was later removed when Black Temple dropped and World PvP took a nosedive due to everyone raiding instead.  ;)
