### ISSUE TITLE
Rain too common and in wrong zones.

### ISSUE THREAD

**Issue by leeviathan** [Atlantiss/NetherwingBugtracker#5754]
**Current behaviour**: Rainy weather is too common, and it lasts a very long time. It's almost always raining in zones that have a chance of rain (e.g. Elwynn Forest), and even zones without a chance of rain (e.g. Tanaris, Dun Morogh #1016) rain occasionally. 

**Expected behaviour**: Rain should occur occasionally and last a short time in zones that have a chance to rain. 

**Server Revision**: 2952

**Comment by leeviathan** [comment]
I've also noticed it can be raining for one player and not raining for another, even if they are standing right next to each other.

**Comment by leeviathan** [comment]
Here's a screenshot of rain in Tanaris:
![WoWScrnShot_091419_103214](https://user-images.githubusercontent.com/8200787/64909533-7d4eaa00-d6db-11e9-9484-b1bf4a976e69.jpg)

**Comment by leeviathan** [comment]
BTW here it is raining 50 minutes later, hasn't stopped:
![WoWScrnShot_091419_111427](https://user-images.githubusercontent.com/8200787/64910123-85a9e380-d6e1-11e9-97e4-f02a340de8e3.jpg)

Again this even more prevalent in places that are meant to rain like Elwynn Forest (which I've only seen sunny once in all of my play time here btw), I'm just pointing out Tanaris because it highlights the buggy behavior especially

**Comment by G3dSage** [comment]
I second that. Rain is far too common in Elwynn forest and other zones where it may rain. Either a percentage chance rebalance is required or the RNG for the weather takes its numbers from very strange places

**Comment by G3dSage** [comment]
I seem to have solved the issue with rain being far too common and weather anomalies. Since weather calculations are done clientside mostly, there are a couple of ways you can go about this problem and fix it for yourself.
1. Clean out your "Cache" and "WTF" folders. You will have to relog again on your next login, and some options may default but the issue could resolve itself. If it doesn't, then:
2. Use another 2.4.3 client, there are multiple provided at the netherwing website. After installing the client just download the realmlist to be safe: https://download.atlantiss.eu/tbc/realmlist.wtf
 Also, clean out the cache and WTF again and you're good to go
