### ISSUE TITLE
[Exploitable] Orgrimmar Graveyard & Spawn Timers

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#5810]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:
Releasing spirit inside of Orgrimmar as Alliance does not teleport you to a graveyard.
Dying to NPCs inside of Orgrimmar does not yield a respawn timer. Dying to players does.

Using these two bugs in tandem can cause level 1 players to become immortal and walk through the city effortlessly.

I am not sure if this issue is just for alliance, just for orgrimmar, etc. It may connect with other parts of the game.

**Server Revision**: 
2967

**Comment by randomuser69** [comment]
According to reddit comment: "I saw that bug often. When the server can't find a graveyard for the zone/faction combination (as is often for enemy faction's cities, because nobody bothered to research/implement that) it just pops your ghost on top of your body.

Some servers just default to Barrens Crossroads graveyard instead. "

https://www.reddit.com/r/wowservers/comments/bv9rx6/orgrimmar_adventure_nearly_banned_from_netherwing

**Comment by danbopes** [comment]
It seems like this has been fixed per the changelog:

![](https://i.imgur.com/wnExkJV.png)

I still think it prudent to default a GY if one isn't connected/make a log entry so it can be corrected in the future.

**Comment by Wolffenstein** [comment]
Fixed in rev 2976.
