### ISSUE TITLE
The Matron Protectorate(Winterspring) Teleport

### ISSUE THREAD

**Issue by Badej** [Atlantiss/NetherwingBugtracker#5873]
**Description**: https://www.wowhead.com/quest=5160/the-matron-protectorate
Awbee in Upper Blackrock Spire giving u quest "The Matron Protectorate" and his scale "Awbbe's Scale which is usable at the Rune in cave to teleport you to Haleh(Quest end NPC)
https://imgur.com/a/qzPQ6oM (standing at rune, not working)
https://www.youtube.com/watch?v=eKltP1p3IMM
**Current behaviour**:
The rune not working at all
**Expected behaviour**: 
Rune should teleport You to Haleh
**Server Revision**: 
2995

**Comment by Manaci** [comment]
I did it [this](https://www.youtube.com/watch?v=uidnaJjIzH0) way, but yeah should get fixed.

**Comment by MisaHack** [comment]
@Manaci @Evolvee @duzyizly @Tereneckla - so #5873 is there for 1 year and you still did not fixed the problem?
Why is this still an issue 1 year later on this server?
It is obvious you know about it but no one wants to fix it?

**Comment by Evolvee** [comment]
Because noone except me gives a shit about fixing it and I didnt know about it until now.

**Comment by MisaHack** [comment]
@Evolvee - thank you for your answer, hope that it will be fixed soon. 
We are doing many quests in Classic WoW, so it is very strange that this bug is around for 1 year, and we also need it for Onyxia's Lair attunement that is really long and hard quest line and then we encounter this bug after all that hard work.

**Comment by Evolvee** [comment]
rev 3377
