### ISSUE TITLE
#1 Formula: Enchant Weapon - Greater Agility  #2 Formula: Enchant Gloves - Superior Agility

### ISSUE THREAD

**Issue by sneballe** [Atlantiss/NetherwingBugtracker#5893]
#1 Formula: Enchant Weapon - Greater Agility ( 20 agi one hand ) from Karazhan exalted was added in 2.0.3 allready and its not out

#2 Formula: Enchant Gloves - Superior Agility Should be out from keepers of time, its added in a later patch BUT since AQ is not out you are not able to get this formula.

https://wow.gamepedia.com/Formula:_Enchant_Weapon_-_Greater_Agility

**Comment by Manaci** [comment]
[2.2 Official Patch Notes](https://wowwiki.fandom.com/wiki/Patch_2.2.0#Enchanting) "[Formula: Enchant Weapon - Greater Agility]: This enchanting recipe is now available from the Violet Eye vendor. "

**Comment by kramnoitseuq** [comment]
Both Enchant Gloves - Superior Agility and Enchant Cloak - Subtlety IS in the game through AQ, but this server has this custom locked off for no reason. These formulas were added by Blizzard as rep rewards to Keepers of Time and Thrallmar/Honor Hold in 2.2, and that's exactly what you should do for 2.1, since going into T6 without 2% reduced threat on DPS and no threat enchant to gloves on tanks would be ridiculous.

**Comment by sneballe** [comment]
bump

**Comment by sneballe** [comment]
@Manaci not legit info there m8

**Comment by SwiftieTBC** [comment]
Both these recipes were added to their respective level 70 vendors in patch 2.2 and updated to their mats to be more tbc relevant. Before this they existed from AQ as drops but had vanilla mats.
from 2.2 patch notes
>  Formula: Enchant Gloves - Threat: This enchanting recipe is now available from the Sha'tar Quartermaster. The reagents required have been adjusted to match the level 70 content.
 Formula: Enchant Weapon - Greater Agility: This enchanting recipe is now available from the Violet Eye vendor.
>
