### ISSUE TITLE
if you die in ogrila zone you can get ghost in sylvanar, forsing you to take corpse

### ISSUE THREAD

**Issue by Dekirayne** [Atlantiss/NetherwingBugtracker#5911]
if you die in ogrila zone you can get ghost in sylvanar, forsing you to take corpse

**Comment by ScottieDOESknow** [comment]
Can confirm. Happened to me in February
![image](https://user-images.githubusercontent.com/43949261/59734612-2b9f9c00-9220-11e9-9229-08d9d036468d.png)

This only happens to Alliance because Horde players spawn at the graveyard up top.

**Comment by Evolvee** [comment]
where should u spawn?

also is it for both horde and alliance?

**Comment by ScottieDOESknow** [comment]
There is a graveyard by Ogri'la in the middle of that area (up top) where you should spawn. I'm guessing the reason why the game sends ghost alliance to Sylvanaar sometimes is due to it being closer than the middle graveyard, but game doesn't consider the area is only reachable with a flying mount, while alive.

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/6123

**Comment by Wolffenstein** [comment]
Fixed in rev 3078.

**Comment by The14me** [comment]
Its bugged again.
