### ISSUE TITLE
Resist is WAY off on this server

### ISSUE THREAD

**Issue by Sosari** [Atlantiss/NetherwingBugtracker#5920]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I was doing my quest for druid flight form to run into this scenario.

https://streamable.com/rtjse

Additionally, Players and NPCs are resisting WAY more then they should be. Not only are melee attacks being "resisted" in pvp, but is happening more than the so called 4% chance to miss vs players. 

**Current behaviour**:
Spells resisting 90% of the time?
**Expected behaviour**: 
Spells to have the correct % to resist.
**Server Revision**: 
3014

**Comment by mbzz88** [comment]
Isn't that the quest where you're meant to use specific forms? Eg. One of the mobs is vulnerable to melee, one is vulnerable to spells etc.

**Comment by ircfelix** [comment]
@Sosari please, go to elementary school again and learn to count, the resists are far from 90%. Also, some mobs have higher resistances (to some magic schools) than others, which is perfectly in line with how it should be.

Also, *guy fails at quest and blames the server administration for it.avi*

**Comment by Wookiefister** [comment]
Make some binds you fucking clicker

**Comment by Evolvee** [comment]
Dont waste our time by stupid bugreports. This mob has more than 300 resistance because of the quest you are doing, ofc you resist to it... jfc... 

Just because you are clueless and dont know anything about this game doesnt mean you have to make bugreports about it.

First, research the subject and THEN make a bugreport, not the other way around. We dont have time to teach you how to play.

![image](https://user-images.githubusercontent.com/1942409/59759810-2cbce180-9291-11e9-9139-7779b9154595.png)
