### ISSUE TITLE
[Spell][Hunter] Wind serpent pet skill - Lightning Breath

### ISSUE THREAD

**Issue by NatsumeLily** [Atlantiss/NetherwingBugtracker#5921]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Lightning breath scaling.

**Current behaviour**: Lightning breath isn't scaling with pets spell bonus.

**Expected behaviour**: Lightning breath should be scaling with pets spell bonus.

**Server Revision**: 3014

**Comment by gunzbngbng** [comment]
So should scorpid poison.  There was a fix implemented a while ago, but it failed to correct the problem.

**Comment by Dragunovka** [comment]
@Wolffenstein

**Comment by NatsumeLily** [comment]
Bump. Currently makes ravagers or cats the best pets without question.

https://www.engadget.com/2007/08/08/bigredkitty-the-whole-scorpid-thing/

```
LB_Damage = LB_Base_Damage + ( Spell_Power_Damage * 42.86% )

LB_Damage = LB_Base_Damage + ( RAP * 0.125 * 42.86% )

LB_Damage = 106 + ( RAP * 0.125 * 0.4286 )

Simplifed, it looks like:

LB_Damage = 106 + ( RAP * 0.053575 )
```

**Comment by NatsumeLily** [comment]
Bump.

**Comment by Manaci** [comment]
@Wolffenstein 

Did some more testing on this, seems like there is scaling atm but it's quite low. I went and tested it out with 0 dmg increasing talents to get 100% focus generation and my Wind Serpents' max damage non-crit was 148 dmg. 

![Current dmg and AP](https://user-images.githubusercontent.com/26745981/72368908-46c38300-36ff-11ea-968c-f35d2d2faba5.png)

![Current pet Spell Dmg increase](https://user-images.githubusercontent.com/26745981/72368953-5cd14380-36ff-11ea-86e1-cdc967e0510f.png)

Now on the PTR I have 1997 RAP, and according to the correct scaling that should equal to 106+(1997*0.053575)= 213 max damage from my wind serpent without any dmg increasing talents or items. So it's currently 148 dmg while it should be 213 dmg which is a pretty big increase. 

This is all according to the real normal damage of lightning breath, because on this server it seems to do a little more dmg for some reason which would equal to an average of 108.5 dmg.

![Live lightning breath](https://user-images.githubusercontent.com/26745981/72369068-9c982b00-36ff-11ea-887c-729fa5645968.png)

When it should be like [this](https://db.excalibur.ws/?spell=25012) instead but with the correct scaling to of course blow the dmg out of the water.

**Comment by Wolffenstein** [comment]
Fixed in rev 3262.

**Comment by NatsumeLily** [comment]
Still bugged, @Wolffenstein 

12.5% of the hunters rap is added to the pet as Spell Bonus.
42.86% of that Spell bonus is added to lightning breath.

At my rap it should look like this =

108.5 + ( 2028 * 0.125 * 0.4286 ) = 217.1501

After the "fix" it's still doing the same amount of damage as before the "fix".

**Comment by Wolffenstein** [comment]
It's fixed now.

**Comment by NatsumeLily** [comment]
@Wolffenstein Bugged again. Lightning breath is doing it's old non-scaling damage.

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/79156780-c7178400-7dd3-11ea-9666-a4eddcb38216.png)

Source: https://www.youtube.com/watch?v=ivS6QDV45Gc&feature=emb_logo

Says you're all wrong and endgadget is wrong.

full swp geared hunter with full set of buffs on him and 2x FI, only thing missing is command and 3rd FI from max you can get. 

Spreadsheet formula appears to be the correct one. 0,0125 * 0,4286 multiplier.
