### ISSUE TITLE
[Spell][Paladin] Retribution Aura being resisted

### ISSUE THREAD

**Issue by cmcit-bferg** [Atlantiss/NetherwingBugtracker#6009]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Incorrect resistance behavior on mobs.
[Spell][Paladin] Retribution Aura

**Current Behavior**:
Retribution Aura (and possibly other Holy school spells?) is being resisted by mobs regularly. 

**Correct Behavior**"
This should not be possible as Holy school magic should not be resistable.
https://wow.gamepedia.com/Magic_schools_(WoW)#Holy

**Server Revision**: 3037

**Comment by Evolvee** [comment]
it cant "resist"
but it can "miss" afaik which in TBC is displayed as "resist" same as the 1st case

**Comment by Easyfraggy** [comment]
I'm pretty sure this whole "holy spells can't be resisted" thing has been discussed and disproven before.

For sure level based resistance (17% spell miss) should apply.

**Comment by cmcit-bferg** [comment]
Anecdotal: In my decade plus of playing paladin, I have never seen retri aura be 'resisted' on a retail server. 

The level-based spell miss does apply, which is irrelevant because reflects cannot miss. This is why AoE prot leveling has always been strong- with all the holy & reflect damage you can effectively ignore hit (and there's 3% talentable hit in the tree), and paladins' lack of offensive abilities at low level is thus rendered moot.

RA, Thorns, Fire Shield, etc are damage shields. There is no roll in the combat table for miss because a hit is determined by the attacker, not the person being attacked. We've been arguing the holy resistance point for over a decade even after Blizzard attempted to clarify and even updated the client to separate misses from resists. I won't go there. Instead, I will direct you to literally any resource you want to use--look up which holy spells are resistable. RA isn't on there.

This is not a big bug, but it _is_ a bug.

**Comment by cmcit-bferg** [comment]
https://wowwiki.fandom.com/wiki/Holy_resistance
https://wow.gamepedia.com/Holy_resistance

There's two links with relatively little digging.

**Comment by Easyfraggy** [comment]
I have no idea what you are even trying to argue? You said

> Retribution Aura (and possibly other Holy school spells?) is being resisted by mobs regularly.

> This should not be possible as Holy school magic should not be resistable.

So we respond that "resist" is "miss" which SHOULD apply to holy spells eg 4% vs same level opponent. This is on the spell hit table. We respond like this because you talk about "other holy school spells".

It is unclear wether or not holy spells should be affected by the level based partial resist chance e.g. ~24 resistance vs +3 enemy. I don't think anyone has the real answer for this question. But I would assume that partial resists on holy damage is not a thing currently. So please provide evidence in case they do.

Now the only thing I was able to take away from your last reply is that your OP is actually about reflect auras like RA, Thorns etc. And that you think they shouldn't roll combat table because they are damage reflections. Can you show some proof of this?

**Comment by Tereneckla** [comment]
can't replicate/fixed
