### ISSUE TITLE
Arena drinking first tick should be  delayed .

### ISSUE THREAD

**Issue by sposobniy** [Atlantiss/NetherwingBugtracker#6013]
Problem  :  At this moment there is a small delay to get the first mana tic while drinking. 

https://clips.twitch.tv/BlueUninterestedClipzPipeHype  

https://clips.twitch.tv/CooperativeNaiveMarjoramTF2John 

How is should work :  
https://wowwiki.fandom.com/wiki/Patch_2.4.0 
"The benefits of drinking out of combat have been delayed while in the Arena. It will now take four seconds before the full benefit of the mana regeneration will come into effect." 

hydra's video  , first tick after 4 sec 
https://www.youtube.com/watch?v=NMkgJmSiMc4&feature=youtu.be&t=989%C2%A0%C2%A0 

also , have some more video proofs , but I think that will be enough.

**Comment by Evolvee** [comment]
> also , have some more video proofs , but I think that will be enough.


if you have more videos, post them pls

there was a spell delay on retail which makes researching things based on time and checking mana bars quite difficult since the mana was updated in batches, not instantly(so u cant get the exact timer)

I understand the patch note as that the food takes a while before it gains the full restoration, e.g.:

The food progressively increases restoration until its full effect --> lets say: 1-3 seconds = 30%, 4-7 seconds = 70%, 8+ seconds full 100% mana restoration. So instead of how often you get the mana restoration tick, it means how long it takes until the food becomes fully effective (basically restoring less mana when you start to eat).

**Comment by Godmatik** [comment]
Fixed a long time ago, closing
