### ISSUE TITLE
[Spell] Some Drywallow Snappers doesnt give leather when skinned

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#602]
**Read title, Dustwallow Marsh**: 

**When skinning some of the crocs, they give skillup but no leather**:

**Giving me my leather**:

**Comment by mbzz88** [comment]
Just to add more to this, I've had this happen with all skinnable mobs in Dustwallow, not sure if it's Dustwallow specific, or level range related

**Comment by Evolvee** [comment]
maybe caused by the issue where u cant skin NPCs that dont drop any loot atm?

**Comment by Shanghi** [comment]
It was just because skinning loot was still completely stock so there were hundreds of problems including many creatures that had a chance to drop nothing. After revision 2221 there shouldn't be anything that gives no loot, and hopefully the majority of all the other problems like missing/wrong items and chances were fixed, but when editing about 1200 loot tables at once there's surely a mistake somewhere!
