### ISSUE TITLE
Icon of mailbox is bugged

### ISSUE THREAD

**Issue by aaddggjj** [Atlantiss/NetherwingBugtracker#6067]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Already for many times I noticed issue with mail box. As many ppl farming and making gold just really annoying cause u never know if mail has really arrived or not. It shows that u have mail but when u open mail box-its empty. Or opposite -it shows u have no mail but if u open u could have lot of mails. I'm really tired of re-logging to check this out and its not only me having this problem. 

**Current behaviour**: Mail icon is inconsistent - You don't know whether it's has appeared or not. ( The item that you supposedly have gotten sent in mail )

**Expected behaviour**: Icon corresponding to the action

**Server Revision**: Netherwing 2.4.3

**Comment by Kaidalen** [comment]
BUMP CAN CONFIRM. Every time I post this bug Devs or whoever controls these threads closes these posts. but I can CONFIRM. The ONLY way to fix this issue is to relog. ALSO

+ When you buy something from the AH It doesn't show up in your Mailbox. You need to relog for it to pop up. Again. I posted this and the thread I made was closed. The control of this "bug thread" is absolutely disgusting!

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/60746295-69215a80-9f7e-11e9-84e5-6a9905a853af.png)

The client puts a 60s cooldown on the CMSG_GET_MAIL packet. When that cooldown is still going the server does not get any notification that you clicked a mailbox, therefore cannot send you the mail you just received. Relogging fixes it because it resets the cooldown. Try waiting a minute next time to confirm whether it's truly bugged or not.

**Comment by Kaidalen** [comment]
I have waited over 1hr and it hasn't gone away. But if you refuse to believe the people reporting the bugs after they have done their "testing" that is fine. I have done ACTUAL beta testing for many games and am a programmer myself. So don't discredit what I say.
