### ISSUE TITLE
[Dungeon][Botanica][NPC] Bloodwarder Protector reflecting seed explosion

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6108]
**Description**:  Bloodwarder Protector reflecting seed explosions instead of seed debuff, and in case of seed before reflect and explosion after - rip from aoe

**Expected behaviour**:  explosion shouldn't be reflected

**Server Revision**: 3068

**Comment by devo6969** [comment]
Appeared to happen in wotlk on the ability called "Shroud of Runes". This doesn't happen anymore in BFA but most likely was a thing back in the day.
Shroud of Runes - Protects the caster in a shroud of runes, reflecting harmful spells. Lasts 8 sec.

https://www.wowhead.com/spell=27243/seed-of-corruption#comments
"Does anyone have problems w/ SoC being spell reflected in the ICC heroics? I am forced to use RoF because I keep getting SoC used against me and instantly killing me and possibly others around me. LOL Really keeps me from doing as much damage as I'd like to be doing. :("
"That sounds like the giant skeletons in FoS. They have a spell reflect ability called Shroud of Runes. Just, uh, don't cast SoC while Shroud of Runes is active, I guess"

**Comment by Godmatik** [comment]
Need to double check and retest with the new aura branch, I suspect though it still exists.

**Comment by Godmatik** [comment]
Fixed now - seed debuff is properly reflected to the caster
