### ISSUE TITLE
[Racial][Blood Elf] Mana Tap & Arcane Torrent 

### ISSUE THREAD

**Issue by DaedalusMachina007** [Atlantiss/NetherwingBugtracker#6229]
**Description**:
Blood Elf Racial Ability 'Mana Tap' does not return any amount of Mana when used (always 0 mana).
Blood Elf Racial Ability 'Arcane Torrent' should restore 6% of total max mana (or 15 of other resources if not using mana) but instead restores far less than that, especially at higher levels.
I believe Arcane Torrent may be using the Mana Tap (50 + currentlevel) formula while Mana Tap has no formula at all (hence 0 mana).

URLs with more info:
https://wow.gamepedia.com/Mana_Tap
https://wow.gamepedia.com/Arcane_Torrent

**Current behaviour**:  Mana Tap returns 0 mana and Arcane Torrent seems to return less than 6% of total max mana.

**Expected behaviour**:  Mana Tap should restore/drain "50 + CurrentCharacterLevel" of mana whenever used on any target that has mana.  Arcane Torrent should restore 6% of total maximum mana (restore more if you are wearing gear with lots of intellect, for example).

**Server Revision**:  3106

**Addendum**:  The Sunwell gets restored in later expansions but in TBC the Blood Elves should have both racials working as intended.  It would be optional but very useful if Mana Tap restored 6% of Maximum Mana each time it is used on a PvE target (any creature that is not another enemy player).  Not only would it encourage use of this useful racial ability far more often but it would help mitigate some mana issues due to some of the significant buffs that some bosses get on the server.

According to the patch revision history on the GamePedia page, Arcane Torrent was 'unintentionally' bugged to restore 6% of maximum mana instead of 3%.  Since we are 'Blizzlike' I believe for TBC we should restore this behavior and only 'fix' it to 2% of base mana once we have a Wrath of the Lich King expansion server.

**Comment by Evolvee** [comment]
mana tap shouldnt give you any mana

**Comment by Evolvee** [comment]
and arcane torrent was fixed prior to launch as well according to old bugtracker

**Comment by DaedalusMachina007** [comment]
Banning me from the server for speaking the truth is not the way to run things.

Proof, directly from the mouths of the people who made Burning Crusade:
https://www.youtube.com/watch?v=NE-4Edh3RuM

Around the 2:30 mark:

> The 'Mana Tap' ability that all Blood Elves have that kind of allows them to kind of **sap mana** from the target and also build up a little bit of a buff that leads into their next ability which is 'Arcane Torrent'.

Blizzard dev himself tells the audience that Mana Tap drains mana from the target and **restores some mana to the player**.  That's how all 'mana drain' abilities work in the game.  Mana Tap is not JUST a builder for Arcane Torrent.  It has always drained mana.  Not a LOT (50 + Level) but every extra bit is useful while leveling and even beyond.  Mana drain counts as an attack so it removes polymorph and other CC effects as well.  If the target does NOT have mana then obviously Mana Tap can't be used on it.

Telling me to use this bugtracker and then banning me because I disagree on a key core racial skill feature of one of the main playable races in the game is really unprofessional.

I only care that the ability is fixed so that Belfs are no longer hindered by non-blizzlike nerfs.

Also if you claim the 6% return was 'fixed by launch' then provide a source for it.

**Comment by Evolvee** [comment]
explain this https://youtu.be/FJXdXvLh4LM?t=32

**Comment by Evolvee** [comment]
Also, I didnt ban you, you have to talk to mods.. there was probably a reason for it.

![image](https://user-images.githubusercontent.com/1942409/63475360-d6c90d80-c47c-11e9-9d3c-2150ccc4fdf4.png)

**Comment by DaedalusMachina007** [comment]
They claimed I was 'trolling' purely because I disagreed with them about this Mana Tap issue.
Do please tell me you aren't basing the source of your entire private server on some random video where the person doesn't explicitly state what retail server they played on (could just be a private server) especially since PvP ranks weren't a thing in TBC.

**Comment by Evolvee** [comment]
random video? its a retail video, I dont need for anyone to tell me where it was taken from as I have enough knowledge to recognize a retail video from private server one (not to mention its recorded in 2007 where private TBC servers hadnt even stamina working)

where are the patchnotes you are talking about?

But yes, I dont care if Mark Morhaime himself said it gave the caster mana.. as long as video evidence says otherwise, his word would mean shit. I trust only video evidence as its the ONLY source that never lies.

**Comment by DaedalusMachina007** [comment]
Ok, how about some more sources then? Or does it have to only be a video that you say is from TBC retail?

Archived racial changes/patch notes:
https://www.dslreports.com/forum/r16977311-The-Burning-Crusade-Racial-Changes

A preview from GameSpot on the TBC expansion dated Oct 31st 2005 (pre-launch):
https://www.gamespot.com/articles/world-of-warcraft-the-burning-crusade-hands-on-impressions-blood-elf-starting-area/1100-6136860/

Another private server that comes across similar issues and fixes em instead of ignoring them:
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2

But of course you'll only demand video proof from 12+ years ago.  I'll do some digging ;)
Nevermind that the literal Blizzard designer doing a Behind the Scenes postmortem on TBC says what the ability does.  Ok then.

**Comment by Evolvee** [comment]
I mean.. it shouldnt be hard to find more mana tam videos right?

**Comment by DaedalusMachina007** [comment]
Sure thing lemme get right on that.  Mana Tap is a mana DRAIN ability which takes from the target and gives to the caster.  That's how every mana drain ability works in WoW TBC.

**Comment by Evolvee** [comment]
https://youtu.be/L7IGUjXvSGY?t=208

**Comment by DaedalusMachina007** [comment]
Found one, lol
https://www.youtube.com/watch?v=dXCwcjHphKI

Mana Tap drained mana from the beta all the way through TBC.

**Comment by DaedalusMachina007** [comment]
Another old post mentions 'mana drain and return' aka mana is taken from the target and given to the caster.

![2019-08-21 21_28_26-Mana Tap - Spell - World of Warcraft - Chromium](https://user-images.githubusercontent.com/54285152/63479115-c9029080-c45a-11e9-8a3a-95ded2cb83b1.png)

That one's actually got the patch 2.4.2 next to it so can be considered Blizzlike/accurate.

**Comment by Kolmarwow** [comment]
the video that you yourself posted shows that mana tap does not drain mana at roughly 5:30 when he uses it a second time. he gains a 2nd charge of arcane energy and his mana tap skill on the toolbar goes on cooldown and the monsters mana goes down (showing it didn't resist) but his mana stays the same at 229/347. 

i'm guessing he got passive 5-second rule regen as soon as he used mana tap the 1st time which might have looked like it gave him mana, since he time-skipped the video there so we can't see what he did in the last 5 seconds. 

as for arcane torrent, it was not percentage based in TBC according to this archived Wowpedia page from back when TBC was the current expansion https://wow.gamepedia.com/index.php?title=Arcane_Torrent&oldid=1468718

"Mana return scales with level; Energy return does not scale with level.

(Given values indicative of a level 1 character. At level 70, Arcane Torrent gives 161 Mana for each charge. The formula is roughly 2.17 * level + 9.136)"

so arcane torrent gives you a flat bonus that scales with your level but does not scale with your mana bar. this was changed in wotlk when mana tap was removed & they instead added percentage-based mana as you can see here https://wow.gamepedia.com/index.php?title=Arcane_Torrent&oldid=1726275

**Comment by Evolvee** [comment]
Your video proves your are indeed incorrect when it comes to mana tap drain mechanic, perhaps you wanted to post some other video? xd

**Comment by Evolvee** [comment]
so tldr:

You claim that 3 out of 3 videos that we gathered so far are all.. "self resists"? ... Link us some that isnt "resisted" according to you then...

**Comment by DaedalusMachina007** [comment]
Despite @Evolvee acting like a petulant child throwing a tantrum, the professionalism & courtesy of @Kolmarwow is duly noted.

I am not giving up on this, but the strict 'proof' requirements of finding non-grainy TBC footage from that timeframe does hinder things somewhat.

When I find the requisite proof, I'll re-open and update the thread here.  For now I'm locking it due to 'excessive trolling' by @Evolvee  lol.

**Comment by Evolvee** [comment]
You realize that the 1st clip I posted is not from 2.4.3 right?
