### ISSUE TITLE
todo: put evade threathDistance

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#6308]
https://gfycat.com/DistantLiveAfricanwilddog

**Comment by HyperAzur** [comment]
I was here 😀

**Comment by troll-supremacy** [comment]
Frankly, I fail to see the issue in this .gif if the point of the server is to be blizz-like.

https://old.reddit.com/r/classicwow/comments/bro6z2/was_it_a_bug_back_in_vanilla_having_servant_of/?st=k16sfppy&sh=5fcd97f0

As seen here, kiting the Servant mobs to a major city was/is something done in order to help people level up their weapon skills. Pulling to Booty Bay seems just a way for Horde to enjoy this as well.

According to the comments from the Reddit thread, this mob would stay up until a GM would come, but it still is just a mechanic that was present on the Blizzard servers.

**Comment by Evolvee** [comment]
I have nothing against kiting whatever into cities, but this is just an exploit at this point. you dont have to kite them across the entire continent in order to skill weapons

**Comment by The14me** [comment]
Like on Vanilla....and in the Classic now  blizzard still have a lot of ''bug's''.Lets bring lord kazzak in stormwind too then.

**Comment by Evolvee** [comment]
fixed in next rev
