### ISSUE TITLE
[Item] Stormchops are not proccing

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#6379]
**Current behaviour**:
[Stormchops](https://db.excalibur.ws/?item=33866) are not zapping critters or any enemies when you're in range, which it should.
**Expected behaviour**: 
[Stormchops](https://db.excalibur.ws/?item=33866)  should occasionally one-shot nearby critters with a lightning zap and deal some dmg to any other enemy in range, also with a lightning zap that should scale with spell-dmg. [Proof](https://www.wowhead.com/item=33866/stormchops#comments)

Databases lists the [Electrified](https://db.excalibur.ws/?spell=43730) buff to  have 2 effects.
The 1st [Lightning Zap](https://db.excalibur.ws/?spell=43731) has no dmg value so that's probably the one shot ability that one-shots critters.
The 2nd [Lightning Zap](https://db.excalibur.ws/?spell=43733) has dmg values and should scale with spell-dmg. [Proof](https://www.wowhead.com/item=33866/stormchops#comments)

**Server Revision**: 
3179

**Comment by Healweed** [comment]
I can confirm this, but your issue is somewhat not explained in detail. Forgive me in advance if i'm being intrusive.

At this moment as @Manaci said, Stormchops is not zapping critters or any enemies( i remember zapping enemies before but not anymore). I belive when 2.3 released devs forgot to make stormchops to include Neutral-Hostile on stormchops target. 

It's also used to break rogue's Stealth. Link and quote below:
https://www.wowhead.com/item=33866/stormchops#comments

> By warcraftzombie (261 – 2) on 2008/05/26 (Patch 2.4.1)

   I've tested this buff, it WILL bring a rogue out of stealth. Very useful for pvp.

As mentioned above also, critter damage is also different:
https://www.wowhead.com/item=33866/stormchops#comments

> By V1nd1c4t0r (7,616 – 1·10·63) on 2008/05/14 (Patch 2.4.1)
   Xelios's Lightning Zap hits Prairie Dog for 666 Nature.
   Xelios's Lightning Zap hits Rabbit for 1334 Nature. (Critical)
   Xelios gains Vengeance.

  Awesome critter killer if you ask me. No more having to walk up to a critter and punch it. Eat one of 
  these and just walk by.

**Comment by Vidovit** [comment]
I just came to say this item isn't working aside from providing the buff, date 09.11.2019.

**Comment by Vidovit** [comment]
Hm i actually saw it proc after eating it directly but later on when i logged back in it wouldn't proc.

**Comment by Wolffenstein** [comment]
It certainly should not benefit from SP/AP.

**Comment by Healweed** [comment]
@Wolffenstein don't think it's an item that scales with sp/ap tho(can't say it with 100% certainty). But stormchops damage modifier does large damage to critters. But as said B4 the item itself was not even killing critters or attacking neutral npcs(at least those which you can attack ofc)

**Comment by Wolffenstein** [comment]
Fixed in rev 3194.
