### ISSUE TITLE
[Suggestion] [Core] Low level mobs high miss/dodge rate

### ISSUE THREAD

**Issue by G3dSage** [Atlantiss/NetherwingBugtracker#6429]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Damage done and received in-game doesn't match up to original TBC standards as well as being sometimes broken from a game-design standpoint.

**Current behaviour**: https://prnt.sc/q1bmgf
https://prnt.sc/q1bmjt
 Most noticeable with low-level mobs, level 1 creatures will miss every attack or it will be dodged by the player, even though the damage effect is played on the player character. The other mobs which are under-level do so little damage it's almost negligible. 
 Perhaps it has something to do with how damage is calculated, but not armor, armor or absence of it doesn't seem to have an effect on mobs whiffing every attack.

**Expected behaviour**:  Damage formula redone in a way that makes low-level players know damage exists, and not dodge every following attack from a level 1 monster.

**Server Revision**: https://prnt.sc/q1bmn0

**Comment by DaedalusMachina007** [comment]
On the other end of things, spell damage in Outland dungeons is obscenely high.

The 'overtuning' of certain bosses/mobs outside of raiding has ruined a lot of the fun that comes with gearing up and playing the game.  Normal dungeons should be doable without epics.  Heroics should be doable without already having full T4 or equivalent badge gear.

I'm all for a challenge, but those who aren't in one of a handful of top raiding guilds have no opportunity to even attempt these types of things because the overtuning has gotten way out of hand.

This isn't about 'nerf cause too hard' it is about 'make it Blizzlike' rather than artificially overtuning things due to perceived 'unfair' additional player power from spells/talents.

World mobs, non-raid bosses, and normal/heroic instance mobs should have damage/health/stat values that coincide with what is known for them from TBC Retail 2.4.3 patch.  Otherwise the gamer creed is typically the 'path of least resistance' and that usually means employing FOSS (first order optimal strategy) and skipping over anything that would take 'too much time' meaning less grouping and a far more insular community.  Good luck getting certain dungeon quests done until you and your group decide to do them after getting full T4 or equivalent.

I'd say with the plans for Sunwell release coming up in a few months, maybe it is time for a 'Blizzlike' values nerf to all pre-T6 content.  Just drop the overtuned stuff and restore the hp/stats to what they are in 100% blizzlike 2.4.3 regardless of what 'extra' player talents/spellpower do for the playerbase.  It might be 5% easier.  So be it.  Balancing is tricky and this 20% overtuning (or sometimes even more than that) is making players just quit rather than waste time with it.

**Comment by DaedalusMachina007** [comment]
To add on to my previous comment, the server has many bugs which ruin dungeon run attempts and mess things up to make them much more difficult than intended.  Mobs that pull other mobs nearby even though they were unlinked on retail (numerous times in various dungeons and areas), Mobs that pull elites/bosses even though they shouldn't do so, buggy aggro radius for certain mobs (run through Hellfire Peninsula and I'm sure you know what mob(s) I am talking about) and much more.

In Shattered Halls for instance, a group wipe on the first boss Grand Warlock Nethekurse will not return him to his throne.  Any further attempts will have him aggroing alongside at least 3 of his minions which puts an undue burden on blue/green-geared tanks/healers.

If it has to be so overtuned, then gear/power should be improved to match or have stats reworked in better ways.  But going down that route would make this a non-Blizzlike server and more of a 'custom' server.

Overtuning isn't necessary.  Let's drop it for anything pre-T6 and get more players enjoying the T6 content before SWP comes out.

**Comment by G3dSage** [comment]
I hear you. And yeah FOSS is what the retail has been designed around, always. you got quests because they gave nice xp and grinding is a pain. It seems that the dev team decided to remake most of the core ground-up, as they like to do and said they'd do with the loot system. So some values may just be completely different to the Blizz experience.
 That's why I said it all needs a big rework.

**Comment by Easyfraggy** [comment]
The spell values are 1:1 copy from the 2.0 client so no the damage values of enemy spells dont differ from retail.

Please don't derail the OP with talking about dungeons and raids. Make a report WITH PROOF of your claims if you think something is wrong.

To the OP you are not adding enough information. What class are you playing - what level are you and what level enemy are you facing?

Miss/dodge parry etc is based on defense/weapon skill aswell as agility. So we need to know your weapon and defense skill aswell.

**Comment by Easyfraggy** [comment]
I've also fixed the title as it was very misleading and likely the reason it got derailed.

**Comment by G3dSage** [comment]
> I've also fixed the title as it was very misleading and likely the reason it got derailed.

Right. It was the right thing to do on your part

**Comment by G3dSage** [comment]
> The spell values are 1:1 copy from the 2.0 client so no the damage values of enemy spells dont differ from retail.
> Please don't derail the OP with talking about dungeons and raids. Make a report WITH PROOF of your claims if you think something is wrong.
> To the OP you are not adding enough information. What class are you playing - what level are you and what level enemy are you facing?
> Miss/dodge parry etc is based on defense/weapon skill aswell as agility. So we need to know your weapon and defense skill aswell. Armor has nothing to do with it.

Thanks for coming back to me about it. It's a level 1 warlock facing off a level 1 Young Wolf, lowest agility so it's lowest natural dodge chance and defense. I've tried with armor and without, at level 1 and at level 10 later, the result is the same. While level 2 mobs do at least 1 damage, the level 1's simply whiff all the time.

**Comment by G3dSage** [comment]
Ok, so I've gathered enough data to make a more informative update on the issue and how it compares to original TBC. I will CLOSE this issue and open up a new one.
