### ISSUE TITLE
Vanilla Dungeons Reset Timer?

### ISSUE THREAD

**Issue by Detozi** [Atlantiss/NetherwingBugtracker#6447]
**Description**: Vanilla dungeons resetting completely in the middle of completing it. 

**Current behaviour**: Dungeons like Sunken Temple, BRD or Stratholme reset completely after a certain time. 

**Expected behaviour**: Slow respawn of trash mobs after a certain amount of time and one by one, not all in one instant with bosses and Events also resetting or if that is not possible no reset at all when the function has not been used.

**Server Revision**:

**Comment by DaedalusMachina007** [comment]
This happens after a wipe if everyone releases spirit and ghost walks back into the dungeon; the way to mitigate this is have at least one person NOT release and then you all meet back up.  Having a soulstone on someone who can resurrect is useful; so is Shaman with self-res.

It doesn't just affect Vanilla dungeons but also affects Outland dungeons as well (but people sometimes get summoned into a fresh instance instead of the one the group is in).

**Comment by raethkcj** [comment]
We had BRD reset with 2 people who didn't release still inside. They are still dead in the old instance, but when the 3 people who released walked in, they walked into a different, reset instance.

**Comment by raethkcj** [comment]
#5406

**Comment by Drayo** [comment]
Most likely fixed with https://github.com/Atlantiss/NetherwingBugtracker/issues/5406
