### ISSUE TITLE
Halaa Battle Token

### ISSUE THREAD

**Issue by homeros333** [Atlantiss/NetherwingBugtracker#6483]
[//]: #

**Description**: 
Slain dozens of Alliance players over the few days at Halaa but I still didn't manage to get Halaa Battle Tokens to drop
**Current behaviour**:
Halaa Battle Tokens won't drop from eligible targets. 
**Expected behaviour**: 
Tested along on all of the vicinity of Halaa(the base and the bombing platforms) doesn't work like it used to before. 
**Server Revision**:

**Comment by Healweed** [comment]
Weird.
Reason for that is because i got 3 battle tokens in my bank at this moment
![WoWScrnShot_121119_133012](https://user-images.githubusercontent.com/52166185/70625524-78d25880-1c1a-11ea-9bec-02429e6c62d1.jpg)

**Comment by homeros333** [comment]
Thanks I'll check my bank

**Comment by homeros333** [comment]
In my bank I still have the same amount I had before those kills

**Comment by Healweed** [comment]
Battle tokens don't drop from alliance playes, but rather is when you kill one, it gets added to your inventory. in case your bags were full, you should receive a mail from "customer support" to retrieve those lost items.

if none of those are at work, thats because core got fucked up

**Comment by homeros333** [comment]
In the past I could kill an Alliance player and have it added into my inventory. I was careful to not have my bags full as I was expecting it to fall into my inventory like before. 
![WoWScrnShot_121119_104549](https://user-images.githubusercontent.com/23630492/70631540-98bf4780-1c2d-11ea-8ac4-614a0817fed4.jpg)

**Comment by DaedalusMachina007** [comment]
Hardly anyone is at Halaa lately.  It is a shame :(

Would love for a compromise of exchanging 5 Halaa Research 
Tokens for a Halaa Battle Token so that the items are at least farmable for those who want them and don't get to see many/any enemy players at Halaa.

Terrokar spirit shards are PvE only (basically).
Hellfire Tokens can be obtained daily by capping towers (which is iffy but still doable).

Halaa in Nagrand is the only one that mandates PvP and a significant amount of it within that tiny little area to get mounts and other unique items from the NPC.

**Comment by homeros333** [comment]
Killing Alliance players in Halaa does not yield Halaa battle tokens this
is why I made this post. I don't think we need to plug a compromise;  there
shouldn't be a purely PvE alternative, its just supposed to work like its
intended.  The fact that there aren't many players there is not a real
problem.

**Comment by Tereneckla** [comment]
#6528 is more detailed
