### ISSUE TITLE
[Spell][Paladin] Judgement ( counts as melee attack )

### ISSUE THREAD

**Issue by Tankdiehutte** [Atlantiss/NetherwingBugtracker#6507]
Link to DB: https://www.wowhead.com/spell=20271/judgment

**Description**: 

The Judgements of the paladin count as Meleeattacks. Triggering Setboni like T6 Retri (2 parts) or Vindication ( https://classicdb.ch/?spell=9452). Leading to 0 resists, more Mana for the Paladin and more dps.

**Current behaviour**:

Every Judgement of the paladin has 0% resistchance and due to the fact that it doesn't get dodged or parried its giving the ret paladin a small buff in PvE and a huge buff in PvP. ( see: https://github.com/Atlantiss/NetherwingBugtracker/issues/6442 ).

**Expected behaviour**: 

The judgement should use Spellhit (17% resistchance without spellhit) and have a minimum resistchance (with 16% spellhit) of 1%. 
The chance to crit should be the Meleecritchance , which is working fine here. ( thats why it very often leads to confusion and blizzard changed the spell to use meleehit later, but not in Burning Crusade)

**Server Revision**:

**Comment by Easyfraggy** [comment]
I believe this issue is invalid. Judgement and HoW should use "ranged hit" (physical hit) mechanics.

Exorcism, Holy Wrath & Cons should use spell hit only.

Need proof otherwise.

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/71427849-02733300-26bd-11ea-834e-f0017d92b558.png)

https://wowwiki.fandom.com/wiki/Judgement_(original)?oldid=1423495

**Comment by Tankdiehutte** [comment]
My Guide says Judgements use Spellhit and on every other Server ppl had resists and me had Resists.
http://world-of-paranoid.com/download/Vergelter_Kompendium.pdf ( sadly in german)
page 78: " (beim Paladin profitiert das Richturteil halt von
Zaubertrefferwertung, sollte aber bald geändert werden). "
Translation: "The Paladins judgements profits from Spellhit, but that should be changed soon."
And on every other server judgement resists happen.

btw on Issue #6442 u can see that the seal of Righteousness gets resisted on that video screenshot and here this doesnt happen aswell. If the SoC judgement hits with meleehit im fine btw ( ret main xD ) but Righteousness and Vengeance doesnt seem to work the way they should + the Judgement shouldn't be counted as a melee attack that triggers on hit effects.

**Comment by Easyfraggy** [comment]
SoR should be spell hit indeed. Command and Blood is physical.

**Comment by Evolvee** [comment]
fixed in rev 3230? or whats the issue in this report exactly?

**Comment by Tereneckla** [comment]
Judgements should use the spell attack table and not the melee attack table
rev 3230 fixed the Seal using spell attack table instead of the melee attack table

**Comment by Sagoona** [comment]
Maybe this helps too: http://web.archive.org/web/20080811083713/http://elitistjerks.com/f47/t21425-paladin_protection/

Section "Hit, Spellhit and Expertise and what they do for you"

**Comment by Tereneckla** [comment]
Paladin spellhit for judgement of Righteousness

Description:
Paladin “Judgement of Righteousness” cant resist on this server right now. and last one got closed cause ONE proof of source didnt count as valid source but the other literal proof just got ignored. ez solution kekw

Current behaviour:
0% resistchance in PvE vs trashmobs, vs bosses, vs horseboss while minus hitchance curse up.
0% resistchance in pvp vs lvl 70 players, vs rogues having cloak of shadows active 

Expected behaviour:
17% resistchance (16% resistchance can be removed by spellhit)


Proof #1 - that it should be resistable:
wowwiki on seals and their judgements:
https://wowwiki.fandom.com/wiki/Judgement_(original)?oldid=1423495
relevant screenshot from that site:
https://i.imgur.com/zHLW70h.jpg
it says that “judgement of Righteousness” is considered a spell
 
Proof #2 - that it should be resistable: 
Elististjerks archived theroycrafting:
http://web.archive.org/web/20080811083713/http://elitistjerks.com/f47/t21425-paladin_protection/
relevant for this topic:
https://i.imgur.com/33PrafU.jpg
“Spellhit affects Seal of Vengeance, all damage dealing Judgements except Judgement of Blood, Consecration, Holy Shield, Exorcism, Holy Wrath, Retribution Aura, Blessing of Sanctuary, Thorns and Fire Shield. Consecration can only have it's first tick fully resisted. It takes 16% spellhit to be hit capped against level 73 targets and bosses, or 6% spellhit against level 72 targets (And 1% less needed per level below that).”

Proof #3 - that it should be resistable:
Dr.Damage ingame Addon:
https://i.imgur.com/DGxg5uV.jpg


Proof #4 - that it should be resistable:
Youtube Video showing a Paladin tanking Felmyst and having a resist on judgement of R 
uploaded Jun 15, 2008
https://www.youtube.com/watch?v=B6RIMIBsIPk
relevant screenshots and timestamps in the video, so you dont have to search for that moments:
#1
https://cdn.discordapp.com/attachments/596075260705767450/650332418292711426/bugreport.png
#2
https://cdn.discordapp.com/attachments/596075260705767450/650332447766085673/bugreport2.png
#3
https://cdn.discordapp.com/attachments/596075260705767450/650332472869126154/bugreport3.png
#4
https://cdn.discordapp.com/attachments/596075260705767450/650332501826469898/bugreport4.png


Proof #5 - that it should be resistable:
Youtube Video showing a Paladin tanking Zul’jin and having some resists on judgement of R - uploaded Mar 9, 2008
https://www.youtube.com/watch?v=5QSg2sbd4PY
Timestamp #1 
0:54-0:56
https://i.imgur.com/fHP1135.jpg
Timestamp #2
1:44-1:46
https://i.imgur.com/sP2mjS2.jpg
Timestamp #3
3:28-3:30
https://i.imgur.com/i5zOODe.jpg


Proof # 1 - that its currently not able to resist on netherwing:
screenshot of ingame Addon Recount:
I did a Gruul Pug + 2 ZA runs (both times i logged on a dps alt for last boss)
with a total of 468x judgements of Righteousness used and not a single resist
https://i.imgur.com/POucfn0.jpg


Proof # 2 - that its currently not able to resist on netherwing:
screenshot of a log of a badly scripted site “legacyplayers.com”:
https://i.imgur.com/ljxiV52.jpg

**Comment by Godmatik** [comment]
Judge of Righteousness was fixed back in rev 3786

Closing
