### ISSUE TITLE
Shaman's Elemental ain't getting anything off party/shaman's buffs.

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#6583]
https://imgur.com/a/N1Cy7kT Pet has gained simply nothing, Unleashed rage, LW Drums, BL etc. Im strongly convinced, this isnt retail behavior so far. Pet should get party buffs that are applied while pet is active.

**Comment by Healweed** [comment]
Err..Pretty sure all totems are standalone till cataclysm. That's when elementals/ spirit wolves and other summoned totems start to gain their respective auras.

**Comment by GMThunderan** [comment]
@AWIDIUS Do you have sources to support your suspicion? Also, there is a difference between a pet (like hunter's) and an fire elemental/water elemental, since they are considered guardians and can not be buffed at all. While actual pets can.

**Comment by Healweed** [comment]
Fire Elementals/ Earth Elementals should never get totem auras on tbc. An example for instance is vanilla trinket House of Barov (which summons 3 npcs to aid you or the book of the dead, which still act as guardians)

The only benefit that Fire Elementals get from shaman is an increase of 30% attack power/spell power and stamina since tbc launched up.
