### ISSUE TITLE
MGT BUFF BUG 

### ISSUE THREAD

**Issue by Flamelol** [Atlantiss/NetherwingBugtracker#6666]
**Description**: 
Buff from sunblade blood knight is not working correctly. DONT MISS https://www.wowhead.com/spell=44480/seal-of-wrath WITH https://www.wowhead.com/spell=45096/seal-of-wrath#see-also-other - on every server including blizzard tbc u could steal buff and improve your blizzard.
**Current behaviour**:
Buff from sunblade blood knight gives additional dmg but not from every spell. 
**Expected behaviour**: 
 It should give also additional dmg from blizzard ticks. 
**Server Revision**:

**Comment by Flamelol** [comment]
Spell descriptions says - u deal additional damage from every damage done. TY

**Comment by Wolffenstein** [comment]
I would love to see proof from official TBC, because the spell has following proc flags:
=================================================
  02 Successful melee attack
  06 Successful Ranged attack(and wand spell cast)
  16 Successful damage from harmful spell cast
=================================================

Which does NOT include flag:
=================================================
  18 Deal periodic damage
=================================================

Blizzard has an attribute SPELL_ATTR3_TREAT_AS_PERIODIC, causing it to trigger periodic procs but not direct procs, that's why Seal of Wrath will not be triggered by it. I did not make it not proc on purpose, that's just how it works by default using proc flags provided with client data. If you find proof from retail TBC I will change it, otherwise I have no reason to do so.
