### ISSUE TITLE
[Spell] Blessings don't generate threat

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6679]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: https://us.forums.blizzard.com/en/wow/t/righteous-fury-mechanics-op-paladin-threat-1k-tps/318279

**Current behaviour**: Blessings don't generate threat

**Expected behaviour**: Blessings should generate threat
Threat generated = level the blessing is learned * targets buffed
blessing of kings threat is your level
This threat is increased by righteous fury

**Server Revision**: 3277

**Comment by DaedalusMachina007** [comment]
As the post explains, this was an unintentional bug that was present throughout the lifespan of 'Vanilla' WoW and was only fixed in TBC (aka what we're playing on Netherwing).

Rightous Fury increases the threat generated by Holy 'attacks' not just 'any Holy spell' so the current implementation is correct & blizzlike.

Unless you can find an older video or some proof from TBC-era that it was unfixed and just like Vanilla WoW then we'll have to go with current behavior.  Tanking threat as a Prot Paladin is based on attacks and not just spamming blessings or something.

**Comment by Cicinus** [comment]
Righteous Fury always was a holy school  threat modifier.  There was just a tool tip change between vanilla and TBC.  AS for baseline threat blessing do, classic is the best resources you have as its almost zero chance of something being changed if noone was actively using it for threat purposes

**Comment by Wolffenstein** [comment]
Fixed in rev 3801.
