### ISSUE TITLE
[Spell][Warlock] Create Soulwell

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#6729]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Soulwell limited charges.

**Current behaviour**: If you already took a healthstone from soulwell you can click it 9 more times even though you won't get any healthstone from it and make it despawn.

**Expected behaviour**: You shouldn't be able to "waste" charge of Soulwell after you got your healthstone from it.

**Server Revision**: 3289

**Comment by tsuone** [comment]
I think same thing might be going on with Mage's Refreshment Table.

**Comment by The14me** [comment]
That must be a new bug...was ok before.

**Comment by tetsugoro** [comment]
It's not a new bug, it's been this way since server launch. I remember getting annoyed during my first Karazhan run that people were spam clicking it. I guess nobody reported it because it's just a minor inconvenience.

A more annoying bug is when the soulwell sometimes doesn't spawn at all which is still a mystery to me. Need to test the specifics of that one before making a report.

**Comment by veekk** [comment]
can confirm this is old bug since launch

**Comment by elenmerbau** [comment]
Can confirm as well.

**Comment by Wolffenstein** [comment]
Fixed in rev 3412.
