### ISSUE TITLE
[Spell] [Priest] Mind Control

### ISSUE THREAD

**Issue by Rayuuken** [Atlantiss/NetherwingBugtracker#6732]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When you cast Mind Control in a PVE situation on a Heroic Dungeon difficulty in Steamvaults of Coilfang Reservoir no matter if its cast on Coilfang Soothsayer or Coilfang Oracle the MC breaks 1 second after its cast its not even enough time to put the Silence spell of the Oracle on a cooldown

**Current behaviour**:
Mind Control breaks out 1 second after beeing used no matter if its cast on a mob one, two or three times 

**Expected behaviour**: 
Mind control doesn't break for the full 1 minute duration if its not resisted or the player using the spell doesnt have it interrupted and also doesnt take damage.

**Server Revision**: 
[3295]

**Comment by TheDdraig** [comment]
Can I also add instead of making a new issue that Mind Control also doesnt cross over the abilities of the mob you mind control (aka if you mc a healer no healing abilities just the claw icon) when it does work and when you do eventually mind control when it does work, the mob who is being attacked doesnt take much damage but the mind control breaks either at start or in midst of mind control.

**Comment by Godmatik** [comment]
Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/5089
