### ISSUE TITLE
Fishing pool stack

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6817]
**Current behaviour**:  Fishing pools stack on each other.
https://streamable.com/hgfyl

**Expected behaviour**: Must be spawned only one type on a given time

**Server Revision**:

**Comment by TranceAccount** [comment]
Maybe you need to get out of GM mode

**Comment by The14me** [comment]
It was GM off...thats why I press it again at the end...

**Comment by DaedalusMachina007** [comment]
I can confirm multiple concurrent stacked fishing pools in:
-Ratchet
-Booty Bay
-Some areas of Hillsbrad Foothills at the river east of Tarren Mill & Southshore

When casting a line on it, it seems to prioritize one of them depending on where the bobber is.
I don't mind having 'permanent' fishing pools or getting fishing mats easier since fishing is already time-consuming/boring, but this isn't very Blizzlike and they should still be separated.

The proper 'fix' is to just have only one type of pool spawn and then the new one doesn't respawn until the old one is all fished-out or replaced.

**Comment by Manaci** [comment]
Also noticed a cluster of schools north of Garadar in Nagrand.

**Comment by tsuone** [comment]
It is not a bug. Floating Wreckage and other "debris" pools have a chance to spawn with other fish pool.

**Comment by DaedalusMachina007** [comment]
I went to some alliance areas on an alt to check there.  Plenty of stacked fishing pools in Azeroth near the docks by Auberdine, Rut'theran Village, Menathil Harbor, and nearly every fishing area in STV that I could find.

**Comment by Evolvee** [comment]
caused by a core fix on pooling, wolf forgot there are 2 types of pooling (one is super old shait), so the older one was unintentionally disabled
