### ISSUE TITLE
[Quest] Isle of Quel'Danas dailies & entrance 

### ISSUE THREAD

**Issue by NatsumeLily** [Atlantiss/NetherwingBugtracker#6832]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Isle has a level restriction. Only level 70s.

**Current behaviour**: Currently you can find players below level 70 on the isle, possibly doing dailies too.

**Expected behaviour**: All the dailies should require level 70, and even entering the isle in the first place should require level 70. 

**Server Revision**: 3320

**Comment by Wolffenstein** [comment]
Proof?

**Comment by tsuone** [comment]
![image](https://user-images.githubusercontent.com/11255782/78463640-9d79a100-76df-11ea-8333-0805a1a61f7b.png)

Node and portal should be only availalbe to use at level 70. People reported it on retail that they can't use portal nor get there through flight path being lower than 70. If you read more there is an info on gamepedia and wowwiki that says it is available at 65 but it is wrong, proved here: https://www.reddit.com/r/wow/comments/5iljo6/why_cant_i_go_to_the_isle_of_queldanas/

**Comment by The14me** [comment]
https://www.engadget.com/2012-12-14-alternative-leveling-in-the-isle-of-queldanas.html
''You can't pass through the portal or get any of the dailies until you are level 70.''

**Comment by DaedalusMachina007** [comment]
Yeah the Isle should definately be a 70-only zone.  Retail TBC never permitted anyone under 70 to go to that zone (swimming would have an invisible wall) and the Flight Path didn't even unlock prior to 70.  When leveling alts it was very explicitly set as a 70-only zone for both portal (Phase 3) and flight path.

Unfortunately WoWPedia has the info for the retail version (post TBC) so we have to turn to the older WoWWiki for the older info:
https://wowwiki.fandom.com/wiki/Isle_of_Quel%27Danas

It was a 70-only zone and (on Blizzard servers) you'd automatically learn the flight path at 65 but be UNABLE TO USE IT until you hit 70.  Apparently this was put in so that people were aware the zone existed and to build anticipation for getting there after hitting 70.

**Comment by Evolvee** [comment]
i can fix the portal but not the fly master

**Comment by Wolffenstein** [comment]
Will boot out players below 70 after next update.
