### ISSUE TITLE
Twin Spire Ruins Cannot be Captured

### ISSUE THREAD

**Issue by wandareu** [Atlantiss/NetherwingBugtracker#6837]
[//]: # (https://www.wowhead.com/npc=18581/alliance-field-scout.)
[//]: # (https://imgur.com/a/puI0UrN
https://imgur.com/a/V2jaUuS)
[//]: # (Write your tickets according to the format:)
[//]: # ([PVP objective][Zangarmarsh] Capture/Control Twinspire Ruins)
[//]: # ([NPC] Alliance Field Scout)
[//]: # ([Spell][All] Capture Twinspire Ruins)

**Description**: 
Twinspire Ruins cannot be captured, nor can the NPC provide you with the item to do so. 

**Current behaviour**:
Twinspire Ruins cannot be captured, nor can the NPC provide you with the item to do so. 

**Expected behaviour**: 
Captured Twinspire Ruins, or NPC correctly provides item to allow players to do so.

**Server Revision**: 
3320

**Comment by DaedalusMachina007** [comment]
Since they failed to do so, I'll link to a wiki with some more information of what they're talking about:
https://wow.gamepedia.com/Twin_Spire_Ruins

It is the Zangarmarsh World PvP thing where you capture both towers and then take a flag from the respective faction 'scout' to capture the graveyard.  Once capture, the graveyard permits the requisite faction a shorter path back inside the Coilfang instances after death.

If fixing the actual capture mechanic will be too time-consuming, a temporary workaround can be to just have the central graveyard be faction-neutral and usable by both factions.

**Comment by hederob** [comment]
Also, some players have problems trading with their respective scout vendors when their faction controls the ruins. However, relogging can help fix this issue and they can become tradable again.

**Comment by Wolffenstein** [comment]
Fixed in rev 3328.
