### ISSUE TITLE
[Raid] Lady Vashj - Toxic sporebat spawn points

### ISSUE THREAD

**Issue by Selphius** [Atlantiss/NetherwingBugtracker#6942]
**Current behaviour**:
Toxic sporebats during phase 3 always spawn in 1 location.

**Expected behaviour**: 
Toxic sporebats during phase 3 should always spawn randomly in 1 of several locations across the boss arena.

**Server Revision**: 
3367

**Comment by NatsumeLily** [comment]
The bats only enter the boss area/arena from 1 way (west).

Provide proof if this isn't the case.

**Comment by Selphius** [comment]
Why else would ppl use beast tracking on this phase.
![Screenshot_1](https://user-images.githubusercontent.com/13300602/81550908-38216b80-9381-11ea-85ed-b10c0b9ea5b2.png)

**Comment by eri1997** [comment]
The reason hunters use beast tracking is so that they don't have to keep the camera on a very awkward position to look for the bats before they are even close enough to be in range for the hunters to hit them . Here is a video of bats all coming from the same side .
https://www.youtube.com/watch?v=A1hNKxTsVRg
