### ISSUE TITLE
[NPC] Shadowpine Oracle

### ISSUE THREAD

**Issue by nycheia** [Atlantiss/NetherwingBugtracker#705]
**Description**: 
Shadowpine Oracle in Ghostlands are casting the healing spell Dark Offering on a friendly target.
**Current behaviour**:
At the moment the only chance you get to see them cast this spell, is if you keep them alive at a very low percentage for a while. It will not cast it if you kill it with normal speed, or semi slow speed (like wanding it down/AA's). However some specific oracles, during the escort, did the cast correctly.
**Expected behaviour**: 
It's supposed to cast it when it gets low health. It currently does it way too late.

**Server Revision**: 
2065

**Comment by Tereneckla** [comment]
Got not even a single heal after tanking 5 oracles for 5 minutes.

**Comment by Easyfraggy** [comment]
They only heal below a threshold which is random 75/50/25%. So try tanking one at low hp. At full they wont heal.

**Comment by Tereneckla** [comment]
Yes, slowly brought them down to ~10%. I'm not that stupid.

**Comment by Evolvee** [comment]
well they had
![image](https://user-images.githubusercontent.com/1942409/73597884-66e1a780-4531-11ea-9f1d-ea624721fdde.png)
flag
because the spell should be casted only on allies (not self)

or is that incorrect?

**Comment by Tereneckla** [comment]
I had 5 oracles and still no heal. So something must be wrong, as they haven't casted a spell at all.

**Comment by duzyizly** [comment]
looks like fixed with some recent core update.
tested on ptr 3392.
Oracles are casting dark offering only if there is **"full or close to full hp"** mob near by.
Any oracle can cast it more than once per fight.

![WoWScrnShot_062020_123051](https://user-images.githubusercontent.com/43931626/85199815-ad724b80-b2f2-11ea-885e-6c1b9b99b20d.jpg)
![WoWScrnShot_062020_123057](https://user-images.githubusercontent.com/43931626/85199818-aea37880-b2f2-11ea-9261-7d1dfadc5334.jpg)
![WoWScrnShot_062020_123523](https://user-images.githubusercontent.com/43931626/85199819-aea37880-b2f2-11ea-953f-0a538f2b4aff.jpg)
![WoWScrnShot_062020_123526](https://user-images.githubusercontent.com/43931626/85199820-af3c0f00-b2f2-11ea-90e0-8e0bc6194614.jpg)
![WoWScrnShot_062020_123534](https://user-images.githubusercontent.com/43931626/85199821-afd4a580-b2f2-11ea-81ce-b220686f82c1.jpg)
![WoWScrnShot_062020_123550](https://user-images.githubusercontent.com/43931626/85199822-b06d3c00-b2f2-11ea-892b-b6e6482e6a39.jpg)
![WoWScrnShot_062020_123558](https://user-images.githubusercontent.com/43931626/85199823-b105d280-b2f2-11ea-8d22-65084c5cd8df.jpg)
