### ISSUE TITLE
[Hunter] [Spell] Hunter Macros bugs

### ISSUE THREAD

**Issue by eri1997** [Atlantiss/NetherwingBugtracker#7069]
**Description**: 
- <del>All hunter macros should start with a auto shot that goess off 0.5 secs after you click the macro and a steady that starts right after. On NW all macros start with a steady shot and combined with some other bugs make hunter macros, like 3:2 which gets impacted the most ,unreliable and rng. 1:1 macro doesn't get as heavily impacted by this bug. Assuming no major haste procs or small amount of haste 3:2 macro should lead to a -> "auto-steady-steady-auto-steady" rotation that keeps repeating. Here is a video showing the rotation also look at how the gcd starts when you press the macro and doesn't wait for you to start casting steady but starts as soon as you click it while waiting for the first auto to go off.
https://www.youtube.com/watch?v=cObqUH-zKwg</del> 
Very close to retail now we'll consider this part fixed.

- Spaming your macro in certain positions will cause a GCD even if your spells can't go off.This seems a bit random and can be pulled off in multiple positions just by spaming your ability sometimes you'll get a "target needs to be in front of you" error msg and your gcd won't be spend but sometimes you don't get this error and you lose a gcd even though you aren't attacking the target because you turned your back to it. Video showing the bug :
https://streamable.com/ih2lzp

- <del>Another problem with hunter macros is that sometimes your character fails to fix the position and face himself toward the target when you are using 2 3:2 macros with different /target x on them. This causes you to be stuck in an animation loop similar to the old hunter bug during 2.0 where hunters would get stuck on attack animation loops when switching targets .Also worth pointing out that you sometimes lose a gcd (you'll do 2 auto shots in a row) from spamming hunter macros in target swap situations . This bug is most noticeable on M'uru and KJ ( maybe it has smth to do with a weird angle if you swap from shoting flying orbs to kj ) . It is quite possible this bug might be related with the 2nd bug about gcd I posted above but just to be sure I added this one too in case its a different issue. Clip of the bug ( hunter gets stuck on attack animation when target swapping):
https://clips.twitch.tv/SwissPrettyWolverineResidentSleeper</del> Fix in testing closed until I see it happen again 

<del>It is also important that the bugs that are already reported and I'll list below are as equally important to get fixed as any of them will cause the macro to reset or not do what its supposed to and become unreliable again : </del>

- <del>Read comment bellow the bugreport for this 1:
https://github.com/Atlantiss/NetherwingBugtracker/issues/6906</del> Fixed with the macro rework

- <del>These 2 bug reports for a different gcd issue(not the one explained above):
https://github.com/Atlantiss/NetherwingBugtracker/issues/6142 and https://github.com/Atlantiss/NetherwingBugtracker/issues/5578 </del> ( Might be fixed with latest update requires testing)

<del>If you need more information on how macro rotations shot order goes ,  Cheeky's hunter dps spreadsheet has a shot rotation section that is very detailed with timers to help with that. </del>

**Current behaviour**: 3:2 is unreliable and will even do different shot rotations on different tests without you even changing anything because of different bugs.

**Expected behaviour**: 3:2 doing the correct rotation and hunter macros starting with a auto shot.  No gcds lost for no reason too 

**Server Revision**: latest

**Comment by NatsumeLily** [comment]
> If you need more information on how macro rotations shot order goes , Cheeky's hunter dps spreadsheet has a shot rotation section that is very detailed with timers to help with that.

This is a bug that needs fixing but I would highly highly recommend not relying on cheeky's spreadsheet. It's wrong in many places. One of the places it's wrong in this context would be rotations. It's 1:1.5 rotation is incorrect, it adds in a extra steady/auto that isn't needed.

**Comment by eri1997** [comment]
Mostly focused on 3:2 rotation since that's the hardest to get right and the most important as well ,  the spreadsheet is a lot more helpful to show how the rotation works since it shows timers and the shots hitting. That link is also useful information but not as specific toward timers . I pointed out the spreadsheet to have a reference on how shots rotation should go off.

**Comment by TheMoneyHater** [comment]
Yes this needs fixing.
https://streamable.com/6lg3jf
https://streamable.com/am4cjh
u shouldn't be getting these full gcd. Ofc the autoshot can push it forward but here it is taking much longer for it to do so then on retail. Its like its removing the next one in the que if it have been pushed forward with a autoshot but still using the gcd.

This is the proof: https://youtu.be/cObqUH-zKwg
As you can clearly see if u slow it down he never gets a full gcd between the steadyshoots.

**Comment by Wolffenstein** [comment]
Please retest in rev 3420.

**Comment by TheMoneyHater** [comment]
@Wolffenstein What exactly did u change? It seems to be working worse now.
Those wrongly/fake gcds are a huge issue to the gameplay since 3:2 rotation is not playable with this being the case.

**Comment by Wolffenstein** [comment]
Another round of changes, what's the verdict now?

**Comment by eri1997** [comment]
Updated the bugreport with the new fixes . 3:2 macro now is much better.

**Comment by ZhengSim** [comment]
Latest fix caused a new bug. Casting **any** shot right at the end of your auto shot swing time will somehow cast a steady shot instead of the initial spell. Easy to replicate.

**Comment by eri1997** [comment]
@Wolffenstein Not sure what has changed in Karazhan but macro is broken again after the first auto - steady it keeps doing 2 steady 1 auto all the time   without haste effects with a 3.0 wep . Didn't do that when we were testing it on the ptr :( I'm assuming smth gcd related has changed but just a guess, hard to test without training dummies on karazhan

**Comment by eri1997** [comment]
This is how the 3:2 macro works atm in Karazhan : https://streamable.com/uv33vl
This is how it worked in ptr much better version (wolf's testing) : https://streamable.com/xay3bu
Idk what change broke it sometime between ptr and karazhan release but the macro is shit and useless atm with a 3.0 speed wep. Tried a few slightly faster weps and even though they were also broken they managed a slightly closer steady/auto % to the macro version which is completely the opposite of what should happen.

**Comment by raethkcj** [comment]
I lined up your videos to start the rotation at the same frame. 
https://drive.google.com/file/d/18c4KaeWohZYHoF_CJTQ1gNIM_KnRQEQX/view?usp=sharing

What it looks like to me is:

**Macro _does not_ work**
You are allowed to queue Steady Shot during your previous GCD, so that as soon as your first GCD ends, your second GCD and cast begins. 

**Macro _does_ work**
You are not allowed to queue a second Steady Shot during your previous GCD, so your second GCD does not begin until your next button press *after* the first GCD has been completed. This means that your second Steady Shot is delayed by ~200ms in this clip, and would be dependent on exactly how fast you mash your button.

What this means is that when you finish casting your 3rd Steady Shot in the rotation, that ~200ms delay causes your button press to occur after your auto windup has begun.

So the question becomes: **did retail TBC allow you to queue your next ability during a GCD?**

The implications of this are beyond steady shot; it means that when you want to cast any 2 GCD spells back to back, you will always be susceptible to this delay. This has a significant impact on things like Affliction lock, or a shaman dropping 4 totems in a row.

**Comment by raethkcj** [comment]
I lined up the two videos to start the rotation at the same frame:   https://drive.google.com/file/d/18c4KaeWohZYHoF_CJTQ1gNIM_KnRQEQX/view?usp=sharing

After watching it through frame by frame, it looks like the current bug on Karazhan is that the GCD for a second Steady Shot can begin while the first Steady Shot is still casting. In the top picture below, note that there are 0.2 seconds left on the Steady Shot cast, but the GCD for the next cast has already begun.
![image](https://user-images.githubusercontent.com/7716908/93409952-a610fe80-f85d-11ea-80db-a14773218da7.png)

Because of these early GCDs, the hunter is able to queue Steady Shot a couple hundred milliseconds before they should be able to. This means that a 4th Steady Shot is queued during the 3:2 rotation when normally it *might* not be able to.

**Comment by raethkcj** [comment]
After talking with another hunter and doing some tests, my theory is it's a side effect of the way shot queuing during auto windup is implemented.

In order to allow hunters to cast Steady Shot during Auto windup, you need a 500ms window where early GCD is allowed. This window is improperly being applied to *all* hunter casts instead of just Auto Shot.

**Comment by Wolffenstein** [comment]
Fixed in rev 3869.
