### ISSUE TITLE
[NPC] Stable Master

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#7109]
**Current behaviour**: If u Dismiss your pet cant take the other from the Stable Master.
https://streamable.com/4x3k9w
If u open the Dialog and the mount up...it bug out again.
https://streamable.com/ed4ugb
From Classic
https://cdn.discordapp.com/attachments/720108220261072926/729020771959177226/unknown.png
https://cdn.discordapp.com/attachments/720108220261072926/729020863483084890/unknown.png

**Expected behaviour**: No matter if the pet is summoned or not,u still own the pet and suppose to be able to swap them.

**Server Revision**: 3436

**Comment by The14me** [comment]
May be related issue's
https://github.com/Atlantiss/NetherwingBugtracker/issues/4448
https://github.com/Atlantiss/NetherwingBugtracker/issues/1187 (not sure how they talk with stable mounted...since at the moment u click to talk=dismounted)

**Comment by Zarant** [comment]
On the classic beta, whenever you spoke with a stable master your pet would be summoned right away and whenever you dismissed your pet, the stable window closed.
I guess a simple fix to this issue is to dismount you + summon your pet whenever you speak with a stable master and close the window whenever your pet is dismissed.

**Comment by Wolffenstein** [comment]
Fixed in rev 3450 (sort of).
