### ISSUE TITLE
[Class] Shaman [Spell] Searing Totem

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#7115]
**Current behaviour**:Searing Totem attack CCed target.
https://streamable.com/vedx1q

**Expected behaviour**: It suppose to ''ignore'' that target.
https://www.wowhead.com/forums&topic=4379#p80592

**Server Revision**: 
2.0.3

**Comment by Wolffenstein** [comment]
https://wowwiki.fandom.com/wiki/Searing_Totem says otherwise - "You should avoid using it in situations where it could accidentally hit a target that shouldn't otherwise be hit (such as something that has been CC'd). ".

Either way need source that Fear should count as the CC that causes the target to ignore the Totem.

**Comment by Wolffenstein** [comment]
https://www.wowhead.com/forums&topic=43494/how-to-control-searing-totem

![obraz](https://user-images.githubusercontent.com/1576644/86518067-92452700-be2e-11ea-94da-9a219ed16b52.png)

**Comment by Drayo** [comment]
One small exception: While Searing Totem does attack CC'd mobs, it should ignore neutral mobs until they get in combat with the player.

It was reported to be "not working" over here: https://github.com/Atlantiss/NetherwingBugtracker/issues/393

**Comment by The14me** [comment]
Just wanted to note that yes.
''  Also note that the totem only engages hostile targets on its own; it ignores neutral targets unless you engage them first. ''
https://wowwiki.fandom.com/wiki/Searing_Totem
