### ISSUE TITLE
[Item] Noggenfogger Elixir and Druid Forms

### ISSUE THREAD

**Issue by norbinorbert** [Atlantiss/NetherwingBugtracker#7400]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Noggenfogger Elixir doesn't work properly with Druid forms.

**Current behaviour**: If a Druid drinks Noggenfogger Elixir and turns into a skeleton, the skeleton form doesn't persists in Cat/Bear/Travel form

![Desktop Screenshot 2020 08 16 - 23 10 09 98](https://user-images.githubusercontent.com/47588133/90343136-6d8bc400-e016-11ea-852c-a5d283d16ae6.png)

**Expected behaviour**: If a Druid drinks Noggenfogger Elixir and turns into a skeleton, the new form should replace all other forms

**Server Revision**:  3511

**Comment by Tereneckla** [comment]
If you shapeshift while wearing any disguise, your form buff will remove the disguise buff. This is because it has a blanket effect and can cause unexpected bugs when two buffs are stacked. Items like the  [Noggenfogger Elixir] were changed in 2007 to not stack with Druid forms so that it would not cause any future problems.

https://wow.gamepedia.com/Druid#Shapeshifting
