### ISSUE TITLE
The Silithus PVP quest 'Scouring The Desert' is not given after turning in breadcrumb quest to General Kirika

### ISSUE THREAD

**Issue by rotorcraft621** [Atlantiss/NetherwingBugtracker#7438]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Silithyst quest in Silithus is unobtainable, Level 60 (Requires 54). I am currently level 60, Horde.
**Current behaviour**:
Quest 'Scouring The Desert' is not offered after turning in 'Report To General Kirika'
**Expected behaviour**: 
'Scouring The Desert' is offered right after turning in 'Report To General Kirika'
See the following: https://wow.gamepedia.com/Scouring_the_Desert_(Horde)
**Server Revision**: 
2.0.3

**Comment by duzyizly** [comment]
As today rev 3651 the quest is still not avaible.
Due to thottbot comments it should exists post vanilla.

But you are able to pick up silithists and bring it back to the camp for cenarion circle reputation. Your faction also recive +1 silithists collected.

![image](https://user-images.githubusercontent.com/43931626/219367959-1c5e4ac6-0bb2-4cf9-8795-b39a2cd7fdac.png)

**Comment by Godmatik** [comment]
Fixed in #8203

can close
