### ISSUE TITLE
[Spell][Rogue] Wound poison proc without melee attacks

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#7510]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Somehow some rogues can abuse "wound poisons" and drop 4 stacks with 1 shiv. As you can see in the video bellow wound poison procs without melee swing. You can see the screenshots bellow there's no melee attack on procs or follow the combat log after the arena in the video.
**Current behaviour**:
https://drive.google.com/file/d/1VN_UpqcAEmrJC3AjyZdqabAar0Kb6f5I/view?usp=sharing
![rank1rogue](https://user-images.githubusercontent.com/52432938/92388972-d13e7400-f120-11ea-81a2-544bc47029c2.jpg)
![rank2rogue](https://user-images.githubusercontent.com/52432938/92387233-d77f2100-f11d-11ea-8674-b70894f94fe4.jpg)
**Expected behaviour**: 

**Server Revision**: 
3519

**Comment by 4egito** [comment]
![image](https://user-images.githubusercontent.com/52432938/92950554-821c7a00-f465-11ea-9a1e-c515ad0c64bc.png)
Tell me please how i get 3 wound poisons with 1 shiv and no melee hits between procs?

**Comment by JohnEU** [comment]
Right at the start you get:
-20 (wound) partly resisted (from Cheap shot)

Then I see
-65 (hit)
-63 (wound)
-80 (pain)
-63 (wound)
-63 (wound)
-84 (hit)

almost at the same time.

Then a little later I see 
-319

which I assume is the shiv. The shiv arrives in the combat log VERY late. But you are clearly shived right from the start in the 2nd global from rogue.

I simply would not trust the exact timing of the combat log. It is very common for rogues to see their white hits much later than when they actually did damage.

**Comment by Tereneckla** [comment]
Standing at an angle to not allow autoattacks. Only using shiv.

2 Weapons with Wound Poison
![image](https://user-images.githubusercontent.com/50233983/92993016-0c5cf080-f4ef-11ea-8cb6-98962587c4e0.png)

Wound poison only on offhand.
![image](https://user-images.githubusercontent.com/50233983/92993028-2d254600-f4ef-11ea-8aec-4480edf3dc3a.png)

Double Deadly Poison
![image](https://user-images.githubusercontent.com/50233983/92993101-a2911680-f4ef-11ea-8ce8-7799de40bb5c.png)

Double Instant
![image](https://user-images.githubusercontent.com/50233983/92993145-e257fe00-f4ef-11ea-8a98-239b84d90898.png)

Current:
It seems to have a chance to proc the mainhand poison if it is the same as the offhand poison.
The guaranteed poison application seems to be in addition the the proc chance right now.

Expected:
Shiv does not proc the mainhand poison if it is the same as the offhand poison.
Shiv overrides the offhand poison proc chance to 100% instead of allowing double procs.

**Comment by Wolffenstein** [comment]
Fixed in rev 3532.
