### ISSUE TITLE
[Spell][Mage] Clearcasting/arcane missiles interaction

### ISSUE THREAD

**Issue by Fierywind** [Atlantiss/NetherwingBugtracker#7607]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Arcane missiles should have a single 10% chance to proc clearcasting at the start of the channel, and not per missile

**Current behaviour**: Clearcasting appears to be coded as an on-hit effect, so has a chance to proc every missile hit

**Expected behaviour**: https://www.youtube.com/watch?v=c2RtyFh5TnE it was coded as on-cast, despite its wording, so only had one chance to proc at the start of the channel, before any missiles go out

**Server Revision**: 3536

**Comment by Ceago** [comment]
Per patch 1.9 "Arcane Missiles - Will now be able to trigger procs based on dealing damage."
Per patch 3.0.8 "Arcane Missiles: This spell now only has one chance to trigger Arcane Concentration."

This suggests to me that it was indeed able to proc clearcasting off of each missile hit instead of only once per cast from patch 1.9 to patch 3.0.8.  You can also see in the video that he is building stacks of The Lightning Capacitor off of crits from individual missile hits and clearcasting shouldn't function differently.

**Comment by Fierywind** [comment]
I've seen the argument made, but the evidence from both period forum conversation and video that clearcasting, despite its wording of being on spell hit, was coded to be on spell *cast*, which exempts it from the 1.9 change. Those other effects working on hit are correct.

**Comment by arcwizard** [comment]
>[Pendant of the Violet Eye] and [Mark of Defiance] as well, since (last I checked the threads anywho) they're both proccing off every AM tick. (https://web.archive.org/web/20071222211936/http://elitistjerks.com/f31/t10907-vontre_s_mage_dps_spreadsheet/p10/  Look 239 message from Vokzhen (< Wraith >, Spinebreaker) at 08/28/07, 2:41 AM.)
Why i wrote this? Because in the description for both items says: "Each spell cast...", but that man say about proc from each missile. So with clearcasting there may be the same interaction.

**Comment by Fierywind** [comment]
Regardless of any other interactions, I provided clear evidence of how it works in the form of the linked video from tbc, and it currently behaves the way shown in that video in classic. There's no evidence anywhere it has ever procced per missile except on private servers.

**Comment by Ceago** [comment]
@Fierywind Besides it being explicitly stated in the patch notes.  I did more of a dive on the arcane missile interaction and found in the threads on other servers the same back and forth we are having here.  While you provided a video showing it proccing near the start that is not evidence enough to discredit something being specifically called out in the patch notes.

I'd say this would require more research before any change is warranted.

**Comment by Fierywind** [comment]
If the 1.9 patch actually had the effect you believe it did with clearcasting, it would function as it does on karazhan in classic, but the truth is it doesn't and it's not a bug. @Ceago

**Comment by Ceago** [comment]
Classic has been wrong before and can't be used as a source 100%.

**Comment by Fierywind** [comment]
I can't find any in-game evidence in classic that it's anything more than a 10% chance per arcane missiles cast, let alone the 50% you seem to be implying.

https://www.youtube.com/watch?v=K4RjdUHbA8Y

Here is a video from at least 1.10 or later because it's a tier 0.5 boss, where the one clearcasting proc he gets from arcane missiles has the same timing as the tbc video, as the first missiles goes out - he gets one proc in what I counted as 12 casts, in line with 10% chance per cast but far below the 50% per cast value.

https://www.youtube.com/watch?v=Mlh8lSaBqPk

3 AM casts, one proc at the same timing.

https://www.youtube.com/watch?v=6za6zGkfhTk

21 casts, 2 procs at the same timing.

**Comment by Fierywind** [comment]
It appears to have been controversial on other pservers and even in classic, but I note that no one who asserts it's per missile can provide any video from vanilla or tbc to support that it works that way.

**Comment by Ceago** [comment]
I think you may be correct that it is on the initial cast but I'll have to do some more digging on if the clearcasting was cumulative or if it was just 10%.  I know that AM spam spec was very popular early in TBC before they changed internal cooldowns on things like The Lightning Capacitor and spamming AM with only a 10% clearcast is almost insta oom regardless of your group comp.

Also the guy in the reddit thread is insinuating on classic it is 50% at the start, counting for each missile, rather than 10%.  This would satisfy both of our thoughts making both the patch notes and the videos correct.  I dont have a mage available on classic to test it but I can look around.  Also will do some more digging in the elitistjerks threads.

As of now like I said above I think it's still in the "needs more research" state.

**Comment by Ceago** [comment]
Now this is gonna drive me crazy because I feel there is information missing that can't be recovered.  Starting right around patch 2.2 the whole arcane thread discussion shifted to arcane missile spam and how good and mana efficient it was now.  

http://web.archive.org/web/20120810160355/http://elitistjerks.com/f31/t13190-mage_how_can_arcane_damage_work/p105/

But many pages are missing sadly.

**Comment by Tereneckla** [comment]
https://wow.gamepedia.com/Talk:Arcane_Missiles#Arcane_Missiles_with_Clearcasting

The 3.0.8 change likely was a bug that emerged with wotlk

One 10% proc chance on mana consumption
30% increased crit applies if the buff is active or was consumed for that cast or arcane missiles (probably stacking if both apply)

**Comment by Wolffenstein** [comment]
Fixed in rev 3717.
