### ISSUE TITLE
Stealth or Stealth detection is way off right now.[stealth] [spell] [core]

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#7611]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
ever since some fix made recently opening on certain classes with stealth detection basically an impossibility.  it is possible if you open in the same packet you reach the target but shadowstepping a warlock / hunter with alert pet is instantly out of stealth.
Sure, increase the BASE stealth detection as you intended, don't overbuff all other sources of stealth detection in the same go.
This is with 5/5 MoD, and the master's threads.
**Current behaviour**:
rogue PoV https://streamable.com/fyjhcb
lock PoV https://gyazo.com/edea25ad0f39733bfdf578c8cb920199
https://streamable.com/gwq98l @33 seconds showcasing aoe cone
longer vid showing the bullshit of current detection cone, he gets a 360 giga detection cone, while his main frontal cone barely increases. afaik stealth detection should give VERY slight increase in AoE cone, and a stronger effect on frontal cone (90degrees or smth)
Detecting people from behind like that would be like a lvl 80 dueling a lvl 60
**Expected behaviour**: 
any stealth detection =! sentry vision
**Server Revision**: 
3536

**Comment by knasen88** [comment]
https://web.archive.org/web/20070127193643/https://wow.ingame.de/guides/sonstige/stealth.php
source for detection not working behind target
some more
https://web.archive.org/web/20150926155935/https://www.wowhead.com/forums&topic=7506/druid-guide-part-1-overview-class-mechanics-leveling
https://wow.gamepedia.com/Stealth?oldid=1421708

**Comment by Tweet1337** [comment]
Where are the sources? I read the whole 1st link and didnt read a single word about stealth detection not working at all from behind.

This is not how a bugtracker works.

___

Here a 100% blizzlike article about stealth from 2010 (stealth was buffed in 2012, but remained unchanged in terms of strength from classic until MoP - see - https://wow.gamepedia.com/Stealth)

https://www.engadget.com/2010-03-10-encrypted-text-stealth-mechanics-deep-dive.html?guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAKLWrCpVoPDyPHH0hrW-LdGWhSBZzmAJnrGJFhMJ-egwG28qziFwcdlVzhXX4-Bl0nbI8TOO7tnonuM7bSLQ7WM5SOr0BAs5JKVtyFWpr1x5wNaHAJwa0c_cx3aAbEJy7FqUfiLs32e2VUEvaGmHmCvSGID51VBqq443gJE3BEdM&guccounter=2

_Quotes:_

"We can avoid all detection by staying behind our enemies, although every player has a small sphere of detection with about a 2 yard diameter. If you're in that 2 yard sphere, on any side, you'll be detected."

"Enemies that are below your level have a less-than-normal chance to detect you, though the 2 yard sphere will cause you to be detected no matter what."

"The trick is to avoid stepping into the 2 yard detection sphere, and since we can attack from 5 yards away, there's no real reason for us to get that close anyway."

___


And now the interesting part:

Shadowstep-Range to target is exactly 2 yards.

Sources:

https://www.wowhead.com/spell=36563/shadowstep
https://www.wow-freakz.com/spells.php?spell=143285&name=shadowstep
https://wotlk.evowow.com/?spell=36563
https://wotlkdb.com/?spell=36563
https://wotlk-twinhead.twinstar.cz/?spell=36563
https://wotlk.cavernoftime.com/spell=36563

Shadowstep-Sap vs. Warlocks or Hunters with aggressive pets (and even boostet stealth detection) isn't supposed to work. You have to Pre-Vanish+Shadowstep or Pre-Vanish+Sprint or Distract+Sprint for a Sap. For this behaviour you also find dozens of sources from back in the day.

**Comment by knasen88** [comment]
it's in chapter 4 of the german link, where he describes how it has near zero effect in the last quadrant behind the player. 
If shadowstep makes you get to close so that you enter their 2yd bubble that every player should have, then it would mean shadowstepping any player even without detection you would enter their holy sphere of detection and get outed. 
This 2yd sphere aswell as you say is detection no matter what, then why would a pre vanish even help? 2yd = detected. Your source even say this. Clearly this was never the case with step back then.
googe translate:
> On the back 90 ° you practically do not notice any effect of stealth discovery - there, as on 360 °, the following applies in general: At a distance of about 2 yards you will be discovered at the latest. The melee range starts at 5 yards.

For the second link just ctrl+f stealth and you get this
> Stealth decreases the range at which players and mobs can see you (and thus, react). Druids have an invisible "stealth skill" called Subtlety that doesn't appear on their character sheet and always increases by 5 for each level (thus at level 70 you have a base Subtlety skill of 350). All characters also have a Stealth Detection skill, which also doesn't appear on their character sheet and always increases by 5 for each level (thus at level 70 you have a base Stealth Detection skill of 350).

> At equal levels of Subtlety and Stealth Detection, a stealthed character can be seen 5 yards away. Each 5 points of skill changes that range by 1 yard either way, up to a maximum of 10 yards and a minimum of 1 yard. So for example:

    If a stealthed cat has a Subtlety of 350, a Stealth Detection of 340 could only see him 3 yards away
    If a stealthed cat has a Subtlety of 350, a Stealth Detection of 365 could see him 8 yards away
    If a stealthed cat has a Subtlety of 5, a Stealth Detection of 400 could see him 10 yards away

> Keep in mind that Stealth Detection only works for your frontal 180 degree cone. A level 1 cat could sneak up on a level 70 human warlock with Perception popped, Hyper-Vision Goggles, a Catseye Elixir, and a Felhunter out, and still be undetected as long as the cat approached from behind.

and this potentially reveals another huge part of stealth if it is correct, No further than 10 yd no matter the detection vs stealth skill? perception + paranoia is basically sentry vision in all angles and nobody bats an eye.

This _should_ be kind of easily testable in classic wow as stealth didn't change much over the years. The only thing missing would be shadowstep.
if a low level can sneak up on a higher level from behind it's pretty clear cut case that from behind you got zilch.

**Comment by Tweet1337** [comment]
> If shadowstep makes you get to close so that you enter their 2yd bubble that every player should have, then it would mean shadowstepping any player even without detection you would enter their holy sphere of detection and get outed. 

if you would stay there  after shadowstep instead of opening (what you ofc dont)-> yes then also players without any detection should see you and be able to attack you. the important part here is the pet, which is on aggressive mode. in the very first moment you are "visible" it will attack you.

> This 2yd sphere aswell as you say is detection no matter what, then why would a pre vanish even help? 2yd = detected. Your source even say this. Clearly this was never the case with step back then.

https://github.com/Atlantiss/NetherwingBugtracker/issues/3466
on karazhan you can't see players who used vanish
if that's blizzlike or not -> hard to say

> and this potentially reveals another huge part of stealth if it is correct, No further than 10 yd no matter the detection vs stealth skill? perception + paranoia is basically sentry vision in all angles and nobody bats an eye.


well, different story, but for a change like this (10 yard max range) -> there probably have to be 100% sources. but thats another story.

but i dont see, what youre meaning with sentry vision, screenshots from you own recorded video, to showcase on which range the pet attacks you, when coming from behind - first screenshot pet still standing there, second screenshot pet tries to attack you:

https://i.imgur.com/ugnfMix.jpg

https://i.imgur.com/Uqv6Kr3.jpg
