### ISSUE TITLE
[SSC] Hydross the Unstable, crushing attacks

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7620]
Hydross is able to crush tanks, he should not be able to crush, he should only do elemental damage that can not be blocked or be crushing hits.

>Water form
Melee: 5.5k frost damage base, cannot be blocked, cannot crush

>Poison form
Melee: 5k nature damage base, cannot be blocked, cannot crush

https://www.wowhead.com/npc=21216/hydross-the-unstable

**Comment by Godmatik** [comment]
Guess I just read that it is intended to crush until 2.1  ... rip

**Comment by Godmatik** [comment]
Re-opening for consideration, the boss crushing is a literal pure RNG element that can potentially one-shot a resistance capped tanked when in mark 3 or 4 during the encounter if only 25% of the damage of the crush is resisted, and there is nothing you can do when it happens.

It wasn't fixed in 2.1, it was corrected in a hotfix between 2.0 and 2.1.

**Comment by Tenoutoften** [comment]
This has been discussed in https://github.com/Atlantiss/NetherwingBugtracker/issues/5530

I don't think crushing makes a fight hard or not, if anything it forces two scenarios:

1.  You reduce the damage to account for the crushing blows that will happen => Result is an overall rather easy fight with low damage incoming
2. You don't reduce the damage to account for the crushing blows that will happen => Result is a boss that, if tuned in such a way that the normal hits are suppose to be challenging, it's crushing blows will one shot. 

Maybe I got this wrong, perhaps someone can give further insight?

**Comment by Fierywind** [comment]
Hard would definitely seem to imply that there's some challenge you have to overcome - but there's no overcoming a crush one-shot. Why not revert the melee damage nerf he just received, and instead remove crushes?

**Comment by OffeSwedin** [comment]
We have been progressing on this boss for two weeks now and are hard stuck by tanks just getting constantly oneshot. We wiped today because tank got one shot on 1-2 stacks because the resistance rolled a low resistance roll and then crush on top of that which resulted in a 15k+ crush.

If you want to make the fight more challenging then including crush is not the way to go in my opinion. Feel free to increase overall boss dmg or increase hp on the boss. 

Now its just left to pure rng and its already starting to cause a lot of frustrations in our guild because it feels like we are literally just playing the lottery. We have had perfect tries with the boss down to 30% and then the main tank just get oneshot and its over.

Please do something, anything :)

**Comment by dshgrove** [comment]
Other guilds have been able to kill this boss and are farming him without problems.
There are other bosses that do crushing blows that would oneshot a tank aswell, using warrior tanks that keep shield block up is a popular way of avoiding this. We very rarely have had our tank get oneshot by crushings, usually due them not keeping shield block up. Speaking from experience, since i am usually the frost resistance tank on Hydross.

This was the case on Netherwing aswell, Hydross got "nerfed" going into 2.1 by removing crushings, but they were a thing in 2.0.

**Comment by Godmatik** [comment]
We've killed him as well, but that doesn't change the substance of the argument, a random 1-shot crush can still occur on good attempts, or you can have good RNG and not experience it.

Also, you can not block elemental attacks, so shield block is useless and does not prevent crushes for this fight.

**Comment by Godmatik** [comment]
Yes we've killed him as well, and guilds are farming him, but still experience the random 1-shot crush - it can still happen on good attempts, or you can have lucky RNG and not experience it. Doesn't change the substance of the argument.

> very rarely have had our tank get oneshot by crushings, and it has usually been because they have not kept shield block up.

You can not block elemental attacks, so shield block is useless and does not prevent crushes for this fight and negates that part of your argument.

**Comment by dshgrove** [comment]
Alright, my bad about the shield block part. I do still not think this is a bigger issue then tank getting oneshot by RNG on FLK or Prince.
My comment was mainly towards OffeSwedin about them being hard stuck on the boss for two weeks only because of their tank getting one-shot. There is an RNG element to it, although i don't really believe that tanks getting oneshot would be the only reason they are stuck on it. During our week of progression and 3-4 kills on farm i can count on one hand the amount of times this has happened.

**Comment by OffeSwedin** [comment]
Ofc we have died a lot to other things also, but having the tank get oneshot on the "good trys" is frustrating. 

And like others have said either, it doenst make for a fun challenge. Its just RNG at this point, pulling the boss over and over and hope the tank doesnt get oneshot basically.

**Comment by Fierywind** [comment]
Actually, good gearing and smart use of buffs (chaining imp loh, armor scroll, imp devo, pre-healing to get inspiration rolling, etc) has been enough to mostly avoid tank oneshots - it's just a question of stacking enough mitigation. There is no way to avoid this hydross issue given the gear requirements for resistance. We weren't hard-stuck by any means, we killed it on our 2nd night of attempts, but I also see no reason this should persist when it can be made challenging in a healthier way.

**Comment by Onsty** [comment]
yea man, stacking armor is really "smart idea", considering boss doing magical damage not physical.

p.s amount of nature/frost resist is your armor on this boss.

**Comment by dshgrove** [comment]
@Onsty I think you should read his message again, he is pointing to how the damage from FLK can to some degree be mitigated while the damage from Hydross can not.

@Fierywind as you say this is enough to _mostly avoid tank oneshots_. Just like on Hydross this still happens if you stack enough mitigation, it is still down to rng with how many windfury hits you get in a row and whether or not you are able to mitigate some of them. It is annoying when it happens on both fights, but i still don't think it is as big of an issue as what has been stated here earlier.

**Comment by Onsty** [comment]
ohh, yea i get it
@Fierywind my bad

**Comment by Fierywind** [comment]
I mean I don't think it's make or break, but it *was* hotfixed like 1-2 months before 2.1, and they have already shown a willing to adjust the fight pre-2.1 by nerfing his melee damage by 10%, so in my mind it just makes a lot more sense to revet the previous nerf bu remove his ability to crush, leading to a fight I don't think will be more *difficult* but one that can be more consistently cleared once you have it down. @Onsty

**Comment by Godmatik** [comment]
2.0 is done, so closing...
