### ISSUE TITLE
Drakefist Hammer - cannot create second one

### ISSUE THREAD

**Issue by Xyston15** [Atlantiss/NetherwingBugtracker#7691]
https://www.wowhead.com/item=28437/drakefist-hammer#created-by-spell

**Description**: 
Second Drakefist Hammer cannot be created.
**Current behaviour**:
When you try to create, game says "can't carry anymore those items".
**Expected behaviour**: 
On the item it does not say "Unique" or "Uniquely equipped". You should be able to have unlimited amount of these. Maybe this happens to other Weaponsmith weapons, have not tested it.
**Server Revision**:

**Comment by raethkcj** [comment]
Blacksmithing weapons are Unique until Patch 2.4. 

To see the proper stats and tooltip, you'll need to close the game, find its folder, and delete the Cache folder.

Because Karazhan uses progressive itemization, you will need to delete this folder each time that a new patch comes out. Patch 2.1 itemization is being released on November 11th, so you will need to do it again after that date:

https://atlantiss.org/news/344/attunements-and-content-adjustments
