### ISSUE TITLE
([Quest][Shadowmoon Valley] dissension amongst the ranks..)

### ISSUE THREAD

**Issue by khs001m** [Atlantiss/NetherwingBugtracker#7701]
**Description**: 

This quest should be counted as kill the "crazed colossus" while equipping the Tabard (given by quest NPC) gives a buff for transform into an agent of illidan.

when equip the tabard, transform buff pops, however, count when kill the giants is not worked even clear that area.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Wolffenstein** [comment]
It works fine. Perhaps you were in a raid and it didn't count.

**Comment by therealCrysis** [comment]
https://youtu.be/AzHL7Q2A8b4

So it actually DOES not work properly. Every problem with credit for killing giants (19823) is based on player's death.
Basically you equip this tabard (you receive it with quest) and you kill giants, credit goes normally. But if you wipe and then revive to try again with tabard equipped - you will NOT be creditted, because disguise buff disappears after death. So you need to reequip tabard and then everything seems to work fine.

The question stands how it works in party, but making this buff stay after dying would probably fix everything.

**Comment by therealCrysis** [comment]
@danbopes

**Comment by Godmatik** [comment]
Rev 4018 still an issue
It's also a problem if you are grouped with someone who does not have the quest. Their killing blows do not count toward quest credit.

**Comment by Godmatik** [comment]
Will be fixed in upcoming server update, the spell for the disguise has been fixed.
