### ISSUE TITLE
[Quest][Aldrassil] Webwood Venom

### ISSUE THREAD

**Issue by Ulrik85** [Atlantiss/NetherwingBugtracker#773]
[Quest][Aldrassil] Webwood Venom

**Current behaviour**: Requires level: 1

**Expected behaviour**: Requires level: 3

**Comment by tcberk12** [comment]
Any source?

**Comment by tcberk12** [comment]
https://web.archive.org/web/20080915224630/http://thottbot.com:80/q916

seems to validate.

**Comment by Shanghi** [comment]
This one was hard to decide about. It was set as 1 because of these things, but maybe my reasoning was flawed:

The Official Strategy Guide shows the minimum as 1. The Master Guide shows it as 3. The followup quest is shown as 1 in both so the 3 doesn't really make sense.

Wowhead/Thottbot/Allakhazam minimum levels can't always be trusted, especially for very low level quests where most people will be a higher level before seeing it. On a lot of quests each site will have a different minimum and sometimes they'll be lower when you go forward in time as they get more data (but unfortunately not in this case until cataclysm). On the followup quest, [Wowhead](https://web.archive.org/web/20080221014255/http://www.wowhead.com:80/?quest=917) shows the minimum as 1 and [Allakhazam](https://web.archive.org/web/20071104071134/http://wow.allakhazam.com:80/db/quest.html?wquest=917) shows 2, which should both be impossible if the first one is 3!

**Comment by Wolffenstein** [comment]
I agree with Pyralis. Let's go with 1.
