### ISSUE TITLE
Hunters pet dont respond to taunt

### ISSUE THREAD

**Issue by mirosvk1** [Atlantiss/NetherwingBugtracker#7730]
[//]: # (https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/111057-guide-warrior-arena-pvp-guide.html)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Pet Taunting- Pets are not immune to taunt, be it the normal one or the aoe one. Use this to your advantage to buy your healer a little extra time to go drink/get away, or to line of sight it to kill it. Also aoe taunt can be used when charging a hunter that you know has placed an ice trap. Hit the taunt right before you get to the hunter and the pet will have no choice but to attack you and break the trap.
**Current behaviour**:
With a guilde i tested it, pet doesnt respond to any tipe of taunt, and we tested it on all pets stences (agresive, defensive or passive)
**Expected behaviour**: 
if pet is taunted right before warr enter the trap, pet should not stop attacking warr and break cc
**Server Revision**:

**Comment by tsuone** [comment]
@mirosvk1 They respond only to pets set for Aggresive and Defensive stance.

On top of that, each of the "Taunt" ability has different effect on the pet.

For example:
- Mocking Blow should force the pet to attack the player only for the duration of the Mocking Blow debuff on the pet.
- Challenging Shout should force the pet to attack the player for the duration, during that time player has to build enough threat to be first on the pet threat list, otherwise pet will stop attacking the player after the duration of the debuff.

@mirosvk1 I am closing the issue. If you can provide with video of the bug I am gonna reopen it.

**Comment by tsuone** [comment]
@mirosvk1 They respond only to pets set for Aggresive and Defensive stance.

On top of that, each of the "Taunt" ability has different effect on the pet.

For example:
- Mocking Blow should force the pet to attack the player only for the duration of the Mocking Blow debuff on the pet.
- Challenging Shout should force the pet to attack the player for the duration, during that time player has to build enough threat to be first on the pet threat list, otherwise pet will stop attacking the player after the duration of the debuff.

@mirosvk1 I am closing the issue. If you can provide with video of the bug I am gonna reopen it.
