### ISSUE TITLE
Rogue  weapon a1  bug

### ISSUE THREAD

**Issue by fulerst34** [Atlantiss/NetherwingBugtracker#7851]
this weapon dont have any stat  [Gladiator's Pummeler] 189-285    Melee stat  449-546   this weapon  have stat  [Drakefist Hammer]  153-285 Melee stat   423-561  pls  tell me how it  work   ,  then i change weapon   my max  dmg in melee  stat  change in downward      how it can be  if  weapon  have  equal  maxdmg  285 and  pvp weapon have somestat         Unlike [Gladiator's Pummeler]  how  it work      how is the counting

**Comment by raethkcj** [comment]
Drakefist Hammer has a slower speed than the Pummeler, therefore it gains more damage per swing from your Attack Power. These numbers aren't perfect because of rounding, but here's an example:
![image](https://user-images.githubusercontent.com/7716908/103385906-07ce3f00-4ac2-11eb-8aaf-727e22f38df9.png)
