### ISSUE TITLE
GetSpellCooldown() returning nil for Faerie Fire (Feral) rank 4

### ISSUE THREAD

**Issue by MecAtlantiss** [Atlantiss/NetherwingBugtracker#7857]
**Description**: Cannot use GetSpellCooldown() to determine if Faerie Fire (Feral) rank 4 is on or off CD.

**Current behaviour**: 

Faerie Fire (Feral) has spellID 17392 and the following script returns nil, when it should return 0 if spell if off CD or length of CD if spell is on CD.

`/script local start, duration = GetSpellCooldown(17392); print(duration);` is returning nil

This script works for all other spells I've tried, such as War Stomp. 

I am sure that I have the spell ID correct, because I ran an event trace in-game and it shows spellID in argument 9:

![unknown](https://user-images.githubusercontent.com/16357005/103465714-756dab80-4d0c-11eb-80b0-c83a79f86d5b.png)

**Expected behaviour**: I think this API command should work for Faerie Fire (Feral). I don't understand why it works for other spells on my character, but not this one. I have not tested it on Faerie Fire (Feral) rank 5 yet...

**Server Revision**: 3578

**Comment by raethkcj** [comment]
`GetSpellCooldown()` doesn't accept spellIDs in the TBC API. it expects spell names or spell *slot* IDs (the index of the spell in your spellbook).

I believe Faerie Fire (Feral) has to have extra parentheses because it has them in the name; if you only include one set, the game will think (Feral) is supposed to be a spell rank, and it will fail.

`GetSpellCooldown("Faerie Fire (Feral)()")`

https://wow.gamepedia.com/API_GetSpellCooldown?oldid=1307366
