### ISSUE TITLE
j

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8200]

**Comment by Godmatik** [comment]
Yes you can queue BGs from anywhere
command is .join

**Comment by Tzeentch123** [comment]
I'll go through in order:
Be transparent on season duration / how titles are handled / set up tourny realm well (if there is one) is in everyones best interest and should be how stuff is done, obviously :)

Arenapoint gains: It is already boosted, much like you suggest. https://atlantiss.org/news/333/karazhans-pvp-adjustments
Check this post for current gains. These were all very nice changes, cant think of anyone serious that disagreed with those and they should be kept. For Season1 (which is shorter than the others) can think about increasing it cause youll struggle to get full gear even if you play high rated 3s every week, especially if you dont rush on launch / have other priorities @70. Maybe double some flushes along the way, at least the last say 3 weeks since thats the deciding time for ladder positionings for tourny/titles

Rating requirements seem fine to me, if pop is low (and higher rating becomes harder to achieve) can think about changing it, its never been a problem tho afaik. 

Decay / wotlkesque MMR system I dont think is possible to  implement into the tbc client, from what Ive heard. Id be down with rating decay for inactive teams above 2k, thats probably a good change. Would give it 2 weeks buffer though or maybe enable it for the last 4 weeks of the season or something so people cant push and then sit on their rating forever. 

queue announcers are already in the game, both for arenas and BGs (arena ones even have rating brackets, e.g. 2k+ or 1500-1800)

Engi/classic items: Imo its best to just disable all the cheese items from classic, for engi i think belt is fine. If that becomes abusable (for whichever reason) and ends up causing issues, can disable it at a later date, none of it was an issue on the previous two servers so I dont see a reason to take action right now.

Honor rates: This is the big topic we COULD change, considering its what ive seen requested a bunch. There currently is roundabout 1k honor, 40 arenapoints available through custom dailies. There also is the rotating bonus honor BG on the weekends. Imo it worked well on the previous servers and doesnt require changing, an idea I liked was to double the reward of the BG marks turning repeatable quest, that would require the NPC that lets you exchange marks (that was introduced late karazhan when some BGs just wouldnt pop anymore) to not be in the game, as that combination would lead to alliance side only doing AV anymore (which they already do to a large degree, requiring different marks to buy offsets and bonus Weekends mitigate this, which is ofc moot if you can exchange AV marks for the other ones). Could also add that NPC but remove AV marks as a currency from him, idk that hes needed though. Maybe an idea for a later date? 

TL,DR my suggestion would be to double honor reward for the turn in 1 mark each repeatable quest and to make sure AV isnt in the rotation for the weekend bonus honor. Everything else imo works really well and Id keep it as is.

**Comment by Tzeentch123** [comment]
Ive seen the idea floated around to promote duels of some kind, if there is an admin that wants to dedicate himself to setting something up can have a duel tournament those are kinda fun albeit imbalaced ofc. I remember having one of those on old AT, ive no clue about the ruleset though. Could be something fun to do but requires time/effort to set up and run, idk that its gonna happen on a pve focussed server like this. Imo if we get end of season tourny thats more than can feasibly be expected and I wouldnt push for more.

**Comment by tsu-1** [comment]
Close.
