### ISSUE TITLE
[Quest] Gahz'ridian - Low spawns

### ISSUE THREAD

**Issue by reetarded** [Atlantiss/NetherwingBugtracker#8450]
Only like 3-5 up per camp with 20+ spawns, and they take a long time to respawn in the same camp. Pretty much undoable if you are grouped with anyone.  Need to allow more to be up at the same time in the zone.

**Comment by Godmatik** [comment]
Yeah there might be some lacking spawns. The Southmoon ruins has a decent amount clustered around though.

If you are grouped with someone it is going to be a pain for sure since you need 30 ... dunno why Blizz designed this quest to require you to gather so many. Maybe temporary solution is to lower the respawn timer of it.

https://www.wowhead.com/tbc/object=140971/gahzridian#map

**Comment by Wolffenstein** [comment]
Fixed in rev 3834.
