### ISSUE TITLE
[Hunter] Flare and Frost Trap debuff not lingering after leaving Visual effect

### ISSUE THREAD

**Issue by bluemanguy112** [Atlantiss/NetherwingBugtracker#8549]
**Description**: 
Flare and Frost Trap debuff not lingering 4-6sec after leaving the Visual effect of it.

**Current behaviour**:
Leaving Flare or Frost Trap removes the debuff immediately.

**Expected behaviour**: 
See below. It was reported as bug for sticking for "too long" in TBCC, however, Blizzard tested and confirmed it as working as intended.

https://github.com/Aeded/BCC_Buglist/issues/5

**Comment by Wolffenstein** [comment]
This might be problematic since I believe it stems from the target list being updated less frequently than with similar, shorter spells which can lead to both the aura lingering for longer after exiting the area of effect as well as letting people sometimes walk through it without getting the aura or getting it very late (depending on how the update tick goes). Either way I implemented a longer update interval in rev 3830 and we can tweak from there.

**Comment by sasadubi** [comment]
As one of somewhat higher rated rogues on this server, my 2 cents:

2007 - wasn't like this.
All other pservers - wasn't like this.
TBC Classic - Yup it was, even too long to some extent, sometimes up to 6sec.

Fair trade as long as rogue can sap on flare now, or Shadowstep into flare and perform an opener ability (CS, Sap, Garrote).

Let's see how this works out. I'll post my feedback after some duels/arenas/testing.

Regards,
Delta

**Comment by dedestus** [comment]
This just adds another layer of RNG to the game that you seem to dislike so much, with a debuff lingering on you for a random amount of time and you cannot counter play. I strongly advise to not put this mechanic in the game and I am sure a lot of people share this opinion. Maybe we could do a poll for this?
