### ISSUE TITLE
[core][loot][quest] 

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#86]
**Description**: 
quest items ignore group loot behaviour
**Current behaviour**:
quest items are FFA, other loot is grp looted 
**Expected behaviour**: 
quest AND loot should be group loot (round robin), else you will have pissed off ranged+healers going in melee in instances and grp quests because melee are shift looting.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Wait, shouldn't it affect only green+ items? Or am I misunderstanding the issue?

**Comment by knasen88** [comment]
No, group loot is round robin on common + grays, roll on uncommon + (or whatever the treshold is set to)
to paraphrase:
now bob and john kill mob X and Y, both have a quest item and Bob the warrior shift clicks both dead mobs. Bob recieves 1 loot with quest, trash and some cloth from X then the Ycorpse gives only quest item. John the mage goes to loot "his" mob (Y) and only recieves a grey item.

**Comment by Drayo** [comment]
This might be a bit more complicated, WoWwiki mentions that Quest loot has slightly different distribution rules.

Summary for Group Loot:

- For **grey and white** Items it works like **round-robin**.

- Uncommon, Rare and Epic items **can be seen by everybody and are rolled for**, depending on the threshold setting. 

- If it is **not a players turn** and no quest items/greens etc. are involved, **the corpses should not glow** for him. 

- Once the eligible player for that specific mob **has opened and closed the loot window**, any loot he left on the mob **should become FFA** and the corpse should THEN glow for the rest of the party.

- **Money should always be FFA** since it is being split up anyway.

- **Quest Items such as heads** should be see-able and **lootable by everybody**. Each player gets his own version, the same rules apply for a lot of Items that start Quests. (Non-Head [Example](http://wowwiki.wikia.com/wiki/Shaman_Voodoo_Charm))

- Quest Items where players must collect more than one, should only be shown to the currently eligible player, UNLESS he is not on the quest, has all of them already or opens and closes the loot window without taking them, **in that case they go FFA!**


One thing that I noticed that is wrong:

- The current Error message "This item is still being rolled for." should not exist for greys and whites because the players should never even see them until they go FFA. (See third and fourth point above)
