### ISSUE TITLE
Pets Missing Family Damage Modifiers and Resist Chance on Spellcast

### ISSUE THREAD

**Issue by spacct** [Atlantiss/NetherwingBugtracker#8723]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
All pets are missing family damage modifiers to their melee damage, and pet spells are not currently resistable.

**Current behaviour**:
All pets currently have the exact same dps and none of their spells roll for resists.

**Expected behaviour**: 
Pet's should have damage coefficients affecting their melee dps (not their special abilities) as can be seen in wowhead from tbc classic below: 

https://www.wowhead.com/tbc/guide/hunter-dps-best-pets-taming-loyalty-burning-crusade-classic
<img width="622" alt="image" src="https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/df3bf67d-6ab6-483e-9f89-b79d135c9038">

Spells should also be rolling against resists:
<img width="634" alt="image" src="https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/1fce8855-0d9e-4201-aba0-a00c0d57dfaf">

These effects have been well known and ubiquitous since original vanilla all the way through classic tbc. Evidence that this is the case can be found on the petopia website (the authority for all pet information dating back to 2004).

https://www.wow-petopia.com/classic/differences.php
<img width="515" alt="image" src="https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/58409ad8-1d4d-4165-9422-2dfafb71c9b8">

https://www.wow-petopia.com/classic/differences.php
<img width="521" alt="image" src="https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/48d84b65-a649-4110-9c4c-c98cca554595">

This has been the case as far back as original vanilla as can be seen here (and reflects the wowhead information perfectly; please click into the link and compare each pet family to verify; I have only posted cats here as an example)
https://www.wow-petopia.com/classic/family.php?id=cat
<img width="457" alt="image" src="https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/91a256d8-c8d4-49d4-853c-fe5a13488280">

If this evidence is insufficient, please advise on what would be sufficient to prove this is blizzlike since original vanilla through tbc classic.

**Server Revision**:

**Comment by fondlez** [comment]
The real question is, while everyone accepts Petopia is almost the authority for pet information in WoW and you are right that this is common knowledge for vanilla and TBC players, where did they get this very specific information from? 

Was it in the client files? Was it an API command? Was it a Beast Lore description? Was it from the Bestiary or other Blizzard document or posts? Or did some very thorough player researcher(s) in the original game test some sample size from all the pet families (how big a sample) and then extrapolate?

It is a curious thing actually since I've never seen pet stat modifier information that does not point back to Petopia data. Perhaps the [Petopia Forums](https://forums.wow-petopia.com/index.php) know ...

Btw, the Burning Crusade pages for Petopia are still there but not directly from the front page: https://www.wow-petopia.com/classic_bc/differences.php

@spacct the links in your post above are not clickable (they point back to the issue tracker currently).

**Comment by spacct** [comment]
Fixed the links.

The forums themselves were started in 2010, several years after vanilla and tbc, and several years after petopia was compiling information about hunter pets. You could have found this yourself. 

I posted links to the vanilla information to show that pet family differences have existed since the beginning.

**Comment by Wolffenstein** [comment]
Fixed in rev 3937.
