### ISSUE TITLE
Paladin Consecration - None of the damage is ever resisted

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8759]
**Current behaviour**:
Consecration currently has none of its damage resisted

**Expected behaviour**: 
Each tick of damage should have a chance to have some resistance applied.

Either the spell is not setup proper or the enemies have no built in holy resistance (but they should)

https://www.youtube.com/watch?v=h0mJI_oXFnU&t=440s

![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/c9a02c39-b081-4e36-bb4a-8ca154eb6af5)

**Server Revision**: 
3914

**Comment by Wolffenstein** [comment]
AoE resisted DoTs do not show up in the combat log https://old.reddit.com/r/classicwow/comments/qgmt5l/psa_for_protection_paladins_consecration_is/

I tested it and it's already working correctly, if you try consecrating a high level enemy on a low level Paladin you will simply not do any ticks of damage
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/8bb02037-e3aa-416d-be33-8a914813f7c1)

It can also partially resist but the chance of that is much lower since just the few points of resistance bosses get from being like 3 levels higher isn't very much
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/35743538-9fbf-4261-8948-573a8e66fb3e)
