### ISSUE TITLE
[Warrior Quest] The Summoning

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#876]
**Description**: 
http://classicdb.ch/?quest=1713

**Current behaviour**:
Quest NPC summons the "Cyclonian" but while summoning he runs back.

**Expected behaviour**: 
https://www.youtube.com/watch?v=gdmwHQnsByE from 2008 shows that the mob is running back after the full 10s cast not inbetween

**Server Revision**: 
[2083]

**Comment by wtRCH** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/287

@pelekon

**Comment by RhadigarTV** [comment]
**Quest**: The quest in question is The Summoning, quest #: 1713, given to the Warrior by Bath'rah the Windwatcher, npc #: 6176, who is located in Hillsbrad Foothills.

**Description**: I am ready to perform the ritual to summon Cyclonian. When he is summoned, you must defeat him and take his whirlwind heart. This I will use to instill a weapon with Cyclonian's power.

<name>, are you ready to face the wind lord?

**Current Behavior**: While casting the ritual, Bath'rah the Windwatcher is not staying in place while casting the ritual. 

**Expected Behavior**: While casting the ritual, Bath'rah the Windwatcher should be staying in place until he finishes casting the ritual. 

**Conclusion**: After completing this quest various times with a character on the PTR, this quest is confirmed to be working as intended and this ticket can be closed.
