### ISSUE TITLE
Warlock Talent Fel Intellect

### ISSUE THREAD

**Issue by budgebudge** [Atlantiss/NetherwingBugtracker#8876]
**Description**: 
"Fel Intellect" (warlock demonology talent) is supposed to increase the pet's intellect by 5% increments per talent point.
it seems like the basis on what the % is calculated is wrong. 

Felhunter specced with 5% increase is 270int  (in a buffed state), the same buffs and felhunter with 15% increased intellect is only 14 intellect more. that doesnt seem right? that means  round about 140 intellect or something is the basis for this calculation? the real base intellect in my pets case is between 200-300, depending on buffs.

so the 14 intellect should be way more?

**Comment by SilverSaw** [comment]
Good observation @budgebudge, in addition to this report i would like to add that i think behavior of this talent is wrong increasing total mana instead of intellect:

Rank#1 Fel Intellect - 1% of total mana
Rank#2 Fel Intellect - 3.02% of total mana
Rank#3 Fel Intellect - 5.05% of total mana
Tested on all 4 pets, succubus, imp, felhunter, void. Percentage what i mentioned is fixed for the mana increase.

So it must be fixed that it is increasing intellect, not total mana of the pet respectively with 5% per rank with total = 15%.

**Comment by Wolffenstein** [comment]
It works correctly, the 5-10-15% bonus is applied to Pet's intellect. The reason the math seems off is because ON TOP OF THAT Warlock's pets gain 30% of owner's intellect. That bonus value does NOT benefit from the 5-10-15% talent increase. If I disabled the owner intellect bonus you would see a direct 5-10-15% increase from the talent alone.

**Comment by budgebudge** [comment]
> It works correctly, the 5-10-15% bonus is applied to Pet's intellect. The reason the math seems off is because ON TOP OF THAT Warlock's pets gain 30% of owner's intellect. That bonus value does NOT benefit from the 5-10-15% talent increase. If I disabled the owner intellect bonus you would see a direct 5-10-15% increase from the talent alone.

i get what you mean, however, it doesnt say "base intellect of the demon"? this makes me think that it should be different to what it is now
