### ISSUE TITLE
Warlock-spell bug: Drain life / Drain mana

### ISSUE THREAD

**Issue by budgebudge** [Atlantiss/NetherwingBugtracker#8891]
only tested in pvp situations:

sometimes when you press the button to drain an opponent, it doesnt say "resist" or anything else and it channels the spell on your side, but the enemy does not have a debuff or effect on himself.

so basically you stand there casting for nothing, spending mana for nothing.

huge bug that can lose you games if you dont adapt and recast immediately. effectifely gamebreaking if opponents are in the process of lining you, the cast gets bugged and then you cant cast again cuz the target is already around the pillar....

happens quite frequently btw!

**Comment by Godmatik** [comment]
Very likely related to the "channeled spells" bug that has been around for a while. Mind Flay is also impacted.

https://github.com/Atlantiss/NetherwingBugtracker/issues/8421
https://github.com/Atlantiss/NetherwingBugtracker/issues/7630

**Comment by Peglaa** [comment]
@Godmatik

**Comment by SilverSaw** [comment]
This is huge, also experience it sometimes, but unable to simulate. I think it happens if you cast you DL in the last milisecond when prevous DL is finishing or something connected with the re-applying function of this spell. Maybe packages lag transfer between client and server. Try to cast DL many times one after another and it may be reproduced. 

I am using macro as a short term solution 
`/cast [nochanneling:Drain Life] Drain Life`

**Comment by tsu-1** [comment]
@Wolffenstein

**Comment by Wolffenstein** [comment]
Please recheck after rev 3975. If still bugged, open a new issue.
