### ISSUE TITLE
[Quest][Wetlands] Young Crocolisk Skins

### ISSUE THREAD

**Issue by scarabadookie** [Atlantiss/NetherwingBugtracker#956]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Quest is not available for my level 22 Draenei hunter, even after completing breadcrumb quest 469 Daily Delivery.

**Current behaviour**:
James Halloran does not offer quest 484 Young Crocolisk Skins , tested both before and after completing 469 Daily Delivery. Maybe he doesn't like Draeneis?

**Expected behaviour**: 
The quest should be available, other bug report suggests others have been able to take it previously.

**Server Revision**: 
2086

**Comment by scarabadookie** [comment]
I just got the quest, seems to be working as of rev 2094 :+1: Acquired at level 23, but should be available from level 18 as per https://web.archive.org/web/20071111191900/http://thottbot.com:80/q484 .

**Comment by Shanghi** [comment]
I think the problem is that it requires honored Ironforge reputation, so maybe you got that eventually and could take it. I don't think it should require that though! I can't find any place that mentions it besides other private servers. It also makes no sense because the quest gives Stormwind reputation. There was a comment where someone assumed Daily Delivery needed honored reputation but someone corrected them - it's just a guess but maybe someone set them both to that long ago based on the probably bad comment, then later the first one was fixed while this one was forgotten about.

It will be removed soon unless someone finds evidence that that's how it should be.

**Comment by Shanghi** [comment]
That requirement is removed in revision 2152.
