### ISSUE TITLE
[NPC] [Spell] Dalaran Summoner 

### ISSUE THREAD

**Issue by GetoBoyz** [Atlantiss/NetherwingBugtracker#976]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Dalaran Summoner [https://www.wowhead.com/npc=2358/dalaran-summoner#comments](url) is capable of summoning multiple npcs. 
![wowscrnshot_093018_124340](https://user-images.githubusercontent.com/43591086/46261425-49c24200-c4c1-11e8-8467-4c54db6ca87e.jpg)
There are 3 Dalaran Theurgists, 2 Dalaran Shield Guards and 1 Dalaran Summoner. There is another Summoner nearby, but I believe do to the mob spacing these were all spawned by the most immediate summoner. 

**Current behaviour**: This mob is able to spawn multiple Dalaran Shield Guards [https://www.wowhead.com/npc=2271/dalaran-shield-guard#comments](url) and Dalaran Theurgists [https://www.wowhead.com/npc=2272/dalaran-theurgist#comments](url). It appears these summons may not despawn, or the summoner is allowed to spawn another of either npc regardless of if they have already summoned one. I imagine this is due to dropping aggro after a mob has been summoned. Spell order behavior seems to follow 1) Frostbolt 2) Summon Shield Guard 3) Summon Theurgist.

**Expected behaviour**: I'm assuming they should not be capable of having more than 1 of each summon up at one time. Maybe the summons have a small despawn timer after loss of aggro? I don't really know how this was handled in live.

**Server Revision**: Sorry I dunno any easy way to find this.

**Comment by Evolvee** [comment]
after rev xdd it should be better

**Comment by totaemoeggerli** [comment]
the summoners still summon alot of adds that don't disappear (at least not instantly, I didn't wait that long for them to despawn)
however it's extremly annyoing to interupt them. If you [interupt Summon Shield Guard](https://gfycat.com/gifs/detail/BeneficialRapidBrownbear), their next cast will be Summen Theurgist and most clases can't deal with it or kill the summoner in time. Since palyers don't need to kill the summoned mobs, they will simply reset them and the next palyer has to deal with them.
If you [don't interupt Summon Shield Guard](https://gfycat.com/upload/results) the next cast is Fireball. The situation would be alot cleaner if they would cast Fireball after the interupt too. This gives players enough time to kill the mob before it spawns another one.

**Comment by Evolvee** [comment]
the revision is not uploaded on the server yet
